// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA47ZGw6IUVkkllwTAx4GLjpMMiQcW_RJM',
    appId: '1:739876569628:web:18c070983fed95c9bd55d9',
    messagingSenderId: '739876569628',
    projectId: 'clinixai-b981d',
    authDomain: 'clinixai-b981d.firebaseapp.com',
    storageBucket: 'clinixai-b981d.firebasestorage.app',
    measurementId: 'G-DZ1KMVSQKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5z7kEsAC2dwn8wVPlZxYHIx1qaq522vY',
    appId: '1:739876569628:android:46bb4d87c76fb88ebd55d9',
    messagingSenderId: '739876569628',
    projectId: 'clinixai-b981d',
    storageBucket: 'clinixai-b981d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9ScAfB-yV52QvAq_o3yxFHbsfIxrQOCo',
    appId: '1:739876569628:ios:95e18d9d0c30a7e2bd55d9',
    messagingSenderId: '739876569628',
    projectId: 'clinixai-b981d',
    storageBucket: 'clinixai-b981d.firebasestorage.app',
    iosBundleId: 'com.example.clinixai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9ScAfB-yV52QvAq_o3yxFHbsfIxrQOCo',
    appId: '1:739876569628:ios:95e18d9d0c30a7e2bd55d9',
    messagingSenderId: '739876569628',
    projectId: 'clinixai-b981d',
    storageBucket: 'clinixai-b981d.firebasestorage.app',
    iosBundleId: 'com.example.clinixai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA47ZGw6IUVkkllwTAx4GLjpMMiQcW_RJM',
    appId: '1:739876569628:web:36734451650c7f38bd55d9',
    messagingSenderId: '739876569628',
    projectId: 'clinixai-b981d',
    authDomain: 'clinixai-b981d.firebaseapp.com',
    storageBucket: 'clinixai-b981d.firebasestorage.app',
    measurementId: 'G-04CJ8LM6W5',
  );
}
