// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Hindi (`hi`).
class AppLocalizationsHi extends AppLocalizations {
  AppLocalizationsHi([String locale = 'hi']) : super(locale);

  @override
  String get appTitle => 'मेडीमित्रा';

  @override
  String get close => 'बंद करें';

  @override
  String get loginTagline => 'आपके और आपके परिवार के लिए सरल स्वास्थ्य सेवा';

  @override
  String get smsLogin => 'एसएमएस लॉगिन';

  @override
  String get emailLogin => 'ईमेल लॉगिन';

  @override
  String get homeHello => 'नमस्ते,';

  @override
  String get homeThere => 'दोस्त';

  @override
  String get homeChatCta => 'हमारे AI हेल्थकेयर चैट असिस्टेंट को आज़माएँ';

  @override
  String get homeOurFeatures => 'हमारी सुविधाएँ';

  @override
  String get homeHighlights => 'मुख्य आकर्षण';

  @override
  String get homeDisclaimerTitle => 'अस्वीकरण';

  @override
  String get homeDisclaimerBody =>
      'MediMitra केवल जानकारी के लिए है और यह चिकित्सीय सलाह नहीं है। यह डॉक्टर की जगह नहीं लेता।\nगंभीर लक्षण या किसी भी मेडिकल इमरजेंसी में, कृपया नज़दीकी अस्पताल जाएँ या तुरंत आपातकालीन सेवाओं से संपर्क करें।';

  @override
  String get featureSymptomChecker => 'लक्षण जाँच';

  @override
  String get featureWomensHealth => 'महिला स्वास्थ्य जागरूकता';

  @override
  String get featureInsurance => 'बीमा';

  @override
  String get featureAiHealthSummary => 'AI स्वास्थ्य सारांश';

  @override
  String get featureReminders => 'रिमाइंडर';

  @override
  String get featureLocateClinics => 'पास के क्लिनिक खोजें';

  @override
  String get promoAiSymptomCheckTitle => 'AI लक्षण जाँच';

  @override
  String get promoAiSymptomCheckSubtitle =>
      'लक्षण बताइए, सेकंडों में मार्गदर्शन पाएँ।';

  @override
  String get promoVoiceWaveformTitle => 'वॉइस + वेवफ़ॉर्म';

  @override
  String get promoVoiceWaveformSubtitle =>
      'वॉइस इनपुट के साथ हैंड्स-फ़्री चैट।';

  @override
  String get promoProfilePersonalizationTitle => 'प्रोफ़ाइल पर्सनलाइज़ेशन';

  @override
  String get promoProfilePersonalizationSubtitle =>
      'बेहतर मदद के लिए उम्र, लिंग और स्थितियाँ सेव करें।';

  @override
  String get promoNearbyClinicsTitle => 'नज़दीकी क्लिनिक';

  @override
  String get promoNearbyClinicsSubtitle =>
      'अपने स्थान के पास स्वास्थ्य सेवाएँ खोजें।';

  @override
  String get settings => 'सेटिंग्स';

  @override
  String get supportAndInformation => 'सहायता और जानकारी';

  @override
  String get notifications => 'सूचनाएँ';

  @override
  String get manageYourNotifications => 'अपनी सूचनाएँ प्रबंधित करें';

  @override
  String get notificationsEnabled => 'सूचनाएँ चालू हैं';

  @override
  String get notificationsDisabled => 'सूचनाएँ बंद हैं';

  @override
  String get couldNotUpdateNotifications => 'सूचनाएँ अपडेट नहीं हो सकीं';

  @override
  String get darkMode => 'डार्क मोड';

  @override
  String get toggleDarkTheme => 'डार्क थीम बदलें';

  @override
  String get helpAndFaq => 'सहायता और FAQ';

  @override
  String get getHelpAndAnswers => 'मदद और उत्तर पाएँ';

  @override
  String get getInTouchWithSupport => 'सपोर्ट से संपर्क करें';

  @override
  String get aboutMediMitra => 'MediMitra के बारे में';

  @override
  String versionLine(Object version) {
    return 'संस्करण $version';
  }

  @override
  String get privacyPolicy => 'गोपनीयता नीति';

  @override
  String get howWeProtectYourData => 'हम आपके डेटा की सुरक्षा कैसे करते हैं';

  @override
  String get termsAndConditions => 'नियम और शर्तें';

  @override
  String get termsConditionsBody =>
      'Terms & Conditions\n\nBy downloading and using this application, you agree to comply with and be bound by these Terms and Conditions. If you do not agree with any part of these terms, you should discontinue using the app.\n\nThis application is designed to provide health-related information and decision-support guidance only. It is not a medical diagnostic tool and does not replace consultation with a qualified doctor or healthcare professional. All information provided by the app is for educational and support purposes, and users must always seek professional medical advice for diagnosis, treatment, or emergencies.\n\nUsers are responsible for providing accurate and honest information while using the app. The guidance generated by the system depends on the inputs provided by the user, and incorrect or incomplete information may lead to inaccurate results. The app should not be used as the sole basis for making medical decisions.\n\nThis application is not intended for emergency situations. In case of severe symptoms such as chest pain, difficulty breathing, loss of consciousness, or heavy bleeding, users must immediately contact local emergency services or visit the nearest hospital.\n\nTo the maximum extent permitted by law, the developers shall not be held liable for any direct or indirect damages arising from the use of this application. Use of the app is entirely at the user’s own risk, and no guarantee is made regarding the accuracy, completeness, or reliability of the information provided.\n\nUse of this application is also governed by our Privacy Policy. By continuing to use the app, you confirm that you have read, understood, and agreed to both the Privacy Policy and these Terms and Conditions.\n\nWe reserve the right to modify or update these Terms and Conditions at any time. Any changes will be displayed within the app, and continued use of the app after such changes indicates acceptance of the updated terms.';

  @override
  String get legalAgreement => 'कानूनी समझौता';

  @override
  String get deleteData => 'डेटा हटाएँ';

  @override
  String get deleteChatsAndSavedSettings => 'चैट और सेव की गई सेटिंग्स हटाएँ';

  @override
  String get logOut => 'लॉग आउट';

  @override
  String get logoutQuestion => 'लॉग आउट करें?';

  @override
  String get logoutReturnToLogin =>
      'आप लॉग आउट हो जाएंगे और लॉगिन स्क्रीन पर वापस आ जाएंगे।';

  @override
  String get chooseAnAction => 'एक विकल्प चुनें';

  @override
  String get deleteAccount => 'खाता हटाएँ';

  @override
  String get permanentlyDeleteAccount => 'अपना खाता स्थायी रूप से हटाएँ';

  @override
  String get deleteLocalData => 'लोकल डेटा हटाएँ';

  @override
  String get deleteLocalDataOnDevice =>
      'इस डिवाइस पर चैट और सेव की गई सेटिंग्स हटाएँ';

  @override
  String get clearLocalDataQuestion => 'लोकल डेटा साफ़ करें?';

  @override
  String get clearLocalDataBody =>
      'यह इस डिवाइस पर सेव किया हुआ लोकल ऐप डेटा (सेटिंग्स, कैश्ड प्रोफ़ाइल विवरण और मेमोरी में चैट हिस्ट्री) हटाएगा।\n\nपरिवर्तन लागू होने के लिए ऐप रीस्टार्ट करना पड़ सकता है।';

  @override
  String get clear => 'साफ़ करें';

  @override
  String get localDataCleared => 'लोकल डेटा साफ़ कर दिया गया';

  @override
  String get couldNotClearLocalData => 'लोकल डेटा साफ़ नहीं हो सका';

  @override
  String get accountDeletionNotAvailable =>
      'इस प्लेटफ़ॉर्म पर खाता हटाना उपलब्ध नहीं है';

  @override
  String get noSignedInAccountFound => 'कोई साइन-इन खाता नहीं मिला';

  @override
  String get deleteAccountQuestion => 'खाता हटाएँ?';

  @override
  String get deleteAccountBody =>
      'यह आपका खाता स्थायी रूप से हटा देगा। आप इस डिवाइस से लॉग आउट हो जाएंगे।';

  @override
  String get deletingAccount => 'खाता हटाया जा रहा है...';

  @override
  String get pleaseLoginAgainThenDelete =>
      'कृपया फिर से लॉगिन करें, फिर खाता हटाएँ';

  @override
  String get couldNotDeleteAccount => 'खाता हटाया नहीं जा सका';

  @override
  String get networkSlowTryAgain => 'नेटवर्क धीमा है। कृपया फिर कोशिश करें।';

  @override
  String get defaultUser => 'उपयोगकर्ता';

  @override
  String userIdLine(Object id) {
    return 'यूज़र आईडी: $id';
  }

  @override
  String get clinicsNearYou => 'आपके पास क्लिनिक';

  @override
  String get refresh => 'रिफ्रेश';

  @override
  String get recenter => 'फिर से केंद्रित करें';

  @override
  String resultsCount(Object count) {
    return 'परिणाम ($count)';
  }

  @override
  String get nearbyClinics => 'नज़दीकी क्लिनिक';

  @override
  String get call => 'कॉल';

  @override
  String get navigate => 'नेविगेट';

  @override
  String get unableToOpenDialer => 'डायलर नहीं खुल सका';

  @override
  String get unableToOpenMaps => 'मैप्स नहीं खुल सके';

  @override
  String get radius => 'दायरा';

  @override
  String get tryAgain => 'फिर कोशिश करें';

  @override
  String get openLocationSettings => 'लोकेशन सेटिंग्स खोलें';

  @override
  String get locationServicesDisabled =>
      'लोकेशन सेवाएँ बंद हैं। कृपया GPS चालू करें।';

  @override
  String get locationPermissionDenied => 'लोकेशन अनुमति अस्वीकार की गई।';

  @override
  String get locationPermissionDeniedForever =>
      'लोकेशन अनुमति स्थायी रूप से अस्वीकार है। सेटिंग्स से सक्षम करें।';

  @override
  String get chooseLanguage => 'भाषा चुनें';

  @override
  String get cancel => 'रद्द करें';

  @override
  String get save => 'सहेजें';

  @override
  String get contactUs => 'संपर्क करें';

  @override
  String get needHelp => 'मदद चाहिए?';

  @override
  String get contactSubtitle => 'हमें संदेश भेजें और हमारी टीम जवाब देगी।';

  @override
  String supportEmailLine(Object email) {
    return 'सपोर्ट ईमेल: $email';
  }

  @override
  String get typicalResponseLine => 'सामान्य प्रतिक्रिया: 24 घंटे के भीतर';

  @override
  String get language => 'भाषा';

  @override
  String languageSetTo(Object language) {
    return 'भाषा सेट हुई: $language';
  }

  @override
  String get fullName => 'पूरा नाम';

  @override
  String get yourName => 'आपका नाम';

  @override
  String get email => 'ईमेल';

  @override
  String get emailHint => 'name@example.com';

  @override
  String get phoneOptional => 'फोन (वैकल्पिक)';

  @override
  String get yourMobileNumber => 'आपका मोबाइल नंबर';

  @override
  String get subject => 'विषय';

  @override
  String get subjectHint => 'यह किस बारे में है?';

  @override
  String get message => 'संदेश';

  @override
  String get messageHint => 'अपनी समस्या या प्रश्न लिखें';

  @override
  String get send => 'भेजें';

  @override
  String get sentSuccess => 'भेज दिया! हम जल्द ही आपसे संपर्क करेंगे।';

  @override
  String get required => 'आवश्यक';

  @override
  String get enterValidEmail => 'मान्य ईमेल दर्ज करें';

  @override
  String get writeMoreDetail => 'कृपया थोड़ा और विवरण लिखें';

  @override
  String get couldNotOpenEmailApp => 'ईमेल ऐप नहीं खुल सका।';

  @override
  String get couldNotSendTryLater =>
      'भेजा नहीं जा सका। कृपया बाद में फिर कोशिश करें।';

  @override
  String get tipNoShareOtp => 'टिप: यहां पासवर्ड या OTP साझा न करें।';

  @override
  String get loginLanguageLabel => 'English / हिंदी';

  @override
  String get loginHeroSubtitle => 'आपका स्वास्थ्य साथी';

  @override
  String get loginMobileNumberLabel => 'मोबाइल नंबर';

  @override
  String get loginMobileHint => '00000 00000';

  @override
  String get loginEmailLabel => 'ईमेल पता';

  @override
  String get loginPasswordLabel => 'पासवर्ड';

  @override
  String get loginPasswordHint => 'पासवर्ड दर्ज करें';

  @override
  String get loginPleaseWait => 'कृपया प्रतीक्षा करें...';

  @override
  String get loginSendOtp => 'OTP भेजें';

  @override
  String get loginContinue => 'जारी रखें';

  @override
  String get loginSendingOtp => 'OTP भेजा जा रहा है...';

  @override
  String get loginOr => 'या';

  @override
  String get loginContinueAsGuest => 'गेस्ट के रूप में जारी रखें';

  @override
  String get loginAgreementText =>
      'लॉगिन करके, आप MediMitra की\nसेवा शर्तों और गोपनीयता नीति से सहमत होते हैं।';

  @override
  String get loginUnableContinueGuest => 'गेस्ट के रूप में जारी नहीं हो सका।';

  @override
  String get loginEnterMobileNumber => 'मोबाइल नंबर दर्ज करें।';

  @override
  String get loginEnterValidMobileNumber =>
      'मान्य 10-अंकों का मोबाइल नंबर दर्ज करें।';

  @override
  String get loginOtpSent => 'OTP भेज दिया गया।';

  @override
  String get loginFailedSendOtp => 'OTP भेजने में विफल।';

  @override
  String get loginEnterValidEmail => 'मान्य ईमेल दर्ज करें।';

  @override
  String get loginPasswordMinChars =>
      'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।';

  @override
  String get loginEmailPasswordDisabled =>
      'Firebase Console में Email/Password साइन-इन बंद है।';

  @override
  String get loginAccountExistsTryLogin =>
      'खाता पहले से मौजूद है। लॉगिन करके देखें।';

  @override
  String get loginWeakPassword => 'पासवर्ड बहुत कमजोर है (कम से कम 6 अक्षर)।';

  @override
  String get loginIncorrectPassword => 'गलत पासवर्ड।';

  @override
  String get loginInvalidEmail => 'अमान्य ईमेल।';

  @override
  String get loginLoginFailed => 'लॉगिन विफल।';

  @override
  String get otpVerifyNumber => 'नंबर सत्यापित करें';

  @override
  String get otpSentTo => 'हमने 6-अंकों का कोड भेजा है';

  @override
  String get otpHaventReceived => 'कोड नहीं मिला?';

  @override
  String get otpResendCode => 'कोड फिर से भेजें';

  @override
  String get otpVerifyProceed => 'सत्यापित करें और आगे बढ़ें';

  @override
  String get otpVerifying => 'सत्यापन हो रहा है...';

  @override
  String get otpEnter6Digit => '6-अंकों का OTP दर्ज करें।';

  @override
  String get otpInvalid => 'अमान्य OTP।';

  @override
  String get otpVerificationFailed => 'OTP सत्यापन विफल।';

  @override
  String get otpFailedResend => 'कोड फिर से भेजने में विफल।';

  @override
  String get otpCodeResent => 'कोड फिर से भेज दिया गया।';

  @override
  String get otpSafetyFirst => 'सुरक्षा पहले';

  @override
  String get otpSafetyNote =>
      'MediMitra के एन्क्रिप्शन के साथ अपने स्वास्थ्य रिकॉर्ड से सुरक्षित रूप से जुड़ें।';

  @override
  String get communityOutbreakAlerts => 'समुदाय प्रकोप अलर्ट';

  @override
  String get outbreakPrivacyNote =>
      'गोपनीयता-प्रथम: केवल PIN3 और दिन के अनुसार समेकित लक्षण गणना। कोई नाम, चैट टेक्स्ट, GPS या सटीक टाइमस्टैम्प नहीं।';

  @override
  String get regionNotSet => 'क्षेत्र: सेट नहीं';

  @override
  String regionPin3Line(Object region) {
    return 'क्षेत्र: $region (PIN3)';
  }

  @override
  String get set => 'सेट करें';

  @override
  String get setAreaPin3Title => 'अपना क्षेत्र सेट करें (PIN3)';

  @override
  String get setAreaPin3Body =>
      'अपना PIN कोड दर्ज करें। हम केवल पहले 3 अंक (मोटा क्षेत्र) ही सहेजते हैं।';

  @override
  String get pinExampleHint => 'जैसे 411001';

  @override
  String get enterFirst3DigitsPin =>
      'अपने PIN के कम से कम पहले 3 अंक दर्ज करें।';

  @override
  String get unableToSaveRegion => 'क्षेत्र सहेजा नहीं जा सका।';

  @override
  String get setPin3ToSeeAlerts =>
      'अपने क्षेत्र के लिए प्रकोप अलर्ट देखने हेतु PIN3 सेट करें।';

  @override
  String get noAlertsToday => 'आज आपके क्षेत्र के लिए कोई अलर्ट नहीं है।';

  @override
  String get prevention => 'बचाव';

  @override
  String get outbreakLevelHighRisk => 'उच्च जोखिम';

  @override
  String get outbreakLevelWarning => 'चेतावनी';

  @override
  String get outbreakLevelWatch => 'निगरानी';

  @override
  String get outbreakLevelNone => 'कोई नहीं';

  @override
  String get back => 'वापस';

  @override
  String get next => 'आगे';

  @override
  String get couldNotSaveConsent =>
      'आपकी सहमति सहेजी नहीं जा सकी। कृपया फिर कोशिश करें।';

  @override
  String get termsSigningTitle => 'सेवा शर्तें';

  @override
  String get termsSigningIntro =>
      'लक्षण आकलन का उपयोग करने से पहले, कृपया सेवा शर्तें और गोपनीयता नीति स्वीकार करें। कृपया ध्यान दें:';

  @override
  String get termsBulletNotDiagnosisTitle => 'यह परिणाम निदान नहीं है।';

  @override
  String get termsBulletNotDiagnosisBody =>
      ' यह केवल जानकारी के लिए है और योग्य चिकित्सीय राय नहीं है।';

  @override
  String get termsBulletNoEmergencyTitle => 'इमरजेंसी में इसका उपयोग न करें।';

  @override
  String get termsBulletNoEmergencyBody =>
      ' स्वास्थ्य आपात स्थिति में तुरंत अपने स्थानीय आपातकालीन नंबर पर कॉल करें।';

  @override
  String get termsBulletDataSafeTitle => 'आपका डेटा सुरक्षित है।';

  @override
  String get termsBulletDataSafeBody =>
      ' आपके द्वारा दी गई जानकारी साझा नहीं की जाएगी या आपकी पहचान के लिए उपयोग नहीं होगी।';

  @override
  String get termsConsentTermsPrefix => 'मैंने ';

  @override
  String get termsConsentTermsLink => 'सेवा शर्तें';

  @override
  String get termsConsentTermsSuffix => ' पढ़ ली हैं और स्वीकार करता/करती हूँ।';

  @override
  String get termsConsentPrivacyPrefix =>
      'मैं अपने स्वास्थ्य जानकारी का इंटरव्यू के लिए उपयोग होने से सहमत हूँ। अधिक जानकारी ';

  @override
  String get termsConsentPrivacyLink => 'गोपनीयता नीति';

  @override
  String get termsConsentPrivacySuffix => ' में है।';

  @override
  String get quickQuestions => 'त्वरित प्रश्न';

  @override
  String get typeAQuestionHint => 'एक प्रश्न लिखें…';

  @override
  String get talkToMaya => 'माया से बात करें';

  @override
  String get womensHealthHubTitle => 'महिला स्वास्थ्य हब';

  @override
  String get womensHealthHubWelcome => 'आपकी स्वास्थ्य यात्रा में स्वागत है';

  @override
  String get womensHealthHubSubtitle =>
      'संसाधन देखने और व्यक्तिगत देखभाल पाने के लिए एक श्रेणी चुनें।';

  @override
  String get menstrualHealth => 'मासिक धर्म स्वास्थ्य';

  @override
  String get pregnancyAndMaternal => 'गर्भावस्था और मातृत्व';

  @override
  String get breastHealth => 'स्तन स्वास्थ्य';

  @override
  String get comingSoon => 'जल्द आ रहा है';

  @override
  String get womensHealthHubTagline => 'MEDIMITRA WELLNESS';

  @override
  String get womensHealthCategoryMenstrualDescription =>
      'अपने मासिक चक्र को समझें, स्वच्छता के बारे में जानें,\nऔर पीरियड्स को आसानी से मैनेज करें।';

  @override
  String get womensHealthCategoryPregnancyDescription =>
      'स्वस्थ गर्भावस्था के लिए विशेषज्ञ मार्गदर्शन,\nपोषण सुझाव, और\nसुरक्षित डिलीवरी सहायता।';

  @override
  String get womensHealthCategoryBreastDescription =>
      'स्व-परीक्षण के सरल गाइड\nऔर जागरूकता सुझाव\nजल्दी पहचान और देखभाल के लिए।';

  @override
  String get recommended => 'अनुशंसित';

  @override
  String get explore => 'एक्सप्लोर करें';

  @override
  String get menstrualScreenTitle => 'मासिक स्वास्थ्य';

  @override
  String get menstrualWhatIsMenstruationTitle => 'मासिक धर्म क्या है?';

  @override
  String get menstrualWhatIsMenstruationBody =>
      'मासिक धर्म एक प्राकृतिक, मासिक प्रक्रिया है जिसमें शरीर गर्भाशय की परत को बाहर निकालता है। यह स्वस्थ प्रजनन प्रणाली का संकेत है और बढ़ने का एक सामान्य हिस्सा है।';

  @override
  String get menstrualQuote => 'नवीनीकरण और जीवन का चक्र';

  @override
  String get menstrualWhatIsNormalTitle => 'क्या सामान्य है?';

  @override
  String get menstrualNormalItem1 => 'चक्र 21 से 35 दिनों के बीच होता है';

  @override
  String get menstrualNormalItem2 => 'रक्तस्राव 3 से 7 दिनों तक रहता है';

  @override
  String get menstrualNormalItem3 => 'हल्की से मध्यम ऐंठन या असुविधा';

  @override
  String get menstrualWarningSignsTitle => 'चेतावनी संकेत';

  @override
  String get menstrualWarningItem1 =>
      'अधिक रक्तस्राव के कारण हर 1–2 घंटे में पैड बदलना';

  @override
  String get menstrualWarningItem2 =>
      'इतना तेज दर्द कि रोज़मर्रा के काम न हो पाएं';

  @override
  String get menstrualWarningItem3 =>
      'चक्र लगातार 21 दिनों से कम या 38 दिनों से अधिक';

  @override
  String get menstrualHygieneTipsTitle => 'स्वच्छता सुझाव';

  @override
  String get menstrualTipChangeRegularlyTitle => 'नियमित बदलें';

  @override
  String get menstrualTipChangeRegularlySubtitle => 'हर 4–6 घंटे में पैड बदलें';

  @override
  String get menstrualTipCleanHandsTitle => 'हाथ साफ रखें';

  @override
  String get menstrualTipCleanHandsSubtitle => 'पहले और बाद में हाथ धोएं';

  @override
  String get menstrualTipStayDryTitle => 'सूखा रखें';

  @override
  String get menstrualTipStayDrySubtitle =>
      'जननांग क्षेत्र को साफ और सूखा रखें';

  @override
  String get menstrualMythsFactsTitle => 'मिथक और तथ्य';

  @override
  String get menstrualMyth1 =>
      'मिथक: \"पीरियड्स के दौरान व्यायाम नहीं करना चाहिए।\"';

  @override
  String get menstrualFact1 =>
      'तथ्य: हल्का व्यायाम ऐंठन कम करने और मूड बेहतर करने में मदद कर सकता है।';

  @override
  String get menstrualMyth2 => 'मिथक: \"मासिक धर्म का खून \'गंदा\' होता है।\"';

  @override
  String get menstrualFact2 =>
      'तथ्य: यह गर्भाशय की परत से सामान्य रक्त और ऊतक होता है।';

  @override
  String get chatHeaderTitle => 'स्वास्थ्य सहायक';

  @override
  String get chatHeaderStatusOnline => 'ऑनलाइन';

  @override
  String get chatToday => 'आज';

  @override
  String get chatQuickChipCheckFever => '🌡️ बुखार जांचें';

  @override
  String get chatQuickPromptCheckFever =>
      'मैं बुखार की जांच करना चाहता/चाहती हूँ।';

  @override
  String get chatQuickChipWomensHealth => '🤰 महिला स्वास्थ्य';

  @override
  String get chatQuickPromptWomensHealth =>
      'मेरा महिला स्वास्थ्य से जुड़ा एक सवाल है।';

  @override
  String get chatQuickChipFirstAid => '🩹 प्राथमिक उपचार';

  @override
  String get chatQuickPromptFirstAid => 'मुझे प्राथमिक उपचार की सलाह चाहिए।';

  @override
  String get chatQuickChipChildCare => '👶 बाल देखभाल';

  @override
  String get chatQuickPromptChildCare => 'मुझे बाल देखभाल मार्गदर्शन चाहिए।';

  @override
  String get chatInputHintAskMeAnything => 'कुछ भी पूछें...';

  @override
  String get profileSaved => 'प्रोफ़ाइल सहेजी गई';

  @override
  String get saving => 'सहेजा जा रहा है...';

  @override
  String get saveChanges => 'परिवर्तन सहेजें';

  @override
  String get profileTopBarTitle => 'Profile Settings';

  @override
  String get profileHeaderSubtitle => 'User Profile';

  @override
  String get profileSectionFullName => 'FULL NAME';

  @override
  String get profileHintFullName => 'e.g. Rahul Sharma';

  @override
  String get profileSectionAge => 'AGE';

  @override
  String get profileHintAge => 'Enter your age';

  @override
  String get profileSectionGender => 'GENDER';

  @override
  String get profileGenderMale => 'Male';

  @override
  String get profileGenderFemale => 'Female';

  @override
  String get profileGenderOther => 'Other';

  @override
  String get profileChronicConditions => 'CHRONIC CONDITIONS';

  @override
  String get profileConditionsBadge => 'BILINGUAL';

  @override
  String get conditionDiabetesTitle => 'Diabetes';

  @override
  String get conditionDiabetesSubtitle => 'Diabetes (Sugar)';

  @override
  String get conditionBpHeartTitle => 'BP & Heart';

  @override
  String get conditionBpHeartSubtitle => 'Blood pressure / Heart';

  @override
  String get conditionAsthmaTitle => 'Asthma';

  @override
  String get conditionAsthmaSubtitle => 'Breathing';

  @override
  String get conditionThyroidTitle => 'Thyroid';

  @override
  String get conditionThyroidSubtitle => 'Thyroid';

  @override
  String get conditionTbTitle => 'TB';

  @override
  String get conditionTbSubtitle => 'Tuberculosis';

  @override
  String get conditionNoneTitle => 'None';

  @override
  String get conditionNoneSubtitle => 'No conditions';

  @override
  String get helpFaqBotGreeting =>
      'Hi! I\'m MediMitra Help. Ask me anything about symptom checking, voice input, outbreak alerts, clinics, login, or privacy.\n\nNote: This is not medical advice. If you have a medical emergency, contact local emergency services.';

  @override
  String get helpFaqSuggestionCheckSymptoms => 'How do I check symptoms?';

  @override
  String get helpFaqSuggestionVoiceSymptoms => 'How do voice symptoms work?';

  @override
  String get helpFaqSuggestionOutbreakAlert => 'What is outbreak alert?';

  @override
  String get helpFaqSuggestionNearbyClinics => 'How to find nearby clinics?';

  @override
  String get helpFaqSuggestionOtpLogin => 'How does OTP login work?';

  @override
  String get helpFaqSuggestionDataSafe => 'Is my data safe?';

  @override
  String get helpFaqSuggestionGuestMode => 'Can I use the app without login?';

  @override
  String get helpFaqSuggestionChangeLanguage => 'How to change language?';

  @override
  String get helpFaqSuggestionDarkMode => 'How to enable dark mode?';

  @override
  String get helpFaqReplySymptomChecking =>
      'To check symptoms:\n1) Open Chat / Symptom Checker\n2) Type your symptoms (or use voice)\n3) Answer follow-up questions\n\nMediMitra will show likely causes and next steps. For severe symptoms (chest pain, trouble breathing, fainting), seek urgent care.';

  @override
  String get helpFaqReplyVoiceSymptoms =>
      'Voice symptoms: tap the microphone, speak your symptoms clearly, and the app converts it to text for analysis.\n\nTips: speak one symptom at a time, use simple words (\"fever\", \"cough\"), and allow microphone permission when asked.';

  @override
  String get helpFaqReplyOutbreakAlert =>
      'Outbreak alert helps you see if certain symptoms are trending in your area. It\'s based on anonymized, aggregated symptom patterns and is meant for awareness (not diagnosis).\n\nYou can view outbreak insights from the Outbreak section.';

  @override
  String get helpFaqReplyNearbyClinics =>
      'Nearby clinics: open the Clinic Locator to see clinics around you.\n\nMake sure Location permission is enabled. If you prefer, you can also search by area/city (if available on your build).';

  @override
  String get helpFaqReplyOtpLogin =>
      'OTP login: enter your 10-digit mobile number and we send a verification OTP. Enter the 6-digit OTP to proceed.\n\nIf you don\'t receive it, wait for the resend timer and try again. Also confirm network/SMS permissions.';

  @override
  String get helpFaqReplyGuestMode =>
      'Guest mode lets you explore the app without signing in. Some features that save to your profile (like personalized settings) may be limited until you log in.';

  @override
  String get helpFaqReplyPrivacy =>
      'Your profile data (like name/age/gender/conditions) is stored securely for your account to personalize your experience. We do not want you to share sensitive info in chat.\n\nFor exact details, check Privacy Policy (in the app).';

  @override
  String get helpFaqReplyChangeLanguage =>
      'You can change language from Profile → Language.';

  @override
  String get helpFaqReplyDarkMode =>
      'Dark mode: go to Profile → Dark Mode and toggle it on/off. Your choice is saved and works across the whole app.';

  @override
  String get helpFaqReplyContactSupport =>
      'Contact support: open Contact Us and send your message. Include screenshots and steps if possible.';

  @override
  String get helpFaqReplyFallback =>
      'I can help with: symptom checking, voice input, outbreak alerts, clinic locator, OTP login, privacy, language, and dark mode.\n\nTry one of these: \"How do I check symptoms?\", \"How to find nearby clinics?\", \"Is my data safe?\"';
}
