// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Malayalam (`ml`).
class AppLocalizationsMl extends AppLocalizations {
  AppLocalizationsMl([String locale = 'ml']) : super(locale);

  @override
  String get appTitle => 'മെഡിമിത്ര';

  @override
  String get close => 'അടയ്ക്കുക';

  @override
  String get loginTagline =>
      'നിങ്ങളുടെയും നിങ്ങളുടെ കുടുംബത്തിന്റെയും ലളിതമായ ആരോഗ്യസംരക്ഷണം';

  @override
  String get smsLogin => 'എസ്‌എം‌എസ് ലോഗിൻ';

  @override
  String get emailLogin => 'ഇമെയിൽ ലോഗിൻ';

  @override
  String get homeHello => 'ഹലോ,';

  @override
  String get homeThere => 'അവിടെ';

  @override
  String get homeChatCta =>
      'ഞങ്ങളുടെ AI ഹെൽത്ത് ചാറ്റ് അസിസ്റ്റന്റ് പരിശോധിക്കുക';

  @override
  String get homeOurFeatures => 'ഞങ്ങളുടെ സവിശേഷതകൾ';

  @override
  String get homeHighlights => 'പ്രധാന ഹൈലൈറ്റുകൾ';

  @override
  String get homeDisclaimerTitle => 'ഡിസ്‌ക്ലൈമർ';

  @override
  String get homeDisclaimerBody =>
      'MediMitra വിവര ആവശ്യങ്ങൾക്ക് മാത്രമാണ്; ഇത് മെഡിക്കൽ ഉപദേശം അല്ല. ഇത് ഡോക്ടറെ പകരം വഹിക്കില്ല.\nതീവ്ര ലക്ഷണങ്ങൾ അല്ലെങ്കിൽ അടിയന്തരാവസ്ഥയാണെങ്കിൽ, അടുത്ത ആശുപത്രിയിലേക്കോ പ്രാദേശിക അടിയന്തര സേവനങ്ങളിലേക്കോ ഉടൻ ബന്ധപ്പെടുക.';

  @override
  String get featureSymptomChecker => 'ലക്ഷണ പരിശോധന';

  @override
  String get featureWomensHealth => 'സ്ത്രീാരോഗ്യ അവബോധം';

  @override
  String get featureInsurance => 'ഇൻഷുറൻസ്';

  @override
  String get featureAiHealthSummary => 'AI ആരോഗ്യ സംഗ്രഹം';

  @override
  String get featureReminders => 'റിമൈൻഡറുകൾ';

  @override
  String get featureLocateClinics =>
      'നിങ്ങളുടെ അടുത്തുള്ള ക്ലിനിക്കുകൾ കണ്ടെത്തുക';

  @override
  String get promoAiSymptomCheckTitle => 'AI ലക്ഷണ പരിശോധന';

  @override
  String get promoAiSymptomCheckSubtitle =>
      'ലക്ഷണങ്ങൾ വിശദീകരിക്കുക, സെക്കൻഡുകളിൽ മാർഗ്ഗനിർദ്ദേശം നേടുക.';

  @override
  String get promoVoiceWaveformTitle => 'വോയ്സ് + വേവ്‌ഫോം';

  @override
  String get promoVoiceWaveformSubtitle =>
      'വോയ്സ് ഇൻപുട്ട് പിന്തുണയോടെ ഹാൻഡ്‌സ്-ഫ്രീ ചാറ്റ്.';

  @override
  String get promoProfilePersonalizationTitle => 'പ്രൊഫൈൽ വ്യക്തിഗതമാക്കൽ';

  @override
  String get promoProfilePersonalizationSubtitle =>
      'മികച്ച സഹായത്തിനായി വയസ്സ്, ലിംഗം, അവസ്ഥകൾ സേവ് ചെയ്യുക.';

  @override
  String get promoNearbyClinicsTitle => 'അടുത്തുള്ള ക്ലിനിക്കുകൾ';

  @override
  String get promoNearbyClinicsSubtitle =>
      'നിങ്ങളുടെ ലൊക്കേഷൻ സമീപമുള്ള ആരോഗ്യ സേവനങ്ങൾ കണ്ടെത്തുക.';

  @override
  String get settings => 'സെറ്റിംഗുകൾ';

  @override
  String get supportAndInformation => 'പിന്തുണ & വിവരം';

  @override
  String get notifications => 'അറിയിപ്പുകൾ';

  @override
  String get manageYourNotifications => 'നിങ്ങളുടെ അറിയിപ്പുകൾ നിയന്ത്രിക്കുക';

  @override
  String get notificationsEnabled => 'അറിയിപ്പുകൾ പ്രവർത്തനക്ഷമമാണ്';

  @override
  String get notificationsDisabled => 'അറിയിപ്പുകൾ പ്രവർത്തനരഹിതമാണ്';

  @override
  String get couldNotUpdateNotifications =>
      'അറിയിപ്പുകൾ അപ്‌ഡേറ്റ് ചെയ്യാനായില്ല';

  @override
  String get darkMode => 'ഡാർക്ക് മോഡ്';

  @override
  String get toggleDarkTheme => 'ഡാർക്ക് തീം ഓൺ/ഓഫ് ചെയ്യുക';

  @override
  String get helpAndFaq => 'സഹായം & FAQ';

  @override
  String get getHelpAndAnswers => 'സഹായവും ഉത്തരങ്ങളും നേടുക';

  @override
  String get getInTouchWithSupport => 'പിന്തുണയുമായി ബന്ധപ്പെടുക';

  @override
  String get aboutMediMitra => 'MediMitraയെ കുറിച്ച്';

  @override
  String versionLine(Object version) {
    return 'വർഷൻ $version';
  }

  @override
  String get privacyPolicy => 'സ്വകാര്യതാ നയം';

  @override
  String get howWeProtectYourData =>
      'നിങ്ങളുടെ ഡാറ്റ ഞങ്ങൾ എങ്ങനെ സംരക്ഷിക്കുന്നു';

  @override
  String get termsAndConditions => 'നിബന്ധനകളും വ്യവസ്ഥകളും';

  @override
  String get termsConditionsBody =>
      'Terms & Conditions\n\nBy downloading and using this application, you agree to comply with and be bound by these Terms and Conditions. If you do not agree with any part of these terms, you should discontinue using the app.\n\nThis application is designed to provide health-related information and decision-support guidance only. It is not a medical diagnostic tool and does not replace consultation with a qualified doctor or healthcare professional. All information provided by the app is for educational and support purposes, and users must always seek professional medical advice for diagnosis, treatment, or emergencies.\n\nUsers are responsible for providing accurate and honest information while using the app. The guidance generated by the system depends on the inputs provided by the user, and incorrect or incomplete information may lead to inaccurate results. The app should not be used as the sole basis for making medical decisions.\n\nThis application is not intended for emergency situations. In case of severe symptoms such as chest pain, difficulty breathing, loss of consciousness, or heavy bleeding, users must immediately contact local emergency services or visit the nearest hospital.\n\nTo the maximum extent permitted by law, the developers shall not be held liable for any direct or indirect damages arising from the use of this application. Use of the app is entirely at the user’s own risk, and no guarantee is made regarding the accuracy, completeness, or reliability of the information provided.\n\nUse of this application is also governed by our Privacy Policy. By continuing to use the app, you confirm that you have read, understood, and agreed to both the Privacy Policy and these Terms and Conditions.\n\nWe reserve the right to modify or update these Terms and Conditions at any time. Any changes will be displayed within the app, and continued use of the app after such changes indicates acceptance of the updated terms.';

  @override
  String get legalAgreement => 'നിയമ ഉടമ്പടി';

  @override
  String get deleteData => 'ഡാറ്റ നീക്കുക';

  @override
  String get deleteChatsAndSavedSettings =>
      'ചാറ്റുകളും സേവ് ചെയ്ത സെറ്റിംഗുകളും നീക്കുക';

  @override
  String get logOut => 'ലോഗ് ഔട്ട്';

  @override
  String get logoutQuestion => 'ലോഗ് ഔട്ട് ചെയ്യണോ?';

  @override
  String get logoutReturnToLogin =>
      'നിങ്ങൾ ലോഗ് ഔട്ട് ചെയ്ത് ലോഗിൻ സ്ക്രീനിലേക്ക് മടങ്ങും.';

  @override
  String get chooseAnAction => 'ഒരു പ്രവർത്തനം തിരഞ്ഞെടുക്കുക';

  @override
  String get deleteAccount => 'അക്കൗണ്ട് നീക്കം ചെയ്യുക';

  @override
  String get permanentlyDeleteAccount =>
      'നിങ്ങളുടെ അക്കൗണ്ട് സ്ഥിരമായി നീക്കം ചെയ്യുക';

  @override
  String get deleteLocalData => 'ലോക്കൽ ഡാറ്റ നീക്കുക';

  @override
  String get deleteLocalDataOnDevice =>
      'ഈ ഡിവൈസിലെ ചാറ്റുകളും സേവ് ചെയ്ത സെറ്റിംഗുകളും നീക്കുക';

  @override
  String get clearLocalDataQuestion => 'ലോക്കൽ ഡാറ്റ നീക്കണോ?';

  @override
  String get clearLocalDataBody =>
      'ഇത് ഈ ഡിവൈസിൽ ലോക്കലായി സൂക്ഷിച്ചിരിക്കുന്ന ആപ്പ് ഡാറ്റ (സേവ് ചെയ്ത സെറ്റിംഗുകൾ, ക്യാഷ് ചെയ്ത പ്രൊഫൈൽ ഫീൽഡുകൾ, മെമ്മറിയിലെ ചാറ്റ് ചരിത്രം) നീക്കും.\n\nഎല്ലാ മാറ്റങ്ങളും പ്രാബല്യത്തിൽ വരാൻ ആപ്പ് റീസ്റ്റാർട്ട് ചെയ്യേണ്ടിവന്നേക്കാം.';

  @override
  String get clear => 'നീക്കുക';

  @override
  String get localDataCleared => 'ലോക്കൽ ഡാറ്റ നീക്കി';

  @override
  String get couldNotClearLocalData => 'ലോക്കൽ ഡാറ്റ നീക്കാനായില്ല';

  @override
  String get accountDeletionNotAvailable =>
      'ഈ പ്ലാറ്റ്‌ഫോമിൽ അക്കൗണ്ട് നീക്കം ചെയ്യൽ ലഭ്യമല്ല';

  @override
  String get noSignedInAccountFound => 'ലോഗിൻ ചെയ്ത അക്കൗണ്ട് കണ്ടെത്തിയില്ല';

  @override
  String get deleteAccountQuestion => 'അക്കൗണ്ട് നീക്കണോ?';

  @override
  String get deleteAccountBody =>
      'ഇത് നിങ്ങളുടെ അക്കൗണ്ട് സ്ഥിരമായി നീക്കും. നിങ്ങൾ ഈ ഡിവൈസിൽ നിന്ന് ലോഗ് ഔട്ട് ചെയ്യപ്പെടും.';

  @override
  String get deletingAccount => 'അക്കൗണ്ട് നീക്കുന്നു...';

  @override
  String get pleaseLoginAgainThenDelete =>
      'ദയവായി വീണ്ടും ലോഗിൻ ചെയ്ത് അക്കൗണ്ട് നീക്കുക';

  @override
  String get couldNotDeleteAccount => 'അക്കൗണ്ട് നീക്കാനായില്ല';

  @override
  String get networkSlowTryAgain =>
      'നെറ്റ്‌വർക്കിന് വൈകുന്നു. ദയവായി വീണ്ടും ശ്രമിക്കുക.';

  @override
  String get defaultUser => 'ഉപയോക്താവ്';

  @override
  String userIdLine(Object id) {
    return 'ഉപയോക്തൃ ID: $id';
  }

  @override
  String get clinicsNearYou => 'Clinics Near You';

  @override
  String get refresh => 'Refresh';

  @override
  String get recenter => 'Re-center';

  @override
  String resultsCount(Object count) {
    return 'Results ($count)';
  }

  @override
  String get nearbyClinics => 'Nearby clinics';

  @override
  String get call => 'Call';

  @override
  String get navigate => 'Navigate';

  @override
  String get unableToOpenDialer => 'Unable to open dialer';

  @override
  String get unableToOpenMaps => 'Unable to open maps';

  @override
  String get radius => 'Radius';

  @override
  String get tryAgain => 'Try again';

  @override
  String get openLocationSettings => 'Open location settings';

  @override
  String get locationServicesDisabled =>
      'Location services are disabled. Please enable GPS.';

  @override
  String get locationPermissionDenied => 'Location permission denied.';

  @override
  String get locationPermissionDeniedForever =>
      'Location permission permanently denied. Enable it from Settings.';

  @override
  String get chooseLanguage => 'ഭാഷ തിരഞ്ഞെടുക്കുക';

  @override
  String get cancel => 'റദ്ദാക്കുക';

  @override
  String get save => 'സംരക്ഷിക്കുക';

  @override
  String get contactUs => 'ബന്ധപ്പെടുക';

  @override
  String get needHelp => 'സഹായം വേണോ?';

  @override
  String get contactSubtitle =>
      'ഞങ്ങൾക്ക് ഒരു സന്ദേശം അയക്കൂ; ഞങ്ങളുടെ ടീം മറുപടി നൽകും.';

  @override
  String supportEmailLine(Object email) {
    return 'സപ്പോർട്ട് ഇമെയിൽ: $email';
  }

  @override
  String get typicalResponseLine => 'സാധാരണ മറുപടി: 24 മണിക്കൂറിനകം';

  @override
  String get language => 'Language';

  @override
  String languageSetTo(Object language) {
    return 'Language set to $language';
  }

  @override
  String get fullName => 'പൂർണ്ണ പേര്';

  @override
  String get yourName => 'നിങ്ങളുടെ പേര്';

  @override
  String get email => 'ഇമെയിൽ';

  @override
  String get emailHint => 'name@example.com';

  @override
  String get phoneOptional => 'ഫോൺ (ഐച്ഛികം)';

  @override
  String get yourMobileNumber => 'നിങ്ങളുടെ മൊബൈൽ നമ്പർ';

  @override
  String get subject => 'വിഷയം';

  @override
  String get subjectHint => 'ഇത് എന്തിനെക്കുറിച്ചാണ്?';

  @override
  String get message => 'സന്ദേശം';

  @override
  String get messageHint => 'നിങ്ങളുടെ പ്രശ്നം അല്ലെങ്കിൽ ചോദ്യം വിവരിക്കുക';

  @override
  String get send => 'അയയ്ക്കുക';

  @override
  String get sentSuccess => 'അയച്ചു! ഞങ്ങൾ ഉടൻ മറുപടി നൽകും.';

  @override
  String get required => 'ആവശ്യമാണ്';

  @override
  String get enterValidEmail => 'സാധുവായ ഇമെയിൽ നൽകുക';

  @override
  String get writeMoreDetail => 'ദയവായി കൂടുതൽ വിശദമായി എഴുതുക';

  @override
  String get couldNotOpenEmailApp => 'ഇമെയിൽ ആപ്പ് തുറക്കാനായില്ല.';

  @override
  String get couldNotSendTryLater =>
      'അയക്കാനായില്ല. ദയവായി പിന്നീട് വീണ്ടും ശ്രമിക്കുക.';

  @override
  String get tipNoShareOtp =>
      'ടിപ്പ്: ഇവിടെ പാസ്‌വേഡ് അല്ലെങ്കിൽ OTP പങ്കിടരുത്.';

  @override
  String get loginLanguageLabel => 'English / हिंदी';

  @override
  String get loginHeroSubtitle => 'Your health companion';

  @override
  String get loginMobileNumberLabel => 'Mobile Number';

  @override
  String get loginMobileHint => '00000 00000';

  @override
  String get loginEmailLabel => 'Email Address';

  @override
  String get loginPasswordLabel => 'Password';

  @override
  String get loginPasswordHint => 'Enter password';

  @override
  String get loginPleaseWait => 'Please wait...';

  @override
  String get loginSendOtp => 'Send OTP';

  @override
  String get loginContinue => 'Continue';

  @override
  String get loginSendingOtp => 'Sending OTP...';

  @override
  String get loginOr => 'OR';

  @override
  String get loginContinueAsGuest => 'Continue as Guest';

  @override
  String get loginAgreementText =>
      'By logging in, you agree to MediMitra\'s\nTerms of Service and Privacy Policy.';

  @override
  String get loginUnableContinueGuest => 'Unable to continue as guest.';

  @override
  String get loginEnterMobileNumber => 'Enter mobile number.';

  @override
  String get loginEnterValidMobileNumber =>
      'Enter a valid 10-digit mobile number.';

  @override
  String get loginOtpSent => 'OTP sent.';

  @override
  String get loginFailedSendOtp => 'Failed to send OTP.';

  @override
  String get loginEnterValidEmail => 'Enter a valid email.';

  @override
  String get loginPasswordMinChars => 'Password must be at least 6 characters.';

  @override
  String get loginEmailPasswordDisabled =>
      'Email/Password sign-in is disabled in Firebase Console.';

  @override
  String get loginAccountExistsTryLogin =>
      'Account already exists. Try logging in.';

  @override
  String get loginWeakPassword => 'Password is too weak (min 6 chars).';

  @override
  String get loginIncorrectPassword => 'Incorrect password.';

  @override
  String get loginInvalidEmail => 'Invalid email.';

  @override
  String get loginLoginFailed => 'Login failed.';

  @override
  String get otpVerifyNumber => 'Verify Number';

  @override
  String get otpSentTo => 'We have sent a 6-digit code to';

  @override
  String get otpHaventReceived => 'Haven\'t received the code?';

  @override
  String get otpResendCode => 'Resend Code';

  @override
  String get otpVerifyProceed => 'Verify & Proceed';

  @override
  String get otpVerifying => 'Verifying...';

  @override
  String get otpEnter6Digit => 'Enter 6-digit OTP.';

  @override
  String get otpInvalid => 'Invalid OTP.';

  @override
  String get otpVerificationFailed => 'OTP verification failed.';

  @override
  String get otpFailedResend => 'Failed to resend code.';

  @override
  String get otpCodeResent => 'Code resent.';

  @override
  String get otpSafetyFirst => 'SAFETY FIRST';

  @override
  String get otpSafetyNote =>
      'Securely connect to your healthcare records with MediMitra’s encryption.';

  @override
  String get communityOutbreakAlerts => 'Community Outbreak Alerts';

  @override
  String get outbreakPrivacyNote =>
      'Privacy-first: only aggregated symptom counts by PIN3 and day. No names, chat text, GPS, or exact timestamps.';

  @override
  String get regionNotSet => 'Region: Not set';

  @override
  String regionPin3Line(Object region) {
    return 'Region: $region (PIN3)';
  }

  @override
  String get set => 'Set';

  @override
  String get setAreaPin3Title => 'Set your area (PIN3)';

  @override
  String get setAreaPin3Body =>
      'Enter your PIN code. We only store the first 3 digits (coarse region).';

  @override
  String get pinExampleHint => 'e.g. 411001';

  @override
  String get enterFirst3DigitsPin =>
      'Enter at least first 3 digits of your PIN.';

  @override
  String get unableToSaveRegion => 'Unable to save region.';

  @override
  String get setPin3ToSeeAlerts =>
      'Set your PIN3 to see outbreak alerts for your area.';

  @override
  String get noAlertsToday => 'No alerts today for your area.';

  @override
  String get prevention => 'Prevention';

  @override
  String get outbreakLevelHighRisk => 'High Risk';

  @override
  String get outbreakLevelWarning => 'Warning';

  @override
  String get outbreakLevelWatch => 'Watch';

  @override
  String get outbreakLevelNone => 'None';

  @override
  String get back => 'Back';

  @override
  String get next => 'Next';

  @override
  String get couldNotSaveConsent =>
      'Could not save your consent. Please try again.';

  @override
  String get termsSigningTitle => 'Terms of Service';

  @override
  String get termsSigningIntro =>
      'Before using the symptom assessment, please accept the Terms of Service and Privacy Policy. Please note:';

  @override
  String get termsBulletNotDiagnosisTitle => 'The result is not a diagnosis.';

  @override
  String get termsBulletNotDiagnosisBody =>
      ' It’s only for your information and not a qualified medical opinion.';

  @override
  String get termsBulletNoEmergencyTitle =>
      'Do not use it in case of an emergency.';

  @override
  String get termsBulletNoEmergencyBody =>
      ' Call your local emergency number right away when there’s a health emergency.';

  @override
  String get termsBulletDataSafeTitle => 'Your data is safe.';

  @override
  String get termsBulletDataSafeBody =>
      ' The information you give won’t be shared or used to identify you.';

  @override
  String get termsConsentTermsPrefix => 'I have read and accept the ';

  @override
  String get termsConsentTermsLink => 'Terms of Service';

  @override
  String get termsConsentTermsSuffix => '.';

  @override
  String get termsConsentPrivacyPrefix =>
      'I agree for my health information to be used for the interview. More information in the ';

  @override
  String get termsConsentPrivacyLink => 'Privacy Policy';

  @override
  String get termsConsentPrivacySuffix => '.';

  @override
  String get quickQuestions => 'Quick questions';

  @override
  String get typeAQuestionHint => 'Type a question…';

  @override
  String get talkToMaya => 'Talk to Maya';

  @override
  String get womensHealthHubTitle => 'Women\'s Health Hub';

  @override
  String get womensHealthHubWelcome => 'Welcome to your health journey';

  @override
  String get womensHealthHubSubtitle =>
      'Select a category to explore resources and get personalized care.';

  @override
  String get menstrualHealth => 'Menstrual Health';

  @override
  String get pregnancyAndMaternal => 'Pregnancy & Maternal';

  @override
  String get breastHealth => 'Breast Health';

  @override
  String get comingSoon => 'Coming soon';

  @override
  String get womensHealthHubTagline => 'MEDIMITRA WELLNESS';

  @override
  String get womensHealthCategoryMenstrualDescription =>
      'നിങ്ങളുടെ മാസചക്രം മനസിലാക്കുക,\nശുചിത്വം പഠിക്കുക, കൂടാതെ\nപീരിയഡ്സ് എളുപ്പത്തിൽ നിയന്ത്രിക്കുക.';

  @override
  String get womensHealthCategoryPregnancyDescription =>
      'ആരോഗ്യമുള്ള ഗർഭധാരണത്തിനായി വിദഗ്ധ മാർഗനിർദ്ദേശം,\nപോഷകാഹാര നിർദേശങ്ങൾ, കൂടാതെ\nസുരക്ഷിത പ്രസവത്തിന് പിന്തുണ.';

  @override
  String get womensHealthCategoryBreastDescription =>
      'ലളിതമായ സ്വയം പരിശോധന മാർഗനിർദ്ദേശങ്ങൾ\nകൂടാതെ അവബോധ നിർദേശങ്ങൾ\nമുൻകരുതൽ കണ്ടെത്തലിനും പരിചരണത്തിനും.';

  @override
  String get recommended => 'ശുപാർശ ചെയ്തത്';

  @override
  String get explore => 'അന്വേഷിക്കുക';

  @override
  String get menstrualScreenTitle => 'മാസികാരോഗ്യം';

  @override
  String get menstrualWhatIsMenstruationTitle => 'മാസികധർമ്മം എന്താണ്?';

  @override
  String get menstrualWhatIsMenstruationBody =>
      'മാസികധർമ്മം ശരീരം ഗർഭാശയത്തിന്റെ ഉള്ളലയം പുറത്താക്കുന്ന സ്വാഭാവികമായ മാസപ്രക്രിയയാണ്. ഇത് ആരോഗ്യമുള്ള പ്രജനന സംവിധാനത്തിന്റെ അടയാളവും വളർച്ചയിലെ സാധാരണ ഭാഗവുമാണ്.';

  @override
  String get menstrualQuote => 'പ്രജനനത്തിന്റെയും ജീവിതത്തിന്റെയും ചക്രം';

  @override
  String get menstrualWhatIsNormalTitle => 'എന്താണ് സാധാരം?';

  @override
  String get menstrualNormalItem1 => 'ചക്രം 21 മുതൽ 35 ദിവസങ്ങൾ വരെ';

  @override
  String get menstrualNormalItem2 => 'രക്തസ്രാവം 3 മുതൽ 7 ദിവസം വരെ';

  @override
  String get menstrualNormalItem3 => 'ലഘുവിൽ നിന്ന് മിതമായ മുറിവ്/അസൗകര്യം';

  @override
  String get menstrualWarningSignsTitle => 'മുന്നറിയിപ്പ് ലക്ഷണങ്ങൾ';

  @override
  String get menstrualWarningItem1 =>
      'കടുത്ത രക്തസ്രാവം കാരണം ഓരോ 1–2 മണിക്കൂറിലും പാഡ് മാറ്റേണ്ടിവരുന്നത്';

  @override
  String get menstrualWarningItem2 =>
      'ദൈനംദിന പ്രവർത്തനങ്ങൾ തടസപ്പെടുന്നത്ര ശക്തമായ വേദന';

  @override
  String get menstrualWarningItem3 =>
      'ചക്രം സ്ഥിരമായി 21 ദിവസത്തിൽ കുറവോ 38 ദിവസത്തിൽ കൂടുതലോ ആകുന്നത്';

  @override
  String get menstrualHygieneTipsTitle => 'ശുചിത്വ നിർദേശങ്ങൾ';

  @override
  String get menstrualTipChangeRegularlyTitle => 'നിയമിതമായി മാറ്റുക';

  @override
  String get menstrualTipChangeRegularlySubtitle =>
      'ഓരോ 4–6 മണിക്കൂറിലും പാഡ് മാറ്റുക';

  @override
  String get menstrualTipCleanHandsTitle => 'കൈകൾ ശുചിയായി';

  @override
  String get menstrualTipCleanHandsSubtitle => 'മുമ്പും ശേഷവും കൈ കഴുകുക';

  @override
  String get menstrualTipStayDryTitle => 'ഉണങ്ങിയതായി സൂക്ഷിക്കുക';

  @override
  String get menstrualTipStayDrySubtitle =>
      'ജനനേന്ദ്രിയ ഭാഗം ശുചിയായി, ഉണങ്ങിയതായി സൂക്ഷിക്കുക';

  @override
  String get menstrualMythsFactsTitle => 'മിഥ്യകൾ & സത്യങ്ങൾ';

  @override
  String get menstrualMyth1 =>
      'മിഥ്യ: \"പീരിയഡ്സ് സമയത്ത് വ്യായാമം ചെയ്യരുത്.\"';

  @override
  String get menstrualFact1 =>
      'സത്യം: ലഘുവായ വ്യായാമം വേദന കുറയ്ക്കുകയും മനോഭാവം മെച്ചപ്പെടുത്തുകയും ചെയ്യാം.';

  @override
  String get menstrualMyth2 => 'മിഥ്യ: \"മാസിക രക്തം \'അശുദ്ധ\' രക്തമാണ്.\"';

  @override
  String get menstrualFact2 =>
      'സത്യം: അത് ഗർഭാശയത്തിന്റെ ഉള്ളലയത്തിൽ നിന്ന് വരുന്ന സാധാരണ രക്തവും കുഴിഞ്ഞ കണികകളും ആണ്.';

  @override
  String get chatHeaderTitle => 'ആരോഗ്യ സഹായി';

  @override
  String get chatHeaderStatusOnline => 'ഓൺലൈൻ';

  @override
  String get chatToday => 'ഇന്ന്';

  @override
  String get chatQuickChipCheckFever => '🌡️ ജ്വരം പരിശോധിക്കുക';

  @override
  String get chatQuickPromptCheckFever => 'എനിക്ക് ജ്വരം പരിശോധിക്കണം.';

  @override
  String get chatQuickChipWomensHealth => '🤰 സ്ത്രീാരോഗ്യം';

  @override
  String get chatQuickPromptWomensHealth =>
      'എനിക്ക് സ്ത്രീാരോഗ്യം സംബന്ധിച്ച് ഒരു ചോദ്യം ഉണ്ട്.';

  @override
  String get chatQuickChipFirstAid => '🩹 പ്രാഥമിക ശുശ്രൂഷ';

  @override
  String get chatQuickPromptFirstAid =>
      'എനിക്ക് പ്രാഥമിക ശുശ്രൂഷാ ഉപദേശം വേണം.';

  @override
  String get chatQuickChipChildCare => '👶 കുട്ടികളുടെ പരിചരണം';

  @override
  String get chatQuickPromptChildCare =>
      'എനിക്ക് കുട്ടികളുടെ പരിചരണ മാർഗ്ഗനിർദ്ദേശം വേണം.';

  @override
  String get chatInputHintAskMeAnything => 'എന്തെങ്കിലും ചോദിക്കൂ...';

  @override
  String get profileSaved => 'പ്രൊഫൈൽ സേവ് ചെയ്തു';

  @override
  String get saving => 'സേവ് ചെയ്യുന്നു...';

  @override
  String get saveChanges => 'മാറ്റങ്ങൾ സേവ് ചെയ്യുക';

  @override
  String get profileTopBarTitle => 'പ്രൊഫൈൽ സെറ്റിംഗുകൾ';

  @override
  String get profileHeaderSubtitle => 'ഉപയോക്തൃ പ്രൊഫൈൽ';

  @override
  String get profileSectionFullName => 'പൂർണ്ണ പേര്';

  @override
  String get profileHintFullName => 'ഉദാ. രാഹുൽ ശർമ്മ';

  @override
  String get profileSectionAge => 'വയസ്സ്';

  @override
  String get profileHintAge => 'നിങ്ങളുടെ വയസ്സ് നൽകുക';

  @override
  String get profileSectionGender => 'ലിംഗം';

  @override
  String get profileGenderMale => 'പുരുഷൻ';

  @override
  String get profileGenderFemale => 'സ്ത്രീ';

  @override
  String get profileGenderOther => 'മറ്റ്';

  @override
  String get profileChronicConditions => 'ദീർഘകാല രോഗങ്ങൾ';

  @override
  String get profileConditionsBadge => 'ദ്വിഭാഷാ';

  @override
  String get conditionDiabetesTitle => 'പ്രമേഹം';

  @override
  String get conditionDiabetesSubtitle => 'ഡയബറ്റീസ് (ഷുഗർ)';

  @override
  String get conditionBpHeartTitle => 'BP & ഹൃദയം';

  @override
  String get conditionBpHeartSubtitle => 'രക്തസമ്മർദം / ഹൃദയം';

  @override
  String get conditionAsthmaTitle => 'ആസ്ത്മ';

  @override
  String get conditionAsthmaSubtitle => 'ശ്വാസം';

  @override
  String get conditionThyroidTitle => 'തൈറോയ്ഡ്';

  @override
  String get conditionThyroidSubtitle => 'തൈറോയ്ഡ്';

  @override
  String get conditionTbTitle => 'TB';

  @override
  String get conditionTbSubtitle => 'ക്ഷയം';

  @override
  String get conditionNoneTitle => 'ഒന്നുമില്ല';

  @override
  String get conditionNoneSubtitle => 'രോഗമൊന്നുമില്ല';

  @override
  String get helpFaqBotGreeting =>
      'ഹായ്! ഞാൻ MediMitra Help. ലക്ഷണ പരിശോധന, വോയ്സ് ഇൻപുട്ട്, ഔട്ട്‌ബ്രേക്ക് അലർട്ടുകൾ, ക്ലിനിക്കുകൾ, ലോഗിൻ, അല്ലെങ്കിൽ സ്വകാര്യത എന്നിവയെ കുറിച്ച് എന്തും ചോദിക്കാം.\n\nകുറിപ്പ്: ഇത് മെഡിക്കൽ ഉപദേശം അല്ല. അടിയന്തരാവസ്ഥയാണെങ്കിൽ, പ്രാദേശിക അടിയന്തര സേവനങ്ങളെ ബന്ധപ്പെടുക.';

  @override
  String get helpFaqSuggestionCheckSymptoms => 'ലക്ഷണങ്ങൾ എങ്ങനെ പരിശോധിക്കും?';

  @override
  String get helpFaqSuggestionVoiceSymptoms =>
      'വോയ്സ് ലക്ഷണങ്ങൾ എങ്ങനെ പ്രവർത്തിക്കുന്നു?';

  @override
  String get helpFaqSuggestionOutbreakAlert =>
      'ഔട്ട്‌ബ്രേക്ക് അലർട്ട് എന്താണ്?';

  @override
  String get helpFaqSuggestionNearbyClinics =>
      'അടുത്തുള്ള ക്ലിനിക്കുകൾ എങ്ങനെ കണ്ടെത്താം?';

  @override
  String get helpFaqSuggestionOtpLogin => 'OTP ലോഗിൻ എങ്ങനെ പ്രവർത്തിക്കുന്നു?';

  @override
  String get helpFaqSuggestionDataSafe => 'എന്റെ ഡാറ്റ സുരക്ഷിതമാണോ?';

  @override
  String get helpFaqSuggestionGuestMode => 'ലോഗിൻ ഇല്ലാതെ ആപ്പ് ഉപയോഗിക്കാമോ?';

  @override
  String get helpFaqSuggestionChangeLanguage => 'ഭാഷ എങ്ങനെ മാറ്റാം?';

  @override
  String get helpFaqSuggestionDarkMode => 'ഡാർക്ക് മോഡ് എങ്ങനെ ഓൺ ചെയ്യാം?';

  @override
  String get helpFaqReplySymptomChecking =>
      'ലക്ഷണങ്ങൾ പരിശോധിക്കാൻ:\n1) ചാറ്റ് / ലക്ഷണ പരിശോധന തുറക്കുക\n2) നിങ്ങളുടെ ലക്ഷണങ്ങൾ ടൈപ്പ് ചെയ്യുക (അല്ലെങ്കിൽ വോയ്സ് ഉപയോഗിക്കുക)\n3) തുടര്‍ചോദ്യങ്ങള്‍ക്ക് ഉത്തരം നല്‍കുക\n\nMediMitra സാധ്യതയുള്ള കാരണങ്ങളും അടുത്ത നടപടികളും കാണിക്കും. ശക്തമായ ലക്ഷണങ്ങൾ (നെഞ്ചുവേദന, ശ്വാസംമുട്ടൽ, ബോധക്ഷയം) ഉണ്ടെങ്കിൽ ഉടൻ ചികിത്സ തേടുക.';

  @override
  String get helpFaqReplyVoiceSymptoms =>
      'വോയ്സ് ലക്ഷണങ്ങൾ: മൈക്ക് ടാപ്പ് ചെയ്ത് ലക്ഷണങ്ങൾ വ്യക്തമായി പറയുക; ആപ്പ് അത് ടെക്സ്റ്റാക്കി മാറ്റി വിശകലനം ചെയ്യും.\n\nടിപ്സ്: ഒരിക്കൽ ഒരു ലക്ഷണം മാത്രം പറയുക, ലളിതമായ വാക്കുകൾ ഉപയോഗിക്കുക (\"ജ്വരം\", \"ചുമ\") കൂടാതെ ചോദിക്കുമ്പോൾ മൈക്രോഫോൺ അനുമതി നൽകുക.';

  @override
  String get helpFaqReplyOutbreakAlert =>
      'ഔട്ട്‌ബ്രേക്ക് അലർട്ട് നിങ്ങളുടെ പ്രദേശത്ത് ചില ലക്ഷണങ്ങൾ ട്രെൻഡ് ആകുന്നുണ്ടോ എന്ന് കാണാൻ സഹായിക്കുന്നു. ഇത് അനാമധേയമായ, സംഗ്രഹിച്ച പാറ്റേണുകളിൽ അധിഷ്ഠിതമാണ്; ബോധവത്കരണത്തിനായി (റോഗനിർണയത്തിനല്ല).\n\nOutbreak വിഭാഗത്തിൽ ഇൻസൈറ്റുകൾ കാണാം.';

  @override
  String get helpFaqReplyNearbyClinics =>
      'അടുത്തുള്ള ക്ലിനിക്കുകൾ: ക്ലിനിക് ലൊക്കേറ്റർ തുറന്ന് നിങ്ങളുടെ ചുറ്റുമുള്ള ക്ലിനിക്കുകൾ കാണുക.\n\nലൊക്കേഷൻ അനുമതി പ്രവർത്തനക്ഷമമാണെന്ന് ഉറപ്പാക്കുക.';

  @override
  String get helpFaqReplyOtpLogin =>
      'OTP ലോഗിൻ: നിങ്ങളുടെ 10 അക്ക മൊബൈൽ നമ്പർ നൽകുക; ഞങ്ങൾ സ്ഥിരീകരണ OTP അയക്കും. 6 അക്ക OTP നൽകി തുടരുക.\n\nOTP ലഭിക്കാത്തപക്ഷം, റിസെൻഡ് ടൈമർ കഴിഞ്ഞ് വീണ്ടും ശ്രമിക്കുക; നെറ്റ്‌വർക്ക് പരിശോധിക്കുക.';

  @override
  String get helpFaqReplyGuestMode =>
      'ഗസ്റ്റ് മോഡിൽ ലോഗിൻ ഇല്ലാതെ ആപ്പ് ഉപയോഗിക്കാം. പക്ഷേ പ്രൊഫൈലിലേക്ക് സേവ് ചെയ്യുന്ന ചില ഫീച്ചറുകൾക്ക് പരിമിതി ഉണ്ടാകാം.';

  @override
  String get helpFaqReplyPrivacy =>
      'നിങ്ങളുടെ അനുഭവം വ്യക്തിഗതമാക്കാൻ (പേര്/വയസ്സ്/ലിംഗം/അവസ്ഥകൾ) പ്രൊഫൈൽ ഡാറ്റ സുരക്ഷിതമായി സൂക്ഷിക്കുന്നു. ചാറ്റിൽ സെൻസിറ്റീവ് വിവരങ്ങൾ പങ്കിടരുത്.\n\nകൃത്യമായ വിശദാംശങ്ങൾക്ക് ആപ്പിലെ സ്വകാര്യതാ നയം കാണുക.';

  @override
  String get helpFaqReplyChangeLanguage => 'ഭാഷ മാറ്റാൻ: പ്രൊഫൈൽ → ഭാഷ.';

  @override
  String get helpFaqReplyDarkMode =>
      'ഡാർക്ക് മോഡ്: പ്രൊഫൈൽ → ഡാർക്ക് മോഡ് ടോഗിൾ ഓൺ/ഓഫ് ചെയ്യുക.';

  @override
  String get helpFaqReplyContactSupport =>
      'പിന്തുണയെ ബന്ധപ്പെടാൻ: Contact Us തുറന്ന് സന്ദേശം അയയ്ക്കുക. കഴിയുമെങ്കിൽ സ്ക്രീൻഷോട്ടുകളും ഘട്ടങ്ങളും ചേർക്കുക.';

  @override
  String get helpFaqReplyFallback =>
      'ഞാൻ സഹായിക്കുന്നത്: ലക്ഷണ പരിശോധന, വോയ്സ് ഇൻപുട്ട്, ഔട്ട്‌ബ്രേക്ക് അലർട്ടുകൾ, ക്ലിനിക് ലൊക്കേറ്റർ, OTP ലോഗിൻ, സ്വകാര്യത, ഭാഷ, ഡാർക്ക് മോഡ്.\n\nഇവയിൽ ഒന്നുകൂടി ശ്രമിക്കുക: \"ലക്ഷണങ്ങൾ എങ്ങനെ പരിശോധിക്കും?\", \"അടുത്തുള്ള ക്ലിനിക്കുകൾ എങ്ങനെ കണ്ടെത്താം?\", \"എന്റെ ഡാറ്റ സുരക്ഷിതമാണോ?\"';
}
