// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'MediMitra';

  @override
  String get close => 'Close';

  @override
  String get loginTagline => 'Simple healthcare for you and your family';

  @override
  String get smsLogin => 'SMS Login';

  @override
  String get emailLogin => 'Email Login';

  @override
  String get homeHello => 'Hello,';

  @override
  String get homeThere => 'there';

  @override
  String get homeChatCta => 'Discover our AI healthcare chat assistant';

  @override
  String get homeOurFeatures => 'Our Features';

  @override
  String get homeHighlights => 'Highlights';

  @override
  String get homeDisclaimerTitle => 'Disclaimer';

  @override
  String get homeDisclaimerBody =>
      'MediMitra is for informational purposes only and is not medical advice. It does not replace a doctor.\nIn case of serious symptoms or any medical emergency, please visit the nearest hospital or contact emergency services immediately.';

  @override
  String get featureSymptomChecker => 'Symptom Checker';

  @override
  String get featureWomensHealth => 'Women\'s Health awareness';

  @override
  String get featureInsurance => 'Insurance';

  @override
  String get featureAiHealthSummary => 'AI Health Summary';

  @override
  String get featureReminders => 'Reminders';

  @override
  String get featureLocateClinics => 'Locate clinics near you';

  @override
  String get promoAiSymptomCheckTitle => 'AI Symptom Check';

  @override
  String get promoAiSymptomCheckSubtitle =>
      'Describe symptoms, get guidance in seconds.';

  @override
  String get promoVoiceWaveformTitle => 'Voice + Waveform';

  @override
  String get promoVoiceWaveformSubtitle =>
      'Hands-free chat with voice input support.';

  @override
  String get promoProfilePersonalizationTitle => 'Profile Personalization';

  @override
  String get promoProfilePersonalizationSubtitle =>
      'Save age, gender, and conditions for better help.';

  @override
  String get promoNearbyClinicsTitle => 'Nearby Clinics';

  @override
  String get promoNearbyClinicsSubtitle =>
      'Find healthcare services near your location.';

  @override
  String get settings => 'Settings';

  @override
  String get supportAndInformation => 'Support & Information';

  @override
  String get notifications => 'Notifications';

  @override
  String get manageYourNotifications => 'Manage your notifications';

  @override
  String get notificationsEnabled => 'Notifications enabled';

  @override
  String get notificationsDisabled => 'Notifications disabled';

  @override
  String get couldNotUpdateNotifications => 'Could not update notifications';

  @override
  String get darkMode => 'Dark Mode';

  @override
  String get toggleDarkTheme => 'Toggle dark theme';

  @override
  String get helpAndFaq => 'Help & FAQ';

  @override
  String get getHelpAndAnswers => 'Get help and answers';

  @override
  String get getInTouchWithSupport => 'Get in touch with support';

  @override
  String get aboutMediMitra => 'About MediMitra';

  @override
  String versionLine(Object version) {
    return 'Version $version';
  }

  @override
  String get privacyPolicy => 'Privacy Policy';

  @override
  String get howWeProtectYourData => 'How we protect your data';

  @override
  String get termsAndConditions => 'Terms & Conditions';

  @override
  String get termsConditionsBody =>
      'Terms & Conditions\n\nBy downloading and using this application, you agree to comply with and be bound by these Terms and Conditions. If you do not agree with any part of these terms, you should discontinue using the app.\n\nThis application is designed to provide health-related information and decision-support guidance only. It is not a medical diagnostic tool and does not replace consultation with a qualified doctor or healthcare professional. All information provided by the app is for educational and support purposes, and users must always seek professional medical advice for diagnosis, treatment, or emergencies.\n\nUsers are responsible for providing accurate and honest information while using the app. The guidance generated by the system depends on the inputs provided by the user, and incorrect or incomplete information may lead to inaccurate results. The app should not be used as the sole basis for making medical decisions.\n\nThis application is not intended for emergency situations. In case of severe symptoms such as chest pain, difficulty breathing, loss of consciousness, or heavy bleeding, users must immediately contact local emergency services or visit the nearest hospital.\n\nTo the maximum extent permitted by law, the developers shall not be held liable for any direct or indirect damages arising from the use of this application. Use of the app is entirely at the user’s own risk, and no guarantee is made regarding the accuracy, completeness, or reliability of the information provided.\n\nUse of this application is also governed by our Privacy Policy. By continuing to use the app, you confirm that you have read, understood, and agreed to both the Privacy Policy and these Terms and Conditions.\n\nWe reserve the right to modify or update these Terms and Conditions at any time. Any changes will be displayed within the app, and continued use of the app after such changes indicates acceptance of the updated terms.';

  @override
  String get legalAgreement => 'Legal agreement';

  @override
  String get deleteData => 'Delete data';

  @override
  String get deleteChatsAndSavedSettings => 'Delete chats & saved settings';

  @override
  String get logOut => 'Log Out';

  @override
  String get logoutQuestion => 'Logout?';

  @override
  String get logoutReturnToLogin =>
      'You will be logged out and returned to the login screen.';

  @override
  String get chooseAnAction => 'Choose an action';

  @override
  String get deleteAccount => 'Delete account';

  @override
  String get permanentlyDeleteAccount => 'Permanently delete your account';

  @override
  String get deleteLocalData => 'Delete local data';

  @override
  String get deleteLocalDataOnDevice =>
      'Delete chats & saved settings on this device';

  @override
  String get clearLocalDataQuestion => 'Clear local data?';

  @override
  String get clearLocalDataBody =>
      'This will delete locally stored app data on this device (saved settings, cached profile fields, and chat history in memory).\n\nYou may need to restart the app to see all changes applied.';

  @override
  String get clear => 'Clear';

  @override
  String get localDataCleared => 'Local data cleared';

  @override
  String get couldNotClearLocalData => 'Could not clear local data';

  @override
  String get accountDeletionNotAvailable =>
      'Account deletion is not available on this platform';

  @override
  String get noSignedInAccountFound => 'No signed-in account found';

  @override
  String get deleteAccountQuestion => 'Delete account?';

  @override
  String get deleteAccountBody =>
      'This will permanently delete your account. You will be logged out from this device.';

  @override
  String get deletingAccount => 'Deleting account...';

  @override
  String get pleaseLoginAgainThenDelete =>
      'Please log in again, then delete your account';

  @override
  String get couldNotDeleteAccount => 'Could not delete account';

  @override
  String get networkSlowTryAgain => 'Network is slow. Please try again.';

  @override
  String get defaultUser => 'User';

  @override
  String userIdLine(Object id) {
    return 'User ID: $id';
  }

  @override
  String get clinicsNearYou => 'Clinics Near You';

  @override
  String get refresh => 'Refresh';

  @override
  String get recenter => 'Re-center';

  @override
  String resultsCount(Object count) {
    return 'Results ($count)';
  }

  @override
  String get nearbyClinics => 'Nearby clinics';

  @override
  String get call => 'Call';

  @override
  String get navigate => 'Navigate';

  @override
  String get unableToOpenDialer => 'Unable to open dialer';

  @override
  String get unableToOpenMaps => 'Unable to open maps';

  @override
  String get radius => 'Radius';

  @override
  String get tryAgain => 'Try again';

  @override
  String get openLocationSettings => 'Open location settings';

  @override
  String get locationServicesDisabled =>
      'Location services are disabled. Please enable GPS.';

  @override
  String get locationPermissionDenied => 'Location permission denied.';

  @override
  String get locationPermissionDeniedForever =>
      'Location permission permanently denied. Enable it from Settings.';

  @override
  String get chooseLanguage => 'Choose language';

  @override
  String get cancel => 'Cancel';

  @override
  String get save => 'Save';

  @override
  String get contactUs => 'Contact Us';

  @override
  String get needHelp => 'Need help?';

  @override
  String get contactSubtitle => 'Send us a message and our team will reply.';

  @override
  String supportEmailLine(Object email) {
    return 'Support email: $email';
  }

  @override
  String get typicalResponseLine => 'Typical response: within 24 hours';

  @override
  String get language => 'Language';

  @override
  String languageSetTo(Object language) {
    return 'Language set to $language';
  }

  @override
  String get fullName => 'Full Name';

  @override
  String get yourName => 'Your name';

  @override
  String get email => 'Email';

  @override
  String get emailHint => 'name@example.com';

  @override
  String get phoneOptional => 'Phone (optional)';

  @override
  String get yourMobileNumber => 'Your mobile number';

  @override
  String get subject => 'Subject';

  @override
  String get subjectHint => 'What is this about?';

  @override
  String get message => 'Message';

  @override
  String get messageHint => 'Describe your issue or question';

  @override
  String get send => 'Send';

  @override
  String get sentSuccess => 'Sent! We will get back to you soon.';

  @override
  String get required => 'Required';

  @override
  String get enterValidEmail => 'Enter a valid email';

  @override
  String get writeMoreDetail => 'Please write a bit more detail';

  @override
  String get couldNotOpenEmailApp => 'Could not open email app.';

  @override
  String get couldNotSendTryLater => 'Could not send. Please try again later.';

  @override
  String get tipNoShareOtp => 'Tip: Don\'t share passwords or OTPs here.';

  @override
  String get loginLanguageLabel => 'English / हिंदी';

  @override
  String get loginHeroSubtitle => 'Your health companion';

  @override
  String get loginMobileNumberLabel => 'Mobile Number';

  @override
  String get loginMobileHint => '00000 00000';

  @override
  String get loginEmailLabel => 'Email Address';

  @override
  String get loginPasswordLabel => 'Password';

  @override
  String get loginPasswordHint => 'Enter password';

  @override
  String get loginPleaseWait => 'Please wait...';

  @override
  String get loginSendOtp => 'Send OTP';

  @override
  String get loginContinue => 'Continue';

  @override
  String get loginSendingOtp => 'Sending OTP...';

  @override
  String get loginOr => 'OR';

  @override
  String get loginContinueAsGuest => 'Continue as Guest';

  @override
  String get loginAgreementText =>
      'By logging in, you agree to MediMitra\'s\nTerms of Service and Privacy Policy.';

  @override
  String get loginUnableContinueGuest => 'Unable to continue as guest.';

  @override
  String get loginEnterMobileNumber => 'Enter mobile number.';

  @override
  String get loginEnterValidMobileNumber =>
      'Enter a valid 10-digit mobile number.';

  @override
  String get loginOtpSent => 'OTP sent.';

  @override
  String get loginFailedSendOtp => 'Failed to send OTP.';

  @override
  String get loginEnterValidEmail => 'Enter a valid email.';

  @override
  String get loginPasswordMinChars => 'Password must be at least 6 characters.';

  @override
  String get loginEmailPasswordDisabled =>
      'Email/Password sign-in is disabled in Firebase Console.';

  @override
  String get loginAccountExistsTryLogin =>
      'Account already exists. Try logging in.';

  @override
  String get loginWeakPassword => 'Password is too weak (min 6 chars).';

  @override
  String get loginIncorrectPassword => 'Incorrect password.';

  @override
  String get loginInvalidEmail => 'Invalid email.';

  @override
  String get loginLoginFailed => 'Login failed.';

  @override
  String get otpVerifyNumber => 'Verify Number';

  @override
  String get otpSentTo => 'We have sent a 6-digit code to';

  @override
  String get otpHaventReceived => 'Haven\'t received the code?';

  @override
  String get otpResendCode => 'Resend Code';

  @override
  String get otpVerifyProceed => 'Verify & Proceed';

  @override
  String get otpVerifying => 'Verifying...';

  @override
  String get otpEnter6Digit => 'Enter 6-digit OTP.';

  @override
  String get otpInvalid => 'Invalid OTP.';

  @override
  String get otpVerificationFailed => 'OTP verification failed.';

  @override
  String get otpFailedResend => 'Failed to resend code.';

  @override
  String get otpCodeResent => 'Code resent.';

  @override
  String get otpSafetyFirst => 'SAFETY FIRST';

  @override
  String get otpSafetyNote =>
      'Securely connect to your healthcare records with MediMitra’s encryption.';

  @override
  String get communityOutbreakAlerts => 'Community Outbreak Alerts';

  @override
  String get outbreakPrivacyNote =>
      'Privacy-first: only aggregated symptom counts by PIN3 and day. No names, chat text, GPS, or exact timestamps.';

  @override
  String get regionNotSet => 'Region: Not set';

  @override
  String regionPin3Line(Object region) {
    return 'Region: $region (PIN3)';
  }

  @override
  String get set => 'Set';

  @override
  String get setAreaPin3Title => 'Set your area (PIN3)';

  @override
  String get setAreaPin3Body =>
      'Enter your PIN code. We only store the first 3 digits (coarse region).';

  @override
  String get pinExampleHint => 'e.g. 411001';

  @override
  String get enterFirst3DigitsPin =>
      'Enter at least first 3 digits of your PIN.';

  @override
  String get unableToSaveRegion => 'Unable to save region.';

  @override
  String get setPin3ToSeeAlerts =>
      'Set your PIN3 to see outbreak alerts for your area.';

  @override
  String get noAlertsToday => 'No alerts today for your area.';

  @override
  String get prevention => 'Prevention';

  @override
  String get outbreakLevelHighRisk => 'High Risk';

  @override
  String get outbreakLevelWarning => 'Warning';

  @override
  String get outbreakLevelWatch => 'Watch';

  @override
  String get outbreakLevelNone => 'None';

  @override
  String get back => 'Back';

  @override
  String get next => 'Next';

  @override
  String get couldNotSaveConsent =>
      'Could not save your consent. Please try again.';

  @override
  String get termsSigningTitle => 'Terms of Service';

  @override
  String get termsSigningIntro =>
      'Before using the symptom assessment, please accept the Terms of Service and Privacy Policy. Please note:';

  @override
  String get termsBulletNotDiagnosisTitle => 'The result is not a diagnosis.';

  @override
  String get termsBulletNotDiagnosisBody =>
      ' It’s only for your information and not a qualified medical opinion.';

  @override
  String get termsBulletNoEmergencyTitle =>
      'Do not use it in case of an emergency.';

  @override
  String get termsBulletNoEmergencyBody =>
      ' Call your local emergency number right away when there’s a health emergency.';

  @override
  String get termsBulletDataSafeTitle => 'Your data is safe.';

  @override
  String get termsBulletDataSafeBody =>
      ' The information you give won’t be shared or used to identify you.';

  @override
  String get termsConsentTermsPrefix => 'I have read and accept the ';

  @override
  String get termsConsentTermsLink => 'Terms of Service';

  @override
  String get termsConsentTermsSuffix => '.';

  @override
  String get termsConsentPrivacyPrefix =>
      'I agree for my health information to be used for the interview. More information in the ';

  @override
  String get termsConsentPrivacyLink => 'Privacy Policy';

  @override
  String get termsConsentPrivacySuffix => '.';

  @override
  String get quickQuestions => 'Quick questions';

  @override
  String get typeAQuestionHint => 'Type a question…';

  @override
  String get talkToMaya => 'Talk to Maya';

  @override
  String get womensHealthHubTitle => 'Women\'s Health Hub';

  @override
  String get womensHealthHubWelcome => 'Welcome to your health journey';

  @override
  String get womensHealthHubSubtitle =>
      'Select a category to explore resources and get personalized care.';

  @override
  String get menstrualHealth => 'Menstrual Health';

  @override
  String get pregnancyAndMaternal => 'Pregnancy & Maternal';

  @override
  String get breastHealth => 'Breast Health';

  @override
  String get comingSoon => 'Coming soon';

  @override
  String get womensHealthHubTagline => 'MEDIMITRA WELLNESS';

  @override
  String get womensHealthCategoryMenstrualDescription =>
      'Track your monthly cycle, learn\nabout hygiene, and manage\nperiods with ease.';

  @override
  String get womensHealthCategoryPregnancyDescription =>
      'Expert guidance for a healthy\npregnancy, nutrition tips, and\nsafe delivery support.';

  @override
  String get womensHealthCategoryBreastDescription =>
      'Simple self-examination guides\nand awareness tips for early\ndetection and care.';

  @override
  String get recommended => 'Recommended';

  @override
  String get explore => 'Explore';

  @override
  String get menstrualScreenTitle => 'Menstrual Health';

  @override
  String get menstrualWhatIsMenstruationTitle => 'What is Menstruation?';

  @override
  String get menstrualWhatIsMenstruationBody =>
      'Menstruation is a natural, monthly process where the body sheds the lining of the uterus. It is a sign of a healthy reproductive system and a normal part of growing up.';

  @override
  String get menstrualQuote => 'A cycle of renewal & life';

  @override
  String get menstrualWhatIsNormalTitle => 'What is Normal?';

  @override
  String get menstrualNormalItem1 => 'Cycle lasts between 21 to 35 days';

  @override
  String get menstrualNormalItem2 => 'Bleeding lasts for 3 to 7 days';

  @override
  String get menstrualNormalItem3 => 'Mild to moderate cramping or discomfort';

  @override
  String get menstrualWarningSignsTitle => 'Warning Signs';

  @override
  String get menstrualWarningItem1 =>
      'Changing pads every 1–2 hours due to heavy flow';

  @override
  String get menstrualWarningItem2 =>
      'Severe pain that prevents you from daily activities';

  @override
  String get menstrualWarningItem3 =>
      'Cycles consistently shorter than 21 days or longer than 38 days';

  @override
  String get menstrualHygieneTipsTitle => 'Hygiene Tips';

  @override
  String get menstrualTipChangeRegularlyTitle => 'Change Regularly';

  @override
  String get menstrualTipChangeRegularlySubtitle =>
      'Replace pads every 4–6 hours';

  @override
  String get menstrualTipCleanHandsTitle => 'Clean Hands';

  @override
  String get menstrualTipCleanHandsSubtitle => 'Wash hands before and after';

  @override
  String get menstrualTipStayDryTitle => 'Stay Dry';

  @override
  String get menstrualTipStayDrySubtitle =>
      'Keep the genital area clean and dry';

  @override
  String get menstrualMythsFactsTitle => 'Myths & Facts';

  @override
  String get menstrualMyth1 =>
      'Myth: \"You shouldn\'t exercise during your period.\"';

  @override
  String get menstrualFact1 =>
      'Fact: Light exercise can actually help reduce cramps and improve mood.';

  @override
  String get menstrualMyth2 => 'Myth: \"Menstrual blood is \'dirty\' blood.\"';

  @override
  String get menstrualFact2 =>
      'Fact: It\'s just normal blood and tissue from the uterine lining.';

  @override
  String get chatHeaderTitle => 'Health Assistant';

  @override
  String get chatHeaderStatusOnline => 'Online';

  @override
  String get chatToday => 'TODAY';

  @override
  String get chatQuickChipCheckFever => '🌡️ Check Fever';

  @override
  String get chatQuickPromptCheckFever => 'I want to check fever.';

  @override
  String get chatQuickChipWomensHealth => '🤰 Women\'s Health';

  @override
  String get chatQuickPromptWomensHealth =>
      'I have a women\'s health question.';

  @override
  String get chatQuickChipFirstAid => '🩹 First Aid';

  @override
  String get chatQuickPromptFirstAid => 'I need first aid advice.';

  @override
  String get chatQuickChipChildCare => '👶 Child Care';

  @override
  String get chatQuickPromptChildCare => 'I need child care guidance.';

  @override
  String get chatInputHintAskMeAnything => 'Ask me anything...';

  @override
  String get profileSaved => 'Profile saved';

  @override
  String get saving => 'Saving...';

  @override
  String get saveChanges => 'Save Changes';

  @override
  String get profileTopBarTitle => 'Profile Settings';

  @override
  String get profileHeaderSubtitle => 'User Profile';

  @override
  String get profileSectionFullName => 'FULL NAME';

  @override
  String get profileHintFullName => 'e.g. Rahul Sharma';

  @override
  String get profileSectionAge => 'AGE';

  @override
  String get profileHintAge => 'Enter your age';

  @override
  String get profileSectionGender => 'GENDER';

  @override
  String get profileGenderMale => 'Male';

  @override
  String get profileGenderFemale => 'Female';

  @override
  String get profileGenderOther => 'Other';

  @override
  String get profileChronicConditions => 'CHRONIC CONDITIONS';

  @override
  String get profileConditionsBadge => 'BILINGUAL';

  @override
  String get conditionDiabetesTitle => 'Diabetes';

  @override
  String get conditionDiabetesSubtitle => 'Diabetes (Sugar)';

  @override
  String get conditionBpHeartTitle => 'BP & Heart';

  @override
  String get conditionBpHeartSubtitle => 'Blood pressure / Heart';

  @override
  String get conditionAsthmaTitle => 'Asthma';

  @override
  String get conditionAsthmaSubtitle => 'Breathing';

  @override
  String get conditionThyroidTitle => 'Thyroid';

  @override
  String get conditionThyroidSubtitle => 'Thyroid';

  @override
  String get conditionTbTitle => 'TB';

  @override
  String get conditionTbSubtitle => 'Tuberculosis';

  @override
  String get conditionNoneTitle => 'None';

  @override
  String get conditionNoneSubtitle => 'No conditions';

  @override
  String get helpFaqBotGreeting =>
      'Hi! I\'m MediMitra Help. Ask me anything about symptom checking, voice input, outbreak alerts, clinics, login, or privacy.\n\nNote: This is not medical advice. If you have a medical emergency, contact local emergency services.';

  @override
  String get helpFaqSuggestionCheckSymptoms => 'How do I check symptoms?';

  @override
  String get helpFaqSuggestionVoiceSymptoms => 'How do voice symptoms work?';

  @override
  String get helpFaqSuggestionOutbreakAlert => 'What is outbreak alert?';

  @override
  String get helpFaqSuggestionNearbyClinics => 'How to find nearby clinics?';

  @override
  String get helpFaqSuggestionOtpLogin => 'How does OTP login work?';

  @override
  String get helpFaqSuggestionDataSafe => 'Is my data safe?';

  @override
  String get helpFaqSuggestionGuestMode => 'Can I use the app without login?';

  @override
  String get helpFaqSuggestionChangeLanguage => 'How to change language?';

  @override
  String get helpFaqSuggestionDarkMode => 'How to enable dark mode?';

  @override
  String get helpFaqReplySymptomChecking =>
      'To check symptoms:\n1) Open Chat / Symptom Checker\n2) Type your symptoms (or use voice)\n3) Answer follow-up questions\n\nMediMitra will show likely causes and next steps. For severe symptoms (chest pain, trouble breathing, fainting), seek urgent care.';

  @override
  String get helpFaqReplyVoiceSymptoms =>
      'Voice symptoms: tap the microphone, speak your symptoms clearly, and the app converts it to text for analysis.\n\nTips: speak one symptom at a time, use simple words (\"fever\", \"cough\"), and allow microphone permission when asked.';

  @override
  String get helpFaqReplyOutbreakAlert =>
      'Outbreak alert helps you see if certain symptoms are trending in your area. It\'s based on anonymized, aggregated symptom patterns and is meant for awareness (not diagnosis).\n\nYou can view outbreak insights from the Outbreak section.';

  @override
  String get helpFaqReplyNearbyClinics =>
      'Nearby clinics: open the Clinic Locator to see clinics around you.\n\nMake sure Location permission is enabled. If you prefer, you can also search by area/city (if available on your build).';

  @override
  String get helpFaqReplyOtpLogin =>
      'OTP login: enter your 10-digit mobile number and we send a verification OTP. Enter the 6-digit OTP to proceed.\n\nIf you don\'t receive it, wait for the resend timer and try again. Also confirm network/SMS permissions.';

  @override
  String get helpFaqReplyGuestMode =>
      'Guest mode lets you explore the app without signing in. Some features that save to your profile (like personalized settings) may be limited until you log in.';

  @override
  String get helpFaqReplyPrivacy =>
      'Your profile data (like name/age/gender/conditions) is stored securely for your account to personalize your experience. We do not want you to share sensitive info in chat.\n\nFor exact details, check Privacy Policy (in the app).';

  @override
  String get helpFaqReplyChangeLanguage =>
      'You can change language from Profile → Language.';

  @override
  String get helpFaqReplyDarkMode =>
      'Dark mode: go to Profile → Dark Mode and toggle it on/off. Your choice is saved and works across the whole app.';

  @override
  String get helpFaqReplyContactSupport =>
      'Contact support: open Contact Us and send your message. Include screenshots and steps if possible.';

  @override
  String get helpFaqReplyFallback =>
      'I can help with: symptom checking, voice input, outbreak alerts, clinic locator, OTP login, privacy, language, and dark mode.\n\nTry one of these: \"How do I check symptoms?\", \"How to find nearby clinics?\", \"Is my data safe?\"';
}
