// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Urdu (`ur`).
class AppLocalizationsUr extends AppLocalizations {
  AppLocalizationsUr([String locale = 'ur']) : super(locale);

  @override
  String get appTitle => 'میڈیمیٹرا';

  @override
  String get close => 'بند کریں';

  @override
  String get loginTagline => 'آپ اور آپ کے خاندان کے لیے آسان صحت کی سہولت';

  @override
  String get smsLogin => 'ایس ایم ایس لاگ اِن';

  @override
  String get emailLogin => 'ای میل لاگ اِن';

  @override
  String get homeHello => 'السلام علیکم،';

  @override
  String get homeThere => 'وہاں';

  @override
  String get homeChatCta => 'ہمارے AI ہیلتھ چیٹ اسسٹنٹ کو آزمائیں';

  @override
  String get homeOurFeatures => 'ہماری خصوصیات';

  @override
  String get homeHighlights => 'اہم نکات';

  @override
  String get homeDisclaimerTitle => 'اعلانِ دستبرداری';

  @override
  String get homeDisclaimerBody =>
      'MediMitra صرف معلوماتی مقاصد کے لیے ہے اور طبی مشورہ نہیں۔ یہ ڈاکٹر کا متبادل نہیں۔\nشدید علامات یا ایمرجنسی کی صورت میں قریب ترین ہسپتال جائیں یا فوراً ہنگامی سروسز سے رابطہ کریں۔';

  @override
  String get featureSymptomChecker => 'علامات چیکر';

  @override
  String get featureWomensHealth => 'خواتین کی صحت کی آگاہی';

  @override
  String get featureInsurance => 'انشورنس';

  @override
  String get featureAiHealthSummary => 'AI صحت خلاصہ';

  @override
  String get featureReminders => 'یاد دہانیاں';

  @override
  String get featureLocateClinics => 'قریب کے کلینکس تلاش کریں';

  @override
  String get promoAiSymptomCheckTitle => 'AI علامات چیک';

  @override
  String get promoAiSymptomCheckSubtitle =>
      'علامات بیان کریں، چند سیکنڈ میں رہنمائی حاصل کریں۔';

  @override
  String get promoVoiceWaveformTitle => 'وائس + ویوفارم';

  @override
  String get promoVoiceWaveformSubtitle => 'وائس اِن پٹ کے ساتھ ہینڈز فری چیٹ۔';

  @override
  String get promoProfilePersonalizationTitle => 'پروفائل پرسنلائزیشن';

  @override
  String get promoProfilePersonalizationSubtitle =>
      'بہتر مدد کے لیے عمر، جنس اور حالتیں محفوظ کریں۔';

  @override
  String get promoNearbyClinicsTitle => 'قریب کے کلینکس';

  @override
  String get promoNearbyClinicsSubtitle =>
      'اپنے مقام کے قریب صحت کی سہولیات تلاش کریں۔';

  @override
  String get settings => 'سیٹنگز';

  @override
  String get supportAndInformation => 'سپورٹ اور معلومات';

  @override
  String get notifications => 'اطلاعات';

  @override
  String get manageYourNotifications => 'اپنی اطلاعات مینیج کریں';

  @override
  String get notificationsEnabled => 'اطلاعات فعال ہیں';

  @override
  String get notificationsDisabled => 'اطلاعات غیر فعال ہیں';

  @override
  String get couldNotUpdateNotifications => 'اطلاعات اپ ڈیٹ نہیں ہو سکیں';

  @override
  String get darkMode => 'ڈارک موڈ';

  @override
  String get toggleDarkTheme => 'ڈارک تھیم آن/آف کریں';

  @override
  String get helpAndFaq => 'مدد اور سوالات';

  @override
  String get getHelpAndAnswers => 'مدد اور جوابات حاصل کریں';

  @override
  String get getInTouchWithSupport => 'سپورٹ سے رابطہ کریں';

  @override
  String get aboutMediMitra => 'MediMitra کے بارے میں';

  @override
  String versionLine(Object version) {
    return 'ورژن $version';
  }

  @override
  String get privacyPolicy => 'پرائیویسی پالیسی';

  @override
  String get howWeProtectYourData => 'ہم آپ کے ڈیٹا کی حفاظت کیسے کرتے ہیں';

  @override
  String get termsAndConditions => 'شرائط و ضوابط';

  @override
  String get termsConditionsBody =>
      'Terms & Conditions\n\nBy downloading and using this application, you agree to comply with and be bound by these Terms and Conditions. If you do not agree with any part of these terms, you should discontinue using the app.\n\nThis application is designed to provide health-related information and decision-support guidance only. It is not a medical diagnostic tool and does not replace consultation with a qualified doctor or healthcare professional. All information provided by the app is for educational and support purposes, and users must always seek professional medical advice for diagnosis, treatment, or emergencies.\n\nUsers are responsible for providing accurate and honest information while using the app. The guidance generated by the system depends on the inputs provided by the user, and incorrect or incomplete information may lead to inaccurate results. The app should not be used as the sole basis for making medical decisions.\n\nThis application is not intended for emergency situations. In case of severe symptoms such as chest pain, difficulty breathing, loss of consciousness, or heavy bleeding, users must immediately contact local emergency services or visit the nearest hospital.\n\nTo the maximum extent permitted by law, the developers shall not be held liable for any direct or indirect damages arising from the use of this application. Use of the app is entirely at the user’s own risk, and no guarantee is made regarding the accuracy, completeness, or reliability of the information provided.\n\nUse of this application is also governed by our Privacy Policy. By continuing to use the app, you confirm that you have read, understood, and agreed to both the Privacy Policy and these Terms and Conditions.\n\nWe reserve the right to modify or update these Terms and Conditions at any time. Any changes will be displayed within the app, and continued use of the app after such changes indicates acceptance of the updated terms.';

  @override
  String get legalAgreement => 'قانونی معاہدہ';

  @override
  String get deleteData => 'ڈیٹا حذف کریں';

  @override
  String get deleteChatsAndSavedSettings => 'چیٹس اور محفوظ سیٹنگز حذف کریں';

  @override
  String get logOut => 'لاگ آؤٹ';

  @override
  String get logoutQuestion => 'لاگ آؤٹ کریں؟';

  @override
  String get logoutReturnToLogin =>
      'آپ لاگ آؤٹ ہو کر لاگ اِن اسکرین پر واپس جائیں گے۔';

  @override
  String get chooseAnAction => 'ایک عمل منتخب کریں';

  @override
  String get deleteAccount => 'اکاؤنٹ حذف کریں';

  @override
  String get permanentlyDeleteAccount => 'اپنا اکاؤنٹ مستقل طور پر حذف کریں';

  @override
  String get deleteLocalData => 'لوکل ڈیٹا حذف کریں';

  @override
  String get deleteLocalDataOnDevice =>
      'اس ڈیوائس پر چیٹس اور محفوظ سیٹنگز حذف کریں';

  @override
  String get clearLocalDataQuestion => 'لوکل ڈیٹا صاف کریں؟';

  @override
  String get clearLocalDataBody =>
      'یہ اس ڈیوائس پر لوکل طور پر محفوظ ایپ ڈیٹا (محفوظ سیٹنگز، کیشڈ پروفائل فیلڈز، اور میموری میں چیٹ ہسٹری) حذف کر دے گا۔\n\nتمام تبدیلیوں کے لاگو ہونے کے لیے ایپ ری اسٹارٹ کرنا پڑ سکتا ہے۔';

  @override
  String get clear => 'صاف کریں';

  @override
  String get localDataCleared => 'لوکل ڈیٹا صاف ہو گیا';

  @override
  String get couldNotClearLocalData => 'لوکل ڈیٹا صاف نہیں ہو سکا';

  @override
  String get accountDeletionNotAvailable =>
      'اس پلیٹ فارم پر اکاؤنٹ حذف کرنا دستیاب نہیں';

  @override
  String get noSignedInAccountFound => 'کوئی سائن اِن اکاؤنٹ نہیں ملا';

  @override
  String get deleteAccountQuestion => 'اکاؤنٹ حذف کریں؟';

  @override
  String get deleteAccountBody =>
      'یہ آپ کا اکاؤنٹ مستقل طور پر حذف کر دے گا۔ آپ اس ڈیوائس سے لاگ آؤٹ ہو جائیں گے۔';

  @override
  String get deletingAccount => 'اکاؤنٹ حذف ہو رہا ہے...';

  @override
  String get pleaseLoginAgainThenDelete =>
      'براہِ کرم دوبارہ لاگ اِن کریں، پھر اکاؤنٹ حذف کریں';

  @override
  String get couldNotDeleteAccount => 'اکاؤنٹ حذف نہیں ہو سکا';

  @override
  String get networkSlowTryAgain =>
      'نیٹ ورک سست ہے۔ براہِ کرم دوبارہ کوشش کریں۔';

  @override
  String get defaultUser => 'صارف';

  @override
  String userIdLine(Object id) {
    return 'صارف ID: $id';
  }

  @override
  String get clinicsNearYou => 'آپ کے قریب کلینکس';

  @override
  String get refresh => 'ری فریش';

  @override
  String get recenter => 'دوبارہ مرکز میں';

  @override
  String resultsCount(Object count) {
    return 'نتائج ($count)';
  }

  @override
  String get nearbyClinics => 'قریب کے کلینکس';

  @override
  String get call => 'کال';

  @override
  String get navigate => 'راستہ';

  @override
  String get unableToOpenDialer => 'ڈائلر نہیں کھل سکا';

  @override
  String get unableToOpenMaps => 'نقشہ نہیں کھل سکا';

  @override
  String get radius => 'رداس';

  @override
  String get tryAgain => 'دوبارہ کوشش کریں';

  @override
  String get openLocationSettings => 'لوکیشن سیٹنگز کھولیں';

  @override
  String get locationServicesDisabled =>
      'لوکیشن سروسز بند ہیں۔ براہِ کرم GPS فعال کریں۔';

  @override
  String get locationPermissionDenied => 'لوکیشن کی اجازت مسترد کر دی گئی۔';

  @override
  String get locationPermissionDeniedForever =>
      'لوکیشن کی اجازت مستقل طور پر مسترد ہے۔ سیٹنگز سے فعال کریں۔';

  @override
  String get chooseLanguage => 'زبان منتخب کریں';

  @override
  String get cancel => 'منسوخ کریں';

  @override
  String get save => 'محفوظ کریں';

  @override
  String get contactUs => 'ہم سے رابطہ کریں';

  @override
  String get needHelp => 'مدد چاہیے؟';

  @override
  String get contactSubtitle => 'ہمیں پیغام بھیجیں اور ہماری ٹیم جواب دے گی۔';

  @override
  String supportEmailLine(Object email) {
    return 'سپورٹ ای میل: $email';
  }

  @override
  String get typicalResponseLine => 'عام جواب: 24 گھنٹوں کے اندر';

  @override
  String get language => 'زبان';

  @override
  String languageSetTo(Object language) {
    return 'زبان $language پر سیٹ ہو گئی';
  }

  @override
  String get fullName => 'پورا نام';

  @override
  String get yourName => 'آپ کا نام';

  @override
  String get email => 'ای میل';

  @override
  String get emailHint => 'name@example.com';

  @override
  String get phoneOptional => 'فون (اختیاری)';

  @override
  String get yourMobileNumber => 'آپ کا موبائل نمبر';

  @override
  String get subject => 'موضوع';

  @override
  String get subjectHint => 'یہ کس بارے میں ہے؟';

  @override
  String get message => 'پیغام';

  @override
  String get messageHint => 'اپنا مسئلہ یا سوال بیان کریں';

  @override
  String get send => 'بھیجیں';

  @override
  String get sentSuccess => 'بھیج دیا گیا! ہم جلد آپ سے رابطہ کریں گے۔';

  @override
  String get required => 'ضروری';

  @override
  String get enterValidEmail => 'درست ای میل درج کریں';

  @override
  String get writeMoreDetail => 'براہِ کرم مزید تفصیل لکھیں';

  @override
  String get couldNotOpenEmailApp => 'ای میل ایپ نہیں کھل سکی۔';

  @override
  String get couldNotSendTryLater =>
      'بھیجا نہیں جا سکا۔ براہِ کرم بعد میں دوبارہ کوشش کریں۔';

  @override
  String get tipNoShareOtp => 'ٹِپ: یہاں پاس ورڈ یا OTP شیئر نہ کریں۔';

  @override
  String get loginLanguageLabel => 'English / हिंदी';

  @override
  String get loginHeroSubtitle => 'آپ کا صحت ساتھی';

  @override
  String get loginMobileNumberLabel => 'موبائل نمبر';

  @override
  String get loginMobileHint => '00000 00000';

  @override
  String get loginEmailLabel => 'ای میل ایڈریس';

  @override
  String get loginPasswordLabel => 'پاس ورڈ';

  @override
  String get loginPasswordHint => 'پاس ورڈ درج کریں';

  @override
  String get loginPleaseWait => 'براہِ کرم انتظار کریں...';

  @override
  String get loginSendOtp => 'OTP بھیجیں';

  @override
  String get loginContinue => 'جاری رکھیں';

  @override
  String get loginSendingOtp => 'OTP بھیجا جا رہا ہے...';

  @override
  String get loginOr => 'یا';

  @override
  String get loginContinueAsGuest => 'مہمان کے طور پر جاری رکھیں';

  @override
  String get loginAgreementText =>
      'لاگ اِن کر کے، آپ MediMitra کی\nTerms of Service اور Privacy Policy سے اتفاق کرتے ہیں۔';

  @override
  String get loginUnableContinueGuest =>
      'مہمان کے طور پر جاری نہیں رکھا جا سکا۔';

  @override
  String get loginEnterMobileNumber => 'موبائل نمبر درج کریں۔';

  @override
  String get loginEnterValidMobileNumber =>
      'درست 10 ہندسوں کا موبائل نمبر درج کریں۔';

  @override
  String get loginOtpSent => 'OTP بھیج دیا گیا۔';

  @override
  String get loginFailedSendOtp => 'OTP بھیجنے میں ناکامی۔';

  @override
  String get loginEnterValidEmail => 'درست ای میل درج کریں۔';

  @override
  String get loginPasswordMinChars => 'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے۔';

  @override
  String get loginEmailPasswordDisabled =>
      'Firebase Console میں Email/Password سائن اِن غیر فعال ہے۔';

  @override
  String get loginAccountExistsTryLogin =>
      'اکاؤنٹ پہلے سے موجود ہے۔ لاگ اِن کرنے کی کوشش کریں۔';

  @override
  String get loginWeakPassword => 'پاس ورڈ کمزور ہے (کم از کم 6 حروف)۔';

  @override
  String get loginIncorrectPassword => 'غلط پاس ورڈ۔';

  @override
  String get loginInvalidEmail => 'غلط ای میل۔';

  @override
  String get loginLoginFailed => 'لاگ اِن ناکام۔';

  @override
  String get otpVerifyNumber => 'نمبر کی تصدیق کریں';

  @override
  String get otpSentTo => 'ہم نے 6 ہندسوں کا کوڈ بھیجا ہے';

  @override
  String get otpHaventReceived => 'کوڈ موصول نہیں ہوا؟';

  @override
  String get otpResendCode => 'کوڈ دوبارہ بھیجیں';

  @override
  String get otpVerifyProceed => 'تصدیق کریں اور آگے بڑھیں';

  @override
  String get otpVerifying => 'تصدیق ہو رہی ہے...';

  @override
  String get otpEnter6Digit => '6 ہندسوں کا OTP درج کریں۔';

  @override
  String get otpInvalid => 'غلط OTP۔';

  @override
  String get otpVerificationFailed => 'OTP کی تصدیق ناکام۔';

  @override
  String get otpFailedResend => 'کوڈ دوبارہ بھیجنے میں ناکامی۔';

  @override
  String get otpCodeResent => 'کوڈ دوبارہ بھیج دیا گیا۔';

  @override
  String get otpSafetyFirst => 'حفاظت پہلے';

  @override
  String get otpSafetyNote =>
      'MediMitra کی انکرپشن کے ساتھ اپنے ہیلتھ ریکارڈز کو محفوظ طریقے سے جوڑیں۔';

  @override
  String get communityOutbreakAlerts => 'کمیونٹی آؤٹ بریک الرٹس';

  @override
  String get outbreakPrivacyNote =>
      'پرائیویسی فرسٹ: صرف PIN3 اور دن کے حساب سے مجموعی علامات کی گنتی۔ نام، چیٹ متن، GPS یا درست ٹائم اسٹیمپس شامل نہیں۔';

  @override
  String get regionNotSet => 'علاقہ: سیٹ نہیں';

  @override
  String regionPin3Line(Object region) {
    return 'علاقہ: $region (PIN3)';
  }

  @override
  String get set => 'سیٹ کریں';

  @override
  String get setAreaPin3Title => 'اپنا علاقہ (PIN3) سیٹ کریں';

  @override
  String get setAreaPin3Body =>
      'اپنا PIN کوڈ درج کریں۔ ہم صرف پہلے 3 ہندسے (موٹا علاقہ) محفوظ کرتے ہیں۔';

  @override
  String get pinExampleHint => 'مثال: 411001';

  @override
  String get enterFirst3DigitsPin =>
      'اپنے PIN کے کم از کم پہلے 3 ہندسے درج کریں۔';

  @override
  String get unableToSaveRegion => 'علاقہ محفوظ نہیں ہو سکا۔';

  @override
  String get setPin3ToSeeAlerts =>
      'اپنے علاقے کے آؤٹ بریک الرٹس دیکھنے کے لیے PIN3 سیٹ کریں۔';

  @override
  String get noAlertsToday => 'آج آپ کے علاقے کے لیے کوئی الرٹ نہیں۔';

  @override
  String get prevention => 'احتیاط';

  @override
  String get outbreakLevelHighRisk => 'زیادہ خطرہ';

  @override
  String get outbreakLevelWarning => 'انتباہ';

  @override
  String get outbreakLevelWatch => 'نگرانی';

  @override
  String get outbreakLevelNone => 'کوئی نہیں';

  @override
  String get back => 'واپس';

  @override
  String get next => 'اگلا';

  @override
  String get couldNotSaveConsent =>
      'آپ کی رضامندی محفوظ نہیں ہو سکی۔ براہِ کرم دوبارہ کوشش کریں۔';

  @override
  String get termsSigningTitle => 'Terms of Service';

  @override
  String get termsSigningIntro =>
      'علامات کے تجزیے سے پہلے، براہِ کرم Terms of Service اور Privacy Policy قبول کریں۔ براہِ کرم نوٹ کریں:';

  @override
  String get termsBulletNotDiagnosisTitle => 'نتیجہ تشخیص نہیں ہے۔';

  @override
  String get termsBulletNotDiagnosisBody =>
      ' یہ صرف معلومات کے لیے ہے، طبی رائے نہیں۔';

  @override
  String get termsBulletNoEmergencyTitle => 'ایمرجنسی میں استعمال نہ کریں۔';

  @override
  String get termsBulletNoEmergencyBody =>
      ' ایمرجنسی میں فوراً مقامی ہنگامی نمبر پر کال کریں۔';

  @override
  String get termsBulletDataSafeTitle => 'آپ کا ڈیٹا محفوظ ہے۔';

  @override
  String get termsBulletDataSafeBody =>
      ' آپ کی دی گئی معلومات شیئر یا شناخت کے لیے استعمال نہیں ہوگی۔';

  @override
  String get termsConsentTermsPrefix =>
      'میں نے پڑھ لیا ہے اور قبول کرتا/کرتی ہوں ';

  @override
  String get termsConsentTermsLink => 'Terms of Service';

  @override
  String get termsConsentTermsSuffix => '.';

  @override
  String get termsConsentPrivacyPrefix =>
      'میں اپنی صحت کی معلومات کو انٹرویو کے لیے استعمال کرنے کی اجازت دیتا/دیتی ہوں۔ مزید معلومات ';

  @override
  String get termsConsentPrivacyLink => 'Privacy Policy';

  @override
  String get termsConsentPrivacySuffix => ' میں موجود ہیں۔';

  @override
  String get quickQuestions => 'فوری سوالات';

  @override
  String get typeAQuestionHint => 'ایک سوال لکھیں…';

  @override
  String get talkToMaya => 'مایا سے بات کریں';

  @override
  String get womensHealthHubTitle => 'Women’s Health Hub';

  @override
  String get womensHealthHubWelcome => 'آپ کے صحت کے سفر میں خوش آمدید';

  @override
  String get womensHealthHubSubtitle =>
      'وسائل دیکھنے اور ذاتی نگہداشت کے لیے ایک زمرہ منتخب کریں۔';

  @override
  String get menstrualHealth => 'ماہواری کی صحت';

  @override
  String get pregnancyAndMaternal => 'حمل اور زچگی';

  @override
  String get breastHealth => 'چھاتی کی صحت';

  @override
  String get comingSoon => 'جلد آ رہا ہے';

  @override
  String get womensHealthHubTagline => 'MEDIMITRA WELLNESS';

  @override
  String get womensHealthCategoryMenstrualDescription =>
      'اپنے ماہواری کے چکر کو سمجھیں،\nصفائی سیکھیں اور\nپیریڈز کو آسانی سے مینیج کریں۔';

  @override
  String get womensHealthCategoryPregnancyDescription =>
      'صحت مند حمل کے لیے ماہر رہنمائی،\nغذائی تجاویز اور\nمحفوظ زچگی کی مدد۔';

  @override
  String get womensHealthCategoryBreastDescription =>
      'سادہ خود معائنہ رہنمائی\nاور آگاہی تجاویز\nجلدی شناخت اور نگہداشت کے لیے۔';

  @override
  String get recommended => 'تجویز کردہ';

  @override
  String get explore => 'دیکھیں';

  @override
  String get menstrualScreenTitle => 'ماہواری کی صحت';

  @override
  String get menstrualWhatIsMenstruationTitle => 'ماہواری کیا ہے؟';

  @override
  String get menstrualWhatIsMenstruationBody =>
      'ماہواری ایک قدرتی ماہانہ عمل ہے جس میں رحم کی اندرونی تہہ خارج ہوتی ہے۔ یہ صحت مند تولیدی نظام کی علامت اور بلوغت کا معمول کا حصہ ہے۔';

  @override
  String get menstrualQuote => 'تولید اور زندگی کا چکر';

  @override
  String get menstrualWhatIsNormalTitle => 'کیا معمول ہے؟';

  @override
  String get menstrualNormalItem1 => 'چکر 21 سے 35 دن کے درمیان';

  @override
  String get menstrualNormalItem2 => 'خون آنا 3 سے 7 دن';

  @override
  String get menstrualNormalItem3 => 'ہلکی سے درمیانی تک تکلیف/درد';

  @override
  String get menstrualWarningSignsTitle => 'خبردار کرنے والی علامات';

  @override
  String get menstrualWarningItem1 =>
      'زیادہ خون آنا (ہر 1–2 گھنٹے میں پیڈ بدلنا پڑے)';

  @override
  String get menstrualWarningItem2 => 'اتنا شدید درد کہ روزمرہ کام متاثر ہوں';

  @override
  String get menstrualWarningItem3 => 'چکر مسلسل 21 دن سے کم یا 38 دن سے زیادہ';

  @override
  String get menstrualHygieneTipsTitle => 'صفائی کے مشورے';

  @override
  String get menstrualTipChangeRegularlyTitle => 'باقاعدگی سے تبدیل کریں';

  @override
  String get menstrualTipChangeRegularlySubtitle =>
      'انفیکشن کے خطرے کو کم کرنے کے لیے پیڈ/ٹیمپون باقاعدگی سے بدلیں۔';

  @override
  String get menstrualTipCleanHandsTitle => 'ہاتھ صاف رکھیں';

  @override
  String get menstrualTipCleanHandsSubtitle =>
      'پیڈ بدلنے سے پہلے اور بعد میں ہاتھ دھوئیں۔';

  @override
  String get menstrualTipStayDryTitle => 'خشک رکھیں';

  @override
  String get menstrualTipStayDrySubtitle =>
      'صاف اور خشک اندرونی کپڑے استعمال کریں۔';

  @override
  String get menstrualMythsFactsTitle => 'غلط فہمیاں اور حقائق';

  @override
  String get menstrualMyth1 => 'غلط فہمی: ماہواری میں نہانا نہیں چاہیے۔';

  @override
  String get menstrualFact1 =>
      'حقیقت: صفائی برقرار رکھنے کے لیے نہانا مفید ہے۔';

  @override
  String get menstrualMyth2 => 'غلط فہمی: ماہواری کا مطلب بیمار ہونا ہے۔';

  @override
  String get menstrualFact2 =>
      'حقیقت: یہ ایک معمول کا حیاتیاتی عمل ہے۔ اگر بہت زیادہ درد یا بے قاعدگی ہو تو ڈاکٹر سے مشورہ کریں۔';

  @override
  String get chatHeaderTitle => 'مایا';

  @override
  String get chatHeaderStatusOnline => 'آن لائن';

  @override
  String get chatToday => 'آج';

  @override
  String get chatQuickChipCheckFever => 'بخار چیک';

  @override
  String get chatQuickPromptCheckFever => 'مجھے بخار ہے، کیا کروں؟';

  @override
  String get chatQuickChipWomensHealth => 'خواتین کی صحت';

  @override
  String get chatQuickPromptWomensHealth =>
      'ماہواری/خواتین کی صحت کے بارے میں مدد کریں۔';

  @override
  String get chatQuickChipFirstAid => 'ابتدائی طبی امداد';

  @override
  String get chatQuickPromptFirstAid =>
      'کٹ/جلن/موچ میں ابتدائی دیکھ بھال کیا ہو؟';

  @override
  String get chatQuickChipChildCare => 'بچوں کی دیکھ بھال';

  @override
  String get chatQuickPromptChildCare => 'بچے کو بخار/کھانسی ہو تو کیا کریں؟';

  @override
  String get chatInputHintAskMeAnything => 'کچھ بھی پوچھیں…';

  @override
  String get profileSaved => 'پروفائل محفوظ ہو گیا';

  @override
  String get saving => 'محفوظ ہو رہا ہے…';

  @override
  String get saveChanges => 'تبدیلیاں محفوظ کریں';

  @override
  String get profileTopBarTitle => 'پروفائل سیٹنگز';

  @override
  String get profileHeaderSubtitle => 'صارف پروفائل';

  @override
  String get profileSectionFullName => 'پورا نام';

  @override
  String get profileHintFullName => 'مثلاً: راہول شرما';

  @override
  String get profileSectionAge => 'عمر';

  @override
  String get profileHintAge => 'اپنی عمر درج کریں';

  @override
  String get profileSectionGender => 'جنس';

  @override
  String get profileGenderMale => 'مرد';

  @override
  String get profileGenderFemale => 'عورت';

  @override
  String get profileGenderOther => 'دیگر';

  @override
  String get profileChronicConditions => 'دائمی بیماریاں';

  @override
  String get profileConditionsBadge => 'دو لسانی';

  @override
  String get conditionDiabetesTitle => 'ذیابیطس';

  @override
  String get conditionDiabetesSubtitle => 'شوگر/ڈایابیٹیز';

  @override
  String get conditionBpHeartTitle => 'بلڈ پریشر اور دل';

  @override
  String get conditionBpHeartSubtitle => 'بلڈ پریشر / دل';

  @override
  String get conditionAsthmaTitle => 'دمہ';

  @override
  String get conditionAsthmaSubtitle => 'سانس';

  @override
  String get conditionThyroidTitle => 'تھائرائیڈ';

  @override
  String get conditionThyroidSubtitle => 'تھائرائیڈ';

  @override
  String get conditionTbTitle => 'ٹی بی';

  @override
  String get conditionTbSubtitle => 'تپِ دق';

  @override
  String get conditionNoneTitle => 'کوئی نہیں';

  @override
  String get conditionNoneSubtitle => 'کوئی بیماری نہیں';

  @override
  String get helpFaqBotGreeting =>
      'السلام علیکم! میں MediMitra Help ہوں۔ علامات چیکنگ، وائس اِن پٹ، آؤٹ بریک الرٹس، کلینکس، لاگ اِن یا پرائیویسی کے بارے میں کچھ بھی پوچھیں۔\n\nنوٹ: یہ طبی مشورہ نہیں۔ ایمرجنسی کی صورت میں مقامی ہنگامی سروسز سے رابطہ کریں۔';

  @override
  String get helpFaqSuggestionCheckSymptoms => 'میں علامات کیسے چیک کروں؟';

  @override
  String get helpFaqSuggestionVoiceSymptoms => 'وائس علامات کیسے کام کرتی ہیں؟';

  @override
  String get helpFaqSuggestionOutbreakAlert => 'آؤٹ بریک الرٹ کیا ہے؟';

  @override
  String get helpFaqSuggestionNearbyClinics => 'قریب کے کلینکس کیسے ڈھونڈیں؟';

  @override
  String get helpFaqSuggestionOtpLogin => 'OTP لاگ اِن کیسے کام کرتا ہے؟';

  @override
  String get helpFaqSuggestionDataSafe => 'کیا میرا ڈیٹا محفوظ ہے؟';

  @override
  String get helpFaqSuggestionGuestMode =>
      'کیا بغیر لاگ اِن کے ایپ استعمال کر سکتا/سکتی ہوں؟';

  @override
  String get helpFaqSuggestionChangeLanguage => 'زبان کیسے تبدیل کریں؟';

  @override
  String get helpFaqSuggestionDarkMode => 'ڈارک موڈ کیسے آن کریں؟';

  @override
  String get helpFaqReplySymptomChecking =>
      'علامات چیک کرنے کے لیے:\n1) چیٹ / علامات چیکر کھولیں\n2) اپنی علامات لکھیں (یا وائس استعمال کریں)\n3) فالو اپ سوالات کے جواب دیں\n\nMediMitra ممکنہ وجوہات اور اگلے قدم بتائے گا۔ شدید علامات (سینے میں درد، سانس میں دشواری، بے ہوشی) کی صورت میں فوری طبی امداد لیں۔';

  @override
  String get helpFaqReplyVoiceSymptoms =>
      'وائس علامات: مائیک پر ٹیپ کریں، اپنی علامات واضح بولیں، اور ایپ انہیں متن میں بدل کر تجزیہ کرے گی۔\n\nٹِپس: ایک وقت میں ایک علامت بولیں، سادہ الفاظ استعمال کریں (\"بخار\", \"کھانسی\") اور اجازت مانگے تو مائیک کی اجازت دیں۔';

  @override
  String get helpFaqReplyOutbreakAlert =>
      'آؤٹ بریک الرٹ آپ کے علاقے میں کچھ علامات کے بڑھنے (ٹرینڈ) کے بارے میں بتاتا ہے۔ یہ گمنام، مجموعی علامات کے پیٹرن پر مبنی ہے اور آگاہی کے لیے ہے (تشخیص کے لیے نہیں)۔\n\nOutbreak سیکشن میں ان سائٹس دیکھیں۔';

  @override
  String get helpFaqReplyNearbyClinics =>
      'قریب کے کلینکس: Clinic Locator کھولیں اور اپنے آس پاس کے کلینکس دیکھیں۔\n\nیقینی بنائیں کہ لوکیشن کی اجازت فعال ہے۔';

  @override
  String get helpFaqReplyOtpLogin =>
      'OTP لاگ اِن: اپنا 10 ہندسوں کا موبائل نمبر درج کریں اور ہم OTP بھیجیں گے۔ 6 ہندسوں کا OTP درج کر کے آگے بڑھیں۔\n\nاگر OTP نہ آئے تو ریسینڈ ٹائمر کے بعد دوبارہ کوشش کریں اور نیٹ ورک چیک کریں۔';

  @override
  String get helpFaqReplyGuestMode =>
      'گسٹ موڈ میں آپ بغیر سائن اِن کے ایپ استعمال کر سکتے ہیں۔ کچھ فیچرز جو پروفائل میں محفوظ ہوتے ہیں (جیسے پرسنلائزڈ سیٹنگز) لاگ اِن تک محدود ہو سکتے ہیں۔';

  @override
  String get helpFaqReplyPrivacy =>
      'آپ کے تجربے کو بہتر بنانے کے لیے (نام/عمر/جنس/حالات) پروفائل ڈیٹا محفوظ طریقے سے محفوظ ہوتا ہے۔ چیٹ میں حساس معلومات شیئر نہ کریں۔\n\nتفصیل کے لیے ایپ میں پرائیویسی پالیسی دیکھیں۔';

  @override
  String get helpFaqReplyChangeLanguage =>
      'زبان تبدیل کرنے کے لیے: Profile → Language۔';

  @override
  String get helpFaqReplyDarkMode =>
      'ڈارک موڈ: Profile → Dark Mode میں ٹوگل آن/آف کریں۔';

  @override
  String get helpFaqReplyContactSupport =>
      'سپورٹ سے رابطہ: Contact Us کھولیں اور پیغام بھیجیں۔ ممکن ہو تو اسکرین شاٹس اور مراحل شامل کریں۔';

  @override
  String get helpFaqReplyFallback =>
      'میں ان موضوعات میں مدد کر سکتا/سکتی ہوں: علامات چیکنگ، وائس اِن پٹ، آؤٹ بریک الرٹس، کلینک لوکیٹر، OTP لاگ اِن، پرائیویسی، زبان اور ڈارک موڈ۔\n\nیہ آزمائیں: \"میں علامات کیسے چیک کروں؟\", \"قریب کے کلینکس کیسے ڈھونڈیں؟\", \"کیا میرا ڈیٹا محفوظ ہے؟\"';
}
