// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Panjabi Punjabi (`pa`).
class AppLocalizationsPa extends AppLocalizations {
  AppLocalizationsPa([String locale = 'pa']) : super(locale);

  @override
  String get appTitle => 'ਮੇਡੀਮਿਤਰਾ';

  @override
  String get close => 'ਬੰਦ ਕਰੋ';

  @override
  String get loginTagline => 'ਤੁਹਾਡੇ ਅਤੇ ਤੁਹਾਡੇ ਪਰਿਵਾਰ ਲਈ ਸੌਖੀ ਸਿਹਤ ਸੇਵਾ';

  @override
  String get smsLogin => 'ਐੱਸਐੱਮਐੱਸ ਲਾਗਿਨ';

  @override
  String get emailLogin => 'ਈਮੇਲ ਲਾਗਿਨ';

  @override
  String get homeHello => 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ,';

  @override
  String get homeThere => 'ਦੋਸਤ';

  @override
  String get homeChatCta => 'ਸਾਡੇ AI ਹੈਲਥਕੇਅਰ ਚੈਟ ਸਹਾਇਕ ਨੂੰ ਜਾਣੋ';

  @override
  String get homeOurFeatures => 'ਸਾਡੇ ਫੀਚਰ';

  @override
  String get homeHighlights => 'ਮੁੱਖ ਖਾਸ ਗੱਲਾਂ';

  @override
  String get homeDisclaimerTitle => 'ਅਸਵੀਕਰਤੀ';

  @override
  String get homeDisclaimerBody =>
      'MediMitra ਸਿਰਫ਼ ਜਾਣਕਾਰੀ ਲਈ ਹੈ ਅਤੇ ਮੈਡੀਕਲ ਸਲਾਹ ਨਹੀਂ। ਇਹ ਡਾਕਟਰ ਦੀ ਥਾਂ ਨਹੀਂ ਲੈ ਸਕਦਾ।\nਗੰਭੀਰ ਲੱਛਣ ਜਾਂ ਕਿਸੇ ਵੀ ਮੈਡੀਕਲ ਇਮਰਜੈਂਸੀ ਵਿੱਚ, ਕਿਰਪਾ ਕਰਕੇ ਨੇੜਲੇ ਹਸਪਤਾਲ ਜਾਓ ਜਾਂ ਤੁਰੰਤ ਇਮਰਜੈਂਸੀ ਸੇਵਾਵਾਂ ਨਾਲ ਸੰਪਰਕ ਕਰੋ।';

  @override
  String get featureSymptomChecker => 'ਲੱਛਣ ਜਾਂਚ';

  @override
  String get featureWomensHealth => 'ਮਹਿਲਾ ਸਿਹਤ ਜਾਗਰੂਕਤਾ';

  @override
  String get featureInsurance => 'ਬੀਮਾ';

  @override
  String get featureAiHealthSummary => 'AI ਸਿਹਤ ਸਾਰ';

  @override
  String get featureReminders => 'ਰੀਮਾਈਂਡਰ';

  @override
  String get featureLocateClinics => 'ਨੇੜਲੇ ਕਲਿਨਿਕ ਲੱਭੋ';

  @override
  String get promoAiSymptomCheckTitle => 'AI ਲੱਛਣ ਜਾਂਚ';

  @override
  String get promoAiSymptomCheckSubtitle =>
      'ਲੱਛਣ ਦੱਸੋ, ਕੁਝ ਸਕਿੰਟਾਂ ਵਿੱਚ ਮਾਰਗਦਰਸ਼ਨ ਲਵੋ।';

  @override
  String get promoVoiceWaveformTitle => 'ਵੌਇਸ + ਵੇਵਫ਼ਾਰਮ';

  @override
  String get promoVoiceWaveformSubtitle => 'ਵੌਇਸ ਇਨਪੁੱਟ ਨਾਲ ਹੈਂਡਸ-ਫ੍ਰੀ ਚੈਟ।';

  @override
  String get promoProfilePersonalizationTitle => 'ਪ੍ਰੋਫ਼ਾਈਲ ਨਿੱਜੀਕਰਨ';

  @override
  String get promoProfilePersonalizationSubtitle =>
      'ਵਧੀਆ ਮਦਦ ਲਈ ਉਮਰ, ਲਿੰਗ ਅਤੇ ਹਾਲਤਾਂ ਸੇਵ ਕਰੋ।';

  @override
  String get promoNearbyClinicsTitle => 'ਨੇੜਲੇ ਕਲਿਨਿਕ';

  @override
  String get promoNearbyClinicsSubtitle => 'ਆਪਣੀ ਥਾਂ ਨੇੜੇ ਸਿਹਤ ਸੇਵਾਵਾਂ ਲੱਭੋ।';

  @override
  String get settings => 'ਸੈਟਿੰਗਜ਼';

  @override
  String get supportAndInformation => 'ਸਹਾਇਤਾ ਅਤੇ ਜਾਣਕਾਰੀ';

  @override
  String get notifications => 'ਸੂਚਨਾਵਾਂ';

  @override
  String get manageYourNotifications => 'ਆਪਣੀਆਂ ਸੂਚਨਾਵਾਂ ਪ੍ਰਬੰਧਿਤ ਕਰੋ';

  @override
  String get notificationsEnabled => 'ਸੂਚਨਾਵਾਂ ਚਾਲੂ ਹਨ';

  @override
  String get notificationsDisabled => 'ਸੂਚਨਾਵਾਂ ਬੰਦ ਹਨ';

  @override
  String get couldNotUpdateNotifications => 'ਸੂਚਨਾਵਾਂ ਅੱਪਡੇਟ ਨਹੀਂ ਹੋ ਸਕੀਆਂ';

  @override
  String get darkMode => 'ਡਾਰਕ ਮੋਡ';

  @override
  String get toggleDarkTheme => 'ਡਾਰਕ ਥੀਮ ਬਦਲੋ';

  @override
  String get helpAndFaq => 'ਮਦਦ ਅਤੇ FAQ';

  @override
  String get getHelpAndAnswers => 'ਮਦਦ ਅਤੇ ਜਵਾਬ ਲਵੋ';

  @override
  String get getInTouchWithSupport => 'ਸਪੋਰਟ ਨਾਲ ਸੰਪਰਕ ਕਰੋ';

  @override
  String get aboutMediMitra => 'MediMitra ਬਾਰੇ';

  @override
  String versionLine(Object version) {
    return 'ਵਰਜਨ $version';
  }

  @override
  String get privacyPolicy => 'ਪਰਦੇਦਾਰੀ ਨੀਤੀ';

  @override
  String get howWeProtectYourData =>
      'ਅਸੀਂ ਤੁਹਾਡੇ ਡਾਟੇ ਦੀ ਸੁਰੱਖਿਆ ਕਿਵੇਂ ਕਰਦੇ ਹਾਂ';

  @override
  String get termsAndConditions => 'ਨਿਯਮ ਅਤੇ ਸ਼ਰਤਾਂ';

  @override
  String get termsConditionsBody =>
      'Terms & Conditions\n\nBy downloading and using this application, you agree to comply with and be bound by these Terms and Conditions. If you do not agree with any part of these terms, you should discontinue using the app.\n\nThis application is designed to provide health-related information and decision-support guidance only. It is not a medical diagnostic tool and does not replace consultation with a qualified doctor or healthcare professional. All information provided by the app is for educational and support purposes, and users must always seek professional medical advice for diagnosis, treatment, or emergencies.\n\nUsers are responsible for providing accurate and honest information while using the app. The guidance generated by the system depends on the inputs provided by the user, and incorrect or incomplete information may lead to inaccurate results. The app should not be used as the sole basis for making medical decisions.\n\nThis application is not intended for emergency situations. In case of severe symptoms such as chest pain, difficulty breathing, loss of consciousness, or heavy bleeding, users must immediately contact local emergency services or visit the nearest hospital.\n\nTo the maximum extent permitted by law, the developers shall not be held liable for any direct or indirect damages arising from the use of this application. Use of the app is entirely at the user’s own risk, and no guarantee is made regarding the accuracy, completeness, or reliability of the information provided.\n\nUse of this application is also governed by our Privacy Policy. By continuing to use the app, you confirm that you have read, understood, and agreed to both the Privacy Policy and these Terms and Conditions.\n\nWe reserve the right to modify or update these Terms and Conditions at any time. Any changes will be displayed within the app, and continued use of the app after such changes indicates acceptance of the updated terms.';

  @override
  String get legalAgreement => 'ਕਾਨੂੰਨੀ ਸਮਝੌਤਾ';

  @override
  String get deleteData => 'ਡਾਟਾ ਮਿਟਾਓ';

  @override
  String get deleteChatsAndSavedSettings => 'ਚੈਟ ਅਤੇ ਸੇਵ ਕੀਤੀਆਂ ਸੈਟਿੰਗਾਂ ਮਿਟਾਓ';

  @override
  String get logOut => 'ਲਾਗ ਆਉਟ';

  @override
  String get logoutQuestion => 'ਲਾਗ ਆਉਟ ਕਰਨਾ ਹੈ?';

  @override
  String get logoutReturnToLogin =>
      'ਤੁਸੀਂ ਲਾਗ ਆਉਟ ਹੋ ਜਾਓਗੇ ਅਤੇ ਲਾਗਿਨ ਸਕ੍ਰੀਨ ਤੇ ਵਾਪਸ ਆ ਜਾਓਗੇ।';

  @override
  String get chooseAnAction => 'ਇੱਕ ਕਾਰਵਾਈ ਚੁਣੋ';

  @override
  String get deleteAccount => 'ਖਾਤਾ ਮਿਟਾਓ';

  @override
  String get permanentlyDeleteAccount => 'ਆਪਣਾ ਖਾਤਾ ਸਦਾ ਲਈ ਮਿਟਾਓ';

  @override
  String get deleteLocalData => 'ਲੋਕਲ ਡਾਟਾ ਮਿਟਾਓ';

  @override
  String get deleteLocalDataOnDevice =>
      'ਇਸ ਡਿਵਾਈਸ ਉਤੇ ਚੈਟ ਅਤੇ ਸੇਵ ਕੀਤੀਆਂ ਸੈਟਿੰਗਾਂ ਮਿਟਾਓ';

  @override
  String get clearLocalDataQuestion => 'ਲੋਕਲ ਡਾਟਾ ਸਾਫ ਕਰੀਏ?';

  @override
  String get clearLocalDataBody =>
      'ਇਸ ਨਾਲ ਇਸ ਡਿਵਾਈਸ ਉਤੇ ਲੋਕਲ ਤੌਰ ਤੇ ਸਟੋਰ ਕੀਤਾ ਐਪ ਡਾਟਾ (ਸੇਵ ਕੀਤੀਆਂ ਸੈਟਿੰਗਾਂ, ਕੈਸ਼ ਕੀਤੇ ਪ੍ਰੋਫ਼ਾਈਲ ਫੀਲਡ, ਅਤੇ ਮੈਮਰੀ ਵਿੱਚ ਚੈਟ ਹਿਸਟਰੀ) ਮਿਟ ਜਾਏਗਾ।\n\nਸਾਰੇ ਬਦਲਾਅ ਲਾਗੂ ਹੋਣ ਲਈ ਤੁਹਾਨੂੰ ਐਪ ਰੀਸਟਾਰਟ ਕਰਨਾ ਪੈ ਸਕਦਾ ਹੈ।';

  @override
  String get clear => 'ਸਾਫ ਕਰੋ';

  @override
  String get localDataCleared => 'ਲੋਕਲ ਡਾਟਾ ਸਾਫ ਹੋ ਗਿਆ';

  @override
  String get couldNotClearLocalData => 'ਲੋਕਲ ਡਾਟਾ ਸਾਫ ਨਹੀਂ ਹੋ ਸਕਿਆ';

  @override
  String get accountDeletionNotAvailable =>
      'ਇਸ ਪਲੇਟਫਾਰਮ ਉਤੇ ਖਾਤਾ ਮਿਟਾਉਣਾ ਉਪਲਬਧ ਨਹੀਂ';

  @override
  String get noSignedInAccountFound => 'ਕੋਈ ਸਾਈਨ-ਇਨ ਖਾਤਾ ਨਹੀਂ ਮਿਲਿਆ';

  @override
  String get deleteAccountQuestion => 'ਖਾਤਾ ਮਿਟਾਉਣਾ ਹੈ?';

  @override
  String get deleteAccountBody =>
      'ਇਸ ਨਾਲ ਤੁਹਾਡਾ ਖਾਤਾ ਸਦਾ ਲਈ ਮਿਟ ਜਾਏਗਾ। ਤੁਸੀਂ ਇਸ ਡਿਵਾਈਸ ਤੋਂ ਲਾਗ ਆਉਟ ਹੋ ਜਾਓਗੇ।';

  @override
  String get deletingAccount => 'ਖਾਤਾ ਮਿਟਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...';

  @override
  String get pleaseLoginAgainThenDelete =>
      'ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਲਾਗਿਨ ਕਰੋ, ਫਿਰ ਖਾਤਾ ਮਿਟਾਓ';

  @override
  String get couldNotDeleteAccount => 'ਖਾਤਾ ਮਿਟਾਇਆ ਨਹੀਂ ਜਾ ਸਕਿਆ';

  @override
  String get networkSlowTryAgain =>
      'ਨੈੱਟਵਰਕ ਹੌਲੀ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।';

  @override
  String get defaultUser => 'ਯੂਜ਼ਰ';

  @override
  String userIdLine(Object id) {
    return 'ਯੂਜ਼ਰ ਆਈਡੀ: $id';
  }

  @override
  String get clinicsNearYou => 'ਤੁਹਾਡੇ ਨੇੜੇ ਕਲਿਨਿਕ';

  @override
  String get refresh => 'ਰੀਫ੍ਰੈਸ਼';

  @override
  String get recenter => 'ਮੁੜ ਕੇਂਦਰਿਤ ਕਰੋ';

  @override
  String resultsCount(Object count) {
    return 'ਨਤੀਜੇ ($count)';
  }

  @override
  String get nearbyClinics => 'ਨੇੜਲੇ ਕਲਿਨਿਕ';

  @override
  String get call => 'ਕਾਲ';

  @override
  String get navigate => 'ਨੈਵੀਗੇਟ';

  @override
  String get unableToOpenDialer => 'ਡਾਇਲਰ ਨਹੀਂ ਖੁੱਲ ਸਕਿਆ';

  @override
  String get unableToOpenMaps => 'ਮੈਪ ਨਹੀਂ ਖੁੱਲ ਸਕੇ';

  @override
  String get radius => 'ਦਾਇਰਾ';

  @override
  String get tryAgain => 'ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ';

  @override
  String get openLocationSettings => 'ਲੋਕੇਸ਼ਨ ਸੈਟਿੰਗਜ਼ ਖੋਲ੍ਹੋ';

  @override
  String get locationServicesDisabled =>
      'ਲੋਕੇਸ਼ਨ ਸੇਵਾਵਾਂ ਬੰਦ ਹਨ। ਕਿਰਪਾ ਕਰਕੇ GPS ਚਾਲੂ ਕਰੋ।';

  @override
  String get locationPermissionDenied => 'ਲੋਕੇਸ਼ਨ ਪਰਮੀਸ਼ਨ ਰੱਦ ਹੋ ਗਈ।';

  @override
  String get locationPermissionDeniedForever =>
      'ਲੋਕੇਸ਼ਨ ਪਰਮੀਸ਼ਨ ਸਦਾ ਲਈ ਰੱਦ ਹੈ। ਸੈਟਿੰਗਜ਼ ਤੋਂ ਚਾਲੂ ਕਰੋ।';

  @override
  String get chooseLanguage => 'ਭਾਸ਼ਾ ਚੁਣੋ';

  @override
  String get cancel => 'ਰੱਦ ਕਰੋ';

  @override
  String get save => 'ਸੰਭਾਲੋ';

  @override
  String get contactUs => 'ਸੰਪਰਕ ਕਰੋ';

  @override
  String get needHelp => 'ਮਦਦ ਚਾਹੀਦੀ ਹੈ?';

  @override
  String get contactSubtitle => 'ਸਾਨੂੰ ਸੁਨੇਹਾ ਭੇਜੋ ਅਤੇ ਸਾਡੀ ਟੀਮ ਜਵਾਬ ਦੇਵੇਗੀ।';

  @override
  String supportEmailLine(Object email) {
    return 'ਸਪੋਰਟ ਈਮੇਲ: $email';
  }

  @override
  String get typicalResponseLine => 'ਆਮ ਜਵਾਬ: 24 ਘੰਟਿਆਂ ਵਿੱਚ';

  @override
  String get language => 'ਭਾਸ਼ਾ';

  @override
  String languageSetTo(Object language) {
    return 'ਭਾਸ਼ਾ ਸੈੱਟ ਹੋ ਗਈ: $language';
  }

  @override
  String get fullName => 'ਪੂਰਾ ਨਾਮ';

  @override
  String get yourName => 'ਤੁਹਾਡਾ ਨਾਮ';

  @override
  String get email => 'ਈਮੇਲ';

  @override
  String get emailHint => 'name@example.com';

  @override
  String get phoneOptional => 'ਫੋਨ (ਚੋਣਵਾਂ)';

  @override
  String get yourMobileNumber => 'ਤੁਹਾਡਾ ਮੋਬਾਈਲ ਨੰਬਰ';

  @override
  String get subject => 'ਵਿਸ਼ਾ';

  @override
  String get subjectHint => 'ਇਹ ਕਿਸ ਬਾਰੇ ਹੈ?';

  @override
  String get message => 'ਸੁਨੇਹਾ';

  @override
  String get messageHint => 'ਆਪਣੀ ਸਮੱਸਿਆ ਜਾਂ ਸਵਾਲ ਬਾਰੇ ਦੱਸੋ';

  @override
  String get send => 'ਭੇਜੋ';

  @override
  String get sentSuccess => 'ਭੇਜ ਦਿੱਤਾ! ਅਸੀਂ ਜਲਦੀ ਸੰਪਰਕ ਕਰਾਂਗੇ।';

  @override
  String get required => 'ਲਾਜ਼ਮੀ';

  @override
  String get enterValidEmail => 'ਠੀਕ ਈਮੇਲ ਦਰਜ ਕਰੋ';

  @override
  String get writeMoreDetail => 'ਕਿਰਪਾ ਕਰਕੇ ਹੋਰ ਕੁਝ ਵੇਰਵਾ ਲਿਖੋ';

  @override
  String get couldNotOpenEmailApp => 'ਈਮੇਲ ਐਪ ਨਹੀਂ ਖੁੱਲਿਆ।';

  @override
  String get couldNotSendTryLater =>
      'ਭੇਜਿਆ ਨਹੀਂ ਜਾ ਸਕਿਆ। ਬਾਅਦ ਵਿੱਚ ਕੋਸ਼ਿਸ਼ ਕਰੋ।';

  @override
  String get tipNoShareOtp => 'ਟਿਪ: ਇੱਥੇ ਪਾਸਵਰਡ ਜਾਂ OTP ਸਾਂਝਾ ਨਾ ਕਰੋ।';

  @override
  String get loginLanguageLabel => 'English / ਪੰਜਾਬੀ';

  @override
  String get loginHeroSubtitle => 'ਤੁਹਾਡਾ ਸਿਹਤ ਸਾਥੀ';

  @override
  String get loginMobileNumberLabel => 'ਮੋਬਾਈਲ ਨੰਬਰ';

  @override
  String get loginMobileHint => '00000 00000';

  @override
  String get loginEmailLabel => 'ਈਮੇਲ ਪਤਾ';

  @override
  String get loginPasswordLabel => 'ਪਾਸਵਰਡ';

  @override
  String get loginPasswordHint => 'ਪਾਸਵਰਡ ਦਰਜ ਕਰੋ';

  @override
  String get loginPleaseWait => 'ਕਿਰਪਾ ਕਰਕੇ ਉਡੀਕ ਕਰੋ...';

  @override
  String get loginSendOtp => 'OTP ਭੇਜੋ';

  @override
  String get loginContinue => 'ਜਾਰੀ ਰੱਖੋ';

  @override
  String get loginSendingOtp => 'OTP ਭੇਜਿਆ ਜਾ ਰਿਹਾ ਹੈ...';

  @override
  String get loginOr => 'ਜਾਂ';

  @override
  String get loginContinueAsGuest => 'ਗੈਸਟ ਵਜੋਂ ਜਾਰੀ ਰੱਖੋ';

  @override
  String get loginAgreementText =>
      'ਲਾਗਿਨ ਕਰਕੇ, ਤੁਸੀਂ MediMitra ਦੀਆਂ\nਸੇਵਾ ਸ਼ਰਤਾਂ ਅਤੇ ਪਰਦੇਦਾਰੀ ਨੀਤੀ ਨਾਲ ਸਹਿਮਤ ਹੋ।';

  @override
  String get loginUnableContinueGuest => 'ਗੈਸਟ ਵਜੋਂ ਜਾਰੀ ਨਹੀਂ ਹੋ ਸਕਿਆ।';

  @override
  String get loginEnterMobileNumber => 'ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ।';

  @override
  String get loginEnterValidMobileNumber =>
      'ਠੀਕ 10 ਅੰਕਾਂ ਵਾਲਾ ਮੋਬਾਈਲ ਨੰਬਰ ਦਰਜ ਕਰੋ।';

  @override
  String get loginOtpSent => 'OTP ਭੇਜ ਦਿੱਤਾ ਗਿਆ।';

  @override
  String get loginFailedSendOtp => 'OTP ਭੇਜਣ ਵਿੱਚ ਅਸਫ਼ਲ।';

  @override
  String get loginEnterValidEmail => 'ਠੀਕ ਈਮੇਲ ਦਰਜ ਕਰੋ।';

  @override
  String get loginPasswordMinChars =>
      'ਪਾਸਵਰਡ ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰਾਂ ਦਾ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।';

  @override
  String get loginEmailPasswordDisabled =>
      'Firebase Console ਵਿੱਚ Email/Password ਸਾਈਨ-ਇਨ ਬੰਦ ਹੈ।';

  @override
  String get loginAccountExistsTryLogin =>
      'ਖਾਤਾ ਪਹਿਲਾਂ ਤੋਂ ਮੌਜੂਦ ਹੈ। ਲਾਗਿਨ ਕਰਕੇ ਵੇਖੋ।';

  @override
  String get loginWeakPassword => 'ਪਾਸਵਰਡ ਕਮਜ਼ੋਰ ਹੈ (ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰ)।';

  @override
  String get loginIncorrectPassword => 'ਗਲਤ ਪਾਸਵਰਡ।';

  @override
  String get loginInvalidEmail => 'ਅਵੈਧ ਈਮੇਲ।';

  @override
  String get loginLoginFailed => 'ਲਾਗਿਨ ਅਸਫ਼ਲ।';

  @override
  String get otpVerifyNumber => 'ਨੰਬਰ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ';

  @override
  String get otpSentTo => 'ਅਸੀਂ 6 ਅੰਕਾਂ ਦਾ ਕੋਡ ਭੇਜਿਆ ਹੈ';

  @override
  String get otpHaventReceived => 'ਕੋਡ ਨਹੀਂ ਮਿਲਿਆ?';

  @override
  String get otpResendCode => 'ਕੋਡ ਮੁੜ ਭੇਜੋ';

  @override
  String get otpVerifyProceed => 'ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਅੱਗੇ ਵਧੋ';

  @override
  String get otpVerifying => 'ਪੁਸ਼ਟੀ ਹੋ ਰਹੀ ਹੈ...';

  @override
  String get otpEnter6Digit => '6 ਅੰਕਾਂ ਵਾਲਾ OTP ਦਰਜ ਕਰੋ।';

  @override
  String get otpInvalid => 'ਅਵੈਧ OTP।';

  @override
  String get otpVerificationFailed => 'OTP ਪੁਸ਼ਟੀ ਅਸਫ਼ਲ।';

  @override
  String get otpFailedResend => 'ਕੋਡ ਮੁੜ ਭੇਜਣ ਵਿੱਚ ਅਸਫ਼ਲ।';

  @override
  String get otpCodeResent => 'ਕੋਡ ਮੁੜ ਭੇਜ ਦਿੱਤਾ ਗਿਆ।';

  @override
  String get otpSafetyFirst => 'ਸੁਰੱਖਿਆ ਪਹਿਲਾਂ';

  @override
  String get otpSafetyNote =>
      'MediMitra ਦੀ ਐਨਕ੍ਰਿਪਸ਼ਨ ਨਾਲ ਆਪਣੇ ਹੈਲਥਕੇਅਰ ਰਿਕਾਰਡਸ ਨਾਲ ਸੁਰੱਖਿਅਤ ਤਰੀਕੇ ਨਾਲ ਜੁੜੋ।';

  @override
  String get communityOutbreakAlerts => 'ਕਮਿਊਨਿਟੀ ਫੈਲਾਅ ਅਲਰਟ';

  @override
  String get outbreakPrivacyNote =>
      'ਪਰਦੇਦਾਰੀ-ਪਹਿਲਾਂ: ਸਿਰਫ਼ PIN3 ਅਤੇ ਦਿਨ ਮੁਤਾਬਕ ਇਕੱਠੀਆਂ ਕੀਤੀਆਂ ਲੱਛਣ ਗਿਣਤੀਆਂ। ਕੋਈ ਨਾਮ, ਚੈਟ ਟੈਕਸਟ, GPS ਜਾਂ ਸਹੀ ਟਾਈਮਸਟੈਂਪ ਨਹੀਂ।';

  @override
  String get regionNotSet => 'ਖੇਤਰ: ਸੈੱਟ ਨਹੀਂ';

  @override
  String regionPin3Line(Object region) {
    return 'ਖੇਤਰ: $region (PIN3)';
  }

  @override
  String get set => 'ਸੈੱਟ ਕਰੋ';

  @override
  String get setAreaPin3Title => 'ਆਪਣਾ ਖੇਤਰ ਸੈੱਟ ਕਰੋ (PIN3)';

  @override
  String get setAreaPin3Body =>
      'ਆਪਣਾ PIN ਕੋਡ ਦਰਜ ਕਰੋ। ਅਸੀਂ ਸਿਰਫ਼ ਪਹਿਲੇ 3 ਅੰਕ (ਵੱਡਾ ਖੇਤਰ) ਹੀ ਸਟੋਰ ਕਰਦੇ ਹਾਂ।';

  @override
  String get pinExampleHint => 'ਜਿਵੇਂ 411001';

  @override
  String get enterFirst3DigitsPin =>
      'ਆਪਣੇ PIN ਦੇ ਘੱਟੋ-ਘੱਟ ਪਹਿਲੇ 3 ਅੰਕ ਦਰਜ ਕਰੋ।';

  @override
  String get unableToSaveRegion => 'ਖੇਤਰ ਸੇਵ ਨਹੀਂ ਹੋ ਸਕਿਆ।';

  @override
  String get setPin3ToSeeAlerts => 'ਆਪਣੇ ਖੇਤਰ ਲਈ ਅਲਰਟ ਵੇਖਣ ਲਈ PIN3 ਸੈੱਟ ਕਰੋ।';

  @override
  String get noAlertsToday => 'ਅੱਜ ਤੁਹਾਡੇ ਖੇਤਰ ਲਈ ਕੋਈ ਅਲਰਟ ਨਹੀਂ।';

  @override
  String get prevention => 'ਬਚਾਅ';

  @override
  String get outbreakLevelHighRisk => 'ਉੱਚ ਜੋਖਮ';

  @override
  String get outbreakLevelWarning => 'ਚੇਤਾਵਨੀ';

  @override
  String get outbreakLevelWatch => 'ਨਿਗਰਾਨੀ';

  @override
  String get outbreakLevelNone => 'ਕੋਈ ਨਹੀਂ';

  @override
  String get back => 'ਪਿੱਛੇ';

  @override
  String get next => 'ਅੱਗੇ';

  @override
  String get couldNotSaveConsent =>
      'ਤੁਹਾਡੀ ਸਹਿਮਤੀ ਸੇਵ ਨਹੀਂ ਹੋ ਸਕੀ। ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।';

  @override
  String get termsSigningTitle => 'ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ';

  @override
  String get termsSigningIntro =>
      'ਲੱਛਣ ਮੁਲਾਂਕਣ ਵਰਤਣ ਤੋਂ ਪਹਿਲਾਂ, ਕਿਰਪਾ ਕਰਕੇ ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ ਅਤੇ ਪਰਦੇਦਾਰੀ ਨੀਤੀ ਸਵੀਕਾਰ ਕਰੋ। ਕਿਰਪਾ ਕਰਕੇ ਧਿਆਨ ਦਿਓ:';

  @override
  String get termsBulletNotDiagnosisTitle => 'ਇਹ ਨਤੀਜਾ ਤਸ਼ਖੀਸ ਨਹੀਂ ਹੈ।';

  @override
  String get termsBulletNotDiagnosisBody =>
      ' ਇਹ ਸਿਰਫ਼ ਜਾਣਕਾਰੀ ਲਈ ਹੈ ਅਤੇ ਯੋਗ ਮੈਡੀਕਲ ਰਾਏ ਨਹੀਂ ਹੈ।';

  @override
  String get termsBulletNoEmergencyTitle =>
      'ਇਮਰਜੈਂਸੀ ਵਿੱਚ ਇਸਦਾ ਇਸਤੇਮਾਲ ਨਾ ਕਰੋ।';

  @override
  String get termsBulletNoEmergencyBody =>
      ' ਸਿਹਤ ਇਮਰਜੈਂਸੀ ਵਿੱਚ ਤੁਰੰਤ ਆਪਣੇ ਸਥਾਨਕ ਇਮਰਜੈਂਸੀ ਨੰਬਰ ਤੇ ਕਾਲ ਕਰੋ।';

  @override
  String get termsBulletDataSafeTitle => 'ਤੁਹਾਡਾ ਡਾਟਾ ਸੁਰੱਖਿਅਤ ਹੈ।';

  @override
  String get termsBulletDataSafeBody =>
      ' ਤੁਹਾਡੇ ਵੱਲੋਂ ਦਿੱਤੀ ਜਾਣਕਾਰੀ ਸਾਂਝੀ ਨਹੀਂ ਕੀਤੀ ਜਾਵੇਗੀ ਜਾਂ ਤੁਹਾਡੀ ਪਛਾਣ ਲਈ ਵਰਤੀ ਨਹੀਂ ਜਾਵੇਗੀ।';

  @override
  String get termsConsentTermsPrefix => 'ਮੈਂ ';

  @override
  String get termsConsentTermsLink => 'ਸੇਵਾ ਦੀਆਂ ਸ਼ਰਤਾਂ';

  @override
  String get termsConsentTermsSuffix =>
      ' ਪੜ੍ਹ ਲਈਆਂ ਹਨ ਅਤੇ ਸਵੀਕਾਰ ਕਰਦਾ/ਕਰਦੀ ਹਾਂ।';

  @override
  String get termsConsentPrivacyPrefix =>
      'ਮੈਂ ਆਪਣੀ ਸਿਹਤ ਜਾਣਕਾਰੀ ਇੰਟਰਵਿਊ ਲਈ ਵਰਤਣ ਲਈ ਸਹਿਮਤ ਹਾਂ। ਹੋਰ ਜਾਣਕਾਰੀ ';

  @override
  String get termsConsentPrivacyLink => 'ਪਰਦੇਦਾਰੀ ਨੀਤੀ';

  @override
  String get termsConsentPrivacySuffix => ' ਵਿੱਚ ਹੈ।';

  @override
  String get quickQuestions => 'ਤੁਰੰਤ ਪ੍ਰਸ਼ਨ';

  @override
  String get typeAQuestionHint => 'ਇੱਕ ਪ੍ਰਸ਼ਨ ਲਿਖੋ…';

  @override
  String get talkToMaya => 'ਮਾਇਆ ਨਾਲ ਗੱਲ ਕਰੋ';

  @override
  String get womensHealthHubTitle => 'ਮਹਿਲਾ ਸਿਹਤ ਹਬ';

  @override
  String get womensHealthHubWelcome => 'ਤੁਹਾਡੇ ਸਿਹਤ ਸਫ਼ਰ ਵਿੱਚ ਸੁਆਗਤ ਹੈ';

  @override
  String get womensHealthHubSubtitle =>
      'ਸਰੋਤ ਵੇਖਣ ਅਤੇ ਨਿੱਜੀ ਦੇਖਭਾਲ ਲਈ ਇੱਕ ਸ਼੍ਰੇਣੀ ਚੁਣੋ।';

  @override
  String get menstrualHealth => 'ਮਹਾਵਾਰੀ ਸਿਹਤ';

  @override
  String get pregnancyAndMaternal => 'ਗਰਭਾਵਸਥਾ ਅਤੇ ਮਾਤृत्व';

  @override
  String get breastHealth => 'ਛਾਤੀ ਸਿਹਤ';

  @override
  String get comingSoon => 'ਜਲਦ ਆ ਰਿਹਾ ਹੈ';

  @override
  String get womensHealthHubTagline => 'MEDIMITRA WELLNESS';

  @override
  String get womensHealthCategoryMenstrualDescription =>
      'ਆਪਣਾ ਮਾਸਿਕ ਚੱਕਰ ਸਮਝੋ,\nਸਫ਼ਾਈ ਬਾਰੇ ਜਾਣੋ, ਅਤੇ\nਪੀਰੀਅਡਜ਼ ਆਸਾਨੀ ਨਾਲ ਮੈਨੇਜ ਕਰੋ।';

  @override
  String get womensHealthCategoryPregnancyDescription =>
      'ਸਿਹਤਮੰਦ ਗਰਭਾਵਸਥਾ ਲਈ ਮਾਹਿਰ ਮਾਰਗਦਰਸ਼ਨ,\nਪੋਸ਼ਣ ਟਿੱਪਸ, ਅਤੇ\nਸੁਰੱਖਿਅਤ ਡਿਲਿਵਰੀ ਲਈ ਸਹਾਇਤਾ।';

  @override
  String get womensHealthCategoryBreastDescription =>
      'ਸੌਖੀਆਂ ਸਵੈ-ਜਾਂਚ ਗਾਈਡਾਂ\nਅਤੇ ਜਾਗਰੂਕਤਾ ਟਿੱਪਸ\nਸ਼ੁਰੂਆਤੀ ਪਛਾਣ ਅਤੇ ਦੇਖਭਾਲ ਲਈ।';

  @override
  String get recommended => 'ਸਿਫਾਰਸ਼ੀ';

  @override
  String get explore => 'ਐਕਸਪਲੋਰ ਕਰੋ';

  @override
  String get menstrualScreenTitle => 'ਮਹਾਵਾਰੀ ਸਿਹਤ';

  @override
  String get menstrualWhatIsMenstruationTitle => 'ਮਹਾਵਾਰੀ ਕੀ ਹੈ?';

  @override
  String get menstrualWhatIsMenstruationBody =>
      'ਮਹਾਵਾਰੀ ਇੱਕ ਕੁਦਰਤੀ, ਮਹੀਨਾਵਾਰ ਪ੍ਰਕਿਰਿਆ ਹੈ ਜਿਸ ਵਿੱਚ ਸਰੀਰ ਗਰਭਾਸ਼ਯ ਦੀ ਅੰਦਰਲੀ ਪਰਤ ਨੂੰ ਬਾਹਰ ਕੱਢਦਾ ਹੈ। ਇਹ ਸਿਹਤਮੰਦ ਪ੍ਰਜਨਨ ਪ੍ਰਣਾਲੀ ਦੀ ਨਿਸ਼ਾਨੀ ਹੈ ਅਤੇ ਵੱਡੇ ਹੋਣ ਦਾ ਇੱਕ ਸਧਾਰਣ ਹਿੱਸਾ ਹੈ।';

  @override
  String get menstrualQuote => 'ਨਵੀਨੀਕਰਨ ਅਤੇ ਜੀਵਨ ਦਾ ਚੱਕਰ';

  @override
  String get menstrualWhatIsNormalTitle => 'ਕੀ ਸਧਾਰਣ ਹੈ?';

  @override
  String get menstrualNormalItem1 => 'ਚੱਕਰ 21 ਤੋਂ 35 ਦਿਨਾਂ ਦੇ ਵਿਚਕਾਰ ਹੁੰਦਾ ਹੈ';

  @override
  String get menstrualNormalItem2 => 'ਰਕਤਸ੍ਰਾਵ 3 ਤੋਂ 7 ਦਿਨ ਤੱਕ ਰਹਿੰਦਾ ਹੈ';

  @override
  String get menstrualNormalItem3 => 'ਹਲਕੀ ਤੋਂ ਦਰਮਿਆਨੀ ਮਰੋੜ ਜਾਂ ਅਸਹਿਜਤਾ';

  @override
  String get menstrualWarningSignsTitle => 'ਚੇਤਾਵਨੀ ਦੇ ਸੰਕੇਤ';

  @override
  String get menstrualWarningItem1 =>
      'ਜ਼ਿਆਦਾ ਰਕਤਸ੍ਰਾਵ ਕਾਰਨ ਹਰ 1–2 ਘੰਟਿਆਂ ਵਿੱਚ ਪੈਡ ਬਦਲਣ ਦੀ ਲੋੜ';

  @override
  String get menstrualWarningItem2 => 'ਦਿਨਚਰਿਆ ਦੇ ਕੰਮ ਰੋਕ ਦੇਣ ਵਾਲਾ ਤੀਖਾ ਦਰਦ';

  @override
  String get menstrualWarningItem3 =>
      'ਚੱਕਰ ਲਗਾਤਾਰ 21 ਦਿਨਾਂ ਤੋਂ ਛੋਟਾ ਜਾਂ 38 ਦਿਨਾਂ ਤੋਂ ਵੱਧ';

  @override
  String get menstrualHygieneTipsTitle => 'ਸਫ਼ਾਈ ਟਿੱਪਸ';

  @override
  String get menstrualTipChangeRegularlyTitle => 'ਨਿਯਮਿਤ ਬਦਲੋ';

  @override
  String get menstrualTipChangeRegularlySubtitle =>
      'ਹਰ 4–6 ਘੰਟਿਆਂ ਵਿੱਚ ਪੈਡ ਬਦਲੋ';

  @override
  String get menstrualTipCleanHandsTitle => 'ਹੱਥ ਸਾਫ਼';

  @override
  String get menstrualTipCleanHandsSubtitle => 'ਪਹਿਲਾਂ ਅਤੇ ਬਾਅਦ ਵਿੱਚ ਹੱਥ ਧੋਵੋ';

  @override
  String get menstrualTipStayDryTitle => 'ਸੁੱਕਾ ਰੱਖੋ';

  @override
  String get menstrualTipStayDrySubtitle =>
      'ਜਨਨ ਅੰਗਾਂ ਵਾਲੇ ਖੇਤਰ ਨੂੰ ਸਾਫ਼ ਅਤੇ ਸੁੱਕਾ ਰੱਖੋ';

  @override
  String get menstrualMythsFactsTitle => 'ਭਰਮ ਅਤੇ ਤੱਥ';

  @override
  String get menstrualMyth1 => 'ਭਰਮ: \"ਮਹਾਵਾਰੀ ਦੌਰਾਨ ਕਸਰਤ ਨਹੀਂ ਕਰਨੀ ਚਾਹੀਦੀ।\"';

  @override
  String get menstrualFact1 =>
      'ਤੱਥ: ਹਲਕੀ ਕਸਰਤ ਮਰੋੜ ਘਟਾਉਣ ਅਤੇ ਮੂਡ ਸੁਧਾਰਣ ਵਿੱਚ ਮਦਦ ਕਰ ਸਕਦੀ ਹੈ।';

  @override
  String get menstrualMyth2 => 'ਭਰਮ: \"ਮਹਾਵਾਰੀ ਦਾ ਖੂਨ \'ਗੰਦਾ\' ਹੁੰਦਾ ਹੈ।\"';

  @override
  String get menstrualFact2 =>
      'ਤੱਥ: ਇਹ ਗਰਭਾਸ਼ਯ ਦੀ ਪਰਤ ਤੋਂ ਆਉਣ ਵਾਲਾ ਆਮ ਖੂਨ ਅਤੇ ਟਿਸ਼ੂ ਹੁੰਦਾ ਹੈ।';

  @override
  String get chatHeaderTitle => 'ਸਿਹਤ ਸਹਾਇਕ';

  @override
  String get chatHeaderStatusOnline => 'ਆਨਲਾਈਨ';

  @override
  String get chatToday => 'ਅੱਜ';

  @override
  String get chatQuickChipCheckFever => '🌡️ ਬੁਖਾਰ ਚੈੱਕ ਕਰੋ';

  @override
  String get chatQuickPromptCheckFever =>
      'ਮੈਂ ਬੁਖਾਰ ਚੈੱਕ ਕਰਨਾ ਚਾਹੁੰਦਾ/ਚਾਹੁੰਦੀ ਹਾਂ।';

  @override
  String get chatQuickChipWomensHealth => '🤰 ਔਰਤਾਂ ਦੀ ਸਿਹਤ';

  @override
  String get chatQuickPromptWomensHealth =>
      'ਮੈਨੂੰ ਔਰਤਾਂ ਦੀ ਸਿਹਤ ਬਾਰੇ ਇੱਕ ਸਵਾਲ ਹੈ।';

  @override
  String get chatQuickChipFirstAid => '🩹 ਫਰਸਟ ਏਡ';

  @override
  String get chatQuickPromptFirstAid => 'ਮੈਨੂੰ ਫਰਸਟ ਏਡ ਦੀ ਸਲਾਹ ਚਾਹੀਦੀ ਹੈ।';

  @override
  String get chatQuickChipChildCare => '👶 ਬੱਚਿਆਂ ਦੀ ਦੇਖਭਾਲ';

  @override
  String get chatQuickPromptChildCare =>
      'ਮੈਨੂੰ ਬੱਚਿਆਂ ਦੀ ਦੇਖਭਾਲ ਲਈ ਮਾਰਗਦਰਸ਼ਨ ਚਾਹੀਦਾ ਹੈ।';

  @override
  String get chatInputHintAskMeAnything => 'ਕੁਝ ਵੀ ਪੁੱਛੋ...';

  @override
  String get profileSaved => 'ਪ੍ਰੋਫਾਈਲ ਸੇਵ ਹੋ ਗਈ';

  @override
  String get saving => 'ਸੇਵ ਹੋ ਰਹੀ ਹੈ...';

  @override
  String get saveChanges => 'ਬਦਲਾਅ ਸੇਵ ਕਰੋ';

  @override
  String get profileTopBarTitle => 'Profile Settings';

  @override
  String get profileHeaderSubtitle => 'User Profile';

  @override
  String get profileSectionFullName => 'FULL NAME';

  @override
  String get profileHintFullName => 'e.g. Rahul Sharma';

  @override
  String get profileSectionAge => 'AGE';

  @override
  String get profileHintAge => 'Enter your age';

  @override
  String get profileSectionGender => 'GENDER';

  @override
  String get profileGenderMale => 'Male';

  @override
  String get profileGenderFemale => 'Female';

  @override
  String get profileGenderOther => 'Other';

  @override
  String get profileChronicConditions => 'CHRONIC CONDITIONS';

  @override
  String get profileConditionsBadge => 'BILINGUAL';

  @override
  String get conditionDiabetesTitle => 'Diabetes';

  @override
  String get conditionDiabetesSubtitle => 'Diabetes (Sugar)';

  @override
  String get conditionBpHeartTitle => 'BP & Heart';

  @override
  String get conditionBpHeartSubtitle => 'Blood pressure / Heart';

  @override
  String get conditionAsthmaTitle => 'Asthma';

  @override
  String get conditionAsthmaSubtitle => 'Breathing';

  @override
  String get conditionThyroidTitle => 'Thyroid';

  @override
  String get conditionThyroidSubtitle => 'Thyroid';

  @override
  String get conditionTbTitle => 'TB';

  @override
  String get conditionTbSubtitle => 'Tuberculosis';

  @override
  String get conditionNoneTitle => 'None';

  @override
  String get conditionNoneSubtitle => 'No conditions';

  @override
  String get helpFaqBotGreeting =>
      'Hi! I\'m MediMitra Help. Ask me anything about symptom checking, voice input, outbreak alerts, clinics, login, or privacy.\n\nNote: This is not medical advice. If you have a medical emergency, contact local emergency services.';

  @override
  String get helpFaqSuggestionCheckSymptoms => 'How do I check symptoms?';

  @override
  String get helpFaqSuggestionVoiceSymptoms => 'How do voice symptoms work?';

  @override
  String get helpFaqSuggestionOutbreakAlert => 'What is outbreak alert?';

  @override
  String get helpFaqSuggestionNearbyClinics => 'How to find nearby clinics?';

  @override
  String get helpFaqSuggestionOtpLogin => 'How does OTP login work?';

  @override
  String get helpFaqSuggestionDataSafe => 'Is my data safe?';

  @override
  String get helpFaqSuggestionGuestMode => 'Can I use the app without login?';

  @override
  String get helpFaqSuggestionChangeLanguage => 'How to change language?';

  @override
  String get helpFaqSuggestionDarkMode => 'How to enable dark mode?';

  @override
  String get helpFaqReplySymptomChecking =>
      'To check symptoms:\n1) Open Chat / Symptom Checker\n2) Type your symptoms (or use voice)\n3) Answer follow-up questions\n\nMediMitra will show likely causes and next steps. For severe symptoms (chest pain, trouble breathing, fainting), seek urgent care.';

  @override
  String get helpFaqReplyVoiceSymptoms =>
      'Voice symptoms: tap the microphone, speak your symptoms clearly, and the app converts it to text for analysis.\n\nTips: speak one symptom at a time, use simple words (\"fever\", \"cough\"), and allow microphone permission when asked.';

  @override
  String get helpFaqReplyOutbreakAlert =>
      'Outbreak alert helps you see if certain symptoms are trending in your area. It\'s based on anonymized, aggregated symptom patterns and is meant for awareness (not diagnosis).\n\nYou can view outbreak insights from the Outbreak section.';

  @override
  String get helpFaqReplyNearbyClinics =>
      'Nearby clinics: open the Clinic Locator to see clinics around you.\n\nMake sure Location permission is enabled. If you prefer, you can also search by area/city (if available on your build).';

  @override
  String get helpFaqReplyOtpLogin =>
      'OTP login: enter your 10-digit mobile number and we send a verification OTP. Enter the 6-digit OTP to proceed.\n\nIf you don\'t receive it, wait for the resend timer and try again. Also confirm network/SMS permissions.';

  @override
  String get helpFaqReplyGuestMode =>
      'Guest mode lets you explore the app without signing in. Some features that save to your profile (like personalized settings) may be limited until you log in.';

  @override
  String get helpFaqReplyPrivacy =>
      'Your profile data (like name/age/gender/conditions) is stored securely for your account to personalize your experience. We do not want you to share sensitive info in chat.\n\nFor exact details, check Privacy Policy (in the app).';

  @override
  String get helpFaqReplyChangeLanguage =>
      'You can change language from Profile → Language.';

  @override
  String get helpFaqReplyDarkMode =>
      'Dark mode: go to Profile → Dark Mode and toggle it on/off. Your choice is saved and works across the whole app.';

  @override
  String get helpFaqReplyContactSupport =>
      'Contact support: open Contact Us and send your message. Include screenshots and steps if possible.';

  @override
  String get helpFaqReplyFallback =>
      'I can help with: symptom checking, voice input, outbreak alerts, clinic locator, OTP login, privacy, language, and dark mode.\n\nTry one of these: \"How do I check symptoms?\", \"How to find nearby clinics?\", \"Is my data safe?\"';
}
