// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Assamese (`as`).
class AppLocalizationsAs extends AppLocalizations {
  AppLocalizationsAs([String locale = 'as']) : super(locale);

  @override
  String get appTitle => 'মেডিমিত্ৰা';

  @override
  String get close => 'বন্ধ কৰক';

  @override
  String get loginTagline =>
      'আপোনাৰ আৰু আপোনাৰ পৰিয়ালৰ বাবে সহজ স্বাস্থ্যসেবা';

  @override
  String get smsLogin => 'এসএমএস লগইন';

  @override
  String get emailLogin => 'ইমেইল লগইন';

  @override
  String get homeHello => 'নমস্কাৰ,';

  @override
  String get homeThere => 'তাত';

  @override
  String get homeChatCta => 'আমাৰ AI স্বাস্থ্য চেট সহায়ক অন্বেষণ কৰক';

  @override
  String get homeOurFeatures => 'আমাৰ বৈশিষ্ট্যসমূহ';

  @override
  String get homeHighlights => 'হাইলাইটসমূহ';

  @override
  String get homeDisclaimerTitle => 'দায়স্বীকাৰ';

  @override
  String get homeDisclaimerBody =>
      'MediMitra কেৱল তথ্যৰ বাবে; ই চিকিৎসা পৰামৰ্শ নহয়। ই ডাক্তৰক সলনি নকৰে।\nগম্ভীৰ লক্ষণ বা জৰুৰী অৱস্থা হ’লে, অনুগ্ৰহ কৰি ওচৰৰ হাস্পতাললৈ যাওক বা তৎক্ষণাৎ জৰুৰী সেৱা সংযোগ কৰক।';

  @override
  String get featureSymptomChecker => 'লক্ষণ পৰীক্ষক';

  @override
  String get featureWomensHealth => 'মহিলা স্বাস্থ্য সচেতনতা';

  @override
  String get featureInsurance => 'বীমা';

  @override
  String get featureAiHealthSummary => 'AI স্বাস্থ্য সাৰাংশ';

  @override
  String get featureReminders => 'স্মৰণকৰ্তা';

  @override
  String get featureLocateClinics => 'ওচৰৰ ক্লিনিক বিচাৰক';

  @override
  String get promoAiSymptomCheckTitle => 'AI লক্ষণ পৰীক্ষা';

  @override
  String get promoAiSymptomCheckSubtitle =>
      'লক্ষণ বৰ্ণনা কৰক, সেকেণ্ডত নিৰ্দেশনা পাওক।';

  @override
  String get promoVoiceWaveformTitle => 'ভইচ + ৱেভফৰ্ম';

  @override
  String get promoVoiceWaveformSubtitle => 'ভইচ ইনপুট সহ হেণ্ড্‌ছ-ফ্ৰী চেট।';

  @override
  String get promoProfilePersonalizationTitle => 'প্ৰ’ফাইল ব্যক্তিগতকৰণ';

  @override
  String get promoProfilePersonalizationSubtitle =>
      'ভাল সহায়ৰ বাবে বয়স, লিংগ আৰু অৱস্থা সাঁচি থওক।';

  @override
  String get promoNearbyClinicsTitle => 'ওচৰৰ ক্লিনিকসমূহ';

  @override
  String get promoNearbyClinicsSubtitle =>
      'আপোনাৰ স্থানৰ ওচৰত স্বাস্থ্যসেৱা বিচাৰক।';

  @override
  String get settings => 'ছেটিংছ';

  @override
  String get supportAndInformation => 'সহায় & তথ্য';

  @override
  String get notifications => 'সূচনাসমূহ';

  @override
  String get manageYourNotifications => 'আপোনাৰ সূচনাসমূহ ব্যৱস্থাপনা কৰক';

  @override
  String get notificationsEnabled => 'সূচনা সক্ৰিয়';

  @override
  String get notificationsDisabled => 'সূচনা নিষ্ক্ৰিয়';

  @override
  String get couldNotUpdateNotifications => 'সূচনা আপডেট কৰিব পৰা নগ’ল';

  @override
  String get darkMode => 'ডাৰ্ক ম’ড';

  @override
  String get toggleDarkTheme => 'ডাৰ্ক থীম অন/অফ কৰক';

  @override
  String get helpAndFaq => 'সহায় & FAQ';

  @override
  String get getHelpAndAnswers => 'সহায় আৰু উত্তৰ লাভ কৰক';

  @override
  String get getInTouchWithSupport => 'সহায় দলৰ সৈতে যোগাযোগ কৰক';

  @override
  String get aboutMediMitra => 'MediMitra সম্পৰ্কে';

  @override
  String versionLine(Object version) {
    return 'সংস্কৰণ $version';
  }

  @override
  String get privacyPolicy => 'গোপনীয়তা নীতি';

  @override
  String get howWeProtectYourData => 'আমি আপোনাৰ তথ্য কেনেকৈ সুৰক্ষিত ৰাখো';

  @override
  String get termsAndConditions => 'চৰ্তাৱলী';

  @override
  String get termsConditionsBody =>
      'Terms & Conditions\n\nBy downloading and using this application, you agree to comply with and be bound by these Terms and Conditions. If you do not agree with any part of these terms, you should discontinue using the app.\n\nThis application is designed to provide health-related information and decision-support guidance only. It is not a medical diagnostic tool and does not replace consultation with a qualified doctor or healthcare professional. All information provided by the app is for educational and support purposes, and users must always seek professional medical advice for diagnosis, treatment, or emergencies.\n\nUsers are responsible for providing accurate and honest information while using the app. The guidance generated by the system depends on the inputs provided by the user, and incorrect or incomplete information may lead to inaccurate results. The app should not be used as the sole basis for making medical decisions.\n\nThis application is not intended for emergency situations. In case of severe symptoms such as chest pain, difficulty breathing, loss of consciousness, or heavy bleeding, users must immediately contact local emergency services or visit the nearest hospital.\n\nTo the maximum extent permitted by law, the developers shall not be held liable for any direct or indirect damages arising from the use of this application. Use of the app is entirely at the user’s own risk, and no guarantee is made regarding the accuracy, completeness, or reliability of the information provided.\n\nUse of this application is also governed by our Privacy Policy. By continuing to use the app, you confirm that you have read, understood, and agreed to both the Privacy Policy and these Terms and Conditions.\n\nWe reserve the right to modify or update these Terms and Conditions at any time. Any changes will be displayed within the app, and continued use of the app after such changes indicates acceptance of the updated terms.';

  @override
  String get legalAgreement => 'আইনী চুক্তি';

  @override
  String get deleteData => 'তথ্য মচি পেলাওক';

  @override
  String get deleteChatsAndSavedSettings =>
      'চেট & সাঁচি থোৱা ছেটিংছ মচি পেলাওক';

  @override
  String get logOut => 'লগ আউট';

  @override
  String get logoutQuestion => 'লগ আউট কৰিব নেকি?';

  @override
  String get logoutReturnToLogin => 'আপুনি লগ আউট হৈ লগইন পৰ্দালৈ উভতি যাব।';

  @override
  String get chooseAnAction => 'এটা কাৰ্য বাছনি কৰক';

  @override
  String get deleteAccount => 'একাউণ্ট মচি পেলাওক';

  @override
  String get permanentlyDeleteAccount =>
      'আপোনাৰ একাউণ্ট স্থায়ীভাৱে মচি পেলাওক';

  @override
  String get deleteLocalData => 'স্থানীয় তথ্য মচি পেলাওক';

  @override
  String get deleteLocalDataOnDevice =>
      'এই ডিভাইচত চেট & সাঁচি থোৱা ছেটিংছ মচি পেলাওক';

  @override
  String get clearLocalDataQuestion => 'স্থানীয় তথ্য মচি পেলাব নেকি?';

  @override
  String get clearLocalDataBody =>
      'ই এই ডিভাইচত স্থানীয়ভাৱে সঞ্চিত এপ ডেটা (সাঁচি থোৱা ছেটিংছ, কেচ কৰা প্ৰ’ফাইল ফিল্ড আৰু মেম’ৰীত থকা চেট ইতিহাস) মচি পেলাব।\n\nসকলো পৰিৱর্তন প্ৰযোজ্য হবলৈ এপ পুনৰাৰম্ভ কৰিব লাগিব পাৰে।';

  @override
  String get clear => 'মচি পেলাওক';

  @override
  String get localDataCleared => 'স্থানীয় তথ্য মচি পেলোৱা হ’ল';

  @override
  String get couldNotClearLocalData => 'স্থানীয় তথ্য মচি পেলাব পৰা নগ’ল';

  @override
  String get accountDeletionNotAvailable =>
      'এই প্লেটফৰ্মত একাউণ্ট মচি পেলোৱা উপলব্ধ নহয়';

  @override
  String get noSignedInAccountFound => 'লগইন কৰা একাউণ্ট পোৱা নগ’ল';

  @override
  String get deleteAccountQuestion => 'একাউণ্ট মচি পেলাব নেকি?';

  @override
  String get deleteAccountBody =>
      'ই আপোনাৰ একাউণ্ট স্থায়ীভাৱে মচি পেলাব। আপুনি এই ডিভাইচৰ পৰা লগ আউট হব।';

  @override
  String get deletingAccount => 'একাউণ্ট মচি পেলাইছে...';

  @override
  String get pleaseLoginAgainThenDelete =>
      'অনুগ্ৰহ কৰি পুনৰ লগইন কৰক, তাৰ পিছত একাউণ্ট মচি পেলাওক';

  @override
  String get couldNotDeleteAccount => 'একাউণ্ট মচি পেলাব পৰা নগ’ল';

  @override
  String get networkSlowTryAgain => 'নেটৱৰ্ক ধীৰ। অনুগ্ৰহ কৰি পুনৰ চেষ্টা কৰক।';

  @override
  String get defaultUser => 'ব্যৱহাৰকাৰী';

  @override
  String userIdLine(Object id) {
    return 'ব্যৱহাৰকাৰী ID: $id';
  }

  @override
  String get clinicsNearYou => 'আপোনাৰ ওচৰৰ ক্লিনিক';

  @override
  String get refresh => 'ৰিফ্ৰেশ';

  @override
  String get recenter => 'পুনৰ কেন্দ্ৰলৈ';

  @override
  String resultsCount(Object count) {
    return 'ফলাফল ($count)';
  }

  @override
  String get nearbyClinics => 'ওচৰৰ ক্লিনিকসমূহ';

  @override
  String get call => 'ফোন কৰক';

  @override
  String get navigate => 'দিশ দেখুৱাওক';

  @override
  String get unableToOpenDialer => 'ডায়েলাৰ খুলিব পৰা নগ’ল';

  @override
  String get unableToOpenMaps => 'মেপ খুলিব পৰা নগ’ল';

  @override
  String get radius => 'ব্যাসাৰ্ধ';

  @override
  String get tryAgain => 'পুনৰ চেষ্টা কৰক';

  @override
  String get openLocationSettings => 'অৱস্থান ছেটিংছ খোলক';

  @override
  String get locationServicesDisabled =>
      'অৱস্থান সেৱা বন্ধ আছে। অনুগ্ৰহ কৰি GPS সক্ৰিয় কৰক।';

  @override
  String get locationPermissionDenied => 'অৱস্থান অনুমতি নাকচ কৰা হৈছে।';

  @override
  String get locationPermissionDeniedForever =>
      'অৱস্থান অনুমতি স্থায়ীভাৱে নাকচ কৰা হৈছে। ছেটিংছৰ পৰা সক্ৰিয় কৰক।';

  @override
  String get chooseLanguage => 'ভাষা বাছনি কৰক';

  @override
  String get cancel => 'বাতিল';

  @override
  String get save => 'সাঁচি থওক';

  @override
  String get contactUs => 'যোগাযোগ কৰক';

  @override
  String get needHelp => 'সহায় লাগে নেকি?';

  @override
  String get contactSubtitle =>
      'আমালৈ এটা বাৰ্তা পঠিয়াওক; আমাৰ দলে উত্তৰ দিব।';

  @override
  String supportEmailLine(Object email) {
    return 'সহায় ইমেইল: $email';
  }

  @override
  String get typicalResponseLine => 'সাধাৰণ উত্তৰ: ২৪ ঘণ্টাৰ ভিতৰত';

  @override
  String get language => 'ভাষা';

  @override
  String languageSetTo(Object language) {
    return 'ভাষা $languageলৈ ছেট কৰা হ’ল';
  }

  @override
  String get fullName => 'সম্পূৰ্ণ নাম';

  @override
  String get yourName => 'আপোনাৰ নাম';

  @override
  String get email => 'ইমেইল';

  @override
  String get emailHint => 'name@example.com';

  @override
  String get phoneOptional => 'ফোন (ঐচ্ছিক)';

  @override
  String get yourMobileNumber => 'আপোনাৰ মোবাইল নম্বৰ';

  @override
  String get subject => 'বিষয়';

  @override
  String get subjectHint => 'এইটো কিহৰ বিষয়ে?';

  @override
  String get message => 'বাৰ্তা';

  @override
  String get messageHint => 'আপোনাৰ সমস্যা বা প্ৰশ্ন বৰ্ণনা কৰক';

  @override
  String get send => 'পঠিয়াওক';

  @override
  String get sentSuccess => 'পঠিওৱা হ’ল! আমি সোনকালে উত্তৰ দিম।';

  @override
  String get required => 'আৱশ্যক';

  @override
  String get enterValidEmail => 'এটা বৈধ ইমেইল দিয়ক';

  @override
  String get writeMoreDetail => 'অনুগ্ৰহ কৰি অলপ বেছি বিৱৰণ লিখক';

  @override
  String get couldNotOpenEmailApp => 'ইমেইল এপ খুলিব পৰা নগ’ল।';

  @override
  String get couldNotSendTryLater =>
      'পঠিয়াব পৰা নগ’ল। অনুগ্ৰহ কৰি পিছত চেষ্টা কৰক।';

  @override
  String get tipNoShareOtp => 'টিপ: ইয়াত পাছৱাৰ্ড বা OTP শ্বেয়াৰ নকৰিব।';

  @override
  String get loginLanguageLabel => 'English / हिंदी';

  @override
  String get loginHeroSubtitle => 'আপোনাৰ স্বাস্থ্য সঙ্গী';

  @override
  String get loginMobileNumberLabel => 'মোবাইল নম্বৰ';

  @override
  String get loginMobileHint => '00000 00000';

  @override
  String get loginEmailLabel => 'ইমেইল ঠিকনা';

  @override
  String get loginPasswordLabel => 'পাছৱাৰ্ড';

  @override
  String get loginPasswordHint => 'পাছৱাৰ্ড দিয়ক';

  @override
  String get loginPleaseWait => 'অনুগ্ৰহ কৰি অপেক্ষা কৰক...';

  @override
  String get loginSendOtp => 'OTP পঠিয়াওক';

  @override
  String get loginContinue => 'আগবঢ়ক';

  @override
  String get loginSendingOtp => 'OTP পঠিয়াইছে...';

  @override
  String get loginOr => 'অথবা';

  @override
  String get loginContinueAsGuest => 'অতিথি হিচাপে আগবঢ়ক';

  @override
  String get loginAgreementText =>
      'লগইন কৰি, আপুনি MediMitra ৰ\nTerms of Service আৰু Privacy Policy-ত সন্মতি জনায়।';

  @override
  String get loginUnableContinueGuest => 'অতিথি হিচাপে আগবঢ়িব পৰা নগ’ল।';

  @override
  String get loginEnterMobileNumber => 'মোবাইল নম্বৰ দিয়ক।';

  @override
  String get loginEnterValidMobileNumber =>
      'এটা বৈধ ১০-অংকৰ মোবাইল নম্বৰ দিয়ক।';

  @override
  String get loginOtpSent => 'OTP পঠিওৱা হ’ল।';

  @override
  String get loginFailedSendOtp => 'OTP পঠিয়াব ব্যৰ্থ।';

  @override
  String get loginEnterValidEmail => 'এটা বৈধ ইমেইল দিয়ক।';

  @override
  String get loginPasswordMinChars => 'পাছৱাৰ্ড কমেও ৬টা অক্ষৰ হ’ব লাগিব।';

  @override
  String get loginEmailPasswordDisabled =>
      'Firebase Console-ত Email/Password সাইন-ইন নিষ্ক্ৰিয়।';

  @override
  String get loginAccountExistsTryLogin =>
      'একাউণ্ট ইতিমধ্যে আছে। লগইন কৰিবলৈ চেষ্টা কৰক।';

  @override
  String get loginWeakPassword => 'পাছৱাৰ্ড দুৰ্বল (কমেও ৬ অক্ষৰ)।';

  @override
  String get loginIncorrectPassword => 'ভুল পাছৱাৰ্ড।';

  @override
  String get loginInvalidEmail => 'অবৈধ ইমেইল।';

  @override
  String get loginLoginFailed => 'লগইন ব্যৰ্থ।';

  @override
  String get otpVerifyNumber => 'নম্বৰ যাচাই কৰক';

  @override
  String get otpSentTo => 'আমি ৬-অংকৰ কোড পঠিয়াইছোঁ';

  @override
  String get otpHaventReceived => 'কোড পোৱা নাই নেকি?';

  @override
  String get otpResendCode => 'কোড পুনৰ পঠিয়াওক';

  @override
  String get otpVerifyProceed => 'যাচাই কৰি আগবঢ়ক';

  @override
  String get otpVerifying => 'যাচাই হৈ আছে...';

  @override
  String get otpEnter6Digit => '৬-অংকৰ OTP দিয়ক।';

  @override
  String get otpInvalid => 'অবৈধ OTP।';

  @override
  String get otpVerificationFailed => 'OTP যাচাই ব্যৰ্থ।';

  @override
  String get otpFailedResend => 'কোড পুনৰ পঠিয়াব ব্যৰ্থ।';

  @override
  String get otpCodeResent => 'কোড পুনৰ পঠিওৱা হ’ল।';

  @override
  String get otpSafetyFirst => 'নিরাপত্তা প্ৰথম';

  @override
  String get otpSafetyNote =>
      'MediMitra ৰ এনক্রিপশ্বনৰ সহায়ত আপোনাৰ স্বাস্থ্য ৰেকৰ্ড সুৰক্ষিতভাৱে সংযোগ কৰক।';

  @override
  String get communityOutbreakAlerts => 'সমুদায়িক প্ৰকোপ সতৰ্কতা';

  @override
  String get outbreakPrivacyNote =>
      'গোপনীয়তা-প্ৰথম: কেৱল PIN3 আৰু দিনে দিনৰ সমষ্টিগত লক্ষণ গণনা। নাম, চেট টেক্স্ট, GPS বা সঠিক টাইমষ্টেম্প নহয়।';

  @override
  String get regionNotSet => 'অঞ্চল: ছেট কৰা নাই';

  @override
  String regionPin3Line(Object region) {
    return 'অঞ্চল: $region (PIN3)';
  }

  @override
  String get set => 'ছেট';

  @override
  String get setAreaPin3Title => 'আপোনাৰ এলেকা (PIN3) ছেট কৰক';

  @override
  String get setAreaPin3Body =>
      'আপোনাৰ PIN কোড দিয়ক। আমি কেৱল প্ৰথম ৩টা অংক (ডাঙৰ অঞ্চল) সাঁচি ৰাখোঁ।';

  @override
  String get pinExampleHint => 'যেনে: 411001';

  @override
  String get enterFirst3DigitsPin => 'আপোনাৰ PIN ৰ কমেও প্ৰথম ৩টা অংক দিয়ক।';

  @override
  String get unableToSaveRegion => 'অঞ্চল সাঁচি ৰাখিব পৰা নগ’ল।';

  @override
  String get setPin3ToSeeAlerts =>
      'আপোনাৰ এলেকাৰ প্ৰকোপ সতৰ্কতা চাবলৈ PIN3 ছেট কৰক।';

  @override
  String get noAlertsToday => 'আজিৰ বাবে আপোনাৰ এলেকাত কোনো সতৰ্কতা নাই।';

  @override
  String get prevention => 'প্ৰতিৰোধ';

  @override
  String get outbreakLevelHighRisk => 'উচ্চ ঝুঁকি';

  @override
  String get outbreakLevelWarning => 'সাৱধানবাণী';

  @override
  String get outbreakLevelWatch => 'নজৰদাৰী';

  @override
  String get outbreakLevelNone => 'একো নহয়';

  @override
  String get back => 'পিছলৈ';

  @override
  String get next => 'পৰৱৰ্তী';

  @override
  String get couldNotSaveConsent =>
      'আপোনাৰ সন্মতি সাঁচি ৰাখিব পৰা নগ’ল। অনুগ্ৰহ কৰি পুনৰ চেষ্টা কৰক।';

  @override
  String get termsSigningTitle => 'Terms of Service';

  @override
  String get termsSigningIntro =>
      'লক্ষণ মূল্যায়ন ব্যৱহাৰ কৰাৰ আগতে, অনুগ্ৰহ কৰি Terms of Service আৰু Privacy Policy গ্ৰহণ কৰক। অনুগ্ৰহ কৰি মনত ৰাখিব:';

  @override
  String get termsBulletNotDiagnosisTitle => 'ই ফলাফল ৰোগ নিৰ্ণয় নহয়।';

  @override
  String get termsBulletNotDiagnosisBody =>
      ' ই কেৱল তথ্যৰ বাবে; ই যোগ্য চিকিৎসা মতামত নহয়।';

  @override
  String get termsBulletNoEmergencyTitle => 'জৰুৰী অৱস্থাত ব্যৱহাৰ নকৰিব।';

  @override
  String get termsBulletNoEmergencyBody =>
      ' স্বাস্থ্য জৰুৰীত আপোনাৰ স্থানীয় জৰুৰী নম্বৰত তৎক্ষণাৎ ফোন কৰক।';

  @override
  String get termsBulletDataSafeTitle => 'আপোনাৰ তথ্য সুৰক্ষিত।';

  @override
  String get termsBulletDataSafeBody =>
      ' আপুনি দিয়া তথ্য শ্বেয়াৰ কৰা নহ’ব বা আপোনাক চিনাক্ত কৰিবলৈ ব্যৱহাৰ কৰা নহ’ব।';

  @override
  String get termsConsentTermsPrefix => 'মই পঢ়িলোঁ আৰু গ্ৰহণ কৰিলোঁ ';

  @override
  String get termsConsentTermsLink => 'Terms of Service';

  @override
  String get termsConsentTermsSuffix => '.';

  @override
  String get termsConsentPrivacyPrefix =>
      'মই মোৰ স্বাস্থ্য তথ্য সাক্ষাৎকাৰৰ বাবে ব্যৱহাৰ কৰিবলৈ সন্মতি দিছোঁ। অধিক তথ্য ';

  @override
  String get termsConsentPrivacyLink => 'Privacy Policy';

  @override
  String get termsConsentPrivacySuffix => '-ত আছে।';

  @override
  String get quickQuestions => 'দ্ৰুত প্ৰশ্নসমূহ';

  @override
  String get typeAQuestionHint => 'এটা প্ৰশ্ন লিখক…';

  @override
  String get talkToMaya => 'মায়াৰ সৈতে কথা পাতক';

  @override
  String get womensHealthHubTitle => 'Women’s Health Hub';

  @override
  String get womensHealthHubWelcome => 'আপোনাৰ স্বাস্থ্য যাত্ৰালৈ স্বাগতম';

  @override
  String get womensHealthHubSubtitle =>
      'সম্পদ অন্বেষণ আৰু ব্যক্তিগত যত্ন পাবলৈ এটা শ্ৰেণী বাছনি কৰক।';

  @override
  String get menstrualHealth => 'মাসিক স্বাস্থ্য';

  @override
  String get pregnancyAndMaternal => 'গৰ্ভধাৰণা & মাতৃত্ব';

  @override
  String get breastHealth => 'স্তন স্বাস্থ্য';

  @override
  String get comingSoon => 'শীঘ্ৰে আহি আছে';

  @override
  String get womensHealthHubTagline => 'MEDIMITRA WELLNESS';

  @override
  String get womensHealthCategoryMenstrualDescription =>
      'আপোনাৰ মাসিক চক্ৰ বুজক,\nস্বচ্ছতা শিকক আৰু\nপিৰিয়ডছ সহজে পৰিচালনা কৰক।';

  @override
  String get womensHealthCategoryPregnancyDescription =>
      'সুস্থ গৰ্ভধাৰণাৰ বাবে বিশেষজ্ঞ সহায়,\nপুষ্টি টিপছ আৰু\nসুৰক্ষিত প্ৰসূতি সহায়।';

  @override
  String get womensHealthCategoryBreastDescription =>
      'সহজ স্ব-পরীক্ষা নিৰ্দেশনা\nআৰু সচেতনতা টিপছ\nশীঘ্ৰে ধৰা আৰু যত্নৰ বাবে।';

  @override
  String get recommended => 'প্ৰস্তাৱিত';

  @override
  String get explore => 'অন্বেষণ';

  @override
  String get menstrualScreenTitle => 'মাসিক স্বাস্থ্য';

  @override
  String get menstrualWhatIsMenstruationTitle => 'মাসিকধৰ্ম কি?';

  @override
  String get menstrualWhatIsMenstruationBody =>
      'মাসিকধৰ্ম হৈছে গৰ্ভাশয়ৰ ভিতৰৰ পৰ্দা স্খলন হোৱা স্বাভাৱিক মাহেকীয়া প্ৰক্ৰিয়া। ই স্বাস্থ্যকৰ প্ৰজনন ব্যৱস্থাৰ লক্ষণ আৰু বিকাশৰ স্বাভাৱিক অংশ।';

  @override
  String get menstrualQuote => 'প্ৰজনন আৰু জীৱনৰ চক্ৰ';

  @override
  String get menstrualWhatIsNormalTitle => 'কি স্বাভাৱিক?';

  @override
  String get menstrualNormalItem1 => 'চক্ৰ ২১ৰ পৰা ৩৫ দিনৰ ভিতৰত';

  @override
  String get menstrualNormalItem2 => 'ৰক্তক্ষৰণ ৩ৰ পৰা ৭ দিন';

  @override
  String get menstrualNormalItem3 => 'হালকা পৰা মধ্যম স্তৰৰ অস্বস্তি/ব্যথা';

  @override
  String get menstrualWarningSignsTitle => 'সতৰ্কতা সংকেত';

  @override
  String get menstrualWarningItem1 =>
      'গম্ভীৰ ৰক্তক্ষৰণ (প্ৰতি ১–২ ঘণ্টাত পেড সলনি কৰিব লাগে)';

  @override
  String get menstrualWarningItem2 => 'দিনচৰ্যা ব্যাহত কৰা তীব্ৰ ব্যথা';

  @override
  String get menstrualWarningItem3 =>
      'চক্ৰ সদায় ২১ দিনতকৈ কম বা ৩৮ দিনতকৈ বেছি';

  @override
  String get menstrualHygieneTipsTitle => 'স্বচ্ছতা টিপছ';

  @override
  String get menstrualTipChangeRegularlyTitle => 'নিয়মিত সলনি কৰক';

  @override
  String get menstrualTipChangeRegularlySubtitle =>
      'পেড/ট্যাম্পন নিয়মিত সলনি কৰক যাতে সংক্ৰমণৰ ঝুঁকি কমে।';

  @override
  String get menstrualTipCleanHandsTitle => 'হাত পৰিষ্কাৰ ৰাখক';

  @override
  String get menstrualTipCleanHandsSubtitle =>
      'পেড সলনি কৰাৰ আগতে/পিছতে হাত ধোৱক।';

  @override
  String get menstrualTipStayDryTitle => 'শুকান ৰাখক';

  @override
  String get menstrualTipStayDrySubtitle =>
      'সাফ আৰু শুকান অন্তৰ্বাস ব্যৱহাৰ কৰক।';

  @override
  String get menstrualMythsFactsTitle => 'ভ্ৰান্তি বনাম সত্য';

  @override
  String get menstrualMyth1 => 'ভ্ৰান্তি: মাসিক সময়ত স্নান কৰিব নালাগে।';

  @override
  String get menstrualFact1 =>
      'সত্য: পৰিষ্কাৰ-পরিচ্ছন্নতা বজাই ৰাখিবলৈ স্নান কৰা সহায়ক।';

  @override
  String get menstrualMyth2 => 'ভ্ৰান্তি: মাসিক মানে অসুস্থ।';

  @override
  String get menstrualFact2 =>
      'সত্য: ই সাধাৰণ জৈৱিক প্ৰক্ৰিয়া। যদি অত্যধিক ব্যথা/অনিয়ম হয়, ডাক্তৰৰ পৰামৰ্শ লওক।';

  @override
  String get chatHeaderTitle => 'মায়া';

  @override
  String get chatHeaderStatusOnline => 'অনলাইন';

  @override
  String get chatToday => 'আজি';

  @override
  String get chatQuickChipCheckFever => 'জ্বৰ চেক';

  @override
  String get chatQuickPromptCheckFever => 'মোৰ জ্বৰ আছে। কি কৰিব লাগে?';

  @override
  String get chatQuickChipWomensHealth => 'মহিলা স্বাস্থ্য';

  @override
  String get chatQuickPromptWomensHealth =>
      'মাসিক/মহিলা স্বাস্থ্য বিষয়ে সহায় কৰক।';

  @override
  String get chatQuickChipFirstAid => 'প্ৰথম সাহায্য';

  @override
  String get chatQuickPromptFirstAid => 'কটা/জ্বলা/মচকা হলে প্ৰাথমিক যত্ন কি?';

  @override
  String get chatQuickChipChildCare => 'শিশু যত্ন';

  @override
  String get chatQuickPromptChildCare => 'শিশুৰ জ্বৰ/কাশি হলে কি কৰিম?';

  @override
  String get chatInputHintAskMeAnything => 'যিকোনো কথা সুধক…';

  @override
  String get profileSaved => 'প্ৰ’ফাইল সাঁচি থোৱা হ’ল';

  @override
  String get saving => 'সাঁচি থোৱা হৈ আছে…';

  @override
  String get saveChanges => 'পৰিৱৰ্তন সাঁচি থওক';

  @override
  String get profileTopBarTitle => 'প্ৰ’ফাইল ছেটিংছ';

  @override
  String get profileHeaderSubtitle => 'ব্যৱহাৰকাৰী প্ৰ’ফাইল';

  @override
  String get profileSectionFullName => 'সম্পূৰ্ণ নাম';

  @override
  String get profileHintFullName => 'যেনে: ৰাহুল শৰ্মা';

  @override
  String get profileSectionAge => 'বয়স';

  @override
  String get profileHintAge => 'আপোনাৰ বয়স দিয়ক';

  @override
  String get profileSectionGender => 'লিংগ';

  @override
  String get profileGenderMale => 'পুৰুষ';

  @override
  String get profileGenderFemale => 'মহিলা';

  @override
  String get profileGenderOther => 'অন্য';

  @override
  String get profileChronicConditions => 'দীৰ্ঘদিনীয়া অৱস্থা';

  @override
  String get profileConditionsBadge => 'দ্বিভাষী';

  @override
  String get conditionDiabetesTitle => 'ডায়াবিটিছ';

  @override
  String get conditionDiabetesSubtitle => 'মধুমেহ (চুগাৰ)';

  @override
  String get conditionBpHeartTitle => 'BP & হৃদয়';

  @override
  String get conditionBpHeartSubtitle => 'ৰক্তচাপ / হৃদয়';

  @override
  String get conditionAsthmaTitle => 'এষ্টমা';

  @override
  String get conditionAsthmaSubtitle => 'শ্বাসকষ্ট';

  @override
  String get conditionThyroidTitle => 'থাইৰয়েড';

  @override
  String get conditionThyroidSubtitle => 'থাইৰয়েড';

  @override
  String get conditionTbTitle => 'TB';

  @override
  String get conditionTbSubtitle => 'ক্ষয় ৰোগ';

  @override
  String get conditionNoneTitle => 'কিছুও নহয়';

  @override
  String get conditionNoneSubtitle => 'কোনো অৱস্থা নাই';

  @override
  String get helpFaqBotGreeting =>
      'হাই! মই MediMitra Help। লক্ষণ পৰীক্ষা, ভইচ ইনপুট, প্ৰকোপ সতৰ্কতা, ক্লিনিক, লগইন বা গোপনীয়তা সম্পৰ্কে যিকোনো কথা সুধিব পাৰে।\n\nটোকা: এইটো চিকিৎসা পৰামৰ্শ নহয়। চিকিৎসা জৰুৰী অৱস্থা হলে, স্থানীয় জৰুৰী সেৱা সংযোগ কৰক।';

  @override
  String get helpFaqSuggestionCheckSymptoms => 'লক্ষণ কেনেকৈ চেক কৰোঁ?';

  @override
  String get helpFaqSuggestionVoiceSymptoms => 'ভইচ লক্ষণ কেনেকৈ কাম কৰে?';

  @override
  String get helpFaqSuggestionOutbreakAlert => 'প্ৰকোপ সতৰ্কতা কি?';

  @override
  String get helpFaqSuggestionNearbyClinics => 'ওচৰৰ ক্লিনিক কেনেকৈ বিচাৰিম?';

  @override
  String get helpFaqSuggestionOtpLogin => 'OTP লগইন কেনেকৈ কাম কৰে?';

  @override
  String get helpFaqSuggestionDataSafe => 'মোৰ তথ্য সুৰক্ষিত নেকি?';

  @override
  String get helpFaqSuggestionGuestMode =>
      'লগইন নকৰাকৈ এপ ব্যৱহাৰ কৰিব পাৰিম নেকি?';

  @override
  String get helpFaqSuggestionChangeLanguage => 'ভাষা কেনেকৈ সলনি কৰিম?';

  @override
  String get helpFaqSuggestionDarkMode => 'ডাৰ্ক ম’ড কেনেকৈ অন কৰিম?';

  @override
  String get helpFaqReplySymptomChecking =>
      'লক্ষণ চেক কৰিবলৈ:\n1) Chat / Symptom Checker খোলক\n2) আপোনাৰ লক্ষণ টাইপ কৰক (বা ভইচ ব্যৱহাৰ কৰক)\n3) পৰৱৰ্তী প্ৰশ্নৰ উত্তৰ দিয়ক\n\nMediMitra সম্ভাৱ্য কাৰণ আৰু পৰৱৰ্তী পদক্ষেপ দেখুৱাব। গম্ভীৰ লক্ষণ (বুকুৰ ব্যথা, শ্বাসকষ্ট, অচেতন হোৱা) থাকিলে তৎক্ষণাৎ চিকিৎসা লওক।';

  @override
  String get helpFaqReplyVoiceSymptoms =>
      'ভইচ লক্ষণ: মাইক বুটাম টেপ কৰক, স্পষ্টকৈ লক্ষণ কওক, আৰু এপে সেয়া টেক্স্টলৈ ৰূপান্তৰ কৰি বিশ্লেষণ কৰে।\n\nটিপছ: এটা-এটা কৰি লক্ষণ কওক, সৰল শব্দ ব্যৱহাৰ কৰক (\"জ্বৰ\", \"কাশি\") আৰু অনুৰোধ কৰিলে মাইক অনুমতি দিয়ক।';

  @override
  String get helpFaqReplyOutbreakAlert =>
      'প্ৰকোপ সতৰ্কতাই আপোনাৰ এলেকাত কিছুমান লক্ষণ বৃদ্ধি পাইছে নেকি বুজিবলৈ সহায় কৰে। ই অনামধেয়, সমষ্টিগত লক্ষণ পেটাৰ্নৰ ওপৰত আধাৰিত আৰু সচেতনতা বাবে (ৰোগ নিৰ্ণয় নহয়)।\n\nOutbreak বিভাগত ইন্সাইট চাব পাৰে।';

  @override
  String get helpFaqReplyNearbyClinics =>
      'ওচৰৰ ক্লিনিক: Clinic Locator খোলক আৰু আপোনাৰ চাৰিওফালে থকা ক্লিনিকসমূহ চাওক।\n\nঅৱস্থান অনুমতি সক্ৰিয় আছে নিশ্চিত কৰক।';

  @override
  String get helpFaqReplyOtpLogin =>
      'OTP লগইন: আপোনাৰ ১০-অংকৰ মোবাইল নম্বৰ দিয়ক; আমি যাচাই OTP পঠিয়াম। ৬-অংকৰ OTP দি আগবঢ়ক।\n\nOTP নাহিলে, ৰিছেণ্ড টাইমাৰ শেষ হলে পুনৰ চেষ্টা কৰক; নেটৱৰ্কো পৰীক্ষা কৰক।';

  @override
  String get helpFaqReplyGuestMode =>
      'অতিথি ম’ডে লগইন নকৰাকৈ এপ অন্বেষণ কৰিব দেয়। প্ৰ’ফাইলত সাঁচি থোৱা কিছুমান সুবিধা লগইন নকৰালৈ সীমিত হ’ব পাৰে।';

  @override
  String get helpFaqReplyPrivacy =>
      'আপোনাৰ অভিজ্ঞতা ব্যক্তিগতকৰণৰ বাবে (নাম/বয়স/লিংগ/অৱস্থা) প্ৰ’ফাইল তথ্য সুৰক্ষিতভাৱে সাঁচি ৰখা হয়। চেটত সংবেদনশীল তথ্য শ্বেয়াৰ নকৰিব।\n\nবিতং তথ্যৰ বাবে এপৰ Privacy Policy চাওক।';

  @override
  String get helpFaqReplyChangeLanguage =>
      'ভাষা সলনি কৰিবলৈ: Profile → Language।';

  @override
  String get helpFaqReplyDarkMode =>
      'ডাৰ্ক ম’ড: Profile → Dark Mode ত ট’গল অন/অফ কৰক।';

  @override
  String get helpFaqReplyContactSupport =>
      'সহায় সংযোগ: Contact Us খোলক আৰু বাৰ্তা পঠিয়াওক। সম্ভৱ হলে স্ক্ৰিনশ্বট আৰু ধাপসমূহ যোগ কৰক।';

  @override
  String get helpFaqReplyFallback =>
      'মই সহায় কৰিব পাৰোঁ: লক্ষণ পৰীক্ষা, ভইচ ইনপুট, প্ৰকোপ সতৰ্কতা, ক্লিনিক লকেটৰ, OTP লগইন, গোপনীয়তা, ভাষা আৰু ডাৰ্ক ম’ড।\n\nএইবোৰ চেষ্টা কৰক: \"লক্ষণ কেনেকৈ চেক কৰোঁ?\", \"ওচৰৰ ক্লিনিক কেনেকৈ বিচাৰিম?\", \"মোৰ তথ্য সুৰক্ষিত নেকি?\"';
}
