// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Bengali Bangla (`bn`).
class AppLocalizationsBn extends AppLocalizations {
  AppLocalizationsBn([String locale = 'bn']) : super(locale);

  @override
  String get appTitle => 'মেডিমিত্রা';

  @override
  String get close => 'বন্ধ করুন';

  @override
  String get loginTagline => 'আপনি এবং আপনার পরিবারের জন্য সহজ স্বাস্থ্যসেবা';

  @override
  String get smsLogin => 'এসএমএস লগইন';

  @override
  String get emailLogin => 'ইমেইল লগইন';

  @override
  String get homeHello => 'হ্যালো,';

  @override
  String get homeThere => 'বন্ধু';

  @override
  String get homeChatCta => 'আমাদের AI হেল্থকেয়ার চ্যাট সহকারী আবিষ্কার করুন';

  @override
  String get homeOurFeatures => 'আমাদের ফিচারসমূহ';

  @override
  String get homeHighlights => 'হাইলাইটস';

  @override
  String get homeDisclaimerTitle => 'অস্বীকৃতি';

  @override
  String get homeDisclaimerBody =>
      'MediMitra শুধুমাত্র তথ্যের জন্য এবং এটি চিকিৎসা পরামর্শ নয়। এটি ডাক্তারের বিকল্প নয়।\nগুরুতর উপসর্গ বা যে কোনও চিকিৎসা জরুরিতে, অনুগ্রহ করে নিকটতম হাসপাতালে যান অথবা অবিলম্বে জরুরি পরিষেবার সাথে যোগাযোগ করুন।';

  @override
  String get featureSymptomChecker => 'উপসর্গ যাচাই';

  @override
  String get featureWomensHealth => 'নারী স্বাস্থ্য সচেতনতা';

  @override
  String get featureInsurance => 'বিমা';

  @override
  String get featureAiHealthSummary => 'AI স্বাস্থ্য সারাংশ';

  @override
  String get featureReminders => 'রিমাইন্ডার';

  @override
  String get featureLocateClinics => 'আপনার কাছাকাছি ক্লিনিক খুঁজুন';

  @override
  String get promoAiSymptomCheckTitle => 'AI উপসর্গ যাচাই';

  @override
  String get promoAiSymptomCheckSubtitle =>
      'উপসর্গ বলুন, সেকেন্ডে গাইডেন্স পান।';

  @override
  String get promoVoiceWaveformTitle => 'ভয়েস + ওয়েভফর্ম';

  @override
  String get promoVoiceWaveformSubtitle =>
      'ভয়েস ইনপুট সাপোর্ট সহ হ্যান্ডস-ফ্রি চ্যাট।';

  @override
  String get promoProfilePersonalizationTitle => 'প্রোফাইল পার্সোনালাইজেশন';

  @override
  String get promoProfilePersonalizationSubtitle =>
      'ভালো সহায়তার জন্য বয়স, লিঙ্গ ও অবস্থা সংরক্ষণ করুন।';

  @override
  String get promoNearbyClinicsTitle => 'কাছাকাছি ক্লিনিক';

  @override
  String get promoNearbyClinicsSubtitle =>
      'আপনার অবস্থানের কাছাকাছি স্বাস্থ্যসেবা খুঁজুন।';

  @override
  String get settings => 'সেটিংস';

  @override
  String get supportAndInformation => 'সাপোর্ট ও তথ্য';

  @override
  String get notifications => 'নোটিফিকেশন';

  @override
  String get manageYourNotifications => 'আপনার নোটিফিকেশন পরিচালনা করুন';

  @override
  String get notificationsEnabled => 'নোটিফিকেশন চালু';

  @override
  String get notificationsDisabled => 'নোটিফিকেশন বন্ধ';

  @override
  String get couldNotUpdateNotifications => 'নোটিফিকেশন আপডেট করা যায়নি';

  @override
  String get darkMode => 'ডার্ক মোড';

  @override
  String get toggleDarkTheme => 'ডার্ক থিম টগল করুন';

  @override
  String get helpAndFaq => 'সহায়তা ও FAQ';

  @override
  String get getHelpAndAnswers => 'সহায়তা এবং উত্তর পান';

  @override
  String get getInTouchWithSupport => 'সাপোর্টের সাথে যোগাযোগ করুন';

  @override
  String get aboutMediMitra => 'MediMitra সম্পর্কে';

  @override
  String versionLine(Object version) {
    return 'ভার্সন $version';
  }

  @override
  String get privacyPolicy => 'প্রাইভেসি পলিসি';

  @override
  String get howWeProtectYourData => 'আমরা কীভাবে আপনার ডেটা সুরক্ষিত রাখি';

  @override
  String get termsAndConditions => 'শর্তাবলী';

  @override
  String get termsConditionsBody =>
      'Terms & Conditions\n\nBy downloading and using this application, you agree to comply with and be bound by these Terms and Conditions. If you do not agree with any part of these terms, you should discontinue using the app.\n\nThis application is designed to provide health-related information and decision-support guidance only. It is not a medical diagnostic tool and does not replace consultation with a qualified doctor or healthcare professional. All information provided by the app is for educational and support purposes, and users must always seek professional medical advice for diagnosis, treatment, or emergencies.\n\nUsers are responsible for providing accurate and honest information while using the app. The guidance generated by the system depends on the inputs provided by the user, and incorrect or incomplete information may lead to inaccurate results. The app should not be used as the sole basis for making medical decisions.\n\nThis application is not intended for emergency situations. In case of severe symptoms such as chest pain, difficulty breathing, loss of consciousness, or heavy bleeding, users must immediately contact local emergency services or visit the nearest hospital.\n\nTo the maximum extent permitted by law, the developers shall not be held liable for any direct or indirect damages arising from the use of this application. Use of the app is entirely at the user’s own risk, and no guarantee is made regarding the accuracy, completeness, or reliability of the information provided.\n\nUse of this application is also governed by our Privacy Policy. By continuing to use the app, you confirm that you have read, understood, and agreed to both the Privacy Policy and these Terms and Conditions.\n\nWe reserve the right to modify or update these Terms and Conditions at any time. Any changes will be displayed within the app, and continued use of the app after such changes indicates acceptance of the updated terms.';

  @override
  String get legalAgreement => 'আইনি চুক্তি';

  @override
  String get deleteData => 'ডেটা মুছুন';

  @override
  String get deleteChatsAndSavedSettings => 'চ্যাট এবং সংরক্ষিত সেটিংস মুছুন';

  @override
  String get logOut => 'লগ আউট';

  @override
  String get logoutQuestion => 'লগ আউট করবেন?';

  @override
  String get logoutReturnToLogin =>
      'আপনি লগ আউট হবেন এবং লগইন স্ক্রিনে ফিরে যাবেন।';

  @override
  String get chooseAnAction => 'একটি অ্যাকশন বেছে নিন';

  @override
  String get deleteAccount => 'অ্যাকাউন্ট মুছুন';

  @override
  String get permanentlyDeleteAccount => 'আপনার অ্যাকাউন্ট স্থায়ীভাবে মুছুন';

  @override
  String get deleteLocalData => 'লোকাল ডেটা মুছুন';

  @override
  String get deleteLocalDataOnDevice =>
      'এই ডিভাইসের চ্যাট ও সংরক্ষিত সেটিংস মুছুন';

  @override
  String get clearLocalDataQuestion => 'লোকাল ডেটা পরিষ্কার করবেন?';

  @override
  String get clearLocalDataBody =>
      'এটি এই ডিভাইসে লোকালভাবে সংরক্ষিত অ্যাপ ডেটা (সংরক্ষিত সেটিংস, ক্যাশড প্রোফাইল ফিল্ড এবং মেমোরিতে চ্যাট হিস্ট্রি) মুছে দেবে।\n\nসব পরিবর্তন প্রয়োগ দেখতে অ্যাপ রিস্টার্ট করতে হতে পারে।';

  @override
  String get clear => 'পরিষ্কার';

  @override
  String get localDataCleared => 'লোকাল ডেটা পরিষ্কার হয়েছে';

  @override
  String get couldNotClearLocalData => 'লোকাল ডেটা পরিষ্কার করা যায়নি';

  @override
  String get accountDeletionNotAvailable =>
      'এই প্ল্যাটফর্মে অ্যাকাউন্ট ডিলিট উপলব্ধ নয়';

  @override
  String get noSignedInAccountFound => 'কোনও সাইন-ইন অ্যাকাউন্ট পাওয়া যায়নি';

  @override
  String get deleteAccountQuestion => 'অ্যাকাউন্ট মুছবেন?';

  @override
  String get deleteAccountBody =>
      'এটি আপনার অ্যাকাউন্ট স্থায়ীভাবে মুছে দেবে। আপনি এই ডিভাইস থেকে লগ আউট হয়ে যাবেন।';

  @override
  String get deletingAccount => 'অ্যাকাউন্ট মুছে ফেলা হচ্ছে...';

  @override
  String get pleaseLoginAgainThenDelete =>
      'অনুগ্রহ করে আবার লগইন করুন, তারপর অ্যাকাউন্ট মুছুন';

  @override
  String get couldNotDeleteAccount => 'অ্যাকাউন্ট মুছতে পারিনি';

  @override
  String get networkSlowTryAgain =>
      'নেটওয়ার্ক ধীর। অনুগ্রহ করে আবার চেষ্টা করুন।';

  @override
  String get defaultUser => 'ব্যবহারকারী';

  @override
  String userIdLine(Object id) {
    return 'ইউজার আইডি: $id';
  }

  @override
  String get clinicsNearYou => 'আপনার কাছাকাছি ক্লিনিক';

  @override
  String get refresh => 'রিফ্রেশ';

  @override
  String get recenter => 'পুনরায় কেন্দ্র করুন';

  @override
  String resultsCount(Object count) {
    return 'ফলাফল ($count)';
  }

  @override
  String get nearbyClinics => 'কাছাকাছি ক্লিনিক';

  @override
  String get call => 'কল';

  @override
  String get navigate => 'নেভিগেট';

  @override
  String get unableToOpenDialer => 'ডায়ালার খুলতে পারিনি';

  @override
  String get unableToOpenMaps => 'ম্যাপ খুলতে পারিনি';

  @override
  String get radius => 'ব্যাসার্ধ';

  @override
  String get tryAgain => 'আবার চেষ্টা করুন';

  @override
  String get openLocationSettings => 'লোকেশন সেটিংস খুলুন';

  @override
  String get locationServicesDisabled =>
      'লোকেশন সার্ভিস বন্ধ। অনুগ্রহ করে GPS চালু করুন।';

  @override
  String get locationPermissionDenied =>
      'লোকেশন পারমিশন প্রত্যাখ্যান করা হয়েছে।';

  @override
  String get locationPermissionDeniedForever =>
      'লোকেশন পারমিশন স্থায়ীভাবে প্রত্যাখ্যান। সেটিংস থেকে চালু করুন।';

  @override
  String get chooseLanguage => 'ভাষা নির্বাচন করুন';

  @override
  String get cancel => 'বাতিল';

  @override
  String get save => 'সংরক্ষণ';

  @override
  String get contactUs => 'যোগাযোগ করুন';

  @override
  String get needHelp => 'সাহায্য দরকার?';

  @override
  String get contactSubtitle =>
      'আমাদের একটি বার্তা পাঠান এবং আমাদের টিম উত্তর দেবে।';

  @override
  String supportEmailLine(Object email) {
    return 'সাপোর্ট ইমেইল: $email';
  }

  @override
  String get typicalResponseLine => 'সাধারণ উত্তর: ২৪ ঘণ্টার মধ্যে';

  @override
  String get language => 'ভাষা';

  @override
  String languageSetTo(Object language) {
    return 'ভাষা সেট হয়েছে: $language';
  }

  @override
  String get fullName => 'পূর্ণ নাম';

  @override
  String get yourName => 'আপনার নাম';

  @override
  String get email => 'ইমেইল';

  @override
  String get emailHint => 'name@example.com';

  @override
  String get phoneOptional => 'ফোন (ঐচ্ছিক)';

  @override
  String get yourMobileNumber => 'আপনার মোবাইল নম্বর';

  @override
  String get subject => 'বিষয়';

  @override
  String get subjectHint => 'এটি কী সম্পর্কে?';

  @override
  String get message => 'বার্তা';

  @override
  String get messageHint => 'আপনার সমস্যা বা প্রশ্ন লিখুন';

  @override
  String get send => 'পাঠান';

  @override
  String get sentSuccess =>
      'পাঠানো হয়েছে! আমরা শীঘ্রই আপনার সাথে যোগাযোগ করব।';

  @override
  String get required => 'আবশ্যক';

  @override
  String get enterValidEmail => 'একটি বৈধ ইমেইল লিখুন';

  @override
  String get writeMoreDetail => 'অনুগ্রহ করে আরও কিছু বিস্তারিত লিখুন';

  @override
  String get couldNotOpenEmailApp => 'ইমেইল অ্যাপ খুলতে পারিনি।';

  @override
  String get couldNotSendTryLater => 'পাঠানো যায়নি। পরে আবার চেষ্টা করুন।';

  @override
  String get tipNoShareOtp => 'টিপ: এখানে পাসওয়ার্ড বা OTP শেয়ার করবেন না।';

  @override
  String get loginLanguageLabel => 'English / বাংলা';

  @override
  String get loginHeroSubtitle => 'আপনার স্বাস্থ্য সঙ্গী';

  @override
  String get loginMobileNumberLabel => 'মোবাইল নম্বর';

  @override
  String get loginMobileHint => '00000 00000';

  @override
  String get loginEmailLabel => 'ইমেইল ঠিকানা';

  @override
  String get loginPasswordLabel => 'পাসওয়ার্ড';

  @override
  String get loginPasswordHint => 'পাসওয়ার্ড লিখুন';

  @override
  String get loginPleaseWait => 'অনুগ্রহ করে অপেক্ষা করুন...';

  @override
  String get loginSendOtp => 'OTP পাঠান';

  @override
  String get loginContinue => 'চালিয়ে যান';

  @override
  String get loginSendingOtp => 'OTP পাঠানো হচ্ছে...';

  @override
  String get loginOr => 'অথবা';

  @override
  String get loginContinueAsGuest => 'গেস্ট হিসেবে চালিয়ে যান';

  @override
  String get loginAgreementText =>
      'লগইন করলে, আপনি MediMitra-এর\nসার্ভিসের শর্তাবলী এবং প্রাইভেসি পলিসিতে সম্মত হচ্ছেন।';

  @override
  String get loginUnableContinueGuest => 'গেস্ট হিসেবে চালিয়ে যেতে পারিনি।';

  @override
  String get loginEnterMobileNumber => 'মোবাইল নম্বর লিখুন।';

  @override
  String get loginEnterValidMobileNumber =>
      'একটি বৈধ ১০ সংখ্যার মোবাইল নম্বর লিখুন।';

  @override
  String get loginOtpSent => 'OTP পাঠানো হয়েছে।';

  @override
  String get loginFailedSendOtp => 'OTP পাঠাতে ব্যর্থ।';

  @override
  String get loginEnterValidEmail => 'একটি বৈধ ইমেইল লিখুন।';

  @override
  String get loginPasswordMinChars => 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে।';

  @override
  String get loginEmailPasswordDisabled =>
      'Firebase Console-এ Email/Password সাইন-ইন বন্ধ আছে।';

  @override
  String get loginAccountExistsTryLogin =>
      'অ্যাকাউন্ট ইতিমধ্যেই আছে। লগইন করে দেখুন।';

  @override
  String get loginWeakPassword => 'পাসওয়ার্ড দুর্বল (কমপক্ষে ৬ অক্ষর)।';

  @override
  String get loginIncorrectPassword => 'ভুল পাসওয়ার্ড।';

  @override
  String get loginInvalidEmail => 'অবৈধ ইমেইল।';

  @override
  String get loginLoginFailed => 'লগইন ব্যর্থ।';

  @override
  String get otpVerifyNumber => 'নম্বর যাচাই করুন';

  @override
  String get otpSentTo => 'আমরা ৬ সংখ্যার কোড পাঠিয়েছি';

  @override
  String get otpHaventReceived => 'কোড পাননি?';

  @override
  String get otpResendCode => 'কোড আবার পাঠান';

  @override
  String get otpVerifyProceed => 'যাচাই করে এগিয়ে যান';

  @override
  String get otpVerifying => 'যাচাই হচ্ছে...';

  @override
  String get otpEnter6Digit => '৬ সংখ্যার OTP লিখুন।';

  @override
  String get otpInvalid => 'অবৈধ OTP।';

  @override
  String get otpVerificationFailed => 'OTP যাচাই ব্যর্থ।';

  @override
  String get otpFailedResend => 'কোড আবার পাঠাতে ব্যর্থ।';

  @override
  String get otpCodeResent => 'কোড আবার পাঠানো হয়েছে।';

  @override
  String get otpSafetyFirst => 'নিরাপত্তা আগে';

  @override
  String get otpSafetyNote =>
      'MediMitra-এর এনক্রিপশন দিয়ে আপনার স্বাস্থ্য রেকর্ডের সাথে নিরাপদে যুক্ত হন।';

  @override
  String get communityOutbreakAlerts => 'কমিউনিটি প্রাদুর্ভাব সতর্কতা';

  @override
  String get outbreakPrivacyNote =>
      'প্রাইভেসি-ফার্স্ট: শুধুমাত্র PIN3 ও দিন অনুযায়ী সমষ্টিগত উপসর্গ গণনা। কোনও নাম, চ্যাট টেক্সট, GPS বা নির্দিষ্ট টাইমস্ট্যাম্প নেই।';

  @override
  String get regionNotSet => 'এলাকা: সেট করা নেই';

  @override
  String regionPin3Line(Object region) {
    return 'এলাকা: $region (PIN3)';
  }

  @override
  String get set => 'সেট করুন';

  @override
  String get setAreaPin3Title => 'আপনার এলাকা সেট করুন (PIN3)';

  @override
  String get setAreaPin3Body =>
      'আপনার PIN কোড লিখুন। আমরা শুধুমাত্র প্রথম ৩ সংখ্যা (মোটামুটি এলাকা) সংরক্ষণ করি।';

  @override
  String get pinExampleHint => 'যেমন 411001';

  @override
  String get enterFirst3DigitsPin =>
      'আপনার PIN-এর কমপক্ষে প্রথম ৩ সংখ্যা লিখুন।';

  @override
  String get unableToSaveRegion => 'এলাকা সংরক্ষণ করতে পারিনি।';

  @override
  String get setPin3ToSeeAlerts =>
      'আপনার এলাকার প্রাদুর্ভাব সতর্কতা দেখতে PIN3 সেট করুন।';

  @override
  String get noAlertsToday => 'আজ আপনার এলাকার জন্য কোনও সতর্কতা নেই।';

  @override
  String get prevention => 'প্রতিরোধ';

  @override
  String get outbreakLevelHighRisk => 'উচ্চ ঝুঁকি';

  @override
  String get outbreakLevelWarning => 'সতর্কতা';

  @override
  String get outbreakLevelWatch => 'পর্যবেক্ষণ';

  @override
  String get outbreakLevelNone => 'কোনওটি নয়';

  @override
  String get back => 'পেছনে';

  @override
  String get next => 'পরবর্তী';

  @override
  String get couldNotSaveConsent =>
      'আপনার সম্মতি সংরক্ষণ করতে পারিনি। অনুগ্রহ করে আবার চেষ্টা করুন।';

  @override
  String get termsSigningTitle => 'সার্ভিসের শর্তাবলী';

  @override
  String get termsSigningIntro =>
      'উপসর্গ মূল্যায়ন ব্যবহারের আগে, অনুগ্রহ করে সার্ভিসের শর্তাবলী এবং প্রাইভেসি পলিসি গ্রহণ করুন। দয়া করে মনে রাখুন:';

  @override
  String get termsBulletNotDiagnosisTitle => 'এটি কোনও রোগ নির্ণয় নয়।';

  @override
  String get termsBulletNotDiagnosisBody =>
      ' এটি শুধুমাত্র তথ্যের জন্য এবং যোগ্য চিকিৎসা মতামত নয়।';

  @override
  String get termsBulletNoEmergencyTitle =>
      'জরুরি অবস্থায় এটি ব্যবহার করবেন না।';

  @override
  String get termsBulletNoEmergencyBody =>
      ' স্বাস্থ্য জরুরিতে অবিলম্বে আপনার স্থানীয় জরুরি নম্বরে কল করুন।';

  @override
  String get termsBulletDataSafeTitle => 'আপনার ডেটা নিরাপদ।';

  @override
  String get termsBulletDataSafeBody =>
      ' আপনি যে তথ্য দেন তা শেয়ার করা হবে না বা আপনাকে শনাক্ত করতে ব্যবহার করা হবে না।';

  @override
  String get termsConsentTermsPrefix => 'আমি ';

  @override
  String get termsConsentTermsLink => 'সার্ভিসের শর্তাবলী';

  @override
  String get termsConsentTermsSuffix => ' পড়েছি এবং গ্রহণ করছি।';

  @override
  String get termsConsentPrivacyPrefix =>
      'ইন্টারভিউয়ের জন্য আমার স্বাস্থ্য তথ্য ব্যবহার করতে আমি সম্মত। আরও তথ্য ';

  @override
  String get termsConsentPrivacyLink => 'প্রাইভেসি পলিসি';

  @override
  String get termsConsentPrivacySuffix => ' তে আছে।';

  @override
  String get quickQuestions => 'দ্রুত প্রশ্ন';

  @override
  String get typeAQuestionHint => 'একটি প্রশ্ন লিখুন…';

  @override
  String get talkToMaya => 'মায়ার সাথে কথা বলুন';

  @override
  String get womensHealthHubTitle => 'নারী স্বাস্থ্য হাব';

  @override
  String get womensHealthHubWelcome => 'আপনার স্বাস্থ্য যাত্রায় স্বাগতম';

  @override
  String get womensHealthHubSubtitle =>
      'রিসোর্স অন্বেষণ ও ব্যক্তিগত যত্ন পেতে একটি বিভাগ বেছে নিন।';

  @override
  String get menstrualHealth => 'মাসিক স্বাস্থ্য';

  @override
  String get pregnancyAndMaternal => 'গর্ভাবস্থা ও মাতৃত্ব';

  @override
  String get breastHealth => 'স্তন স্বাস্থ্য';

  @override
  String get comingSoon => 'শিগগিরই আসছে';

  @override
  String get womensHealthHubTagline => 'MEDIMITRA WELLNESS';

  @override
  String get womensHealthCategoryMenstrualDescription =>
      'আপনার মাসিক চক্র বুঝুন,\nস্বাস্থ্যবিধি সম্পর্কে জানুন, এবং\nসহজে পিরিয়ড ম্যানেজ করুন।';

  @override
  String get womensHealthCategoryPregnancyDescription =>
      'সুস্থ গর্ভাবস্থার জন্য বিশেষজ্ঞ পরামর্শ,\nপুষ্টির টিপস, এবং\nনিরাপদ ডেলিভারি সহায়তা।';

  @override
  String get womensHealthCategoryBreastDescription =>
      'সহজ স্ব-পরীক্ষা নির্দেশিকা\nএবং সচেতনতা টিপস\nআগে শনাক্তকরণ ও যত্নের জন্য।';

  @override
  String get recommended => 'প্রস্তাবিত';

  @override
  String get explore => 'এক্সপ্লোর করুন';

  @override
  String get menstrualScreenTitle => 'মাসিক স্বাস্থ্য';

  @override
  String get menstrualWhatIsMenstruationTitle => 'মাসিক ঋতুস্রাব কী?';

  @override
  String get menstrualWhatIsMenstruationBody =>
      'মাসিক ঋতুস্রাব একটি স্বাভাবিক, মাসিক প্রক্রিয়া যেখানে শরীর জরায়ুর আস্তরণ ঝরিয়ে ফেলে। এটি সুস্থ প্রজনন ব্যবস্থার একটি লক্ষণ এবং বড় হওয়ার স্বাভাবিক অংশ।';

  @override
  String get menstrualQuote => 'নবায়ন ও জীবনের চক্র';

  @override
  String get menstrualWhatIsNormalTitle => 'কী স্বাভাবিক?';

  @override
  String get menstrualNormalItem1 => 'চক্র ২১ থেকে ৩৫ দিনের মধ্যে থাকে';

  @override
  String get menstrualNormalItem2 => 'রক্তপাত ৩ থেকে ৭ দিন স্থায়ী হয়';

  @override
  String get menstrualNormalItem3 => 'হালকা থেকে মাঝারি খিঁচুনি বা অস্বস্তি';

  @override
  String get menstrualWarningSignsTitle => 'সতর্কতার লক্ষণ';

  @override
  String get menstrualWarningItem1 =>
      'ভারী রক্তপাতের কারণে প্রতি ১–২ ঘণ্টায় প্যাড বদলাতে হওয়া';

  @override
  String get menstrualWarningItem2 => 'দৈনন্দিন কাজ ব্যাহত করে এমন তীব্র ব্যথা';

  @override
  String get menstrualWarningItem3 =>
      'চক্র নিয়মিতভাবে ২১ দিনের কম বা ৩৮ দিনের বেশি';

  @override
  String get menstrualHygieneTipsTitle => 'স্বাস্থ্যবিধি টিপস';

  @override
  String get menstrualTipChangeRegularlyTitle => 'নিয়মিত বদলান';

  @override
  String get menstrualTipChangeRegularlySubtitle =>
      'প্রতি ৪–৬ ঘণ্টায় প্যাড বদলান';

  @override
  String get menstrualTipCleanHandsTitle => 'হাত পরিষ্কার রাখুন';

  @override
  String get menstrualTipCleanHandsSubtitle => 'আগে ও পরে হাত ধুয়ে নিন';

  @override
  String get menstrualTipStayDryTitle => 'শুষ্ক রাখুন';

  @override
  String get menstrualTipStayDrySubtitle =>
      'জননাঙ্গের অংশ পরিষ্কার ও শুষ্ক রাখুন';

  @override
  String get menstrualMythsFactsTitle => 'মিথ ও তথ্য';

  @override
  String get menstrualMyth1 => 'মিথ: \"পিরিয়ডের সময় ব্যায়াম করা উচিত নয়।\"';

  @override
  String get menstrualFact1 =>
      'তথ্য: হালকা ব্যায়াম খিঁচুনি কমাতে এবং মন ভালো রাখতে সাহায্য করতে পারে।';

  @override
  String get menstrualMyth2 => 'মিথ: \"মাসিকের রক্ত \'নোংরা\' রক্ত।\"';

  @override
  String get menstrualFact2 =>
      'তথ্য: এটি জরায়ুর আস্তরণ থেকে আসা স্বাভাবিক রক্ত ও টিস্যু।';

  @override
  String get chatHeaderTitle => 'স্বাস্থ্য সহকারী';

  @override
  String get chatHeaderStatusOnline => 'অনলাইন';

  @override
  String get chatToday => 'আজ';

  @override
  String get chatQuickChipCheckFever => '🌡️ জ্বর পরীক্ষা';

  @override
  String get chatQuickPromptCheckFever => 'আমি জ্বর পরীক্ষা করতে চাই।';

  @override
  String get chatQuickChipWomensHealth => '🤰 নারী স্বাস্থ্য';

  @override
  String get chatQuickPromptWomensHealth =>
      'আমার নারী স্বাস্থ্য নিয়ে একটি প্রশ্ন আছে।';

  @override
  String get chatQuickChipFirstAid => '🩹 প্রাথমিক চিকিৎসা';

  @override
  String get chatQuickPromptFirstAid => 'আমার প্রাথমিক চিকিৎসার পরামর্শ দরকার।';

  @override
  String get chatQuickChipChildCare => '👶 শিশু যত্ন';

  @override
  String get chatQuickPromptChildCare => 'আমার শিশু যত্নের নির্দেশনা দরকার।';

  @override
  String get chatInputHintAskMeAnything => 'যা খুশি জিজ্ঞেস করুন...';

  @override
  String get profileSaved => 'প্রোফাইল সংরক্ষিত হয়েছে';

  @override
  String get saving => 'সংরক্ষণ করা হচ্ছে...';

  @override
  String get saveChanges => 'পরিবর্তন সংরক্ষণ করুন';

  @override
  String get profileTopBarTitle => 'Profile Settings';

  @override
  String get profileHeaderSubtitle => 'User Profile';

  @override
  String get profileSectionFullName => 'FULL NAME';

  @override
  String get profileHintFullName => 'e.g. Rahul Sharma';

  @override
  String get profileSectionAge => 'AGE';

  @override
  String get profileHintAge => 'Enter your age';

  @override
  String get profileSectionGender => 'GENDER';

  @override
  String get profileGenderMale => 'Male';

  @override
  String get profileGenderFemale => 'Female';

  @override
  String get profileGenderOther => 'Other';

  @override
  String get profileChronicConditions => 'CHRONIC CONDITIONS';

  @override
  String get profileConditionsBadge => 'BILINGUAL';

  @override
  String get conditionDiabetesTitle => 'Diabetes';

  @override
  String get conditionDiabetesSubtitle => 'Diabetes (Sugar)';

  @override
  String get conditionBpHeartTitle => 'BP & Heart';

  @override
  String get conditionBpHeartSubtitle => 'Blood pressure / Heart';

  @override
  String get conditionAsthmaTitle => 'Asthma';

  @override
  String get conditionAsthmaSubtitle => 'Breathing';

  @override
  String get conditionThyroidTitle => 'Thyroid';

  @override
  String get conditionThyroidSubtitle => 'Thyroid';

  @override
  String get conditionTbTitle => 'TB';

  @override
  String get conditionTbSubtitle => 'Tuberculosis';

  @override
  String get conditionNoneTitle => 'None';

  @override
  String get conditionNoneSubtitle => 'No conditions';

  @override
  String get helpFaqBotGreeting =>
      'Hi! I\'m MediMitra Help. Ask me anything about symptom checking, voice input, outbreak alerts, clinics, login, or privacy.\n\nNote: This is not medical advice. If you have a medical emergency, contact local emergency services.';

  @override
  String get helpFaqSuggestionCheckSymptoms => 'How do I check symptoms?';

  @override
  String get helpFaqSuggestionVoiceSymptoms => 'How do voice symptoms work?';

  @override
  String get helpFaqSuggestionOutbreakAlert => 'What is outbreak alert?';

  @override
  String get helpFaqSuggestionNearbyClinics => 'How to find nearby clinics?';

  @override
  String get helpFaqSuggestionOtpLogin => 'How does OTP login work?';

  @override
  String get helpFaqSuggestionDataSafe => 'Is my data safe?';

  @override
  String get helpFaqSuggestionGuestMode => 'Can I use the app without login?';

  @override
  String get helpFaqSuggestionChangeLanguage => 'How to change language?';

  @override
  String get helpFaqSuggestionDarkMode => 'How to enable dark mode?';

  @override
  String get helpFaqReplySymptomChecking =>
      'To check symptoms:\n1) Open Chat / Symptom Checker\n2) Type your symptoms (or use voice)\n3) Answer follow-up questions\n\nMediMitra will show likely causes and next steps. For severe symptoms (chest pain, trouble breathing, fainting), seek urgent care.';

  @override
  String get helpFaqReplyVoiceSymptoms =>
      'Voice symptoms: tap the microphone, speak your symptoms clearly, and the app converts it to text for analysis.\n\nTips: speak one symptom at a time, use simple words (\"fever\", \"cough\"), and allow microphone permission when asked.';

  @override
  String get helpFaqReplyOutbreakAlert =>
      'Outbreak alert helps you see if certain symptoms are trending in your area. It\'s based on anonymized, aggregated symptom patterns and is meant for awareness (not diagnosis).\n\nYou can view outbreak insights from the Outbreak section.';

  @override
  String get helpFaqReplyNearbyClinics =>
      'Nearby clinics: open the Clinic Locator to see clinics around you.\n\nMake sure Location permission is enabled. If you prefer, you can also search by area/city (if available on your build).';

  @override
  String get helpFaqReplyOtpLogin =>
      'OTP login: enter your 10-digit mobile number and we send a verification OTP. Enter the 6-digit OTP to proceed.\n\nIf you don\'t receive it, wait for the resend timer and try again. Also confirm network/SMS permissions.';

  @override
  String get helpFaqReplyGuestMode =>
      'Guest mode lets you explore the app without signing in. Some features that save to your profile (like personalized settings) may be limited until you log in.';

  @override
  String get helpFaqReplyPrivacy =>
      'Your profile data (like name/age/gender/conditions) is stored securely for your account to personalize your experience. We do not want you to share sensitive info in chat.\n\nFor exact details, check Privacy Policy (in the app).';

  @override
  String get helpFaqReplyChangeLanguage =>
      'You can change language from Profile → Language.';

  @override
  String get helpFaqReplyDarkMode =>
      'Dark mode: go to Profile → Dark Mode and toggle it on/off. Your choice is saved and works across the whole app.';

  @override
  String get helpFaqReplyContactSupport =>
      'Contact support: open Contact Us and send your message. Include screenshots and steps if possible.';

  @override
  String get helpFaqReplyFallback =>
      'I can help with: symptom checking, voice input, outbreak alerts, clinic locator, OTP login, privacy, language, and dark mode.\n\nTry one of these: \"How do I check symptoms?\", \"How to find nearby clinics?\", \"Is my data safe?\"';
}
