// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Tamil (`ta`).
class AppLocalizationsTa extends AppLocalizations {
  AppLocalizationsTa([String locale = 'ta']) : super(locale);

  @override
  String get appTitle => 'மெடிமித்ரா';

  @override
  String get close => 'மூடு';

  @override
  String get loginTagline =>
      'உங்களுக்கும் உங்கள் குடும்பத்திற்கும் எளிய சுகாதார சேவை';

  @override
  String get smsLogin => 'எஸ்எம்எஸ் உள்நுழைவு';

  @override
  String get emailLogin => 'மின்னஞ்சல் உள்நுழைவு';

  @override
  String get homeHello => 'வணக்கம்,';

  @override
  String get homeThere => 'நண்பா';

  @override
  String get homeChatCta =>
      'எங்கள் AI சுகாதார சேட் உதவியாளரை அறிந்து கொள்ளுங்கள்';

  @override
  String get homeOurFeatures => 'எங்கள் அம்சங்கள்';

  @override
  String get homeHighlights => 'முக்கிய அம்சங்கள்';

  @override
  String get homeDisclaimerTitle => 'துறப்பு';

  @override
  String get homeDisclaimerBody =>
      'MediMitra தகவலுக்காக மட்டும்; இது மருத்துவ ஆலோசனை அல்ல. இது மருத்துவரை மாற்றாது.\nகடுமையான அறிகுறிகள் அல்லது மருத்துவ அவசரநிலையில், அருகிலுள்ள மருத்துவமனைக்கு செல்லவும் அல்லது அவசர சேவைகளை உடனடியாக தொடர்பு கொள்ளவும்.';

  @override
  String get featureSymptomChecker => 'அறிகுறி சரிபார்ப்பு';

  @override
  String get featureWomensHealth => 'பெண்கள் ஆரோக்கிய விழிப்புணர்வு';

  @override
  String get featureInsurance => 'காப்பீடு';

  @override
  String get featureAiHealthSummary => 'AI ஆரோக்கிய சுருக்கம்';

  @override
  String get featureReminders => 'நினைவூட்டல்கள்';

  @override
  String get featureLocateClinics =>
      'உங்கள் அருகிலுள்ள கிளினிக்குகளை கண்டுபிடிக்கவும்';

  @override
  String get promoAiSymptomCheckTitle => 'AI அறிகுறி சரிபார்ப்பு';

  @override
  String get promoAiSymptomCheckSubtitle =>
      'அறிகுறிகளை கூறுங்கள்; சில வினாடிகளில் வழிகாட்டல் பெறுங்கள்.';

  @override
  String get promoVoiceWaveformTitle => 'குரல் + அலைவடிவம்';

  @override
  String get promoVoiceWaveformSubtitle =>
      'குரல் உள்ளீட்டுடன் கைமுற்றிலும் இல்லாமல் சேட் செய்யுங்கள்.';

  @override
  String get promoProfilePersonalizationTitle => 'சுயவிவர தனிப்பயனாக்கம்';

  @override
  String get promoProfilePersonalizationSubtitle =>
      'சிறந்த உதவிக்காக வயது, பாலினம் மற்றும் நிலைகளை சேமிக்கவும்.';

  @override
  String get promoNearbyClinicsTitle => 'அருகிலுள்ள கிளினிக்குகள்';

  @override
  String get promoNearbyClinicsSubtitle =>
      'உங்கள் இடத்திற்கு அருகிலுள்ள சுகாதார சேவைகளை கண்டுபிடிக்கவும்.';

  @override
  String get settings => 'அமைப்புகள்';

  @override
  String get supportAndInformation => 'ஆதரவு மற்றும் தகவல்';

  @override
  String get notifications => 'அறிவிப்புகள்';

  @override
  String get manageYourNotifications => 'உங்கள் அறிவிப்புகளை நிர்வகிக்கவும்';

  @override
  String get notificationsEnabled => 'அறிவிப்புகள் இயக்கு நிலையில் உள்ளன';

  @override
  String get notificationsDisabled => 'அறிவிப்புகள் நிறுத்தப்பட்டுள்ளது';

  @override
  String get couldNotUpdateNotifications =>
      'அறிவிப்புகளை புதுப்பிக்க முடியவில்லை';

  @override
  String get darkMode => 'இருள் முறை';

  @override
  String get toggleDarkTheme => 'இருள் தீமை மாற்று';

  @override
  String get helpAndFaq => 'உதவி மற்றும் FAQ';

  @override
  String get getHelpAndAnswers => 'உதவியும் பதில்களும் பெறுங்கள்';

  @override
  String get getInTouchWithSupport => 'ஆதரவை தொடர்பு கொள்ளுங்கள்';

  @override
  String get aboutMediMitra => 'MediMitra பற்றி';

  @override
  String versionLine(Object version) {
    return 'பதிப்பு $version';
  }

  @override
  String get privacyPolicy => 'தனியுரிமைக் கொள்கை';

  @override
  String get howWeProtectYourData => 'உங்கள் தரவை எவ்வாறு பாதுகாப்போம்';

  @override
  String get termsAndConditions => 'விதிமுறைகள் மற்றும் நிபந்தனைகள்';

  @override
  String get termsConditionsBody =>
      'Terms & Conditions\n\nBy downloading and using this application, you agree to comply with and be bound by these Terms and Conditions. If you do not agree with any part of these terms, you should discontinue using the app.\n\nThis application is designed to provide health-related information and decision-support guidance only. It is not a medical diagnostic tool and does not replace consultation with a qualified doctor or healthcare professional. All information provided by the app is for educational and support purposes, and users must always seek professional medical advice for diagnosis, treatment, or emergencies.\n\nUsers are responsible for providing accurate and honest information while using the app. The guidance generated by the system depends on the inputs provided by the user, and incorrect or incomplete information may lead to inaccurate results. The app should not be used as the sole basis for making medical decisions.\n\nThis application is not intended for emergency situations. In case of severe symptoms such as chest pain, difficulty breathing, loss of consciousness, or heavy bleeding, users must immediately contact local emergency services or visit the nearest hospital.\n\nTo the maximum extent permitted by law, the developers shall not be held liable for any direct or indirect damages arising from the use of this application. Use of the app is entirely at the user’s own risk, and no guarantee is made regarding the accuracy, completeness, or reliability of the information provided.\n\nUse of this application is also governed by our Privacy Policy. By continuing to use the app, you confirm that you have read, understood, and agreed to both the Privacy Policy and these Terms and Conditions.\n\nWe reserve the right to modify or update these Terms and Conditions at any time. Any changes will be displayed within the app, and continued use of the app after such changes indicates acceptance of the updated terms.';

  @override
  String get legalAgreement => 'சட்ட ஒப்பந்தம்';

  @override
  String get deleteData => 'தரவை நீக்கு';

  @override
  String get deleteChatsAndSavedSettings =>
      'சேட்களையும் சேமிக்கப்பட்ட அமைப்புகளையும் நீக்கு';

  @override
  String get logOut => 'வெளியேறு';

  @override
  String get logoutQuestion => 'வெளியேறவா?';

  @override
  String get logoutReturnToLogin =>
      'நீங்கள் வெளியேற்றப்படுவீர்கள் மற்றும் உள்நுழைவு திரைக்குத் திருப்பப்படுவீர்கள்.';

  @override
  String get chooseAnAction => 'ஒரு செயலைத் தேர்வு செய்யவும்';

  @override
  String get deleteAccount => 'கணக்கை நீக்கு';

  @override
  String get permanentlyDeleteAccount => 'உங்கள் கணக்கை நிரந்தரமாக நீக்கு';

  @override
  String get deleteLocalData => 'உள்ளூர் தரவை நீக்கு';

  @override
  String get deleteLocalDataOnDevice =>
      'இந்த சாதனத்தில் சேட்களும் சேமிக்கப்பட்ட அமைப்புகளும் நீக்கப்படும்';

  @override
  String get clearLocalDataQuestion => 'உள்ளூர் தரவை அழிக்கவா?';

  @override
  String get clearLocalDataBody =>
      'இந்த சாதனத்தில் உள்ளூராக சேமிக்கப்பட்ட பயன்பாட்டு தரவை (சேமிக்கப்பட்ட அமைப்புகள், கேஷ் செய்யப்பட்ட சுயவிவரப் புலங்கள், மற்றும் நினைவகத்தில் உள்ள சேட் வரலாறு) நீக்கும்.\n\nஅனைத்து மாற்றங்களும் செயல்பட பயன்பாட்டை மீள்தொடக்க வேண்டியிருக்கலாம்.';

  @override
  String get clear => 'அழி';

  @override
  String get localDataCleared => 'உள்ளூர் தரவு அழிக்கப்பட்டது';

  @override
  String get couldNotClearLocalData => 'உள்ளூர் தரவை அழிக்க முடியவில்லை';

  @override
  String get accountDeletionNotAvailable =>
      'இந்த தளத்தில் கணக்கு நீக்கம் கிடைக்கவில்லை';

  @override
  String get noSignedInAccountFound => 'உள்நுழைந்த கணக்கு எதுவும் இல்லை';

  @override
  String get deleteAccountQuestion => 'கணக்கை நீக்கவா?';

  @override
  String get deleteAccountBody =>
      'இதனால் உங்கள் கணக்கு நிரந்தரமாக நீக்கப்படும். இந்த சாதனத்தில் இருந்து நீங்கள் வெளியேற்றப்படுவீர்கள்.';

  @override
  String get deletingAccount => 'கணக்கை நீக்குகிறது...';

  @override
  String get pleaseLoginAgainThenDelete =>
      'மீண்டும் உள்நுழைந்து பிறகு கணக்கை நீக்கவும்';

  @override
  String get couldNotDeleteAccount => 'கணக்கை நீக்க முடியவில்லை';

  @override
  String get networkSlowTryAgain =>
      'நெட்வொர்க் மெதுவாக உள்ளது. மீண்டும் முயற்சிக்கவும்.';

  @override
  String get defaultUser => 'பயனர்';

  @override
  String userIdLine(Object id) {
    return 'பயனர் ஐடி: $id';
  }

  @override
  String get clinicsNearYou => 'உங்கள் அருகிலுள்ள கிளினிக்குகள்';

  @override
  String get refresh => 'புதுப்பி';

  @override
  String get recenter => 'மீண்டும் மையப்படுத்து';

  @override
  String resultsCount(Object count) {
    return 'முடிவுகள் ($count)';
  }

  @override
  String get nearbyClinics => 'அருகிலுள்ள கிளினிக்குகள்';

  @override
  String get call => 'அழை';

  @override
  String get navigate => 'வழிகாட்டு';

  @override
  String get unableToOpenDialer => 'டயலரை திறக்க முடியவில்லை';

  @override
  String get unableToOpenMaps => 'வரைபடங்களை திறக்க முடியவில்லை';

  @override
  String get radius => 'அரைவு';

  @override
  String get tryAgain => 'மீண்டும் முயற்சி';

  @override
  String get openLocationSettings => 'இட அமைப்புகளை திறக்கவும்';

  @override
  String get locationServicesDisabled =>
      'இட சேவைகள் நிறுத்தப்பட்டுள்ளன. GPS-ஐ இயக்கவும்.';

  @override
  String get locationPermissionDenied => 'இட அனுமதி மறுக்கப்பட்டது.';

  @override
  String get locationPermissionDeniedForever =>
      'இட அனுமதி நிரந்தரமாக மறுக்கப்பட்டுள்ளது. அமைப்புகளில் இருந்து இயக்கவும்.';

  @override
  String get chooseLanguage => 'மொழியை தேர்வு செய்யவும்';

  @override
  String get cancel => 'ரத்து';

  @override
  String get save => 'சேமிக்கவும்';

  @override
  String get contactUs => 'தொடர்பு கொள்ளவும்';

  @override
  String get needHelp => 'உதவி வேண்டுமா?';

  @override
  String get contactSubtitle =>
      'எங்களுக்கு செய்தி அனுப்புங்கள்; எங்கள் குழு பதில் அளிக்கும்.';

  @override
  String supportEmailLine(Object email) {
    return 'ஆதரவு மின்னஞ்சல்: $email';
  }

  @override
  String get typicalResponseLine => 'சாதாரண பதில்: 24 மணிநேரத்திற்குள்';

  @override
  String get language => 'மொழி';

  @override
  String languageSetTo(Object language) {
    return 'மொழி அமைக்கப்பட்டது: $language';
  }

  @override
  String get fullName => 'முழு பெயர்';

  @override
  String get yourName => 'உங்கள் பெயர்';

  @override
  String get email => 'மின்னஞ்சல்';

  @override
  String get emailHint => 'name@example.com';

  @override
  String get phoneOptional => 'தொலைபேசி (விருப்பம்)';

  @override
  String get yourMobileNumber => 'உங்கள் மொபைல் எண்';

  @override
  String get subject => 'தலைப்பு';

  @override
  String get subjectHint => 'இது எதை பற்றி?';

  @override
  String get message => 'செய்தி';

  @override
  String get messageHint => 'உங்கள் பிரச்சனை அல்லது கேள்வியை விவரிக்கவும்';

  @override
  String get send => 'அனுப்பவும்';

  @override
  String get sentSuccess => 'அனுப்பப்பட்டது! விரைவில் பதில் அளிப்போம்.';

  @override
  String get required => 'அவசியம்';

  @override
  String get enterValidEmail => 'சரியான மின்னஞ்சலை உள்ளிடவும்';

  @override
  String get writeMoreDetail => 'தயவுசெய்து மேலும் விவரமாக எழுதுங்கள்';

  @override
  String get couldNotOpenEmailApp => 'மின்னஞ்சல் ஆப்பை திறக்க முடியவில்லை.';

  @override
  String get couldNotSendTryLater =>
      'அனுப்ப முடியவில்லை. பிறகு முயற்சிக்கவும்.';

  @override
  String get tipNoShareOtp =>
      'குறிப்பு: இங்கே கடவுச்சொற்கள் அல்லது OTP பகிர வேண்டாம்.';

  @override
  String get loginLanguageLabel => 'English / தமிழ்';

  @override
  String get loginHeroSubtitle => 'உங்கள் ஆரோக்கிய துணை';

  @override
  String get loginMobileNumberLabel => 'மொபைல் எண்';

  @override
  String get loginMobileHint => '00000 00000';

  @override
  String get loginEmailLabel => 'மின்னஞ்சல் முகவரி';

  @override
  String get loginPasswordLabel => 'கடவுச்சொல்';

  @override
  String get loginPasswordHint => 'கடவுச்சொல்லை உள்ளிடவும்';

  @override
  String get loginPleaseWait => 'தயவு செய்து காத்திருக்கவும்...';

  @override
  String get loginSendOtp => 'OTP அனுப்பு';

  @override
  String get loginContinue => 'தொடரவும்';

  @override
  String get loginSendingOtp => 'OTP அனுப்புகிறது...';

  @override
  String get loginOr => 'அல்லது';

  @override
  String get loginContinueAsGuest => 'விருந்தினராக தொடரவும்';

  @override
  String get loginAgreementText =>
      'உள்நுழைவதன் மூலம், நீங்கள் MediMitra இன்\nசேவை விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை ஒப்புக்கொள்கிறீர்கள்.';

  @override
  String get loginUnableContinueGuest => 'விருந்தினராக தொடர முடியவில்லை.';

  @override
  String get loginEnterMobileNumber => 'மொபைல் எண்ணை உள்ளிடவும்.';

  @override
  String get loginEnterValidMobileNumber =>
      'சரியான 10 இலக்க மொபைல் எண்ணை உள்ளிடவும்.';

  @override
  String get loginOtpSent => 'OTP அனுப்பப்பட்டது.';

  @override
  String get loginFailedSendOtp => 'OTP அனுப்ப முடியவில்லை.';

  @override
  String get loginEnterValidEmail => 'சரியான மின்னஞ்சலை உள்ளிடவும்.';

  @override
  String get loginPasswordMinChars =>
      'கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்.';

  @override
  String get loginEmailPasswordDisabled =>
      'Firebase Console இல் Email/Password உள்நுழைவு முடக்கப்பட்டுள்ளது.';

  @override
  String get loginAccountExistsTryLogin =>
      'கணக்கு ஏற்கனவே உள்ளது. உள்நுழைய முயற்சிக்கவும்.';

  @override
  String get loginWeakPassword =>
      'கடவுச்சொல் பலவீனமாக உள்ளது (குறைந்தது 6 எழுத்துகள்).';

  @override
  String get loginIncorrectPassword => 'தவறான கடவுச்சொல்.';

  @override
  String get loginInvalidEmail => 'தவறான மின்னஞ்சல்.';

  @override
  String get loginLoginFailed => 'உள்நுழைவு தோல்வி.';

  @override
  String get otpVerifyNumber => 'எண்ணை சரிபார்க்கவும்';

  @override
  String get otpSentTo => 'நாங்கள் 6 இலக்க குறியீட்டை அனுப்பியுள்ளோம்';

  @override
  String get otpHaventReceived => 'குறியீடு வரவில்லையா?';

  @override
  String get otpResendCode => 'குறியீட்டை மீண்டும் அனுப்பு';

  @override
  String get otpVerifyProceed => 'சரிபார்த்து தொடரவும்';

  @override
  String get otpVerifying => 'சரிபார்க்கிறது...';

  @override
  String get otpEnter6Digit => '6 இலக்க OTP ஐ உள்ளிடவும்.';

  @override
  String get otpInvalid => 'தவறான OTP.';

  @override
  String get otpVerificationFailed => 'OTP சரிபார்ப்பு தோல்வி.';

  @override
  String get otpFailedResend => 'குறியீட்டை மீண்டும் அனுப்ப முடியவில்லை.';

  @override
  String get otpCodeResent => 'குறியீடு மீண்டும் அனுப்பப்பட்டது.';

  @override
  String get otpSafetyFirst => 'பாதுகாப்பு முதலில்';

  @override
  String get otpSafetyNote =>
      'MediMitra இன் குறியாக்கத்துடன் உங்கள் சுகாதார பதிவுகளுடன் பாதுகாப்பாக இணைக.';

  @override
  String get communityOutbreakAlerts => 'சமூக பரவல் எச்சரிக்கைகள்';

  @override
  String get outbreakPrivacyNote =>
      'தனியுரிமை முதலில்: PIN3 மற்றும் நாளுக்கு ஏற்ப தொகுக்கப்பட்ட அறிகுறி எண்ணிக்கைகள் மட்டும். பெயர்கள், சேட் உரை, GPS அல்லது துல்லிய நேரமுத்திரைகள் இல்லை.';

  @override
  String get regionNotSet => 'பகுதி: அமைக்கப்படவில்லை';

  @override
  String regionPin3Line(Object region) {
    return 'பகுதி: $region (PIN3)';
  }

  @override
  String get set => 'அமை';

  @override
  String get setAreaPin3Title => 'உங்கள் பகுதியை அமைக்கவும் (PIN3)';

  @override
  String get setAreaPin3Body =>
      'உங்கள் PIN குறியீட்டை உள்ளிடவும். முதல் 3 இலக்கங்களை மட்டும் (பெரிய பகுதி) சேமிப்போம்.';

  @override
  String get pinExampleHint => 'எ.கா. 411001';

  @override
  String get enterFirst3DigitsPin =>
      'உங்கள் PIN இன் குறைந்தது முதல் 3 இலக்கங்களை உள்ளிடவும்.';

  @override
  String get unableToSaveRegion => 'பகுதியை சேமிக்க முடியவில்லை.';

  @override
  String get setPin3ToSeeAlerts =>
      'உங்கள் பகுதியின் பரவல் எச்சரிக்கைகளை பார்க்க PIN3 ஐ அமைக்கவும்.';

  @override
  String get noAlertsToday => 'இன்று உங்கள் பகுதிக்கு எச்சரிக்கைகள் இல்லை.';

  @override
  String get prevention => 'தடுப்பு';

  @override
  String get outbreakLevelHighRisk => 'உயர் ஆபத்து';

  @override
  String get outbreakLevelWarning => 'எச்சரிக்கை';

  @override
  String get outbreakLevelWatch => 'கவனிப்பு';

  @override
  String get outbreakLevelNone => 'இல்லை';

  @override
  String get back => 'பின்';

  @override
  String get next => 'அடுத்து';

  @override
  String get couldNotSaveConsent =>
      'உங்கள் சம்மதத்தை சேமிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.';

  @override
  String get termsSigningTitle => 'சேவை விதிமுறைகள்';

  @override
  String get termsSigningIntro =>
      'அறிகுறி மதிப்பீட்டை பயன்படுத்துவதற்கு முன், சேவை விதிமுறைகள் மற்றும் தனியுரிமைக் கொள்கையை ஏற்றுக்கொள்ளவும். தயவுசெய்து கவனிக்கவும்:';

  @override
  String get termsBulletNotDiagnosisTitle => 'இந்த முடிவு ஒரு நோயறிதல் அல்ல.';

  @override
  String get termsBulletNotDiagnosisBody =>
      ' இது தகவலுக்காக மட்டும்; தகுதியான மருத்துவ கருத்து அல்ல.';

  @override
  String get termsBulletNoEmergencyTitle =>
      'அவசரநிலையில் இதைப் பயன்படுத்த வேண்டாம்.';

  @override
  String get termsBulletNoEmergencyBody =>
      ' சுகாதார அவசரநிலையில் உடனே உங்கள் உள்ளூர் அவசர எண் அழைக்கவும்.';

  @override
  String get termsBulletDataSafeTitle => 'உங்கள் தரவு பாதுகாப்பாக உள்ளது.';

  @override
  String get termsBulletDataSafeBody =>
      ' நீங்கள் அளிக்கும் தகவல் பகிரப்படாது அல்லது உங்களை அடையாளம் காண பயன்படுத்தப்படாது.';

  @override
  String get termsConsentTermsPrefix => 'நான் ';

  @override
  String get termsConsentTermsLink => 'சேவை விதிமுறைகள்';

  @override
  String get termsConsentTermsSuffix => ' வாசித்து ஏற்றுக்கொள்கிறேன்.';

  @override
  String get termsConsentPrivacyPrefix =>
      'எனது சுகாதார தகவல் நேர்காணலுக்காக பயன்படுத்தப்படுவதற்கு நான் சம்மதிக்கிறேன். மேலும் தகவல் ';

  @override
  String get termsConsentPrivacyLink => 'தனியுரிமைக் கொள்கை';

  @override
  String get termsConsentPrivacySuffix => ' இல் உள்ளது.';

  @override
  String get quickQuestions => 'விரைவு கேள்விகள்';

  @override
  String get typeAQuestionHint => 'ஒரு கேள்வியை உள்ளிடுங்கள்…';

  @override
  String get talkToMaya => 'மாயாவுடன் பேசுங்கள்';

  @override
  String get womensHealthHubTitle => 'பெண்கள் ஆரோக்கிய மையம்';

  @override
  String get womensHealthHubWelcome =>
      'உங்கள் ஆரோக்கிய பயணத்திற்கு வரவேற்கிறோம்';

  @override
  String get womensHealthHubSubtitle =>
      'வளங்களை ஆராயவும் தனிப்பயன் பராமரிப்பு பெறவும் ஒரு வகையைத் தேர்வு செய்யவும்.';

  @override
  String get menstrualHealth => 'மாதவிடாய் ஆரோக்கியம்';

  @override
  String get pregnancyAndMaternal => 'கர்ப்பம் மற்றும் தாய்மை';

  @override
  String get breastHealth => 'மார்பக ஆரோக்கியம்';

  @override
  String get comingSoon => 'விரைவில் வருகிறது';

  @override
  String get womensHealthHubTagline => 'MEDIMITRA WELLNESS';

  @override
  String get womensHealthCategoryMenstrualDescription =>
      'மாதவிடாய் சுழற்சியை அறிந்து,\nசுகாதாரம் பற்றி தெரிந்து,\nஎளிதாக மேலாண்மை செய்யுங்கள்.';

  @override
  String get womensHealthCategoryPregnancyDescription =>
      'ஆரோக்கியமான கர்ப்பத்திற்கான நிபுணர் வழிகாட்டுதல்,\nஉணவுச் சத்து குறிப்புகள், மற்றும்\nபாதுகாப்பான பிரசவ உதவி.';

  @override
  String get womensHealthCategoryBreastDescription =>
      'எளிய சுய பரிசோதனை வழிகாட்டி\nமற்றும் விழிப்புணர்வு குறிப்புகள்\nமுன்கூட்டிய கண்டறிதல்/பராமரிப்பிற்கு.';

  @override
  String get recommended => 'பரிந்துரைக்கப்பட்டது';

  @override
  String get explore => 'ஆராயுங்கள்';

  @override
  String get menstrualScreenTitle => 'மாதவிடாய் ஆரோக்கியம்';

  @override
  String get menstrualWhatIsMenstruationTitle => 'மாதவிடாய் என்ன?';

  @override
  String get menstrualWhatIsMenstruationBody =>
      'மாதவிடாய் என்பது உடல் கருப்பையின் உள் அடர்த்தியை வெளியேற்றும் ஒரு இயற்கையான மாதாந்திர செயல்முறை. இது ஆரோக்கியமான இனப்பெருக்க அமைப்பின் ஒரு அறிகுறி மற்றும் வளர்ப்பின் இயல்பான பகுதி.';

  @override
  String get menstrualQuote => 'புதுப்பிப்பு மற்றும் வாழ்க்கையின் சுழற்சி';

  @override
  String get menstrualWhatIsNormalTitle => 'எது சாதாரணம்?';

  @override
  String get menstrualNormalItem1 =>
      'சுழற்சி 21 முதல் 35 நாட்கள் வரை நீடிக்கும்';

  @override
  String get menstrualNormalItem2 =>
      'இரத்தப்போக்கு 3 முதல் 7 நாட்கள் வரை நீடிக்கும்';

  @override
  String get menstrualNormalItem3 => 'லேசான முதல் நடுத்தர வலி/அசௌகரியம்';

  @override
  String get menstrualWarningSignsTitle => 'எச்சரிக்கை அறிகுறிகள்';

  @override
  String get menstrualWarningItem1 =>
      'அதிக இரத்தப்போக்கால் ஒவ்வொரு 1–2 மணி நேரத்திற்கும் பேட் மாற்ற வேண்டுதல்';

  @override
  String get menstrualWarningItem2 =>
      'தினசரி செயல்களைத் தடுக்கும் அளவிற்கு கடுமையான வலி';

  @override
  String get menstrualWarningItem3 =>
      'சுழற்சி தொடர்ந்து 21 நாட்களுக்கும் குறைவு அல்லது 38 நாட்களுக்கும் அதிகம்';

  @override
  String get menstrualHygieneTipsTitle => 'சுகாதார குறிப்புகள்';

  @override
  String get menstrualTipChangeRegularlyTitle => 'முறையாக மாற்றவும்';

  @override
  String get menstrualTipChangeRegularlySubtitle =>
      'ஒவ்வொரு 4–6 மணி நேரத்திற்கும் பேட் மாற்றவும்';

  @override
  String get menstrualTipCleanHandsTitle => 'கைகளை சுத்தமாக வைத்துக் கொள்ளவும்';

  @override
  String get menstrualTipCleanHandsSubtitle =>
      'முன்பும் பின்னும் கைகளை கழுவவும்';

  @override
  String get menstrualTipStayDryTitle => 'உலர்வாக வைத்துக் கொள்ளவும்';

  @override
  String get menstrualTipStayDrySubtitle =>
      'பாலுறுப்பு பகுதியை சுத்தமாகவும் உலர்வாகவும் வைத்துக் கொள்ளவும்';

  @override
  String get menstrualMythsFactsTitle => 'நம்பிக்கைகள் & உண்மைகள்';

  @override
  String get menstrualMyth1 =>
      'நம்பிக்கை: \"மாதவிடாயில் உடற்பயிற்சி செய்யக் கூடாது.\"';

  @override
  String get menstrualFact1 =>
      'உண்மை: லேசான உடற்பயிற்சி வலியை குறைக்கவும் மனநிலையை மேம்படுத்தவும் உதவும்.';

  @override
  String get menstrualMyth2 =>
      'நம்பிக்கை: \"மாதவிடாய் இரத்தம் \'அழுக்கு\' இரத்தம்.\"';

  @override
  String get menstrualFact2 =>
      'உண்மை: அது கருப்பையின் உள் அடர்த்தியிலிருந்து வரும் இயல்பான இரத்தம் மற்றும் திசு.';

  @override
  String get chatHeaderTitle => 'ஆரோக்கிய உதவியாளர்';

  @override
  String get chatHeaderStatusOnline => 'ஆன்லைன்';

  @override
  String get chatToday => 'இன்று';

  @override
  String get chatQuickChipCheckFever => '🌡️ காய்ச்சல் சோதனை';

  @override
  String get chatQuickPromptCheckFever =>
      'எனக்கு காய்ச்சலைச் சோதிக்க வேண்டும்.';

  @override
  String get chatQuickChipWomensHealth => '🤰 பெண்கள் ஆரோக்கியம்';

  @override
  String get chatQuickPromptWomensHealth =>
      'எனக்கு பெண்கள் ஆரோக்கியம் குறித்து ஒரு கேள்வி உள்ளது.';

  @override
  String get chatQuickChipFirstAid => '🩹 முதலுதவி';

  @override
  String get chatQuickPromptFirstAid => 'எனக்கு முதலுதவி ஆலோசனை வேண்டும்.';

  @override
  String get chatQuickChipChildCare => '👶 குழந்தை பராமரிப்பு';

  @override
  String get chatQuickPromptChildCare =>
      'எனக்கு குழந்தை பராமரிப்பு வழிகாட்டுதல் வேண்டும்.';

  @override
  String get chatInputHintAskMeAnything => 'எதையும் கேளுங்கள்...';

  @override
  String get profileSaved => 'சுயவிவரம் சேமிக்கப்பட்டது';

  @override
  String get saving => 'சேமிக்கப்படுகிறது...';

  @override
  String get saveChanges => 'மாற்றங்களை சேமிக்கவும்';

  @override
  String get profileTopBarTitle => 'Profile Settings';

  @override
  String get profileHeaderSubtitle => 'User Profile';

  @override
  String get profileSectionFullName => 'FULL NAME';

  @override
  String get profileHintFullName => 'e.g. Rahul Sharma';

  @override
  String get profileSectionAge => 'AGE';

  @override
  String get profileHintAge => 'Enter your age';

  @override
  String get profileSectionGender => 'GENDER';

  @override
  String get profileGenderMale => 'Male';

  @override
  String get profileGenderFemale => 'Female';

  @override
  String get profileGenderOther => 'Other';

  @override
  String get profileChronicConditions => 'CHRONIC CONDITIONS';

  @override
  String get profileConditionsBadge => 'BILINGUAL';

  @override
  String get conditionDiabetesTitle => 'Diabetes';

  @override
  String get conditionDiabetesSubtitle => 'Diabetes (Sugar)';

  @override
  String get conditionBpHeartTitle => 'BP & Heart';

  @override
  String get conditionBpHeartSubtitle => 'Blood pressure / Heart';

  @override
  String get conditionAsthmaTitle => 'Asthma';

  @override
  String get conditionAsthmaSubtitle => 'Breathing';

  @override
  String get conditionThyroidTitle => 'Thyroid';

  @override
  String get conditionThyroidSubtitle => 'Thyroid';

  @override
  String get conditionTbTitle => 'TB';

  @override
  String get conditionTbSubtitle => 'Tuberculosis';

  @override
  String get conditionNoneTitle => 'None';

  @override
  String get conditionNoneSubtitle => 'No conditions';

  @override
  String get helpFaqBotGreeting =>
      'Hi! I\'m MediMitra Help. Ask me anything about symptom checking, voice input, outbreak alerts, clinics, login, or privacy.\n\nNote: This is not medical advice. If you have a medical emergency, contact local emergency services.';

  @override
  String get helpFaqSuggestionCheckSymptoms => 'How do I check symptoms?';

  @override
  String get helpFaqSuggestionVoiceSymptoms => 'How do voice symptoms work?';

  @override
  String get helpFaqSuggestionOutbreakAlert => 'What is outbreak alert?';

  @override
  String get helpFaqSuggestionNearbyClinics => 'How to find nearby clinics?';

  @override
  String get helpFaqSuggestionOtpLogin => 'How does OTP login work?';

  @override
  String get helpFaqSuggestionDataSafe => 'Is my data safe?';

  @override
  String get helpFaqSuggestionGuestMode => 'Can I use the app without login?';

  @override
  String get helpFaqSuggestionChangeLanguage => 'How to change language?';

  @override
  String get helpFaqSuggestionDarkMode => 'How to enable dark mode?';

  @override
  String get helpFaqReplySymptomChecking =>
      'To check symptoms:\n1) Open Chat / Symptom Checker\n2) Type your symptoms (or use voice)\n3) Answer follow-up questions\n\nMediMitra will show likely causes and next steps. For severe symptoms (chest pain, trouble breathing, fainting), seek urgent care.';

  @override
  String get helpFaqReplyVoiceSymptoms =>
      'Voice symptoms: tap the microphone, speak your symptoms clearly, and the app converts it to text for analysis.\n\nTips: speak one symptom at a time, use simple words (\"fever\", \"cough\"), and allow microphone permission when asked.';

  @override
  String get helpFaqReplyOutbreakAlert =>
      'Outbreak alert helps you see if certain symptoms are trending in your area. It\'s based on anonymized, aggregated symptom patterns and is meant for awareness (not diagnosis).\n\nYou can view outbreak insights from the Outbreak section.';

  @override
  String get helpFaqReplyNearbyClinics =>
      'Nearby clinics: open the Clinic Locator to see clinics around you.\n\nMake sure Location permission is enabled. If you prefer, you can also search by area/city (if available on your build).';

  @override
  String get helpFaqReplyOtpLogin =>
      'OTP login: enter your 10-digit mobile number and we send a verification OTP. Enter the 6-digit OTP to proceed.\n\nIf you don\'t receive it, wait for the resend timer and try again. Also confirm network/SMS permissions.';

  @override
  String get helpFaqReplyGuestMode =>
      'Guest mode lets you explore the app without signing in. Some features that save to your profile (like personalized settings) may be limited until you log in.';

  @override
  String get helpFaqReplyPrivacy =>
      'Your profile data (like name/age/gender/conditions) is stored securely for your account to personalize your experience. We do not want you to share sensitive info in chat.\n\nFor exact details, check Privacy Policy (in the app).';

  @override
  String get helpFaqReplyChangeLanguage =>
      'You can change language from Profile → Language.';

  @override
  String get helpFaqReplyDarkMode =>
      'Dark mode: go to Profile → Dark Mode and toggle it on/off. Your choice is saved and works across the whole app.';

  @override
  String get helpFaqReplyContactSupport =>
      'Contact support: open Contact Us and send your message. Include screenshots and steps if possible.';

  @override
  String get helpFaqReplyFallback =>
      'I can help with: symptom checking, voice input, outbreak alerts, clinic locator, OTP login, privacy, language, and dark mode.\n\nTry one of these: \"How do I check symptoms?\", \"How to find nearby clinics?\", \"Is my data safe?\"';
}
