// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Kannada (`kn`).
class AppLocalizationsKn extends AppLocalizations {
  AppLocalizationsKn([String locale = 'kn']) : super(locale);

  @override
  String get appTitle => 'ಮೆಡಿಮಿತ್ರಾ';

  @override
  String get close => 'ಮುಚ್ಚಿ';

  @override
  String get loginTagline => 'ನಿಮ್ಮ ಹಾಗೂ ನಿಮ್ಮ ಕುಟುಂಬಕ್ಕಾಗಿ ಸರಳ ಆರೋಗ್ಯ ಸೇವೆ';

  @override
  String get smsLogin => 'ಎಸ್‌ಎಂಎಸ್ ಲಾಗಿನ್';

  @override
  String get emailLogin => 'ಇಮೇಲ್ ಲಾಗಿನ್';

  @override
  String get homeHello => 'ನಮಸ್ಕಾರ,';

  @override
  String get homeThere => 'ಅಲ್ಲಿ';

  @override
  String get homeChatCta => 'ನಮ್ಮ AI ಆರೋಗ್ಯ ಚಾಟ್ ಸಹಾಯಕನ್ನು ಅನ್ವೇಷಿಸಿ';

  @override
  String get homeOurFeatures => 'ನಮ್ಮ ವೈಶಿಷ್ಟ್ಯಗಳು';

  @override
  String get homeHighlights => 'ಮುಖ್ಯಾಂಶಗಳು';

  @override
  String get homeDisclaimerTitle => 'ಅಸ್ವೀಕರಣ';

  @override
  String get homeDisclaimerBody =>
      'MediMitra ಮಾಹಿತಿ ಉದ್ದೇಶಗಳಿಗಾಗಿ ಮಾತ್ರ ಮತ್ತು ವೈದ್ಯಕೀಯ ಸಲಹೆಯಲ್ಲ. ಇದು ವೈದ್ಯರನ್ನು ಬದಲಿಸದು.\nಗಂಭೀರ ಲಕ್ಷಣಗಳು ಅಥವಾ ತುರ್ತು ಪರಿಸ್ಥಿತಿಯಲ್ಲಿ, ದಯವಿಟ್ಟು ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆಗೆ ಭೇಟಿ ನೀಡಿ ಅಥವಾ ತಕ್ಷಣ ತುರ್ತು ಸೇವೆಗಳನ್ನು ಸಂಪರ್ಕಿಸಿ.';

  @override
  String get featureSymptomChecker => 'ಲಕ್ಷಣ ಪರಿಶೀಲಕ';

  @override
  String get featureWomensHealth => 'ಮಹಿಳಾ ಆರೋಗ್ಯ ಜಾಗೃತಿ';

  @override
  String get featureInsurance => 'ವಿಮೆ';

  @override
  String get featureAiHealthSummary => 'AI ಆರೋಗ್ಯ ಸಾರಾಂಶ';

  @override
  String get featureReminders => 'ರಿಮೈಂಡರ್‌ಗಳು';

  @override
  String get featureLocateClinics => 'ನಿಮ್ಮ ಬಳಿ ಕ್ಲಿನಿಕ್‌ಗಳನ್ನು ಹುಡುಕಿ';

  @override
  String get promoAiSymptomCheckTitle => 'AI ಲಕ್ಷಣ ಪರಿಶೀಲನೆ';

  @override
  String get promoAiSymptomCheckSubtitle =>
      'ಲಕ್ಷಣಗಳನ್ನು ವಿವರಿಸಿ, ಸೆಕೆಂಡುಗಳಲ್ಲಿ ಮಾರ್ಗದರ್ಶನ ಪಡೆಯಿರಿ.';

  @override
  String get promoVoiceWaveformTitle => 'ಧ್ವನಿ + ವೇವ್‌ಫಾರ್ಮ್';

  @override
  String get promoVoiceWaveformSubtitle =>
      'ಧ್ವನಿ ಇನ್‌ಪುಟ್ ಬೆಂಬಲದೊಂದಿಗೆ ಹ್ಯಾಂಡ್ಸ್-ಫ್ರೀ ಚಾಟ್.';

  @override
  String get promoProfilePersonalizationTitle => 'ಪ್ರೊಫೈಲ್ ವೈಯಕ್ತೀಕರಣ';

  @override
  String get promoProfilePersonalizationSubtitle =>
      'ಉತ್ತಮ ಸಹಾಯಕ್ಕಾಗಿ ವಯಸ್ಸು, ಲಿಂಗ ಮತ್ತು ಸ್ಥಿತಿಗಳನ್ನು ಉಳಿಸಿ.';

  @override
  String get promoNearbyClinicsTitle => 'ಹತ್ತಿರದ ಕ್ಲಿನಿಕ್‌ಗಳು';

  @override
  String get promoNearbyClinicsSubtitle =>
      'ನಿಮ್ಮ ಸ್ಥಳದ ಬಳಿ ಆರೋಗ್ಯ ಸೇವೆಗಳನ್ನು ಹುಡುಕಿ.';

  @override
  String get settings => 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು';

  @override
  String get supportAndInformation => 'ಬೆಂಬಲ & ಮಾಹಿತಿ';

  @override
  String get notifications => 'ಅಧಿಸೂಚನೆಗಳು';

  @override
  String get manageYourNotifications => 'ನಿಮ್ಮ ಅಧಿಸೂಚನೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ';

  @override
  String get notificationsEnabled => 'ಅಧಿಸೂಚನೆಗಳು ಸಕ್ರಿಯವಾಗಿವೆ';

  @override
  String get notificationsDisabled => 'ಅಧಿಸೂಚನೆಗಳು ನಿಷ್ಕ್ರಿಯವಾಗಿವೆ';

  @override
  String get couldNotUpdateNotifications => 'ಅಧಿಸೂಚನೆಗಳನ್ನು ನವೀಕರಿಸಲಾಗಲಿಲ್ಲ';

  @override
  String get darkMode => 'ಡಾರ್ಕ್ ಮೋಡ್';

  @override
  String get toggleDarkTheme => 'ಡಾರ್ಕ್ ಥೀಮ್ ಆನ್/ಆಫ್ ಮಾಡಿ';

  @override
  String get helpAndFaq => 'ಸಹಾಯ & FAQ';

  @override
  String get getHelpAndAnswers => 'ಸಹಾಯ ಮತ್ತು ಉತ್ತರಗಳನ್ನು ಪಡೆಯಿರಿ';

  @override
  String get getInTouchWithSupport => 'ಬೆಂಬಲ ತಂಡವನ್ನು ಸಂಪರ್ಕಿಸಿ';

  @override
  String get aboutMediMitra => 'MediMitra ಬಗ್ಗೆ';

  @override
  String versionLine(Object version) {
    return 'ಆವೃತ್ತಿ $version';
  }

  @override
  String get privacyPolicy => 'ಗೌಪ್ಯತಾ ನೀತಿ';

  @override
  String get howWeProtectYourData => 'ನಾವು ನಿಮ್ಮ ಡೇಟಾವನ್ನು ಹೇಗೆ ರಕ್ಷಿಸುತ್ತೇವೆ';

  @override
  String get termsAndConditions => 'ನಿಯಮಗಳು & ಷರತ್ತುಗಳು';

  @override
  String get termsConditionsBody =>
      'Terms & Conditions\n\nBy downloading and using this application, you agree to comply with and be bound by these Terms and Conditions. If you do not agree with any part of these terms, you should discontinue using the app.\n\nThis application is designed to provide health-related information and decision-support guidance only. It is not a medical diagnostic tool and does not replace consultation with a qualified doctor or healthcare professional. All information provided by the app is for educational and support purposes, and users must always seek professional medical advice for diagnosis, treatment, or emergencies.\n\nUsers are responsible for providing accurate and honest information while using the app. The guidance generated by the system depends on the inputs provided by the user, and incorrect or incomplete information may lead to inaccurate results. The app should not be used as the sole basis for making medical decisions.\n\nThis application is not intended for emergency situations. In case of severe symptoms such as chest pain, difficulty breathing, loss of consciousness, or heavy bleeding, users must immediately contact local emergency services or visit the nearest hospital.\n\nTo the maximum extent permitted by law, the developers shall not be held liable for any direct or indirect damages arising from the use of this application. Use of the app is entirely at the user’s own risk, and no guarantee is made regarding the accuracy, completeness, or reliability of the information provided.\n\nUse of this application is also governed by our Privacy Policy. By continuing to use the app, you confirm that you have read, understood, and agreed to both the Privacy Policy and these Terms and Conditions.\n\nWe reserve the right to modify or update these Terms and Conditions at any time. Any changes will be displayed within the app, and continued use of the app after such changes indicates acceptance of the updated terms.';

  @override
  String get legalAgreement => 'ಕಾನೂನು ಒಪ್ಪಂದ';

  @override
  String get deleteData => 'ಡೇಟಾ ಅಳಿಸಿ';

  @override
  String get deleteChatsAndSavedSettings =>
      'ಚಾಟ್‌ಗಳು & ಉಳಿಸಿದ ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಅಳಿಸಿ';

  @override
  String get logOut => 'ಲಾಗ್ ಔಟ್';

  @override
  String get logoutQuestion => 'ಲಾಗ್ ಔಟ್ ಮಾಡಬೇಕೇ?';

  @override
  String get logoutReturnToLogin =>
      'ನೀವು ಲಾಗ್ ಔಟ್ ಆಗಿ ಲಾಗಿನ್ ಪರದೆಗೆ ಮರಳುತ್ತೀರಿ.';

  @override
  String get chooseAnAction => 'ಕ್ರಿಯೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ';

  @override
  String get deleteAccount => 'ಖಾತೆ ಅಳಿಸಿ';

  @override
  String get permanentlyDeleteAccount => 'ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಶಾಶ್ವತವಾಗಿ ಅಳಿಸಿ';

  @override
  String get deleteLocalData => 'ಸ್ಥಳೀಯ ಡೇಟಾ ಅಳಿಸಿ';

  @override
  String get deleteLocalDataOnDevice =>
      'ಈ ಸಾಧನದಲ್ಲಿನ ಚಾಟ್‌ಗಳು & ಉಳಿಸಿದ ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಅಳಿಸಿ';

  @override
  String get clearLocalDataQuestion => 'ಸ್ಥಳೀಯ ಡೇಟಾವನ್ನು ಅಳಿಸಲೇವಾ?';

  @override
  String get clearLocalDataBody =>
      'ಇದು ಈ ಸಾಧನದಲ್ಲಿನ ಸ್ಥಳೀಯವಾಗಿ ಸಂಗ್ರಹಿಸಿದ ಆಪ್ ಡೇಟಾವನ್ನು (ಉಳಿಸಿದ ಸೆಟ್ಟಿಂಗ್‌ಗಳು, ಕ್ಯಾಶ್ ಮಾಡಿದ ಪ್ರೊಫೈಲ್ ಕ್ಷೇತ್ರಗಳು, ಮತ್ತು ಮೆಮೊರಿಯಲ್ಲಿನ ಚಾಟ್ ಇತಿಹಾಸ) ಅಳಿಸುತ್ತದೆ.\n\nಎಲ್ಲಾ ಬದಲಾವಣೆಗಳು ಅನ್ವಯವಾಗಲು ಆಪ್ ಮರುಪ್ರಾರಂಭಿಸಬೇಕಾಗಬಹುದು.';

  @override
  String get clear => 'ಅಳಿಸಿ';

  @override
  String get localDataCleared => 'ಸ್ಥಳೀಯ ಡೇಟಾ ಅಳಿಸಲಾಗಿದೆ';

  @override
  String get couldNotClearLocalData => 'ಸ್ಥಳೀಯ ಡೇಟಾವನ್ನು ಅಳಿಸಲಾಗಲಿಲ್ಲ';

  @override
  String get accountDeletionNotAvailable =>
      'ಈ ಪ್ಲಾಟ್‌ಫಾರ್ಮ್‌ನಲ್ಲಿ ಖಾತೆ ಅಳಿಸುವಿಕೆ ಲಭ್ಯವಿಲ್ಲ';

  @override
  String get noSignedInAccountFound => 'ಲಾಗಿನ್ ಆಗಿರುವ ಖಾತೆ ಕಂಡುಬಂದಿಲ್ಲ';

  @override
  String get deleteAccountQuestion => 'ಖಾತೆಯನ್ನು ಅಳಿಸಲೇವಾ?';

  @override
  String get deleteAccountBody =>
      'ಇದು ನಿಮ್ಮ ಖಾತೆಯನ್ನು ಶಾಶ್ವತವಾಗಿ ಅಳಿಸುತ್ತದೆ. ನೀವು ಈ ಸಾಧನದಿಂದ ಲಾಗ್ ಔಟ್ ಆಗುತ್ತೀರಿ.';

  @override
  String get deletingAccount => 'ಖಾತೆ ಅಳಿಸಲಾಗುತ್ತಿದೆ...';

  @override
  String get pleaseLoginAgainThenDelete =>
      'ದಯವಿಟ್ಟು ಮತ್ತೆ ಲಾಗಿನ್ ಮಾಡಿ, ನಂತರ ಖಾತೆಯನ್ನು ಅಳಿಸಿ';

  @override
  String get couldNotDeleteAccount => 'ಖಾತೆಯನ್ನು ಅಳಿಸಲಾಗಲಿಲ್ಲ';

  @override
  String get networkSlowTryAgain =>
      'ನೆಟ್ವರ್ಕ್ ನಿಧಾನವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.';

  @override
  String get defaultUser => 'ಬಳಕೆದಾರ';

  @override
  String userIdLine(Object id) {
    return 'ಬಳಕೆದಾರ ID: $id';
  }

  @override
  String get clinicsNearYou => 'Clinics Near You';

  @override
  String get refresh => 'Refresh';

  @override
  String get recenter => 'Re-center';

  @override
  String resultsCount(Object count) {
    return 'Results ($count)';
  }

  @override
  String get nearbyClinics => 'Nearby clinics';

  @override
  String get call => 'Call';

  @override
  String get navigate => 'Navigate';

  @override
  String get unableToOpenDialer => 'Unable to open dialer';

  @override
  String get unableToOpenMaps => 'Unable to open maps';

  @override
  String get radius => 'Radius';

  @override
  String get tryAgain => 'Try again';

  @override
  String get openLocationSettings => 'Open location settings';

  @override
  String get locationServicesDisabled =>
      'Location services are disabled. Please enable GPS.';

  @override
  String get locationPermissionDenied => 'Location permission denied.';

  @override
  String get locationPermissionDeniedForever =>
      'Location permission permanently denied. Enable it from Settings.';

  @override
  String get chooseLanguage => 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ';

  @override
  String get cancel => 'ರದ್ದುಮಾಡಿ';

  @override
  String get save => 'ಉಳಿಸಿ';

  @override
  String get contactUs => 'ಸಂಪರ್ಕಿಸಿ';

  @override
  String get needHelp => 'ಸಹಾಯ ಬೇಕೆ?';

  @override
  String get contactSubtitle => 'ನಮಗೆ ಸಂದೇಶ ಕಳುಹಿಸಿ; ನಮ್ಮ ತಂಡ ಉತ್ತರಿಸುತ್ತದೆ.';

  @override
  String supportEmailLine(Object email) {
    return 'ಬೆಂಬಲ ಇಮೇಲ್: $email';
  }

  @override
  String get typicalResponseLine => 'ಸಾಮಾನ್ಯ ಪ್ರತಿಕ್ರಿಯೆ: 24 ಗಂಟೆಗಳೊಳಗೆ';

  @override
  String get language => 'Language';

  @override
  String languageSetTo(Object language) {
    return 'Language set to $language';
  }

  @override
  String get fullName => 'ಪೂರ್ಣ ಹೆಸರು';

  @override
  String get yourName => 'ನಿಮ್ಮ ಹೆಸರು';

  @override
  String get email => 'ಇಮೇಲ್';

  @override
  String get emailHint => 'name@example.com';

  @override
  String get phoneOptional => 'ಫೋನ್ (ಐಚ್ಛಿಕ)';

  @override
  String get yourMobileNumber => 'ನಿಮ್ಮ ಮೊಬೈಲ್ ಸಂಖ್ಯೆ';

  @override
  String get subject => 'ವಿಷಯ';

  @override
  String get subjectHint => 'ಇದು ಯಾವುದರ ಬಗ್ಗೆ?';

  @override
  String get message => 'ಸಂದೇಶ';

  @override
  String get messageHint => 'ನಿಮ್ಮ ಸಮಸ್ಯೆ ಅಥವಾ ಪ್ರಶ್ನೆಯನ್ನು ವಿವರಿಸಿ';

  @override
  String get send => 'ಕಳುಹಿಸಿ';

  @override
  String get sentSuccess => 'ಕಳುಹಿಸಲಾಗಿದೆ! ನಾವು ಶೀಘ್ರದಲ್ಲೇ ಉತ್ತರಿಸುತ್ತೇವೆ.';

  @override
  String get required => 'ಅಗತ್ಯ';

  @override
  String get enterValidEmail => 'ಮಾನ್ಯ ಇಮೇಲ್ ನಮೂದಿಸಿ';

  @override
  String get writeMoreDetail => 'ದಯವಿಟ್ಟು ಇನ್ನಷ್ಟು ವಿವರವಾಗಿ ಬರೆಯಿರಿ';

  @override
  String get couldNotOpenEmailApp => 'ಇಮೇಲ್ ಆಪ್ ತೆರೆಯಲಾಗಲಿಲ್ಲ.';

  @override
  String get couldNotSendTryLater =>
      'ಕಳುಹಿಸಲಾಗಲಿಲ್ಲ. ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.';

  @override
  String get tipNoShareOtp =>
      'ಸೂಚನೆ: ಇಲ್ಲಿ ಪಾಸ್‌ವರ್ಡ್‌ಗಳು ಅಥವಾ OTPಗಳನ್ನು ಹಂಚಿಕೊಳ್ಳಬೇಡಿ.';

  @override
  String get loginLanguageLabel => 'English / हिंदी';

  @override
  String get loginHeroSubtitle => 'Your health companion';

  @override
  String get loginMobileNumberLabel => 'Mobile Number';

  @override
  String get loginMobileHint => '00000 00000';

  @override
  String get loginEmailLabel => 'Email Address';

  @override
  String get loginPasswordLabel => 'Password';

  @override
  String get loginPasswordHint => 'Enter password';

  @override
  String get loginPleaseWait => 'Please wait...';

  @override
  String get loginSendOtp => 'Send OTP';

  @override
  String get loginContinue => 'Continue';

  @override
  String get loginSendingOtp => 'Sending OTP...';

  @override
  String get loginOr => 'OR';

  @override
  String get loginContinueAsGuest => 'Continue as Guest';

  @override
  String get loginAgreementText =>
      'By logging in, you agree to MediMitra\'s\nTerms of Service and Privacy Policy.';

  @override
  String get loginUnableContinueGuest => 'Unable to continue as guest.';

  @override
  String get loginEnterMobileNumber => 'Enter mobile number.';

  @override
  String get loginEnterValidMobileNumber =>
      'Enter a valid 10-digit mobile number.';

  @override
  String get loginOtpSent => 'OTP sent.';

  @override
  String get loginFailedSendOtp => 'Failed to send OTP.';

  @override
  String get loginEnterValidEmail => 'Enter a valid email.';

  @override
  String get loginPasswordMinChars => 'Password must be at least 6 characters.';

  @override
  String get loginEmailPasswordDisabled =>
      'Email/Password sign-in is disabled in Firebase Console.';

  @override
  String get loginAccountExistsTryLogin =>
      'Account already exists. Try logging in.';

  @override
  String get loginWeakPassword => 'Password is too weak (min 6 chars).';

  @override
  String get loginIncorrectPassword => 'Incorrect password.';

  @override
  String get loginInvalidEmail => 'Invalid email.';

  @override
  String get loginLoginFailed => 'Login failed.';

  @override
  String get otpVerifyNumber => 'Verify Number';

  @override
  String get otpSentTo => 'We have sent a 6-digit code to';

  @override
  String get otpHaventReceived => 'Haven\'t received the code?';

  @override
  String get otpResendCode => 'Resend Code';

  @override
  String get otpVerifyProceed => 'Verify & Proceed';

  @override
  String get otpVerifying => 'Verifying...';

  @override
  String get otpEnter6Digit => 'Enter 6-digit OTP.';

  @override
  String get otpInvalid => 'Invalid OTP.';

  @override
  String get otpVerificationFailed => 'OTP verification failed.';

  @override
  String get otpFailedResend => 'Failed to resend code.';

  @override
  String get otpCodeResent => 'Code resent.';

  @override
  String get otpSafetyFirst => 'SAFETY FIRST';

  @override
  String get otpSafetyNote =>
      'Securely connect to your healthcare records with MediMitra’s encryption.';

  @override
  String get communityOutbreakAlerts => 'Community Outbreak Alerts';

  @override
  String get outbreakPrivacyNote =>
      'Privacy-first: only aggregated symptom counts by PIN3 and day. No names, chat text, GPS, or exact timestamps.';

  @override
  String get regionNotSet => 'Region: Not set';

  @override
  String regionPin3Line(Object region) {
    return 'Region: $region (PIN3)';
  }

  @override
  String get set => 'Set';

  @override
  String get setAreaPin3Title => 'Set your area (PIN3)';

  @override
  String get setAreaPin3Body =>
      'Enter your PIN code. We only store the first 3 digits (coarse region).';

  @override
  String get pinExampleHint => 'e.g. 411001';

  @override
  String get enterFirst3DigitsPin =>
      'Enter at least first 3 digits of your PIN.';

  @override
  String get unableToSaveRegion => 'Unable to save region.';

  @override
  String get setPin3ToSeeAlerts =>
      'Set your PIN3 to see outbreak alerts for your area.';

  @override
  String get noAlertsToday => 'No alerts today for your area.';

  @override
  String get prevention => 'Prevention';

  @override
  String get outbreakLevelHighRisk => 'High Risk';

  @override
  String get outbreakLevelWarning => 'Warning';

  @override
  String get outbreakLevelWatch => 'Watch';

  @override
  String get outbreakLevelNone => 'None';

  @override
  String get back => 'Back';

  @override
  String get next => 'Next';

  @override
  String get couldNotSaveConsent =>
      'Could not save your consent. Please try again.';

  @override
  String get termsSigningTitle => 'Terms of Service';

  @override
  String get termsSigningIntro =>
      'Before using the symptom assessment, please accept the Terms of Service and Privacy Policy. Please note:';

  @override
  String get termsBulletNotDiagnosisTitle => 'The result is not a diagnosis.';

  @override
  String get termsBulletNotDiagnosisBody =>
      ' It’s only for your information and not a qualified medical opinion.';

  @override
  String get termsBulletNoEmergencyTitle =>
      'Do not use it in case of an emergency.';

  @override
  String get termsBulletNoEmergencyBody =>
      ' Call your local emergency number right away when there’s a health emergency.';

  @override
  String get termsBulletDataSafeTitle => 'Your data is safe.';

  @override
  String get termsBulletDataSafeBody =>
      ' The information you give won’t be shared or used to identify you.';

  @override
  String get termsConsentTermsPrefix => 'I have read and accept the ';

  @override
  String get termsConsentTermsLink => 'Terms of Service';

  @override
  String get termsConsentTermsSuffix => '.';

  @override
  String get termsConsentPrivacyPrefix =>
      'I agree for my health information to be used for the interview. More information in the ';

  @override
  String get termsConsentPrivacyLink => 'Privacy Policy';

  @override
  String get termsConsentPrivacySuffix => '.';

  @override
  String get quickQuestions => 'Quick questions';

  @override
  String get typeAQuestionHint => 'Type a question…';

  @override
  String get talkToMaya => 'Talk to Maya';

  @override
  String get womensHealthHubTitle => 'Women\'s Health Hub';

  @override
  String get womensHealthHubWelcome => 'Welcome to your health journey';

  @override
  String get womensHealthHubSubtitle =>
      'Select a category to explore resources and get personalized care.';

  @override
  String get menstrualHealth => 'Menstrual Health';

  @override
  String get pregnancyAndMaternal => 'Pregnancy & Maternal';

  @override
  String get breastHealth => 'Breast Health';

  @override
  String get comingSoon => 'Coming soon';

  @override
  String get womensHealthHubTagline => 'MEDIMITRA WELLNESS';

  @override
  String get womensHealthCategoryMenstrualDescription =>
      'ನಿಮ್ಮ ಮಾಸಿಕ ಚಕ್ರವನ್ನು ತಿಳಿದುಕೊಳ್ಳಿ,\nಸ್ವಚ್ಛತೆಯನ್ನು ಕಲಿಯಿರಿ ಮತ್ತು\nಪಿರಿಯಡ್ಸ್‌ನ್ನು ಸುಲಭವಾಗಿ ನಿರ್ವಹಿಸಿ.';

  @override
  String get womensHealthCategoryPregnancyDescription =>
      'ಆರೋಗ್ಯಕರ ಗರ್ಭಧಾರಣೆಗಾಗಿ ತಜ್ಞ ಮಾರ್ಗದರ್ಶನ,\nಪೋಷಣಾ ಸಲಹೆಗಳು ಮತ್ತು\nಸುರಕ್ಷಿತ ಹೆರಿಗೆ ಬೆಂಬಲ.';

  @override
  String get womensHealthCategoryBreastDescription =>
      'ಸರಳ ಸ್ವಯಂ ಪರೀಕ್ಷೆ ಮಾರ್ಗದರ್ಶನಗಳು\nಮತ್ತು ಅರಿವು ಸಲಹೆಗಳು\nಶೀಘ್ರ ಪತ್ತೆ ಹಾಗೂ ಆರೈಕೆಗೆ.';

  @override
  String get recommended => 'ಶಿಫಾರಸು ಮಾಡಿದವು';

  @override
  String get explore => 'ಅನ್ವೇಷಿಸಿ';

  @override
  String get menstrualScreenTitle => 'ಮಾಸಿಕ ಆರೋಗ್ಯ';

  @override
  String get menstrualWhatIsMenstruationTitle => 'ಮಾಸಿಕಧರ್ಮ ಎಂದರೆ ಏನು?';

  @override
  String get menstrualWhatIsMenstruationBody =>
      'ಮಾಸಿಕಧರ್ಮವು ಗರ್ಭಾಶಯದ ಒಳಪದರವನ್ನು ಹೊರಹಾಕುವ ಸಹಜವಾದ ತಿಂಗಳ ಪ್ರಕ್ರಿಯೆ. ಇದು ಆರೋಗ್ಯಕರ ಪ್ರಜನನ ವ್ಯವಸ್ಥೆಯ ಸೂಚನೆ ಮತ್ತು ಬೆಳವಣಿಗೆಯ ಸಾಮಾನ್ಯ ಭಾಗವಾಗಿದೆ.';

  @override
  String get menstrualQuote => 'ಪ್ರಜನನ ಮತ್ತು ಜೀವನದ ಚಕ್ರ';

  @override
  String get menstrualWhatIsNormalTitle => 'ಏನು ಸಾಮಾನ್ಯ?';

  @override
  String get menstrualNormalItem1 => 'ಚಕ್ರ 21 ರಿಂದ 35 ದಿನಗಳ ನಡುವೆ';

  @override
  String get menstrualNormalItem2 => 'ರಕ್ತಸ್ರಾವ 3 ರಿಂದ 7 ದಿನಗಳು';

  @override
  String get menstrualNormalItem3 => 'ಸ್ವಲ್ಪದಿಂದ ಮಧ್ಯಮ ಮಟ್ಟದ ತೊಂದರೆ/ನೋವು';

  @override
  String get menstrualWarningSignsTitle => 'ಎಚ್ಚರಿಕೆ ಸೂಚನೆಗಳು';

  @override
  String get menstrualWarningItem1 =>
      'ತೀವ್ರ ರಕ್ತಸ್ರಾವದಿಂದ ಪ್ರತಿ 1–2 ಗಂಟೆಗೆ ಪ್ಯಾಡ್ ಬದಲಿಸಬೇಕಾಗುವುದು';

  @override
  String get menstrualWarningItem2 =>
      'ದೈನಂದಿನ ಕೆಲಸಗಳನ್ನು ಅಡ್ಡಿಪಡಿಸುವಷ್ಟು ತೀವ್ರ ನೋವು';

  @override
  String get menstrualWarningItem3 =>
      'ಚಕ್ರವು ನಿರಂತರವಾಗಿ 21 ದಿನಕ್ಕಿಂತ ಕಡಿಮೆ ಅಥವಾ 38 ದಿನಕ್ಕಿಂತ ಹೆಚ್ಚು ಇರುವುದು';

  @override
  String get menstrualHygieneTipsTitle => 'ಸ್ವಚ್ಛತೆ ಸಲಹೆಗಳು';

  @override
  String get menstrualTipChangeRegularlyTitle => 'ನಿಯಮಿತವಾಗಿ ಬದಲಿಸಿ';

  @override
  String get menstrualTipChangeRegularlySubtitle =>
      'ಪ್ರತಿ 4–6 ಗಂಟೆಗೆ ಪ್ಯಾಡ್ ಬದಲಿಸಿ';

  @override
  String get menstrualTipCleanHandsTitle => 'ಕೈಗಳನ್ನು ಸ್ವಚ್ಛವಾಗಿ';

  @override
  String get menstrualTipCleanHandsSubtitle =>
      'ಮುನ್ಸೂಚನೆ ಮತ್ತು ನಂತರ ಕೈ ತೊಳೆಯಿರಿ';

  @override
  String get menstrualTipStayDryTitle => 'ಒಣಗಾಗಿ ಇಡಿ';

  @override
  String get menstrualTipStayDrySubtitle =>
      'ಜನನಾಂಗ ಪ್ರದೇಶವನ್ನು ಸ್ವಚ್ಛವಾಗಿ ಮತ್ತು ಒಣಗಾಗಿ ಇಡಿ';

  @override
  String get menstrualMythsFactsTitle => 'ಮಿಥ್ಯೆಗಳು & ಸತ್ಯಗಳು';

  @override
  String get menstrualMyth1 => 'ಮಿಥ್ಯೆ: \"ಪಿರಿಯಡ್ಸ್ ವೇಳೆ ವ್ಯಾಯಾಮ ಮಾಡಬಾರದು.\"';

  @override
  String get menstrualFact1 =>
      'ಸತ್ಯ: ಲಘು ವ್ಯಾಯಾಮವು ನೋವನ್ನು ಕಡಿಮೆ ಮಾಡಿ ಮನೋಭಾವವನ್ನು ಸುಧಾರಿಸಬಹುದು.';

  @override
  String get menstrualMyth2 => 'ಮಿಥ್ಯೆ: \"ಮಾಸಿಕ ರಕ್ತವು \'ಕಲುಷಿತ\' ರಕ್ತ.\"';

  @override
  String get menstrualFact2 =>
      'ಸತ್ಯ: ಅದು ಗರ್ಭಾಶಯದ ಒಳಪದರದಿಂದ ಹೊರಬರುವ ಸಾಮಾನ್ಯ ರಕ್ತ ಮತ್ತು ಕಣಜ.';

  @override
  String get chatHeaderTitle => 'ಆರೋಗ್ಯ ಸಹಾಯಕ';

  @override
  String get chatHeaderStatusOnline => 'ಆನ್‌ಲೈನ್';

  @override
  String get chatToday => 'ಇಂದು';

  @override
  String get chatQuickChipCheckFever => '🌡️ ಜ್ವರ ಪರಿಶೀಲನೆ';

  @override
  String get chatQuickPromptCheckFever => 'ನನಗೆ ಜ್ವರ ಪರಿಶೀಲಿಸಬೇಕು.';

  @override
  String get chatQuickChipWomensHealth => '🤰 ಮಹಿಳಾ ಆರೋಗ್ಯ';

  @override
  String get chatQuickPromptWomensHealth =>
      'ನನಗೆ ಮಹಿಳಾ ಆರೋಗ್ಯ ಕುರಿತು ಪ್ರಶ್ನೆ ಇದೆ.';

  @override
  String get chatQuickChipFirstAid => '🩹 ಪ್ರಾಥಮಿಕ ಚಿಕಿತ್ಸೆ';

  @override
  String get chatQuickPromptFirstAid => 'ನನಗೆ ಪ್ರಾಥಮಿಕ ಚಿಕಿತ್ಸೆಯ ಸಲಹೆ ಬೇಕು.';

  @override
  String get chatQuickChipChildCare => '👶 ಮಕ್ಕಳ ಆರೈಕೆ';

  @override
  String get chatQuickPromptChildCare => 'ನನಗೆ ಮಕ್ಕಳ ಆರೈಕೆ ಮಾರ್ಗದರ್ಶನ ಬೇಕು.';

  @override
  String get chatInputHintAskMeAnything => 'ಏನಾದರೂ ಕೇಳಿ...';

  @override
  String get profileSaved => 'ಪ್ರೊಫೈಲ್ ಉಳಿಸಲಾಗಿದೆ';

  @override
  String get saving => 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...';

  @override
  String get saveChanges => 'ಮಾರ್ಪಾಡುಗಳನ್ನು ಉಳಿಸಿ';

  @override
  String get profileTopBarTitle => 'ಪ್ರೊಫೈಲ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು';

  @override
  String get profileHeaderSubtitle => 'ಬಳಕೆದಾರ ಪ್ರೊಫೈಲ್';

  @override
  String get profileSectionFullName => 'ಪೂರ್ಣ ಹೆಸರು';

  @override
  String get profileHintFullName => 'ಉದಾ. ರಾಹುಲ್ ಶರ್ಮಾ';

  @override
  String get profileSectionAge => 'ವಯಸ್ಸು';

  @override
  String get profileHintAge => 'ನಿಮ್ಮ ವಯಸ್ಸು ನಮೂದಿಸಿ';

  @override
  String get profileSectionGender => 'ಲಿಂಗ';

  @override
  String get profileGenderMale => 'ಪುರುಷ';

  @override
  String get profileGenderFemale => 'ಸ್ತ್ರೀ';

  @override
  String get profileGenderOther => 'ಇತರೆ';

  @override
  String get profileChronicConditions => 'ದೀರ್ಘಕಾಲೀನ ರೋಗಗಳು';

  @override
  String get profileConditionsBadge => 'ದ್ವಿಭಾಷಾ';

  @override
  String get conditionDiabetesTitle => 'ಮಧುಮೇಹ';

  @override
  String get conditionDiabetesSubtitle => 'ಡಯಾಬಿಟಿಸ್ (ಶುಗರ್)';

  @override
  String get conditionBpHeartTitle => 'ಬಿಪಿ & ಹೃದಯ';

  @override
  String get conditionBpHeartSubtitle => 'ರಕ್ತದೊತ್ತಡ / ಹೃದಯ';

  @override
  String get conditionAsthmaTitle => 'ಆಸ್ತಮಾ';

  @override
  String get conditionAsthmaSubtitle => 'ಉಸಿರಾಟ';

  @override
  String get conditionThyroidTitle => 'ಥೈರಾಯ್ಡ್';

  @override
  String get conditionThyroidSubtitle => 'ಥೈರಾಯ್ಡ್';

  @override
  String get conditionTbTitle => 'ಟಿಬಿ';

  @override
  String get conditionTbSubtitle => 'ಕ್ಷಯರೋಗ';

  @override
  String get conditionNoneTitle => 'ಯಾವುದೂ ಇಲ್ಲ';

  @override
  String get conditionNoneSubtitle => 'ಯಾವುದೇ ಕಾಯಿಲೆ ಇಲ್ಲ';

  @override
  String get helpFaqBotGreeting =>
      'ನಮಸ್ಕಾರ! ನಾನು MediMitra ಸಹಾಯ. ಲಕ್ಷಣ ಪರಿಶೀಲನೆ, ಧ್ವನಿ ಇನ್‌ಪುಟ್, ಪ್ರಕೋಪ ಅಲರ್ಟ್‌ಗಳು, ಕ್ಲಿನಿಕ್‌ಗಳು, ಲಾಗಿನ್ ಅಥವಾ ಗೌಪ್ಯತೆ ಕುರಿತು ಏನೇ ಬೇಕಾದರೂ ಕೇಳಿ.\n\nಗಮನಿಸಿ: ಇದು ವೈದ್ಯಕೀಯ ಸಲಹೆಯಲ್ಲ. ತುರ್ತು ವೈದ್ಯಕೀಯ ಪರಿಸ್ಥಿತಿಯಲ್ಲಿ, ಸ್ಥಳೀಯ ತುರ್ತು ಸೇವೆಗಳನ್ನು ಸಂಪರ್ಕಿಸಿ.';

  @override
  String get helpFaqSuggestionCheckSymptoms => 'ಲಕ್ಷಣಗಳನ್ನು ಹೇಗೆ ಪರಿಶೀಲಿಸಬೇಕು?';

  @override
  String get helpFaqSuggestionVoiceSymptoms =>
      'ಧ್ವನಿ ಮೂಲಕ ಲಕ್ಷಣಗಳು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತವೆ?';

  @override
  String get helpFaqSuggestionOutbreakAlert => 'ಪ್ರಕೋಪ ಅಲರ್ಟ್ ಎಂದರೆ ಏನು?';

  @override
  String get helpFaqSuggestionNearbyClinics =>
      'ಹತ್ತಿರದ ಕ್ಲಿನಿಕ್‌ಗಳನ್ನು ಹೇಗೆ ಹುಡುಕುವುದು?';

  @override
  String get helpFaqSuggestionOtpLogin => 'OTP ಲಾಗಿನ್ ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ?';

  @override
  String get helpFaqSuggestionDataSafe => 'ನನ್ನ ಡೇಟಾ ಸುರಕ್ಷಿತವೇ?';

  @override
  String get helpFaqSuggestionGuestMode => 'ಲಾಗಿನ್ ಇಲ್ಲದೆ ಆಪ್ ಬಳಸಬಹುದೇ?';

  @override
  String get helpFaqSuggestionChangeLanguage => 'ಭಾಷೆ ಹೇಗೆ ಬದಲಾಯಿಸಬೇಕು?';

  @override
  String get helpFaqSuggestionDarkMode => 'ಡಾರ್ಕ್ ಮೋಡ್ ಹೇಗೆ ಆನ್ ಮಾಡುವುದು?';

  @override
  String get helpFaqReplySymptomChecking =>
      'ಲಕ್ಷಣಗಳನ್ನು ಪರಿಶೀಲಿಸಲು:\n1) ಚಾಟ್ / ಲಕ್ಷಣ ಪರಿಶೀಲಕ ತೆರೆಯಿರಿ\n2) ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ಟೈಪ್ ಮಾಡಿ (ಅಥವಾ ಧ್ವನಿ ಬಳಸಿ)\n3) ಮುಂದಿನ ಪ್ರಶ್ನೆಗಳಿಗೆ ಉತ್ತರಿಸಿ\n\nMediMitra ಸಾಧ್ಯವಾದ ಕಾರಣಗಳು ಮತ್ತು ಮುಂದಿನ ಹೆಜ್ಜೆಗಳನ್ನು ತೋರಿಸುತ್ತದೆ. ಗಂಭೀರ ಲಕ್ಷಣಗಳು (ಛಾತಿ ನೋವು, ಉಸಿರಾಟ ಕಷ್ಟ, ಮೂರ್ಚೆ) ಇದ್ದರೆ ತಕ್ಷಣ ಚಿಕಿತ್ಸೆ ಪಡೆಯಿರಿ.';

  @override
  String get helpFaqReplyVoiceSymptoms =>
      'ಧ್ವನಿ ಲಕ್ಷಣಗಳು: ಮೈಕ್ ಬಟನ್ ಟ್ಯಾಪ್ ಮಾಡಿ, ನಿಮ್ಮ ಲಕ್ಷಣಗಳನ್ನು ಸ್ಪಷ್ಟವಾಗಿ ಹೇಳಿ; ಆಪ್ ಅದನ್ನು ಪಠ್ಯವಾಗಿ ಪರಿವರ್ತಿಸಿ ವಿಶ್ಲೇಷಿಸುತ್ತದೆ.\n\nಟಿಪ್ಸ್: ಒಂದೊಮ್ಮೆ ಒಂದು ಲಕ್ಷಣ ಹೇಳಿ, ಸರಳ ಪದಗಳನ್ನು ಬಳಸಿ (\"ಜ್ವരം\", \"ಕೆಮ್ಮು\") ಮತ್ತು ಕೇಳಿದಾಗ ಮೈಕ್ರೋಫೋನ್ ಅನುಮತಿ ನೀಡಿ.';

  @override
  String get helpFaqReplyOutbreakAlert =>
      'ಪ್ರಕೋಪ ಅಲರ್ಟ್ ನಿಮ್ಮ ಪ್ರದೇಶದಲ್ಲಿ ಯಾವ ಲಕ್ಷಣಗಳು ಹೆಚ್ಚಾಗಿ ಕಂಡುಬರುತ್ತಿವೆ ಎಂಬುದನ್ನು ತಿಳಿಯಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ. ಇದು ಅನಾಮಧೇಯ, ಒಟ್ಟುಗೂಡಿಸಿದ ಡೇಟಾದ ಮೇಲೆ ಆಧಾರಿತವಾಗಿದೆ ಮತ್ತು ಅರಿವಿಗಾಗಿ (ರೋಗನಿರ್ಣಯಕ್ಕೆ ಅಲ್ಲ).\n\nOutbreak ವಿಭಾಗದಲ್ಲಿ ಇನ್‌ಸೈಟ್‌ಗಳನ್ನು ನೋಡಬಹುದು.';

  @override
  String get helpFaqReplyNearbyClinics =>
      'ಹತ್ತಿರದ ಕ್ಲಿನಿಕ್‌ಗಳು: ಕ್ಲಿನಿಕ್ ಲೊಕೇಟರ್ ತೆರೆಯಿರಿ ಮತ್ತು ನಿಮ್ಮ ಸುತ್ತಲಿನ ಕ್ಲಿನಿಕ್‌ಗಳನ್ನು ನೋಡಿ.\n\nಸ್ಥಳ ಅನುಮತಿ ಸಕ್ರಿಯವಾಗಿದೆ ಎಂಬುದು ಖಚಿತಪಡಿಸಿ.';

  @override
  String get helpFaqReplyOtpLogin =>
      'OTP ಲಾಗಿನ್: ನಿಮ್ಮ 10 ಅಂಕಿಯ ಮೊಬೈಲ್ ಸಂಖ್ಯೆಯನ್ನು ನಮೂದಿಸಿ; ನಾವು ಪರಿಶೀಲನಾ OTP ಕಳುಹಿಸುತ್ತೇವೆ. 6 ಅಂಕಿಯ OTP ನಮೂದಿಸಿ ಮುಂದುವರಿಯಿರಿ.\n\nಬರದಿದ್ದರೆ, ರಿಸೆಂಡ್ ಟೈಮರ್ ನಂತರ ಮರುಪ್ರಯತ್ನಿಸಿ; ನೆಟ್ವರ್ಕ್ ಪರಿಶೀಲಿಸಿ.';

  @override
  String get helpFaqReplyGuestMode =>
      'ಗೆಸ್ಟ್ ಮೋಡ್‌ನಲ್ಲಿ ಲಾಗಿನ್ ಇಲ್ಲದೆ ಆಪ್ ಬಳಸಬಹುದು. ಆದರೆ ಪ್ರೊಫೈಲ್‌ಗೆ ಸೇವ್ ಆಗುವ ಕೆಲವು ವೈಶಿಷ್ಟ್ಯಗಳು ಮಿತವಾಗಿರಬಹುದು.';

  @override
  String get helpFaqReplyPrivacy =>
      'ನಿಮ್ಮ ಅನುಭವವನ್ನು ವೈಯಕ್ತೀಕರಿಸಲು (ಹೆಸರು/ವಯಸ್ಸು/ಲಿಂಗ/ಸ್ಥಿತಿಗಳು) ಪ್ರೊಫೈಲ್ ಡೇಟಾವನ್ನು ಸುರಕ್ಷಿತವಾಗಿ ಉಳಿಸಲಾಗುತ್ತದೆ. ಚಾಟ್‌ನಲ್ಲಿ ಸಂವೇದನಾಶೀಲ ಮಾಹಿತಿ ಹಂಚಿಕೊಳ್ಳಬೇಡಿ.\n\nವಿವರಗಳಿಗೆ ಆಪ್‌ನ ಗೌಪ್ಯತಾ ನೀತಿಯನ್ನು ನೋಡಿ.';

  @override
  String get helpFaqReplyChangeLanguage => 'ಭಾಷೆ ಬದಲಾಯಿಸಲು: ಪ್ರೊಫೈಲ್ → ಭಾಷೆ.';

  @override
  String get helpFaqReplyDarkMode =>
      'ಡಾರ್ಕ್ ಮೋಡ್: ಪ್ರೊಫೈಲ್ → ಡಾರ್ಕ್ ಮೋಡ್‌ನಲ್ಲಿ ಟಾಗಲ್ ಮಾಡಿ.';

  @override
  String get helpFaqReplyContactSupport =>
      'ಬೆಂಬಲವನ್ನು ಸಂಪರ್ಕಿಸಲು: Contact Us ತೆರೆಯಿರಿ ಮತ್ತು ಸಂದೇಶ ಕಳುಹಿಸಿ. ಸಾಧ್ಯವಾದರೆ ಸ್ಕ್ರೀನ್‌ಶಾಟ್‌ಗಳು ಮತ್ತು ಹಂತಗಳನ್ನು ಸೇರಿಸಿ.';

  @override
  String get helpFaqReplyFallback =>
      'ನಾನು ಸಹಾಯ ಮಾಡುವ ವಿಷಯಗಳು: ಲಕ್ಷಣ ಪರಿಶೀಲನೆ, ಧ್ವನಿ ಇನ್‌ಪುಟ್, ಪ್ರಕೋಪ ಅಲರ್ಟ್‌ಗಳು, ಕ್ಲಿನಿಕ್ ಲೊಕೇಟರ್, OTP ಲಾಗಿನ್, ಗೌಪ್ಯತೆ, ಭಾಷೆ, ಮತ್ತು ಡಾರ್ಕ್ ಮೋಡ್.\n\nಇವುಗಳಲ್ಲಿ ಒಂದನ್ನು ಪ್ರಯತ್ನಿಸಿ: \"ಲಕ್ಷಣಗಳನ್ನು ಹೇಗೆ ಪರಿಶೀಲಿಸಬೇಕು?\", \"ಹತ್ತಿರದ ಕ್ಲಿನಿಕ್‌ಗಳನ್ನು ಹೇಗೆ ಹುಡುಕುವುದು?\", \"ನನ್ನ ಡೇಟಾ ಸುರಕ್ಷಿತವೇ?\"';
}
