// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Oriya (`or`).
class AppLocalizationsOr extends AppLocalizations {
  AppLocalizationsOr([String locale = 'or']) : super(locale);

  @override
  String get appTitle => 'ମେଡିମିତ୍ରା';

  @override
  String get close => 'ବନ୍ଦ କରନ୍ତୁ';

  @override
  String get loginTagline => 'ଆପଣ ଏବଂ ଆପଣଙ୍କ ପରିବାର ପାଇଁ ସହଜ ସ୍ୱାସ୍ଥ୍ୟ ସେବା';

  @override
  String get smsLogin => 'ଏସଏମଏସ ଲଗଇନ୍';

  @override
  String get emailLogin => 'ଇମେଲ ଲଗଇନ୍';

  @override
  String get homeHello => 'ନମସ୍କାର,';

  @override
  String get homeThere => 'ସେଠାରେ';

  @override
  String get homeChatCta => 'ଆମ AI ସ୍ୱାସ୍ଥ୍ୟ ଚାଟ୍ ସହାୟକକୁ ଅନ୍ୱେଷଣ କରନ୍ତୁ';

  @override
  String get homeOurFeatures => 'ଆମ ବୈଶିଷ୍ଟ୍ୟଗୁଡିକ';

  @override
  String get homeHighlights => 'ହାଇଲାଇଟ୍‌ସ';

  @override
  String get homeDisclaimerTitle => 'ଦାୟିତ୍ୱ ତ୍ୟାଗ';

  @override
  String get homeDisclaimerBody =>
      'MediMitra କେବଳ ସୂଚନା ପାଇଁ; ଏହା ଚିକିତ୍ସା ପରାମର୍ଶ ନୁହେଁ। ଏହା ଡାକ୍ତରଙ୍କ ପରିବର୍ତ୍ତେ ନୁହେଁ।\nଗୁରୁତର ଲକ୍ଷଣ କିମ୍ବା ଆପାତକାଳୀନ ଅବସ୍ଥା ହେଲେ, ନିକଟସ୍ଥ ହସ୍ପିଟାଲକୁ ଯାଆନ୍ତୁ କିମ୍ବା ତୁରନ୍ତ ଆପାତକାଳୀନ ସେବାକୁ ଯୋଗାଯୋଗ କରନ୍ତୁ।';

  @override
  String get featureSymptomChecker => 'ଲକ୍ଷଣ ପରୀକ୍ଷକ';

  @override
  String get featureWomensHealth => 'ମହିଳା ସ୍ୱାସ୍ଥ୍ୟ ସଚେତନତା';

  @override
  String get featureInsurance => 'ବୀମା';

  @override
  String get featureAiHealthSummary => 'AI ସ୍ୱାସ୍ଥ୍ୟ ସାରାଂଶ';

  @override
  String get featureReminders => 'ରିମାଇଣ୍ଡର୍‌ସ';

  @override
  String get featureLocateClinics => 'ନିକଟସ୍ଥ କ୍ଲିନିକ୍ ଖୋଜନ୍ତୁ';

  @override
  String get promoAiSymptomCheckTitle => 'AI ଲକ୍ଷଣ ପରୀକ୍ଷା';

  @override
  String get promoAiSymptomCheckSubtitle =>
      'ଲକ୍ଷଣ ବର୍ଣ୍ଣନା କରନ୍ତୁ, କିଛି ସେକେଣ୍ଡରେ ମାର୍ଗଦର୍ଶନ ପାଆନ୍ତୁ।';

  @override
  String get promoVoiceWaveformTitle => 'ଭଏସ୍ + ଵେଭଫର୍ମ';

  @override
  String get promoVoiceWaveformSubtitle =>
      'ଭଏସ୍ ଇନ୍‌ପୁଟ୍ ସହିତ ହ୍ୟାଣ୍ଡସ୍-ଫ୍ରି ଚାଟ୍।';

  @override
  String get promoProfilePersonalizationTitle => 'ପ୍ରୋଫାଇଲ୍ ବ୍ୟକ୍ତିଗତକରଣ';

  @override
  String get promoProfilePersonalizationSubtitle =>
      'ଭଲ ସହାୟତା ପାଇଁ ବୟସ, ଲିଙ୍ଗ ଏବଂ ଅବସ୍ଥା ସେଭ୍ କରନ୍ତୁ।';

  @override
  String get promoNearbyClinicsTitle => 'ନିକଟସ୍ଥ କ୍ଲିନିକ୍‌ସ';

  @override
  String get promoNearbyClinicsSubtitle =>
      'ଆପଣଙ୍କ ସ୍ଥାନ ନିକଟର ସ୍ୱାସ୍ଥ୍ୟ ସେବା ଖୋଜନ୍ତୁ।';

  @override
  String get settings => 'ସେଟିଂସ୍';

  @override
  String get supportAndInformation => 'ସହାୟତା & ସୂଚନା';

  @override
  String get notifications => 'ନୋଟିଫିକେସନ୍‌ସ';

  @override
  String get manageYourNotifications =>
      'ଆପଣଙ୍କ ନୋଟିଫିକେସନ୍‌ସ ବ୍ୟବସ୍ଥାପନ କରନ୍ତୁ';

  @override
  String get notificationsEnabled => 'ନୋଟିଫିକେସନ୍ ସକ୍ରିୟ';

  @override
  String get notificationsDisabled => 'ନୋଟିଫିକେସନ୍ ନିଷ୍କ୍ରିୟ';

  @override
  String get couldNotUpdateNotifications =>
      'ନୋଟିଫିକେସନ୍ ଅପଡେଟ୍ କରି ପାରିଲୁ ନାହିଁ';

  @override
  String get darkMode => 'ଡାର୍କ ମୋଡ୍';

  @override
  String get toggleDarkTheme => 'ଡାର୍କ ଥିମ୍ ଅନ/ଅଫ୍ କରନ୍ତୁ';

  @override
  String get helpAndFaq => 'ସହାୟତା & FAQ';

  @override
  String get getHelpAndAnswers => 'ସହାୟତା ଏବଂ ଉତ୍ତର ପାଆନ୍ତୁ';

  @override
  String get getInTouchWithSupport => 'ସପୋର୍ଟ ସହିତ ଯୋଗାଯୋଗ କରନ୍ତୁ';

  @override
  String get aboutMediMitra => 'MediMitra ବିଷୟରେ';

  @override
  String versionLine(Object version) {
    return 'ଭାର୍ସନ୍ $version';
  }

  @override
  String get privacyPolicy => 'ଗୋପନୀୟତା ନୀତି';

  @override
  String get howWeProtectYourData => 'ଆମେ ଆପଣଙ୍କ ତଥ୍ୟ କିପରି ସୁରକ୍ଷା କରୁ';

  @override
  String get termsAndConditions => 'ନିୟମ & ସର୍ତ୍ତ';

  @override
  String get termsConditionsBody =>
      'Terms & Conditions\n\nBy downloading and using this application, you agree to comply with and be bound by these Terms and Conditions. If you do not agree with any part of these terms, you should discontinue using the app.\n\nThis application is designed to provide health-related information and decision-support guidance only. It is not a medical diagnostic tool and does not replace consultation with a qualified doctor or healthcare professional. All information provided by the app is for educational and support purposes, and users must always seek professional medical advice for diagnosis, treatment, or emergencies.\n\nUsers are responsible for providing accurate and honest information while using the app. The guidance generated by the system depends on the inputs provided by the user, and incorrect or incomplete information may lead to inaccurate results. The app should not be used as the sole basis for making medical decisions.\n\nThis application is not intended for emergency situations. In case of severe symptoms such as chest pain, difficulty breathing, loss of consciousness, or heavy bleeding, users must immediately contact local emergency services or visit the nearest hospital.\n\nTo the maximum extent permitted by law, the developers shall not be held liable for any direct or indirect damages arising from the use of this application. Use of the app is entirely at the user’s own risk, and no guarantee is made regarding the accuracy, completeness, or reliability of the information provided.\n\nUse of this application is also governed by our Privacy Policy. By continuing to use the app, you confirm that you have read, understood, and agreed to both the Privacy Policy and these Terms and Conditions.\n\nWe reserve the right to modify or update these Terms and Conditions at any time. Any changes will be displayed within the app, and continued use of the app after such changes indicates acceptance of the updated terms.';

  @override
  String get legalAgreement => 'ଆଇନ ଚୁକ୍ତି';

  @override
  String get deleteData => 'ଡାଟା ଡିଲିଟ୍ କରନ୍ତୁ';

  @override
  String get deleteChatsAndSavedSettings =>
      'ଚାଟ୍‌ସ & ସେଭ୍ କରା ସେଟିଂସ୍ ଡିଲିଟ୍ କରନ୍ତୁ';

  @override
  String get logOut => 'ଲଗ୍ ଆଉଟ୍';

  @override
  String get logoutQuestion => 'ଲଗ୍ ଆଉଟ୍ କରିବେ?';

  @override
  String get logoutReturnToLogin => 'ଆପଣ ଲଗ୍ ଆଉଟ୍ ହୋଇ ଲଗଇନ୍ ସ୍କ୍ରିନକୁ ଫେରିବେ।';

  @override
  String get chooseAnAction => 'ଏକ କାର୍ଯ୍ୟ ବାଛନ୍ତୁ';

  @override
  String get deleteAccount => 'ଆକାଉଣ୍ଟ ଡିଲିଟ୍ କରନ୍ତୁ';

  @override
  String get permanentlyDeleteAccount =>
      'ଆପଣଙ୍କ ଆକାଉଣ୍ଟ ସ୍ଥାୟୀଭାବେ ଡିଲିଟ୍ କରନ୍ତୁ';

  @override
  String get deleteLocalData => 'ଲୋକାଲ୍ ଡାଟା ଡିଲିଟ୍ କରନ୍ତୁ';

  @override
  String get deleteLocalDataOnDevice =>
      'ଏହି ଡିଭାଇସରେ ଚାଟ୍‌ସ & ସେଭ୍ ସେଟିଂସ୍ ଡିଲିଟ୍ କରନ୍ତୁ';

  @override
  String get clearLocalDataQuestion => 'ଲୋକାଲ୍ ଡାଟା କ୍ଲିୟାର୍ କରିବେ?';

  @override
  String get clearLocalDataBody =>
      'ଏହା ଏହି ଡିଭାଇସରେ ସ୍ଥାନୀୟଭାବେ ସଂରକ୍ଷିତ ଆପ୍ ଡାଟା (ସେଭ୍ ସେଟିଂସ୍, କ୍ୟାସ୍ କରା ପ୍ରୋଫାଇଲ୍ ଫିଲ୍ଡ, ଏବଂ ମେମୋରିରେ ଥିବା ଚାଟ୍ ଇତିହାସ) ଡିଲିଟ୍ କରିଦେବ।\n\nସମସ୍ତ ପରିବର୍ତ୍ତନ ଲାଗୁ ହେବା ପାଇଁ ଆପ୍ ପୁନଃଚାଲୁ କରିବାକୁ ପଡିପାରେ।';

  @override
  String get clear => 'କ୍ଲିୟାର୍';

  @override
  String get localDataCleared => 'ଲୋକାଲ୍ ଡାଟା କ୍ଲିୟାର୍ ହେଲା';

  @override
  String get couldNotClearLocalData => 'ଲୋକାଲ୍ ଡାଟା କ୍ଲିୟାର୍ କରି ପାରିଲୁ ନାହିଁ';

  @override
  String get accountDeletionNotAvailable =>
      'ଏହି ପ୍ଲାଟଫର୍ମରେ ଆକାଉଣ୍ଟ ଡିଲିଟ୍ ଉପଲବ୍ଧ ନୁହେଁ';

  @override
  String get noSignedInAccountFound => 'ଲଗଇନ୍ ହୋଇଥିବା ଆକାଉଣ୍ଟ ମିଳିଲା ନାହିଁ';

  @override
  String get deleteAccountQuestion => 'ଆକାଉଣ୍ଟ ଡିଲିଟ୍ କରିବେ?';

  @override
  String get deleteAccountBody =>
      'ଏହା ଆପଣଙ୍କ ଆକାଉଣ୍ଟ ସ୍ଥାୟୀଭାବେ ଡିଲିଟ୍ କରିଦେବ। ଆପଣ ଏହି ଡିଭାଇସରୁ ଲଗ୍ ଆଉଟ୍ ହେବେ।';

  @override
  String get deletingAccount => 'ଆକାଉଣ୍ଟ ଡିଲିଟ୍ ହେଉଛି...';

  @override
  String get pleaseLoginAgainThenDelete =>
      'ଦୟାକରି ପୁଣି ଲଗଇନ୍ କରନ୍ତୁ, ତାପରେ ଆକାଉଣ୍ଟ ଡିଲିଟ୍ କରନ୍ତୁ';

  @override
  String get couldNotDeleteAccount => 'ଆକାଉଣ୍ଟ ଡିଲିଟ୍ କରି ପାରିଲୁ ନାହିଁ';

  @override
  String get networkSlowTryAgain => 'ନେଟୱର୍କ ଧୀର। ଦୟାକରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।';

  @override
  String get defaultUser => 'ଉପଯୋଗକର୍ତ୍ତା';

  @override
  String userIdLine(Object id) {
    return 'ଉପଯୋଗକର୍ତ୍ତା ID: $id';
  }

  @override
  String get clinicsNearYou => 'ଆପଣଙ୍କ ନିକଟର କ୍ଲିନିକ୍‌ସ';

  @override
  String get refresh => 'ରିଫ୍ରେଶ୍';

  @override
  String get recenter => 'ପୁଣି କେନ୍ଦ୍ରକୁ';

  @override
  String resultsCount(Object count) {
    return 'ଫଳାଫଳ ($count)';
  }

  @override
  String get nearbyClinics => 'ନିକଟସ୍ଥ କ୍ଲିନିକ୍‌ସ';

  @override
  String get call => 'କଲ୍';

  @override
  String get navigate => 'ନେଭିଗେଟ୍';

  @override
  String get unableToOpenDialer => 'ଡାୟାଲର୍ ଖୋଲି ପାରିଲୁ ନାହିଁ';

  @override
  String get unableToOpenMaps => 'ମ୍ୟାପ୍ ଖୋଲି ପାରିଲୁ ନାହିଁ';

  @override
  String get radius => 'ରେଡିଅସ୍';

  @override
  String get tryAgain => 'ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ';

  @override
  String get openLocationSettings => 'ଲୋକେସନ୍ ସେଟିଂସ୍ ଖୋଲନ୍ତୁ';

  @override
  String get locationServicesDisabled =>
      'ଲୋକେସନ୍ ସେବା ବନ୍ଦ ଅଛି। ଦୟାକରି GPS ସକ୍ରିୟ କରନ୍ତୁ।';

  @override
  String get locationPermissionDenied => 'ଲୋକେସନ୍ ପରମିସନ୍ ଅସ୍ୱୀକୃତ।';

  @override
  String get locationPermissionDeniedForever =>
      'ଲୋକେସନ୍ ପରମିସନ୍ ସ୍ଥାୟୀଭାବେ ଅସ୍ୱୀକୃତ। ସେଟିଂସ୍‌ରୁ ସକ୍ରିୟ କରନ୍ତୁ।';

  @override
  String get chooseLanguage => 'ଭାଷା ବାଛନ୍ତୁ';

  @override
  String get cancel => 'ବାତିଲ';

  @override
  String get save => 'ସେଭ୍';

  @override
  String get contactUs => 'ସମ୍ପର୍କ କରନ୍ତୁ';

  @override
  String get needHelp => 'ସାହାଯ୍ୟ ଦରକାର?';

  @override
  String get contactSubtitle => 'ଆମକୁ ସନ୍ଦେଶ ପଠାନ୍ତୁ; ଆମ ଟିମ୍ ଉତ୍ତର ଦେବ।';

  @override
  String supportEmailLine(Object email) {
    return 'ସପୋର୍ଟ ଇମେଲ: $email';
  }

  @override
  String get typicalResponseLine => 'ସାଧାରଣ ଉତ୍ତର: 24 ଘଣ୍ଟା ମଧ୍ୟରେ';

  @override
  String get language => 'ଭାଷା';

  @override
  String languageSetTo(Object language) {
    return 'ଭାଷା $language କୁ ସେଟ୍ ହେଲା';
  }

  @override
  String get fullName => 'ପୁରା ନାମ';

  @override
  String get yourName => 'ଆପଣଙ୍କ ନାମ';

  @override
  String get email => 'ଇମେଲ';

  @override
  String get emailHint => 'name@example.com';

  @override
  String get phoneOptional => 'ଫୋନ (ଇଚ୍ଛାନୁସାରେ)';

  @override
  String get yourMobileNumber => 'ଆପଣଙ୍କ ମୋବାଇଲ୍ ନମ୍ବର';

  @override
  String get subject => 'ବିଷୟ';

  @override
  String get subjectHint => 'ଏହା କଣ ବିଷୟରେ?';

  @override
  String get message => 'ସନ୍ଦେଶ';

  @override
  String get messageHint => 'ଆପଣଙ୍କ ସମସ୍ୟା କିମ୍ବା ପ୍ରଶ୍ନ ଲେଖନ୍ତୁ';

  @override
  String get send => 'ପଠାନ୍ତୁ';

  @override
  String get sentSuccess => 'ପଠାଗଲା! ଆମେ ସିଘ୍ର ଉତ୍ତର ଦେବୁ।';

  @override
  String get required => 'ଆବଶ୍ୟକ';

  @override
  String get enterValidEmail => 'ବୈଧ ଇମେଲ ଦିଅନ୍ତୁ';

  @override
  String get writeMoreDetail => 'ଦୟାକରି ଅଧିକ ବିବରଣୀ ଲେଖନ୍ତୁ';

  @override
  String get couldNotOpenEmailApp => 'ଇମେଲ ଆପ୍ ଖୋଲି ପାରିଲୁ ନାହିଁ।';

  @override
  String get couldNotSendTryLater => 'ପଠାଇ ପାରିଲୁ ନାହିଁ। ପରେ ଚେଷ୍ଟା କରନ୍ତୁ।';

  @override
  String get tipNoShareOtp =>
      'ଟିପ୍: ଏଠାରେ ପାସୱାର୍ଡ କିମ୍ବା OTP ସେୟାର କରନ୍ତୁ ନାହିଁ।';

  @override
  String get loginLanguageLabel => 'English / हिंदी';

  @override
  String get loginHeroSubtitle => 'ଆପଣଙ୍କ ସ୍ୱାସ୍ଥ୍ୟ ସଙ୍ଗୀ';

  @override
  String get loginMobileNumberLabel => 'ମୋବାଇଲ୍ ନମ୍ବର';

  @override
  String get loginMobileHint => '00000 00000';

  @override
  String get loginEmailLabel => 'ଇମେଲ ଠିକଣା';

  @override
  String get loginPasswordLabel => 'ପାସୱାର୍ଡ';

  @override
  String get loginPasswordHint => 'ପାସୱାର୍ଡ ଦିଅନ୍ତୁ';

  @override
  String get loginPleaseWait => 'ଦୟାକରି ଅପେକ୍ଷା କରନ୍ତୁ...';

  @override
  String get loginSendOtp => 'OTP ପଠାନ୍ତୁ';

  @override
  String get loginContinue => 'ଚାଲୁ ରଖନ୍ତୁ';

  @override
  String get loginSendingOtp => 'OTP ପଠାଯାଉଛି...';

  @override
  String get loginOr => 'କିମ୍ବା';

  @override
  String get loginContinueAsGuest => 'ଗେଷ୍ଟ ଭାବେ ଚାଲୁ ରଖନ୍ତୁ';

  @override
  String get loginAgreementText =>
      'ଲଗଇନ୍ କରି, ଆପଣ MediMitra ର\nTerms of Service ଏବଂ Privacy Policy ରେ ସମ୍ମତି ଦେଉଛନ୍ତି।';

  @override
  String get loginUnableContinueGuest => 'ଗେଷ୍ଟ ଭାବେ ଚାଲୁ ରଖି ପାରିଲୁ ନାହିଁ।';

  @override
  String get loginEnterMobileNumber => 'ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ।';

  @override
  String get loginEnterValidMobileNumber =>
      'ବୈଧ 10-ଡିଜିଟ୍ ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ।';

  @override
  String get loginOtpSent => 'OTP ପଠାଗଲା।';

  @override
  String get loginFailedSendOtp => 'OTP ପଠାଇବାରେ ବିଫଳ।';

  @override
  String get loginEnterValidEmail => 'ବୈଧ ଇମେଲ ଦିଅନ୍ତୁ।';

  @override
  String get loginPasswordMinChars => 'ପାସୱାର୍ଡ କମେ କମ 6 ଅକ୍ଷର ହେବା ଦରକାର।';

  @override
  String get loginEmailPasswordDisabled =>
      'Firebase Console ରେ Email/Password ସାଇନ୍-ଇନ୍ ନିଷ୍କ୍ରିୟ।';

  @override
  String get loginAccountExistsTryLogin =>
      'ଆକାଉଣ୍ଟ ପୂର୍ବରୁ ଅଛି। ଲଗଇନ୍ କରି ଦେଖନ୍ତୁ।';

  @override
  String get loginWeakPassword => 'ପାସୱାର୍ଡ ଦୁର୍ବଳ (କମେ କମ 6 ଅକ୍ଷର)।';

  @override
  String get loginIncorrectPassword => 'ଭୁଲ ପାସୱାର୍ଡ।';

  @override
  String get loginInvalidEmail => 'ଅବୈଧ ଇମେଲ।';

  @override
  String get loginLoginFailed => 'ଲଗଇନ୍ ବିଫଳ।';

  @override
  String get otpVerifyNumber => 'ନମ୍ବର ଯାଞ୍ଚ କରନ୍ତୁ';

  @override
  String get otpSentTo => 'ଆମେ 6-ଡିଜିଟ୍ କୋଡ୍ ପଠାଇଛୁ';

  @override
  String get otpHaventReceived => 'କୋଡ୍ ମିଳିଲା ନାହିଁ?';

  @override
  String get otpResendCode => 'କୋଡ୍ ପୁଣି ପଠାନ୍ତୁ';

  @override
  String get otpVerifyProceed => 'ଯାଞ୍ଚ କରି ଆଗକୁ ଯାଆନ୍ତୁ';

  @override
  String get otpVerifying => 'ଯାଞ୍ଚ ହେଉଛି...';

  @override
  String get otpEnter6Digit => '6-ଡିଜିଟ୍ OTP ଦିଅନ୍ତୁ।';

  @override
  String get otpInvalid => 'ଅବୈଧ OTP।';

  @override
  String get otpVerificationFailed => 'OTP ଯାଞ୍ଚ ବିଫଳ।';

  @override
  String get otpFailedResend => 'କୋଡ୍ ପୁଣି ପଠାଇବାରେ ବିଫଳ।';

  @override
  String get otpCodeResent => 'କୋଡ୍ ପୁଣି ପଠାଗଲା।';

  @override
  String get otpSafetyFirst => 'ସୁରକ୍ଷା ପ୍ରଥମ';

  @override
  String get otpSafetyNote =>
      'MediMitra ର ଏନକ୍ରିପ୍‌ସନ୍ ସହିତ ଆପଣଙ୍କ ସ୍ୱାସ୍ଥ୍ୟ ରେକର୍ଡକୁ ସୁରକ୍ଷିତଭାବେ ଯୋଡନ୍ତୁ।';

  @override
  String get communityOutbreakAlerts => 'ସମୁଦାୟ ଆଉଟ୍‌ବ୍ରେକ୍ ସତର୍କତା';

  @override
  String get outbreakPrivacyNote =>
      'ଗୋପନୀୟତା-ପ୍ରଥମ: କେବଳ PIN3 ଏବଂ ଦିନ ଅନୁଯାୟୀ ସମୁଦାୟ ଲକ୍ଷଣ ଗଣନା। ନାମ, ଚାଟ୍ ଟେକ୍ସଟ୍, GPS କିମ୍ବା ସଠିକ୍ ଟାଇମ୍‌ଷ୍ଟାମ୍ପ ନୁହେଁ।';

  @override
  String get regionNotSet => 'ଅଞ୍ଚଳ: ସେଟ୍ ହୋଇନାହିଁ';

  @override
  String regionPin3Line(Object region) {
    return 'ଅଞ୍ଚଳ: $region (PIN3)';
  }

  @override
  String get set => 'ସେଟ୍';

  @override
  String get setAreaPin3Title => 'ଆପଣଙ୍କ ଅଞ୍ଚଳ (PIN3) ସେଟ୍ କରନ୍ତୁ';

  @override
  String get setAreaPin3Body =>
      'ଆପଣଙ୍କ PIN କୋଡ୍ ଦିଅନ୍ତୁ। ଆମେ କେବଳ ପ୍ରଥମ 3 ଡିଜିଟ୍ (ମୋଟା ଅଞ୍ଚଳ) ସଂରକ୍ଷଣ କରୁ।';

  @override
  String get pinExampleHint => 'ଉଦାହରଣ: 411001';

  @override
  String get enterFirst3DigitsPin =>
      'ଆପଣଙ୍କ PIN ର କମେ କମ ପ୍ରଥମ 3 ଡିଜିଟ୍ ଦିଅନ୍ତୁ।';

  @override
  String get unableToSaveRegion => 'ଅଞ୍ଚଳ ସେଭ୍ କରି ପାରିଲୁ ନାହିଁ।';

  @override
  String get setPin3ToSeeAlerts =>
      'ଆପଣଙ୍କ ଅଞ୍ଚଳ ପାଇଁ ଆଲର୍ଟ ଦେଖିବାକୁ PIN3 ସେଟ୍ କରନ୍ତୁ।';

  @override
  String get noAlertsToday => 'ଆଜି ଆପଣଙ୍କ ଅଞ୍ଚଳ ପାଇଁ କୌଣସି ଆଲର୍ଟ ନାହିଁ।';

  @override
  String get prevention => 'ପ୍ରତିରୋଧ';

  @override
  String get outbreakLevelHighRisk => 'ଉଚ୍ଚ ଜୋଖିମ';

  @override
  String get outbreakLevelWarning => 'ସଚେତନତା';

  @override
  String get outbreakLevelWatch => 'ନଜର';

  @override
  String get outbreakLevelNone => 'କିଛି ନୁହେଁ';

  @override
  String get back => 'ପଛକୁ';

  @override
  String get next => 'ପରବର୍ତ୍ତୀ';

  @override
  String get couldNotSaveConsent =>
      'ଆପଣଙ୍କ ସମ୍ମତି ସେଭ୍ କରି ପାରିଲୁ ନାହିଁ। ଦୟାକରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।';

  @override
  String get termsSigningTitle => 'Terms of Service';

  @override
  String get termsSigningIntro =>
      'ଲକ୍ଷଣ ମୂଲ୍ୟାଙ୍କନ ବ୍ୟବହାର ପୂର୍ବରୁ, ଦୟାକରି Terms of Service ଏବଂ Privacy Policy ଗ୍ରହଣ କରନ୍ତୁ। ଦୟାକରି ଧ୍ୟାନ ଦିଅନ୍ତୁ:';

  @override
  String get termsBulletNotDiagnosisTitle => 'ଫଳାଫଳ ଡାୟାଗ୍ନୋସିସ୍ ନୁହେଁ।';

  @override
  String get termsBulletNotDiagnosisBody =>
      ' ଏହା କେବଳ ସୂଚନା ପାଇଁ; ଯୋଗ୍ୟ ଚିକିତ୍ସା ମତାମତ ନୁହେଁ।';

  @override
  String get termsBulletNoEmergencyTitle =>
      'ଆପାତକାଳୀନ ସ୍ଥିତିରେ ବ୍ୟବହାର କରନ୍ତୁ ନାହିଁ।';

  @override
  String get termsBulletNoEmergencyBody =>
      ' ଜରୁରୀ ଅବସ୍ଥା ହେଲେ ତୁରନ୍ତ ଆପଣଙ୍କ ଆପାତକାଳୀନ ନମ୍ବରକୁ ଫୋନ୍ କରନ୍ତୁ।';

  @override
  String get termsBulletDataSafeTitle => 'ଆପଣଙ୍କ ତଥ୍ୟ ସୁରକ୍ଷିତ।';

  @override
  String get termsBulletDataSafeBody =>
      ' ଆପଣ ଦିଆଥିବା ସୂଚନା ଶେୟାର କରାଯିବ ନାହିଁ କିମ୍ବା ଆପଣଙ୍କୁ ଚିହ୍ନଟ କରିବାକୁ ବ୍ୟବହାର ହେବ ନାହିଁ।';

  @override
  String get termsConsentTermsPrefix => 'ମୁଁ ପଢିଛି ଏବଂ ଗ୍ରହଣ କରୁଛି ';

  @override
  String get termsConsentTermsLink => 'Terms of Service';

  @override
  String get termsConsentTermsSuffix => '.';

  @override
  String get termsConsentPrivacyPrefix =>
      'ମୁଁ ମୋର ସ୍ୱାସ୍ଥ୍ୟ ସୂଚନା ସାକ୍ଷାତ୍କାର ପାଇଁ ବ୍ୟବହାର କରିବାକୁ ସମ୍ମତ। ଅଧିକ ସୂଚନା ';

  @override
  String get termsConsentPrivacyLink => 'Privacy Policy';

  @override
  String get termsConsentPrivacySuffix => 'ରେ ଅଛି।';

  @override
  String get quickQuestions => 'ଦ୍ରୁତ ପ୍ରଶ୍ନ';

  @override
  String get typeAQuestionHint => 'ଏକ ପ୍ରଶ୍ନ ଲେଖନ୍ତୁ…';

  @override
  String get talkToMaya => 'ମାୟା ସହ କଥାହୁଅନ୍ତୁ';

  @override
  String get womensHealthHubTitle => 'Women’s Health Hub';

  @override
  String get womensHealthHubWelcome => 'ଆପଣଙ୍କ ସ୍ୱାସ୍ଥ୍ୟ ଯାତ୍ରାକୁ ସ୍ୱାଗତ';

  @override
  String get womensHealthHubSubtitle =>
      'ସମ୍ପଦ ଅନ୍ୱେଷଣ ଏବଂ ବ୍ୟକ୍ତିଗତ ଯତ୍ନ ପାଇଁ ଏକ ବିଭାଗ ବାଛନ୍ତୁ।';

  @override
  String get menstrualHealth => 'ମାସିକ ସ୍ୱାସ୍ଥ୍ୟ';

  @override
  String get pregnancyAndMaternal => 'ଗର୍ଭଧାରଣ & ମାତୃତ୍ୱ';

  @override
  String get breastHealth => 'ଷଣ୍ଠି/ସ୍ତନ ସ୍ୱାସ୍ଥ୍ୟ';

  @override
  String get comingSoon => 'ଶୀଘ୍ର ଆସୁଛି';

  @override
  String get womensHealthHubTagline => 'MEDIMITRA WELLNESS';

  @override
  String get womensHealthCategoryMenstrualDescription =>
      'ଆପଣଙ୍କ ମାସିକ ଚକ୍ରକୁ ବୁଝନ୍ତୁ,\nସ୍ୱଚ୍ଛତା ଶିଖନ୍ତୁ ଏବଂ\nପିରିଅଡ୍‌ସ ସହଜରେ ପରିଚାଳନା କରନ୍ତୁ।';

  @override
  String get womensHealthCategoryPregnancyDescription =>
      'ସୁସ୍ଥ ଗର୍ଭଧାରଣ ପାଇଁ ବିଶେଷଜ୍ଞ ମାର୍ଗଦର୍ଶନ,\nପୋଷଣ ଟିପ୍‌ସ ଏବଂ\nସୁରକ୍ଷିତ ପ୍ରସବ ସହାୟତା।';

  @override
  String get womensHealthCategoryBreastDescription =>
      'ସରଳ ସ୍ୱ-ପରୀକ୍ଷା ମାର୍ଗଦର୍ଶନ\nଏବଂ ସଚେତନତା ଟିପ୍‌ସ\nଶୀଘ୍ର ଚିହ୍ନଟ ଓ ଯତ୍ନ ପାଇଁ।';

  @override
  String get recommended => 'ପରାମର୍ଶିତ';

  @override
  String get explore => 'ଅନ୍ୱେଷଣ କରନ୍ତୁ';

  @override
  String get menstrualScreenTitle => 'ମାସିକ ସ୍ୱାସ୍ଥ୍ୟ';

  @override
  String get menstrualWhatIsMenstruationTitle => 'ମାସିକ ରଜସ୍ରାବ କଣ?';

  @override
  String get menstrualWhatIsMenstruationBody =>
      'ମାସିକ ହେଉଛି ଗର୍ଭାଶୟର ଭିତର ପରତ ଖସିବାର ସ୍ୱାଭାବିକ ମାସିକ ପ୍ରକ୍ରିୟା। ଏହା ସୁସ୍ଥ ପ୍ରଜନନ ପ୍ରଣାଳୀର ଚିହ୍ନ ଏବଂ ବିକାଶର ସାଧାରଣ ଅଂଶ।';

  @override
  String get menstrualQuote => 'ପ୍ରଜନନ ଓ ଜୀବନର ଚକ୍ର';

  @override
  String get menstrualWhatIsNormalTitle => 'କଣ ସାଧାରଣ?';

  @override
  String get menstrualNormalItem1 => 'ଚକ୍ର 21 ରୁ 35 ଦିନ ମଧ୍ୟରେ';

  @override
  String get menstrualNormalItem2 => 'ରକ୍ତସ୍ରାବ 3 ରୁ 7 ଦିନ';

  @override
  String get menstrualNormalItem3 => 'ହାଲୁକା ରୁ ମଧ୍ୟମ ଅସୁବିଧା/ବେଦନା';

  @override
  String get menstrualWarningSignsTitle => 'ସତର୍କ ସଙ୍କେତ';

  @override
  String get menstrualWarningItem1 =>
      'ଅଧିକ ରକ୍ତସ୍ରାବ (ପ୍ରତି 1–2 ଘଣ୍ଟାରେ ପ୍ୟାଡ୍ ବଦଳାଇବା)';

  @override
  String get menstrualWarningItem2 => 'ଦୈନନ୍ଦିନ କାମକୁ ବାଧା ଦେଉଥିବା ତୀବ୍ର ବେଦନା';

  @override
  String get menstrualWarningItem3 =>
      'ଚକ୍ର ସଦା 21 ଦିନ ଠାରୁ କମ୍ କିମ୍ବା 38 ଦିନ ଠାରୁ ଅଧିକ';

  @override
  String get menstrualHygieneTipsTitle => 'ସ୍ୱଚ୍ଛତା ଟିପ୍‌ସ';

  @override
  String get menstrualTipChangeRegularlyTitle => 'ନିୟମିତ ଭାବେ ବଦଳାନ୍ତୁ';

  @override
  String get menstrualTipChangeRegularlySubtitle =>
      'ସଂକ୍ରମଣ ଝୁଁକି କମେଇବାକୁ ପ୍ୟାଡ୍/ଟ୍ୟାମ୍ପନ୍ ନିୟମିତ ବଦଳାନ୍ତୁ।';

  @override
  String get menstrualTipCleanHandsTitle => 'ହାତ ସଫା ରଖନ୍ତୁ';

  @override
  String get menstrualTipCleanHandsSubtitle =>
      'ପ୍ୟାଡ୍ ବଦଳାଇବା ପୂର୍ବରୁ/ପରେ ହାତ ଧୁଅନ୍ତୁ।';

  @override
  String get menstrualTipStayDryTitle => 'ଶୁଖିଲା ରଖନ୍ତୁ';

  @override
  String get menstrualTipStayDrySubtitle =>
      'ସଫା ଏବଂ ଶୁଖିଲା ଅନ୍ତର୍ବସ୍ତ୍ର ବ୍ୟବହାର କରନ୍ତୁ।';

  @override
  String get menstrualMythsFactsTitle => 'ଭ୍ରାନ୍ତି ବନାମ ସତ୍ୟ';

  @override
  String get menstrualMyth1 => 'ଭ୍ରାନ୍ତି: ମାସିକ ସମୟରେ ନହାଇବା ଉଚିତ୍ ନୁହେଁ।';

  @override
  String get menstrualFact1 => 'ସତ୍ୟ: ସ୍ୱଚ୍ଛତା ପାଇଁ ନହାଇବା ଉପକାରୀ।';

  @override
  String get menstrualMyth2 => 'ଭ୍ରାନ୍ତି: ମାସିକ ଅର୍ଥ ଅସୁସ୍ଥ।';

  @override
  String get menstrualFact2 =>
      'ସତ୍ୟ: ଏହା ସାଧାରଣ ଜୈବିକ ପ୍ରକ୍ରିୟା। ଯଦି ଅଧିକ ବେଦନା/ଅନିୟମିତତା ଥାଏ, ଡାକ୍ତରଙ୍କୁ ପଚାରନ୍ତୁ।';

  @override
  String get chatHeaderTitle => 'ମାୟା';

  @override
  String get chatHeaderStatusOnline => 'ଅନଲାଇନ୍';

  @override
  String get chatToday => 'ଆଜି';

  @override
  String get chatQuickChipCheckFever => 'ଜ୍ୱର ଯାଞ୍ଚ';

  @override
  String get chatQuickPromptCheckFever => 'ମୋତେ ଜ୍ୱର ଅଛି। କଣ କରିବି?';

  @override
  String get chatQuickChipWomensHealth => 'ମହିଳା ସ୍ୱାସ୍ଥ୍ୟ';

  @override
  String get chatQuickPromptWomensHealth =>
      'ମାସିକ/ମହିଳା ସ୍ୱାସ୍ଥ୍ୟ ବିଷୟରେ ସହାୟତା କରନ୍ତୁ।';

  @override
  String get chatQuickChipFirstAid => 'ପ୍ରଥମ ସହାୟତା';

  @override
  String get chatQuickPromptFirstAid => 'କାଟ/ପୋଡ଼ା/ମୋଚ ହେଲେ ପ୍ରଥମେ କଣ କରିବି?';

  @override
  String get chatQuickChipChildCare => 'ଶିଶୁ ଯତ୍ନ';

  @override
  String get chatQuickPromptChildCare => 'ଶିଶୁର ଜ୍ୱର/କାଶି ହେଲେ କଣ କରିବି?';

  @override
  String get chatInputHintAskMeAnything => 'କିଛି ପଚାରନ୍ତୁ…';

  @override
  String get profileSaved => 'ପ୍ରୋଫାଇଲ୍ ସେଭ୍ ହେଲା';

  @override
  String get saving => 'ସେଭ୍ ହେଉଛି…';

  @override
  String get saveChanges => 'ପରିବର୍ତ୍ତନ ସେଭ୍ କରନ୍ତୁ';

  @override
  String get profileTopBarTitle => 'ପ୍ରୋଫାଇଲ୍ ସେଟିଂସ୍';

  @override
  String get profileHeaderSubtitle => 'ଉପଯୋଗକର୍ତ୍ତା ପ୍ରୋଫାଇଲ୍';

  @override
  String get profileSectionFullName => 'ପୁରା ନାମ';

  @override
  String get profileHintFullName => 'ଉଦାହରଣ: ରାହୁଲ ଶର୍ମା';

  @override
  String get profileSectionAge => 'ବୟସ';

  @override
  String get profileHintAge => 'ଆପଣଙ୍କ ବୟସ ଦିଅନ୍ତୁ';

  @override
  String get profileSectionGender => 'ଲିଙ୍ଗ';

  @override
  String get profileGenderMale => 'ପୁରୁଷ';

  @override
  String get profileGenderFemale => 'ମହିଳା';

  @override
  String get profileGenderOther => 'ଅନ୍ୟ';

  @override
  String get profileChronicConditions => 'ଦୀର୍ଘକାଳୀନ ଅବସ୍ଥା';

  @override
  String get profileConditionsBadge => 'ଦ୍ୱିଭାଷୀ';

  @override
  String get conditionDiabetesTitle => 'ଡାୟାବେଟିଜ୍';

  @override
  String get conditionDiabetesSubtitle => 'ମଧୁମେହ (ସୁଗର)';

  @override
  String get conditionBpHeartTitle => 'BP & ହୃଦୟ';

  @override
  String get conditionBpHeartSubtitle => 'ରକ୍ତଚାପ / ହୃଦୟ';

  @override
  String get conditionAsthmaTitle => 'ଆସ୍ଥମା';

  @override
  String get conditionAsthmaSubtitle => 'ଶ୍ୱାସକଷ୍ଟ';

  @override
  String get conditionThyroidTitle => 'ଥାଇରଏଡ୍';

  @override
  String get conditionThyroidSubtitle => 'ଥାଇରଏଡ୍';

  @override
  String get conditionTbTitle => 'TB';

  @override
  String get conditionTbSubtitle => 'କ୍ଷୟ ରୋଗ';

  @override
  String get conditionNoneTitle => 'କିଛି ନୁହେଁ';

  @override
  String get conditionNoneSubtitle => 'କୌଣସି ଅବସ୍ଥା ନାହିଁ';

  @override
  String get helpFaqBotGreeting =>
      'ହାଇ! ମୁଁ MediMitra Help। ଲକ୍ଷଣ ଯାଞ୍ଚ, ଭଏସ୍ ଇନପୁଟ୍, ଆଉଟ୍‌ବ୍ରେକ୍ ଆଲର୍ଟ, କ୍ଲିନିକ୍, ଲଗଇନ୍ କିମ୍ବା ଗୋପନୀୟତା ବିଷୟରେ ଯେକୌଣସି ପ୍ରଶ୍ନ କରନ୍ତୁ।\n\nଟିପ୍ପଣୀ: ଏହା ଚିକିତ୍ସା ପରାମର୍ଶ ନୁହେଁ। ଆପାତକାଳୀନ ଅବସ୍ଥା ହେଲେ, ସ୍ଥାନୀୟ ଆପାତକାଳୀନ ସେବାକୁ ଯୋଗାଯୋଗ କରନ୍ତୁ।';

  @override
  String get helpFaqSuggestionCheckSymptoms => 'ଲକ୍ଷଣ କିପରି ଯାଞ୍ଚ କରିବି?';

  @override
  String get helpFaqSuggestionVoiceSymptoms => 'ଭଏସ୍ ଲକ୍ଷଣ କିପରି କାମ କରେ?';

  @override
  String get helpFaqSuggestionOutbreakAlert => 'ଆଉଟ୍‌ବ୍ରେକ୍ ଆଲର୍ଟ କ’ଣ?';

  @override
  String get helpFaqSuggestionNearbyClinics => 'ନିକଟସ୍ଥ କ୍ଲିନିକ୍ କିପରି ଖୋଜିବି?';

  @override
  String get helpFaqSuggestionOtpLogin => 'OTP ଲଗଇନ୍ କିପରି କାମ କରେ?';

  @override
  String get helpFaqSuggestionDataSafe => 'ମୋ ତଥ୍ୟ ସୁରକ୍ଷିତ କି?';

  @override
  String get helpFaqSuggestionGuestMode =>
      'ଲଗଇନ୍ ବିନା ଆପ୍ ବ୍ୟବହାର କରିପାରିବି କି?';

  @override
  String get helpFaqSuggestionChangeLanguage => 'ଭାଷା କିପରି ବଦଳାଇବି?';

  @override
  String get helpFaqSuggestionDarkMode => 'ଡାର୍କ ମୋଡ୍ କିପରି ଅନ କରିବି?';

  @override
  String get helpFaqReplySymptomChecking =>
      'ଲକ୍ଷଣ ଯାଞ୍ଚ ପାଇଁ:\n1) Chat / Symptom Checker ଖୋଲନ୍ତୁ\n2) ଆପଣଙ୍କ ଲକ୍ଷଣ ଟାଇପ୍ କରନ୍ତୁ (କିମ୍ବା ଭଏସ୍ ବ୍ୟବହାର କରନ୍ତୁ)\n3) ପରବର୍ତ୍ତୀ ପ୍ରଶ୍ନଗୁଡିକର ଉତ୍ତର ଦିଅନ୍ତୁ\n\nMediMitra ସମ୍ଭାବ୍ୟ କାରଣ ଏବଂ ପରବର୍ତ୍ତୀ ପଦକ୍ଷେପ ଦେଖାଇବ। ଗୁରୁତର ଲକ୍ଷଣ (ଛାତିବେଦନା, ଶ୍ୱାସକଷ୍ଟ, ବେହୋଶ) ଥାକିଲେ ତୁରନ୍ତ ଚିକିତ୍ସା ନିଅନ୍ତୁ।';

  @override
  String get helpFaqReplyVoiceSymptoms =>
      'ଭଏସ୍ ଲକ୍ଷଣ: ମାଇକ୍ ଟାପ୍ କରନ୍ତୁ, ସ୍ପଷ୍ଟଭାବେ ଲକ୍ଷଣ କହନ୍ତୁ, ଏବଂ ଆପ୍ ଏହାକୁ ଟେକ୍ସଟ୍ କରି ବିଶ୍ଳେଷଣ କରିବ।\n\nଟିପ୍‌ସ: ଏକ ସମୟରେ ଗୋଟିଏ ଲକ୍ଷଣ କହନ୍ତୁ, ସରଳ ଶବ୍ଦ ବ୍ୟବହାର କରନ୍ତୁ (\"ଜ୍ୱର\", \"କାଶ\") ଏବଂ ଅନୁରୋଧ ହେଲେ ମାଇକ୍ ପରମିସନ୍ ଦିଅନ୍ତୁ।';

  @override
  String get helpFaqReplyOutbreakAlert =>
      'ଆଉଟ୍‌ବ୍ରେକ୍ ଆଲର୍ଟ ଆପଣଙ୍କ ଅଞ୍ଚଳରେ କିଛି ଲକ୍ଷଣ ଟ୍ରେଣ୍ଡ ହେଉଛି କି ନାହିଁ ଦେଖାଏ। ଏହା ଗୋପନୀୟ, ସମୁଦାୟ ପ୍ୟାଟର୍ନ ଉପରେ ଆଧାରିତ ଏବଂ ସଚେତନତା ପାଇଁ (ଡାୟାଗ୍ନୋସିସ୍ ପାଇଁ ନୁହେଁ)।\n\nOutbreak ବିଭାଗରୁ ଇନ୍‌ସାଇଟ୍‌ସ ଦେଖିପାରିବେ।';

  @override
  String get helpFaqReplyNearbyClinics =>
      'ନିକଟସ୍ଥ କ୍ଲିନିକ୍: Clinic Locator ଖୋଲନ୍ତୁ ଏବଂ ଆପଣଙ୍କ ଚାରିପାଖରେ କ୍ଲିନିକ୍‌ସ ଦେଖନ୍ତୁ।\n\nଲୋକେସନ୍ ପରମିସନ୍ ସକ୍ରିୟ ଅଛି କି ନିଶ୍ଚିତ କରନ୍ତୁ।';

  @override
  String get helpFaqReplyOtpLogin =>
      'OTP ଲଗଇନ୍: ଆପଣଙ୍କ 10-ଡିଜିଟ୍ ମୋବାଇଲ୍ ନମ୍ବର ଦିଅନ୍ତୁ; ଆମେ ଏକ ଭେରିଫିକେସନ୍ OTP ପଠାଇବୁ। 6-ଡିଜିଟ୍ OTP ଦେଇ ଆଗକୁ ବଢନ୍ତୁ।\n\nOTP ନାଆସିଲେ, ରିସେଣ୍ଡ ଟାଇମର୍ ସମାପ୍ତ ହେବା ପରେ ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ; ନେଟୱର୍କ ଯାଞ୍ଚ କରନ୍ତୁ।';

  @override
  String get helpFaqReplyGuestMode =>
      'ଗେଷ୍ଟ ମୋଡ୍ ରେ ଆପଣ ଲଗଇନ୍ ବିନା ଆପ୍ ଅନ୍ୱେଷଣ କରିପାରିବେ। କିଛି ପ୍ରୋଫାଇଲ୍-ସେଭ୍ ବୈଶିଷ୍ଟ୍ୟ (ବ୍ୟକ୍ତିଗତ ସେଟିଂସ୍) ଲଗଇନ୍ ପର୍ଯ୍ୟନ୍ତ ସୀମିତ ହୋଇପାରେ।';

  @override
  String get helpFaqReplyPrivacy =>
      'ଆପଣଙ୍କ ଅନୁଭବକୁ ବ୍ୟକ୍ତିଗତ କରିବା ପାଇଁ (ନାମ/ବୟସ/ଲିଙ୍ଗ/ଅବସ୍ଥା) ପ୍ରୋଫାଇଲ୍ ଡାଟା ସୁରକ୍ଷିତଭାବେ ସଂରକ୍ଷିତ ହୁଏ। ଚାଟ୍‌ରେ ସେନ୍ସିଟିଭ୍ ସୂଚନା ଶେୟାର୍ କରନ୍ତୁ ନାହିଁ।\n\nବିସ୍ତୃତ ତଥ୍ୟ ପାଇଁ ଆପ୍‌ର Privacy Policy ଦେଖନ୍ତୁ।';

  @override
  String get helpFaqReplyChangeLanguage =>
      'ଭାଷା ବଦଳାଇବାକୁ: Profile → Language।';

  @override
  String get helpFaqReplyDarkMode =>
      'ଡାର୍କ ମୋଡ୍: Profile → Dark Mode ରେ ଟଗଲ୍ ଅନ/ଅଫ୍ କରନ୍ତୁ।';

  @override
  String get helpFaqReplyContactSupport =>
      'ସପୋର୍ଟ ସହିତ ଯୋଗାଯୋଗ: Contact Us ଖୋଲନ୍ତୁ ଏବଂ ସନ୍ଦେଶ ପଠାନ୍ତୁ। ସମ୍ଭବ ହେଲେ ସ୍କ୍ରିନସଟ୍ ଏବଂ ପଦକ୍ଷେପ ଯୋଗ କରନ୍ତୁ।';

  @override
  String get helpFaqReplyFallback =>
      'ମୁଁ ସହାୟତା କରିପାରିବି: ଲକ୍ଷଣ ଯାଞ୍ଚ, ଭଏସ୍ ଇନପୁଟ୍, ଆଉଟ୍‌ବ୍ରେକ୍ ଆଲର୍ଟ, କ୍ଲିନିକ୍ ଲୋକେଟର୍, OTP ଲଗଇନ୍, ଗୋପନୀୟତା, ଭାଷା ଏବଂ ଡାର୍କ ମୋଡ୍।\n\nଏହିଗୁଡିକ ଚେଷ୍ଟା କରନ୍ତୁ: \"ଲକ୍ଷଣ କିପରି ଯାଞ୍ଚ କରିବି?\", \"ନିକଟସ୍ଥ କ୍ଲିନିକ୍ କିପରି ଖୋଜିବି?\", \"ମୋ ତଥ୍ୟ ସୁରକ୍ଷିତ କି?\"';
}
