// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Telugu (`te`).
class AppLocalizationsTe extends AppLocalizations {
  AppLocalizationsTe([String locale = 'te']) : super(locale);

  @override
  String get appTitle => 'మెడిమిత్రా';

  @override
  String get close => 'మూసివేయి';

  @override
  String get loginTagline =>
      'మీరు మరియు మీ కుటుంబం కోసం సులభమైన ఆరోగ్య సంరక్షణ';

  @override
  String get smsLogin => 'ఎస్‌ఎంఎస్ లాగిన్';

  @override
  String get emailLogin => 'ఇమెయిల్ లాగిన్';

  @override
  String get homeHello => 'హలో,';

  @override
  String get homeThere => 'అక్కడ';

  @override
  String get homeChatCta => 'మా AI హెల్త్ చాట్ సహాయకుడిని అన్వేషించండి';

  @override
  String get homeOurFeatures => 'మా ఫీచర్లు';

  @override
  String get homeHighlights => 'హైలైట్స్';

  @override
  String get homeDisclaimerTitle => 'డిస్క్లెయిమర్';

  @override
  String get homeDisclaimerBody =>
      'MediMitra సమాచార ప్రయోజనాల కోసం మాత్రమే; ఇది వైద్య సలహా కాదు. ఇది డాక్టర్‌ను భర్తీ చేయదు.\nతీవ్రమైన లక్షణాలు లేదా అత్యవసర పరిస్థితి ఉంటే, దయచేసి సమీప ఆసుపత్రిని సందర్శించండి లేదా వెంటనే అత్యవసర సేవలను సంప్రదించండి.';

  @override
  String get featureSymptomChecker => 'లక్షణాల తనిఖీ';

  @override
  String get featureWomensHealth => 'మహిళల ఆరోగ్య అవగాహన';

  @override
  String get featureInsurance => 'బీమా';

  @override
  String get featureAiHealthSummary => 'AI ఆరోగ్య సారాంశం';

  @override
  String get featureReminders => 'రిమైండర్లు';

  @override
  String get featureLocateClinics => 'మీ దగ్గర క్లినిక్‌లు కనుగొనండి';

  @override
  String get promoAiSymptomCheckTitle => 'AI లక్షణ తనిఖీ';

  @override
  String get promoAiSymptomCheckSubtitle =>
      'లక్షణాలను వివరించండి, సెకన్లలో మార్గనిర్దేశం పొందండి.';

  @override
  String get promoVoiceWaveformTitle => 'వాయిస్ + వేవ్‌ఫార్మ్';

  @override
  String get promoVoiceWaveformSubtitle =>
      'వాయిస్ ఇన్‌పుట్‌తో హ్యాండ్స్-ఫ్రీ చాట్.';

  @override
  String get promoProfilePersonalizationTitle => 'ప్రొఫైల్ వ్యక్తిగతీకరణ';

  @override
  String get promoProfilePersonalizationSubtitle =>
      'మెరుగైన సహాయం కోసం వయస్సు, లింగం మరియు పరిస్థితులను సేవ్ చేయండి.';

  @override
  String get promoNearbyClinicsTitle => 'సమీప క్లినిక్‌లు';

  @override
  String get promoNearbyClinicsSubtitle =>
      'మీ ప్రాంతానికి దగ్గర ఆరోగ్య సేవలను కనుగొనండి.';

  @override
  String get settings => 'సెట్టింగ్స్';

  @override
  String get supportAndInformation => 'సపోర్ట్ & సమాచారం';

  @override
  String get notifications => 'నోటిఫికేషన్లు';

  @override
  String get manageYourNotifications => 'మీ నోటిఫికేషన్లను నిర్వహించండి';

  @override
  String get notificationsEnabled => 'నోటిఫికేషన్లు ఆన్ ఉన్నాయి';

  @override
  String get notificationsDisabled => 'నోటిఫికేషన్లు ఆఫ్ ఉన్నాయి';

  @override
  String get couldNotUpdateNotifications => 'నోటిఫికేషన్లు నవీకరించలేకపోయాం';

  @override
  String get darkMode => 'డార్క్ మోడ్';

  @override
  String get toggleDarkTheme => 'డార్క్ థీమ్ ఆన్/ఆఫ్ చేయండి';

  @override
  String get helpAndFaq => 'సహాయం & FAQ';

  @override
  String get getHelpAndAnswers => 'సహాయం మరియు సమాధానాలు పొందండి';

  @override
  String get getInTouchWithSupport => 'సపోర్ట్‌ను సంప్రదించండి';

  @override
  String get aboutMediMitra => 'MediMitra గురించి';

  @override
  String versionLine(Object version) {
    return 'వర్షన్ $version';
  }

  @override
  String get privacyPolicy => 'గోప్యతా విధానం';

  @override
  String get howWeProtectYourData => 'మీ డేటాను మేము ఎలా రక్షిస్తాం';

  @override
  String get termsAndConditions => 'నియమాలు & షరతులు';

  @override
  String get termsConditionsBody =>
      'Terms & Conditions\n\nBy downloading and using this application, you agree to comply with and be bound by these Terms and Conditions. If you do not agree with any part of these terms, you should discontinue using the app.\n\nThis application is designed to provide health-related information and decision-support guidance only. It is not a medical diagnostic tool and does not replace consultation with a qualified doctor or healthcare professional. All information provided by the app is for educational and support purposes, and users must always seek professional medical advice for diagnosis, treatment, or emergencies.\n\nUsers are responsible for providing accurate and honest information while using the app. The guidance generated by the system depends on the inputs provided by the user, and incorrect or incomplete information may lead to inaccurate results. The app should not be used as the sole basis for making medical decisions.\n\nThis application is not intended for emergency situations. In case of severe symptoms such as chest pain, difficulty breathing, loss of consciousness, or heavy bleeding, users must immediately contact local emergency services or visit the nearest hospital.\n\nTo the maximum extent permitted by law, the developers shall not be held liable for any direct or indirect damages arising from the use of this application. Use of the app is entirely at the user’s own risk, and no guarantee is made regarding the accuracy, completeness, or reliability of the information provided.\n\nUse of this application is also governed by our Privacy Policy. By continuing to use the app, you confirm that you have read, understood, and agreed to both the Privacy Policy and these Terms and Conditions.\n\nWe reserve the right to modify or update these Terms and Conditions at any time. Any changes will be displayed within the app, and continued use of the app after such changes indicates acceptance of the updated terms.';

  @override
  String get legalAgreement => 'చట్టపరమైన ఒప్పందం';

  @override
  String get deleteData => 'డేటా తొలగించండి';

  @override
  String get deleteChatsAndSavedSettings =>
      'చాట్లు & సేవ్ చేసిన సెట్టింగ్స్ తొలగించండి';

  @override
  String get logOut => 'లాగ్ అవుట్';

  @override
  String get logoutQuestion => 'లాగ్ అవుట్ చేయాలా?';

  @override
  String get logoutReturnToLogin =>
      'మీరు లాగ్ అవుట్ అయి లాగిన్ స్క్రీన్‌కి తిరిగి వెళ్తారు.';

  @override
  String get chooseAnAction => 'ఒక చర్యను ఎంచుకోండి';

  @override
  String get deleteAccount => 'ఖాతాను తొలగించండి';

  @override
  String get permanentlyDeleteAccount => 'మీ ఖాతాను శాశ్వతంగా తొలగించండి';

  @override
  String get deleteLocalData => 'లోకల్ డేటా తొలగించండి';

  @override
  String get deleteLocalDataOnDevice =>
      'ఈ డివైస్‌లోని చాట్లు & సేవ్ చేసిన సెట్టింగ్స్ తొలగించండి';

  @override
  String get clearLocalDataQuestion => 'లోకల్ డేటాను క్లియర్ చేయాలా?';

  @override
  String get clearLocalDataBody =>
      'ఇది ఈ డివైస్‌లో లోకల్‌గా సేవ్ చేసిన యాప్ డేటాను (సేవ్ చేసిన సెట్టింగ్స్, క్యాష్ చేసిన ప్రొఫైల్ ఫీల్డ్స్, మరియు మెమరీలోని చాట్ హిస్టరీ) తొలగిస్తుంది.\n\nఅన్ని మార్పులు అమలులో రావడానికి యాప్‌ని రీస్టార్ట్ చేయాల్సి ఉండొచ్చు.';

  @override
  String get clear => 'క్లియర్';

  @override
  String get localDataCleared => 'లోకల్ డేటా క్లియర్ అయింది';

  @override
  String get couldNotClearLocalData => 'లోకల్ డేటాను క్లియర్ చేయలేకపోయాం';

  @override
  String get accountDeletionNotAvailable =>
      'ఈ ప్లాట్‌ఫార్మ్‌లో ఖాతా తొలగింపు అందుబాటులో లేదు';

  @override
  String get noSignedInAccountFound => 'సైన్-ఇన్ అయిన ఖాతా కనబడలేదు';

  @override
  String get deleteAccountQuestion => 'ఖాతాను తొలగించాలా?';

  @override
  String get deleteAccountBody =>
      'ఇది మీ ఖాతాను శాశ్వతంగా తొలగిస్తుంది. మీరు ఈ డివైస్ నుండి లాగ్ అవుట్ అవుతారు.';

  @override
  String get deletingAccount => 'ఖాతా తొలగిస్తోంది...';

  @override
  String get pleaseLoginAgainThenDelete =>
      'దయచేసి మళ్లీ లాగిన్ చేసి, తరువాత ఖాతాను తొలగించండి';

  @override
  String get couldNotDeleteAccount => 'ఖాతాను తొలగించలేకపోయాం';

  @override
  String get networkSlowTryAgain =>
      'నెట్‌వర్క్ నెమ్మదిగా ఉంది. మళ్లీ ప్రయత్నించండి.';

  @override
  String get defaultUser => 'వినియోగదారు';

  @override
  String userIdLine(Object id) {
    return 'వినియోగదారు ID: $id';
  }

  @override
  String get clinicsNearYou => 'మీ దగ్గర క్లినిక్‌లు';

  @override
  String get refresh => 'రిఫ్రెష్';

  @override
  String get recenter => 'మళ్లీ కేంద్రానికి';

  @override
  String resultsCount(Object count) {
    return 'ఫలితాలు ($count)';
  }

  @override
  String get nearbyClinics => 'సమీప క్లినిక్‌లు';

  @override
  String get call => 'కాల్';

  @override
  String get navigate => 'నావిగేట్';

  @override
  String get unableToOpenDialer => 'డయలర్ తెరవలేకపోయాం';

  @override
  String get unableToOpenMaps => 'మ్యాప్స్ తెరవలేకపోయాం';

  @override
  String get radius => 'వ్యాసార్థం';

  @override
  String get tryAgain => 'మళ్లీ ప్రయత్నించండి';

  @override
  String get openLocationSettings => 'లోకేషన్ సెట్టింగ్స్ తెరవండి';

  @override
  String get locationServicesDisabled =>
      'లోకేషన్ సర్వీసులు ఆఫ్ ఉన్నాయి. దయచేసి GPS ఆన్ చేయండి.';

  @override
  String get locationPermissionDenied => 'లోకేషన్ అనుమతి నిరాకరించబడింది.';

  @override
  String get locationPermissionDeniedForever =>
      'లోకేషన్ అనుమతి శాశ్వతంగా నిరాకరించబడింది. సెట్టింగ్స్ నుండి ఆన్ చేయండి.';

  @override
  String get chooseLanguage => 'భాషను ఎంచుకోండి';

  @override
  String get cancel => 'రద్దు';

  @override
  String get save => 'సేవ్';

  @override
  String get contactUs => 'మమ్మల్ని సంప్రదించండి';

  @override
  String get needHelp => 'సహాయం కావాలా?';

  @override
  String get contactSubtitle => 'మాకు సందేశం పంపండి, మా బృందం స్పందిస్తుంది.';

  @override
  String supportEmailLine(Object email) {
    return 'సపోర్ట్ ఇమెయిల్: $email';
  }

  @override
  String get typicalResponseLine => 'సాధారణ స్పందన: 24 గంటల్లో';

  @override
  String get language => 'భాష';

  @override
  String languageSetTo(Object language) {
    return 'భాష $language గా సెట్ అయింది';
  }

  @override
  String get fullName => 'పూర్తి పేరు';

  @override
  String get yourName => 'మీ పేరు';

  @override
  String get email => 'ఇమెయిల్';

  @override
  String get emailHint => 'name@example.com';

  @override
  String get phoneOptional => 'ఫోన్ (ఐచ్చికం)';

  @override
  String get yourMobileNumber => 'మీ మొబైల్ నంబర్';

  @override
  String get subject => 'విషయం';

  @override
  String get subjectHint => 'ఇది ఏ విషయం గురించి?';

  @override
  String get message => 'సందేశం';

  @override
  String get messageHint => 'మీ సమస్య లేదా ప్రశ్నను వివరించండి';

  @override
  String get send => 'పంపండి';

  @override
  String get sentSuccess => 'పంపాం! మేము త్వరలో స్పందిస్తాం.';

  @override
  String get required => 'అవసరం';

  @override
  String get enterValidEmail => 'చెల్లుబాటు అయ్యే ఇమెయిల్ నమోదు చేయండి';

  @override
  String get writeMoreDetail => 'దయచేసి మరికొంత వివరంగా రాయండి';

  @override
  String get couldNotOpenEmailApp => 'ఇమెయిల్ యాప్‌ను తెరవలేకపోయాం.';

  @override
  String get couldNotSendTryLater => 'పంపలేకపోయాం. తర్వాత మళ్లీ ప్రయత్నించండి.';

  @override
  String get tipNoShareOtp =>
      'టిప్: ఇక్కడ పాస్‌వర్డ్‌లు లేదా OTPలను పంచుకోకండి.';

  @override
  String get loginLanguageLabel => 'English / తెలుగు';

  @override
  String get loginHeroSubtitle => 'మీ ఆరోగ్య సహచరుడు';

  @override
  String get loginMobileNumberLabel => 'మొబైల్ నంబర్';

  @override
  String get loginMobileHint => '00000 00000';

  @override
  String get loginEmailLabel => 'ఇమెయిల్ చిరునామా';

  @override
  String get loginPasswordLabel => 'పాస్‌వర్డ్';

  @override
  String get loginPasswordHint => 'పాస్‌వర్డ్ నమోదు చేయండి';

  @override
  String get loginPleaseWait => 'దయచేసి వేచి ఉండండి...';

  @override
  String get loginSendOtp => 'OTP పంపండి';

  @override
  String get loginContinue => 'కొనసాగించండి';

  @override
  String get loginSendingOtp => 'OTP పంపుతోంది...';

  @override
  String get loginOr => 'లేదా';

  @override
  String get loginContinueAsGuest => 'అతిథిగా కొనసాగించండి';

  @override
  String get loginAgreementText =>
      'లాగిన్ చేయడం ద్వారా, మీరు MediMitra యొక్క\nTerms of Service మరియు Privacy Policy కి అంగీకరిస్తారు.';

  @override
  String get loginUnableContinueGuest => 'అతిథిగా కొనసాగించలేకపోయాం.';

  @override
  String get loginEnterMobileNumber => 'మొబైల్ నంబర్ నమోదు చేయండి.';

  @override
  String get loginEnterValidMobileNumber =>
      'చెల్లుబాటు అయ్యే 10-అంకెల మొబైల్ నంబర్ నమోదు చేయండి.';

  @override
  String get loginOtpSent => 'OTP పంపబడింది.';

  @override
  String get loginFailedSendOtp => 'OTP పంపడం విఫలమైంది.';

  @override
  String get loginEnterValidEmail => 'చెల్లుబాటు అయ్యే ఇమెయిల్ నమోదు చేయండి.';

  @override
  String get loginPasswordMinChars => 'పాస్‌వర్డ్ కనీసం 6 అక్షరాలు ఉండాలి.';

  @override
  String get loginEmailPasswordDisabled =>
      'Firebase Console లో Email/Password సైన్-ఇన్ ఆఫ్ చేయబడింది.';

  @override
  String get loginAccountExistsTryLogin =>
      'ఖాతా ఇప్పటికే ఉంది. లాగిన్ చేసి చూడండి.';

  @override
  String get loginWeakPassword =>
      'పాస్‌వర్డ్ బలహీనంగా ఉంది (కనీసం 6 అక్షరాలు).';

  @override
  String get loginIncorrectPassword => 'తప్పు పాస్‌వర్డ్.';

  @override
  String get loginInvalidEmail => 'చెల్లని ఇమెయిల్.';

  @override
  String get loginLoginFailed => 'లాగిన్ విఫలమైంది.';

  @override
  String get otpVerifyNumber => 'నంబర్‌ను నిర్ధారించండి';

  @override
  String get otpSentTo => 'మేము 6-అంకెల కోడ్ పంపాము';

  @override
  String get otpHaventReceived => 'కోడ్ రాలేదా?';

  @override
  String get otpResendCode => 'కోడ్ మళ్లీ పంపండి';

  @override
  String get otpVerifyProceed => 'నిర్ధారించి కొనసాగించండి';

  @override
  String get otpVerifying => 'నిర్ధారిస్తోంది...';

  @override
  String get otpEnter6Digit => '6-అంకెల OTP నమోదు చేయండి.';

  @override
  String get otpInvalid => 'చెల్లని OTP.';

  @override
  String get otpVerificationFailed => 'OTP నిర్ధారణ విఫలమైంది.';

  @override
  String get otpFailedResend => 'కోడ్ మళ్లీ పంపడం విఫలమైంది.';

  @override
  String get otpCodeResent => 'కోడ్ మళ్లీ పంపబడింది.';

  @override
  String get otpSafetyFirst => 'భద్రత ముందుగా';

  @override
  String get otpSafetyNote =>
      'MediMitra ఎన్‌క్రిప్షన్‌తో మీ హెల్త్ రికార్డ్స్‌ను సురక్షితంగా కనెక్ట్ చేయండి.';

  @override
  String get communityOutbreakAlerts => 'కమ్యూనిటీ అవుట్‌బ్రేక్ అలర్ట్స్';

  @override
  String get outbreakPrivacyNote =>
      'గోప్యత ముందుగా: PIN3 మరియు రోజుకు సమిష్టి లక్షణాల సంఖ్యలు మాత్రమే. పేర్లు, చాట్ టెక్స్ట్, GPS లేదా ఖచ్చితమైన టైమ్‌స్టాంప్స్ కాదు.';

  @override
  String get regionNotSet => 'ప్రాంతం: సెట్ చేయలేదు';

  @override
  String regionPin3Line(Object region) {
    return 'ప్రాంతం: $region (PIN3)';
  }

  @override
  String get set => 'సెట్';

  @override
  String get setAreaPin3Title => 'మీ ప్రాంతాన్ని (PIN3) సెట్ చేయండి';

  @override
  String get setAreaPin3Body =>
      'మీ PIN కోడ్ నమోదు చేయండి. మేము మొదటి 3 అంకెలను మాత్రమే (స్థూల ప్రాంతం) నిల్వ చేస్తాం.';

  @override
  String get pinExampleHint => 'ఉదా: 411001';

  @override
  String get enterFirst3DigitsPin =>
      'మీ PIN యొక్క కనీసం మొదటి 3 అంకెలను నమోదు చేయండి.';

  @override
  String get unableToSaveRegion => 'ప్రాంతాన్ని సేవ్ చేయలేకపోయాం.';

  @override
  String get setPin3ToSeeAlerts =>
      'మీ ప్రాంతానికి అవుట్‌బ్రేక్ అలర్ట్స్ చూడడానికి PIN3 సెట్ చేయండి.';

  @override
  String get noAlertsToday => 'ఈరోజు మీ ప్రాంతానికి అలర్ట్స్ లేవు.';

  @override
  String get prevention => 'నివారణ';

  @override
  String get outbreakLevelHighRisk => 'అధిక ప్రమాదం';

  @override
  String get outbreakLevelWarning => 'హెచ్చరిక';

  @override
  String get outbreakLevelWatch => 'పర్యవేక్షణ';

  @override
  String get outbreakLevelNone => 'ఏమీలేదు';

  @override
  String get back => 'వెనుకకు';

  @override
  String get next => 'తర్వాత';

  @override
  String get couldNotSaveConsent =>
      'మీ సమ్మతిని సేవ్ చేయలేకపోయాం. మళ్లీ ప్రయత్నించండి.';

  @override
  String get termsSigningTitle => 'Terms of Service';

  @override
  String get termsSigningIntro =>
      'లక్షణాల అంచనా ప్రారంభించే ముందు, దయచేసి Terms of Service మరియు Privacy Policy ని అంగీకరించండి. దయచేసి గమనించండి:';

  @override
  String get termsBulletNotDiagnosisTitle =>
      'ఫలితం నిర్ధారణ (డయాగ్నోసిస్) కాదు.';

  @override
  String get termsBulletNotDiagnosisBody =>
      ' ఇది సమాచార ప్రయోజనాల కోసం మాత్రమే; ఇది అర్హత కలిగిన వైద్య అభిప్రాయం కాదు.';

  @override
  String get termsBulletNoEmergencyTitle => 'అత్యవసరంలో దీనిని ఉపయోగించవద్దు.';

  @override
  String get termsBulletNoEmergencyBody =>
      ' ఆరోగ్య అత్యవసరంలో వెంటనే స్థానిక ఎమర్జెన్సీ నంబర్‌కు కాల్ చేయండి.';

  @override
  String get termsBulletDataSafeTitle => 'మీ డేటా సురక్షితం.';

  @override
  String get termsBulletDataSafeBody =>
      ' మీరు ఇచ్చిన సమాచారం పంచుకోబడదు లేదా మీను గుర్తించడానికి ఉపయోగించబడదు.';

  @override
  String get termsConsentTermsPrefix => 'నేను చదివి అంగీకరిస్తున్నాను ';

  @override
  String get termsConsentTermsLink => 'Terms of Service';

  @override
  String get termsConsentTermsSuffix => '.';

  @override
  String get termsConsentPrivacyPrefix =>
      'ఇంటర్వ్యూ కోసం నా ఆరోగ్య సమాచారాన్ని ఉపయోగించడానికి నేను అంగీకరిస్తున్నాను. మరిన్ని వివరాలు ';

  @override
  String get termsConsentPrivacyLink => 'Privacy Policy';

  @override
  String get termsConsentPrivacySuffix => ' లో ఉన్నాయి.';

  @override
  String get quickQuestions => 'త్వరిత ప్రశ్నలు';

  @override
  String get typeAQuestionHint => 'ఒక ప్రశ్న టైప్ చేయండి…';

  @override
  String get talkToMaya => 'మాయాతో మాట్లాడండి';

  @override
  String get womensHealthHubTitle => 'మహిళల ఆరోగ్య హబ్';

  @override
  String get womensHealthHubWelcome => 'మీ ఆరోగ్య ప్రయాణానికి స్వాగతం';

  @override
  String get womensHealthHubSubtitle =>
      'వనరులను అన్వేషించడానికి మరియు వ్యక్తిగత సంరక్షణ పొందడానికి ఒక విభాగాన్ని ఎంచుకోండి.';

  @override
  String get menstrualHealth => 'మాసిక ఆరోగ్యం';

  @override
  String get pregnancyAndMaternal => 'గర్భధారణ & మాతృత్వం';

  @override
  String get breastHealth => 'స్తన ఆరోగ్యం';

  @override
  String get comingSoon => 'త్వరలో';

  @override
  String get womensHealthHubTagline => 'MEDIMITRA WELLNESS';

  @override
  String get womensHealthCategoryMenstrualDescription =>
      'మీ నెలసరి చక్రాన్ని అర్థం చేసుకోండి,\nశుభ్రత గురించి తెలుసుకోండి, మరియు\nపీరియడ్స్‌ను సులభంగా నిర్వహించండి.';

  @override
  String get womensHealthCategoryPregnancyDescription =>
      'ఆరోగ్యమైన గర్భధారణకు నిపుణుల మార్గదర్శకం,\nపోషణ సూచనలు, మరియు\nసురక్షిత డెలివరీ సహాయం.';

  @override
  String get womensHealthCategoryBreastDescription =>
      'సులభమైన స్వయంపరీక్ష మార్గదర్శకాలు\nమరియు అవగాహన సూచనలు\nముందస్తు గుర్తింపు, సంరక్షణ కోసం.';

  @override
  String get recommended => 'సిఫారసు చేసినవి';

  @override
  String get explore => 'అన్వేషించండి';

  @override
  String get menstrualScreenTitle => 'మాసిక ఆరోగ్యం';

  @override
  String get menstrualWhatIsMenstruationTitle => 'మాసికధర్మం అంటే ఏమిటి?';

  @override
  String get menstrualWhatIsMenstruationBody =>
      'మాసికధర్మం అనేది శరీరం గర్భాశయపు పొరను విడిచిపెట్టే సహజమైన నెలవారీ ప్రక్రియ. ఇది ఆరోగ్యమైన ప్రজনన వ్యవస్థకు సంకేతం మరియు పెరుగుదలలో సాధారణ భాగం.';

  @override
  String get menstrualQuote => 'పునరుత్పత్తి మరియు జీవితం యొక్క చక్రం';

  @override
  String get menstrualWhatIsNormalTitle => 'ఏది సాధారణం?';

  @override
  String get menstrualNormalItem1 => 'చక్రం 21 నుండి 35 రోజుల మధ్య ఉంటుంది';

  @override
  String get menstrualNormalItem2 => 'రక్తస్రావం 3 నుండి 7 రోజులు ఉంటుంది';

  @override
  String get menstrualNormalItem3 => 'తేలికపాటి నుంచి మధ్యస్థ ముట్టడి/అసౌకర్యం';

  @override
  String get menstrualWarningSignsTitle => 'హెచ్చరిక సంకేతాలు';

  @override
  String get menstrualWarningItem1 =>
      'భారీ రక్తస్రావం వల్ల ప్రతి 1–2 గంటలకు ప్యాడ్ మార్చాల్సి రావడం';

  @override
  String get menstrualWarningItem2 =>
      'రోజువారీ పనులు చేయనివ్వని తీవ్రమైన నొప్పి';

  @override
  String get menstrualWarningItem3 =>
      'చక్రం స్థిరంగా 21 రోజులకు తక్కువగా లేదా 38 రోజులకు ఎక్కువగా ఉండడం';

  @override
  String get menstrualHygieneTipsTitle => 'శుభ్రత సూచనలు';

  @override
  String get menstrualTipChangeRegularlyTitle => 'నియమితంగా మార్చండి';

  @override
  String get menstrualTipChangeRegularlySubtitle =>
      'ప్రతి 4–6 గంటలకు ప్యాడ్ మార్చండి';

  @override
  String get menstrualTipCleanHandsTitle => 'చేతులు శుభ్రంగా';

  @override
  String get menstrualTipCleanHandsSubtitle => 'ముందు, తరువాత చేతులు కడగండి';

  @override
  String get menstrualTipStayDryTitle => 'ఎండగా ఉంచండి';

  @override
  String get menstrualTipStayDrySubtitle =>
      'జననేంద్రియ ప్రాంతాన్ని శుభ్రంగా మరియు ఎండగా ఉంచండి';

  @override
  String get menstrualMythsFactsTitle => 'భ్రమలు & నిజాలు';

  @override
  String get menstrualMyth1 => 'భ్రమ: \"పీరియడ్స్ సమయంలో వ్యాయామం చేయకూడదు.\"';

  @override
  String get menstrualFact1 =>
      'నిజం: తేలికపాటి వ్యాయామం ముట్టడిని తగ్గించి మూడ్‌ను మెరుగుపరచవచ్చు.';

  @override
  String get menstrualMyth2 => 'భ్రమ: \"మాసిక రక్తం \'మురికి\' రక్తం.\"';

  @override
  String get menstrualFact2 =>
      'నిజం: అది గర్భాశయపు పొర నుంచి వచ్చే సాధారణ రక్తం మరియు కణజం.';

  @override
  String get chatHeaderTitle => 'ఆరోగ్య సహాయకుడు';

  @override
  String get chatHeaderStatusOnline => 'ఆన్‌లైన్';

  @override
  String get chatToday => 'ఈ రోజు';

  @override
  String get chatQuickChipCheckFever => '🌡️ జ్వరం తనిఖీ';

  @override
  String get chatQuickPromptCheckFever => 'నాకు జ్వరం తనిఖీ చేయాలి.';

  @override
  String get chatQuickChipWomensHealth => '🤰 మహిళల ఆరోగ్యం';

  @override
  String get chatQuickPromptWomensHealth =>
      'నాకు మహిళల ఆరోగ్యం గురించి ఒక ప్రశ్న ఉంది.';

  @override
  String get chatQuickChipFirstAid => '🩹 ప్రథమ చికిత్స';

  @override
  String get chatQuickPromptFirstAid => 'నాకు ప్రథమ చికిత్స సలహా కావాలి.';

  @override
  String get chatQuickChipChildCare => '👶 పిల్లల సంరక్షణ';

  @override
  String get chatQuickPromptChildCare =>
      'నాకు పిల్లల సంరక్షణ మార్గదర్శనం కావాలి.';

  @override
  String get chatInputHintAskMeAnything => 'ఏదైనా అడగండి...';

  @override
  String get profileSaved => 'ప్రొఫైల్ సేవ్ చేయబడింది';

  @override
  String get saving => 'సేవ్ అవుతోంది...';

  @override
  String get saveChanges => 'మార్పులు సేవ్ చేయండి';

  @override
  String get profileTopBarTitle => 'ప్రొఫైల్ సెట్టింగ్స్';

  @override
  String get profileHeaderSubtitle => 'వినియోగదారు ప్రొఫైల్';

  @override
  String get profileSectionFullName => 'పూర్తి పేరు';

  @override
  String get profileHintFullName => 'ఉదా. రాహుల్ శర్మ';

  @override
  String get profileSectionAge => 'వయస్సు';

  @override
  String get profileHintAge => 'మీ వయస్సు నమోదు చేయండి';

  @override
  String get profileSectionGender => 'లింగం';

  @override
  String get profileGenderMale => 'పురుషుడు';

  @override
  String get profileGenderFemale => 'స్త్రీ';

  @override
  String get profileGenderOther => 'ఇతర';

  @override
  String get profileChronicConditions => 'దీర్ఘకాలిక పరిస్థితులు';

  @override
  String get profileConditionsBadge => 'ద్విభాషా';

  @override
  String get conditionDiabetesTitle => 'డయాబెటిస్';

  @override
  String get conditionDiabetesSubtitle => 'మధుమేహం (షుగర్)';

  @override
  String get conditionBpHeartTitle => 'బీపీ & గుండె';

  @override
  String get conditionBpHeartSubtitle => 'రక్తపోటు / గుండె';

  @override
  String get conditionAsthmaTitle => 'ఆస్తమా';

  @override
  String get conditionAsthmaSubtitle => 'శ్వాస';

  @override
  String get conditionThyroidTitle => 'థైరాయిడ్';

  @override
  String get conditionThyroidSubtitle => 'థైరాయిడ్';

  @override
  String get conditionTbTitle => 'టిబి';

  @override
  String get conditionTbSubtitle => 'క్షయవ్యాధి';

  @override
  String get conditionNoneTitle => 'ఏమీలేదు';

  @override
  String get conditionNoneSubtitle => 'ఏ వ్యాధి లేదు';

  @override
  String get helpFaqBotGreeting =>
      'హాయ్! నేను MediMitra Help. లక్షణాల తనిఖీ, వాయిస్ ఇన్‌పుట్, అవుట్‌బ్రేక్ అలర్ట్స్, క్లినిక్‌లు, లాగిన్ లేదా గోప్యత గురించి ఏదైనా అడగండి.\n\nగమనిక: ఇది వైద్య సలహా కాదు. అత్యవసర పరిస్థితి ఉంటే, స్థానిక అత్యవసర సేవలను సంప్రదించండి.';

  @override
  String get helpFaqSuggestionCheckSymptoms => 'లక్షణాలను ఎలా చెక్ చేయాలి?';

  @override
  String get helpFaqSuggestionVoiceSymptoms =>
      'వాయిస్ లక్షణాలు ఎలా పనిచేస్తాయి?';

  @override
  String get helpFaqSuggestionOutbreakAlert =>
      'అవుట్‌బ్రేక్ అలర్ట్ అంటే ఏమిటి?';

  @override
  String get helpFaqSuggestionNearbyClinics =>
      'సమీప క్లినిక్‌లు ఎలా కనుగొనాలి?';

  @override
  String get helpFaqSuggestionOtpLogin => 'OTP లాగిన్ ఎలా పనిచేస్తుంది?';

  @override
  String get helpFaqSuggestionDataSafe => 'నా డేటా సురక్షితమా?';

  @override
  String get helpFaqSuggestionGuestMode => 'లాగిన్ లేకుండా యాప్ వాడొచ్చా?';

  @override
  String get helpFaqSuggestionChangeLanguage => 'భాష ఎలా మార్చాలి?';

  @override
  String get helpFaqSuggestionDarkMode => 'డార్క్ మోడ్ ఎలా ఆన్ చేయాలి?';

  @override
  String get helpFaqReplySymptomChecking =>
      'లక్షణాలు చెక్ చేయడానికి:\n1) Chat / Symptom Checker తెరవండి\n2) మీ లక్షణాలను టైప్ చేయండి (లేదా వాయిస్ వాడండి)\n3) ఫాలో-అప్ ప్రశ్నలకు సమాధానం ఇవ్వండి\n\nMediMitra సాధ్యమైన కారణాలు మరియు తదుపరి చర్యలను చూపిస్తుంది. తీవ్రమైన లక్షణాలు (ఛాతి నొప్పి, శ్వాస తీసుకోవడం కష్టం, మూర్చ) ఉంటే తక్షణమే చికిత్స పొందండి.';

  @override
  String get helpFaqReplyVoiceSymptoms =>
      'వాయిస్ లక్షణాలు: మైక్‌పై ట్యాప్ చేసి లక్షణాలను స్పష్టంగా చెప్పండి; యాప్ దాన్ని టెక్స్ట్‌గా మార్చి విశ్లేషిస్తుంది.\n\nటిప్స్: ఒక్కసారి ఒక్క లక్షణం చెప్పండి, సులభమైన పదాలు వాడండి (\"జ్వరం\", \"దగ్గు\") మరియు అడిగితే మైక్రోఫోన్ అనుమతి ఇవ్వండి.';

  @override
  String get helpFaqReplyOutbreakAlert =>
      'అవుట్‌బ్రేక్ అలర్ట్ మీ ప్రాంతంలో కొన్ని లక్షణాలు పెరుగుతున్నాయా (ట్రెండ్) అని చూపుతుంది. ఇది గోప్యంగా, సమిష్టి లక్షణాల నమూనాల ఆధారంగా ఉంటుంది మరియు అవగాహన కోసం మాత్రమే (డయాగ్నోసిస్ కాదు).\n\nOutbreak విభాగంలో ఇన్‌సైట్స్ చూడొచ్చు.';

  @override
  String get helpFaqReplyNearbyClinics =>
      'సమీప క్లినిక్‌లు: Clinic Locator తెరచి మీ చుట్టూ ఉన్న క్లినిక్‌లను చూడండి.\n\nలోకేషన్ అనుమతి ఆన్‌లో ఉందని నిర్ధారించండి.';

  @override
  String get helpFaqReplyOtpLogin =>
      'OTP లాగిన్: మీ 10-అంకెల మొబైల్ నంబర్ నమోదు చేయండి; మేము వెరిఫికేషన్ OTP పంపుతాం. 6-అంకెల OTP నమోదు చేసి కొనసాగించండి.\n\nOTP రాకపోతే, రీసెండ్ టైమర్ తర్వాత మళ్లీ ప్రయత్నించండి; నెట్‌వర్క్‌ను కూడా తనిఖీ చేయండి.';

  @override
  String get helpFaqReplyGuestMode =>
      'గెస్ట్ మోడ్‌లో సైన్-ఇన్ లేకుండా యాప్‌ను అన్వేషించొచ్చు. మీ ప్రొఫైల్‌కు సేవ్ అయ్యే కొన్ని ఫీచర్లు (ఉదా. వ్యక్తిగత సెట్టింగ్స్) లాగిన్ వరకు పరిమితంగా ఉండొచ్చు.';

  @override
  String get helpFaqReplyPrivacy =>
      'మీ అనుభవాన్ని వ్యక్తిగతీకరించడానికి (పేరు/వయస్సు/లింగం/పరిస్థితులు) ప్రొఫైల్ డేటా సురక్షితంగా నిల్వ ఉంటుంది. చాట్‌లో సున్నితమైన సమాచారం పంచుకోకండి.\n\nవివరాల కోసం యాప్‌లోని Privacy Policy చూడండి.';

  @override
  String get helpFaqReplyChangeLanguage =>
      'భాష మార్చడానికి: Profile → Language.';

  @override
  String get helpFaqReplyDarkMode =>
      'డార్క్ మోడ్: Profile → Dark Mode కి వెళ్లి టాగిల్‌ను ఆన్/ఆఫ్ చేయండి.';

  @override
  String get helpFaqReplyContactSupport =>
      'సపోర్ట్‌ను సంప్రదించడానికి: Contact Us తెరిచి మీ సందేశాన్ని పంపండి. వీలైతే స్క్రీన్‌షాట్లు మరియు స్టెప్స్ జత చేయండి.';

  @override
  String get helpFaqReplyFallback =>
      'నేను సహాయపడగల విషయాలు: లక్షణాల తనిఖీ, వాయిస్ ఇన్‌పుట్, అవుట్‌బ్రేక్ అలర్ట్స్, క్లినిక్ లొకేటర్, OTP లాగిన్, గోప్యత, భాష, మరియు డార్క్ మోడ్.\n\nఇవి ప్రయత్నించండి: \"లక్షణాలను ఎలా చెక్ చేయాలి?\", \"సమీప క్లినిక్‌లు ఎలా కనుగొనాలి?\", \"నా డేటా సురక్షితమా?\"';
}
