// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Marathi (`mr`).
class AppLocalizationsMr extends AppLocalizations {
  AppLocalizationsMr([String locale = 'mr']) : super(locale);

  @override
  String get appTitle => 'मेडीमित्रा';

  @override
  String get close => 'बंद करा';

  @override
  String get loginTagline =>
      'तुमच्यासाठी आणि तुमच्या कुटुंबासाठी सोपी आरोग्यसेवा';

  @override
  String get smsLogin => 'एसएमएस लॉगिन';

  @override
  String get emailLogin => 'ईमेल लॉगिन';

  @override
  String get homeHello => 'नमस्कार,';

  @override
  String get homeThere => 'मित्रा';

  @override
  String get homeChatCta => 'आमचा AI हेल्थकेअर चॅट असिस्टंट वापरून पाहा';

  @override
  String get homeOurFeatures => 'आमची वैशिष्ट्ये';

  @override
  String get homeHighlights => 'ठळक वैशिष्ट्ये';

  @override
  String get homeDisclaimerTitle => 'अस्वीकरण';

  @override
  String get homeDisclaimerBody =>
      'MediMitra फक्त माहितीपुरते आहे आणि वैद्यकीय सल्ला नाही. हे डॉक्टरांचा पर्याय नाही.\nगंभीर लक्षणे किंवा कोणत्याही वैद्यकीय आपत्कालीन परिस्थितीत, कृपया जवळच्या रुग्णालयात जा किंवा तात्काळ आपत्कालीन सेवांशी संपर्क करा.';

  @override
  String get featureSymptomChecker => 'लक्षण तपासणी';

  @override
  String get featureWomensHealth => 'महिला आरोग्य जागरूकता';

  @override
  String get featureInsurance => 'विमा';

  @override
  String get featureAiHealthSummary => 'AI आरोग्य सारांश';

  @override
  String get featureReminders => 'स्मरणपत्रे';

  @override
  String get featureLocateClinics => 'जवळची क्लिनिक शोधा';

  @override
  String get promoAiSymptomCheckTitle => 'AI लक्षण तपासणी';

  @override
  String get promoAiSymptomCheckSubtitle =>
      'लक्षणे सांगा, काही सेकंदांत मार्गदर्शन मिळवा.';

  @override
  String get promoVoiceWaveformTitle => 'व्हॉईस + वेव्हफॉर्म';

  @override
  String get promoVoiceWaveformSubtitle => 'व्हॉईस इनपुटसह हातमुक्त चॅट.';

  @override
  String get promoProfilePersonalizationTitle => 'प्रोफाइल वैयक्तिकरण';

  @override
  String get promoProfilePersonalizationSubtitle =>
      'अधिक चांगल्या मदतीसाठी वय, लिंग आणि स्थिती जतन करा.';

  @override
  String get promoNearbyClinicsTitle => 'जवळची क्लिनिक';

  @override
  String get promoNearbyClinicsSubtitle =>
      'तुमच्या ठिकाणाजवळ आरोग्य सेवा शोधा.';

  @override
  String get settings => 'सेटिंग्ज';

  @override
  String get supportAndInformation => 'सहाय्य आणि माहिती';

  @override
  String get notifications => 'सूचना';

  @override
  String get manageYourNotifications => 'तुमच्या सूचनांचे व्यवस्थापन करा';

  @override
  String get notificationsEnabled => 'सूचना सुरू आहेत';

  @override
  String get notificationsDisabled => 'सूचना बंद आहेत';

  @override
  String get couldNotUpdateNotifications => 'सूचना अपडेट करता आल्या नाहीत';

  @override
  String get darkMode => 'डार्क मोड';

  @override
  String get toggleDarkTheme => 'डार्क थीम बदला';

  @override
  String get helpAndFaq => 'सहाय्य आणि FAQ';

  @override
  String get getHelpAndAnswers => 'मदत आणि उत्तरे मिळवा';

  @override
  String get getInTouchWithSupport => 'सपोर्टशी संपर्क करा';

  @override
  String get aboutMediMitra => 'MediMitra बद्दल';

  @override
  String versionLine(Object version) {
    return 'आवृत्ती $version';
  }

  @override
  String get privacyPolicy => 'गोपनीयता धोरण';

  @override
  String get howWeProtectYourData => 'आम्ही तुमचा डेटा कसा संरक्षित करतो';

  @override
  String get termsAndConditions => 'नियम आणि अटी';

  @override
  String get termsConditionsBody =>
      'Terms & Conditions\n\nBy downloading and using this application, you agree to comply with and be bound by these Terms and Conditions. If you do not agree with any part of these terms, you should discontinue using the app.\n\nThis application is designed to provide health-related information and decision-support guidance only. It is not a medical diagnostic tool and does not replace consultation with a qualified doctor or healthcare professional. All information provided by the app is for educational and support purposes, and users must always seek professional medical advice for diagnosis, treatment, or emergencies.\n\nUsers are responsible for providing accurate and honest information while using the app. The guidance generated by the system depends on the inputs provided by the user, and incorrect or incomplete information may lead to inaccurate results. The app should not be used as the sole basis for making medical decisions.\n\nThis application is not intended for emergency situations. In case of severe symptoms such as chest pain, difficulty breathing, loss of consciousness, or heavy bleeding, users must immediately contact local emergency services or visit the nearest hospital.\n\nTo the maximum extent permitted by law, the developers shall not be held liable for any direct or indirect damages arising from the use of this application. Use of the app is entirely at the user’s own risk, and no guarantee is made regarding the accuracy, completeness, or reliability of the information provided.\n\nUse of this application is also governed by our Privacy Policy. By continuing to use the app, you confirm that you have read, understood, and agreed to both the Privacy Policy and these Terms and Conditions.\n\nWe reserve the right to modify or update these Terms and Conditions at any time. Any changes will be displayed within the app, and continued use of the app after such changes indicates acceptance of the updated terms.';

  @override
  String get legalAgreement => 'कायदेशीर करार';

  @override
  String get deleteData => 'डेटा हटवा';

  @override
  String get deleteChatsAndSavedSettings =>
      'चॅट आणि जतन केलेल्या सेटिंग्ज हटवा';

  @override
  String get logOut => 'लॉग आउट';

  @override
  String get logoutQuestion => 'लॉग आउट करायचे?';

  @override
  String get logoutReturnToLogin =>
      'तुम्ही लॉग आउट व्हाल आणि लॉगिन स्क्रीनवर परत जाल.';

  @override
  String get chooseAnAction => 'एक पर्याय निवडा';

  @override
  String get deleteAccount => 'खाते हटवा';

  @override
  String get permanentlyDeleteAccount => 'तुमचे खाते कायमचे हटवा';

  @override
  String get deleteLocalData => 'लोकल डेटा हटवा';

  @override
  String get deleteLocalDataOnDevice =>
      'या डिव्हाइसवरील चॅट आणि जतन केलेल्या सेटिंग्ज हटवा';

  @override
  String get clearLocalDataQuestion => 'लोकल डेटा साफ करायचा?';

  @override
  String get clearLocalDataBody =>
      'यामुळे या डिव्हाइसवरील स्थानिक अॅप डेटा (सेटिंग्ज, कॅश केलेली प्रोफाइल माहिती आणि मेमरीतील चॅट हिस्ट्री) हटवला जाईल.\n\nसर्व बदल लागू होण्यासाठी अॅप रीस्टार्ट करावा लागू शकतो.';

  @override
  String get clear => 'साफ करा';

  @override
  String get localDataCleared => 'लोकल डेटा साफ झाला';

  @override
  String get couldNotClearLocalData => 'लोकल डेटा साफ करता आला नाही';

  @override
  String get accountDeletionNotAvailable =>
      'या प्लॅटफॉर्मवर खाते हटवणे उपलब्ध नाही';

  @override
  String get noSignedInAccountFound => 'कोणतेही साइन-इन खाते सापडले नाही';

  @override
  String get deleteAccountQuestion => 'खाते हटवायचे?';

  @override
  String get deleteAccountBody =>
      'हे तुमचे खाते कायमचे हटवेल. तुम्ही या डिव्हाइसवरून लॉग आउट व्हाल.';

  @override
  String get deletingAccount => 'खाते हटवत आहे...';

  @override
  String get pleaseLoginAgainThenDelete =>
      'कृपया पुन्हा लॉगिन करा, मग खाते हटवा';

  @override
  String get couldNotDeleteAccount => 'खाते हटवता आले नाही';

  @override
  String get networkSlowTryAgain =>
      'नेटवर्क मंद आहे. कृपया पुन्हा प्रयत्न करा.';

  @override
  String get defaultUser => 'वापरकर्ता';

  @override
  String userIdLine(Object id) {
    return 'यूजर आयडी: $id';
  }

  @override
  String get clinicsNearYou => 'जवळची क्लिनिक';

  @override
  String get refresh => 'रिफ्रेश';

  @override
  String get recenter => 'पुन्हा केंद्रित करा';

  @override
  String resultsCount(Object count) {
    return 'निकाल ($count)';
  }

  @override
  String get nearbyClinics => 'जवळची क्लिनिक';

  @override
  String get call => 'कॉल';

  @override
  String get navigate => 'नेव्हिगेट';

  @override
  String get unableToOpenDialer => 'डायलर उघडता आला नाही';

  @override
  String get unableToOpenMaps => 'नकाशे उघडता आले नाहीत';

  @override
  String get radius => 'परिघ';

  @override
  String get tryAgain => 'पुन्हा प्रयत्न करा';

  @override
  String get openLocationSettings => 'लोकेशन सेटिंग्ज उघडा';

  @override
  String get locationServicesDisabled =>
      'लोकेशन सेवा बंद आहेत. कृपया GPS सुरू करा.';

  @override
  String get locationPermissionDenied => 'लोकेशन परवानगी नाकारली.';

  @override
  String get locationPermissionDeniedForever =>
      'लोकेशन परवानगी कायमची नाकारली आहे. सेटिंग्जमधून सक्षम करा.';

  @override
  String get chooseLanguage => 'भाषा निवडा';

  @override
  String get cancel => 'रद्द करा';

  @override
  String get save => 'जतन करा';

  @override
  String get contactUs => 'संपर्क करा';

  @override
  String get needHelp => 'मदत हवी आहे का?';

  @override
  String get contactSubtitle => 'आम्हाला संदेश पाठवा आणि आमची टीम उत्तर देईल.';

  @override
  String supportEmailLine(Object email) {
    return 'सपोर्ट ईमेल: $email';
  }

  @override
  String get typicalResponseLine => 'सामान्य प्रतिसाद: 24 तासांत';

  @override
  String get language => 'भाषा';

  @override
  String languageSetTo(Object language) {
    return 'भाषा सेट झाली: $language';
  }

  @override
  String get fullName => 'पूर्ण नाव';

  @override
  String get yourName => 'तुमचे नाव';

  @override
  String get email => 'ईमेल';

  @override
  String get emailHint => 'name@example.com';

  @override
  String get phoneOptional => 'फोन (ऐच्छिक)';

  @override
  String get yourMobileNumber => 'तुमचा मोबाइल नंबर';

  @override
  String get subject => 'विषय';

  @override
  String get subjectHint => 'हे कशाबद्दल आहे?';

  @override
  String get message => 'संदेश';

  @override
  String get messageHint => 'तुमची समस्या किंवा प्रश्न लिहा';

  @override
  String get send => 'पाठवा';

  @override
  String get sentSuccess => 'पाठवले! आम्ही लवकरच संपर्क करू.';

  @override
  String get required => 'आवश्यक';

  @override
  String get enterValidEmail => 'वैध ईमेल टाका';

  @override
  String get writeMoreDetail => 'कृपया थोडे अधिक तपशील लिहा';

  @override
  String get couldNotOpenEmailApp => 'ईमेल अॅप उघडता आले नाही.';

  @override
  String get couldNotSendTryLater =>
      'पाठवता आले नाही. कृपया नंतर पुन्हा प्रयत्न करा.';

  @override
  String get tipNoShareOtp => 'टीप: येथे पासवर्ड किंवा OTP शेअर करू नका.';

  @override
  String get loginLanguageLabel => 'English / हिंदी';

  @override
  String get loginHeroSubtitle => 'तुमचा आरोग्य साथी';

  @override
  String get loginMobileNumberLabel => 'मोबाईल नंबर';

  @override
  String get loginMobileHint => '00000 00000';

  @override
  String get loginEmailLabel => 'ईमेल पत्ता';

  @override
  String get loginPasswordLabel => 'पासवर्ड';

  @override
  String get loginPasswordHint => 'पासवर्ड टाका';

  @override
  String get loginPleaseWait => 'कृपया थांबा...';

  @override
  String get loginSendOtp => 'OTP पाठवा';

  @override
  String get loginContinue => 'सुरू ठेवा';

  @override
  String get loginSendingOtp => 'OTP पाठवत आहे...';

  @override
  String get loginOr => 'किंवा';

  @override
  String get loginContinueAsGuest => 'गेस्ट म्हणून सुरू ठेवा';

  @override
  String get loginAgreementText =>
      'लॉगिन करून, तुम्ही MediMitra च्या\nसेवा अटी आणि गोपनीयता धोरणाला सहमती देता.';

  @override
  String get loginUnableContinueGuest => 'गेस्ट म्हणून पुढे जाऊ शकले नाही.';

  @override
  String get loginEnterMobileNumber => 'मोबाईल नंबर टाका.';

  @override
  String get loginEnterValidMobileNumber => 'वैध 10-अंकी मोबाईल नंबर टाका.';

  @override
  String get loginOtpSent => 'OTP पाठवला.';

  @override
  String get loginFailedSendOtp => 'OTP पाठवता आला नाही.';

  @override
  String get loginEnterValidEmail => 'वैध ईमेल टाका.';

  @override
  String get loginPasswordMinChars => 'पासवर्ड किमान 6 अक्षरांचा असावा.';

  @override
  String get loginEmailPasswordDisabled =>
      'Firebase Console मध्ये Email/Password साइन-इन बंद आहे.';

  @override
  String get loginAccountExistsTryLogin => 'खाते आधीच आहे. लॉगिन करून पाहा.';

  @override
  String get loginWeakPassword => 'पासवर्ड खूप कमकुवत आहे (किमान 6 अक्षरे).';

  @override
  String get loginIncorrectPassword => 'चुकीचा पासवर्ड.';

  @override
  String get loginInvalidEmail => 'अवैध ईमेल.';

  @override
  String get loginLoginFailed => 'लॉगिन अयशस्वी.';

  @override
  String get otpVerifyNumber => 'नंबर सत्यापित करा';

  @override
  String get otpSentTo => 'आम्ही 6-अंकी कोड पाठवला आहे';

  @override
  String get otpHaventReceived => 'कोड मिळाला नाही?';

  @override
  String get otpResendCode => 'कोड पुन्हा पाठवा';

  @override
  String get otpVerifyProceed => 'सत्यापित करा आणि पुढे जा';

  @override
  String get otpVerifying => 'सत्यापन चालू आहे...';

  @override
  String get otpEnter6Digit => '6-अंकी OTP टाका.';

  @override
  String get otpInvalid => 'अवैध OTP.';

  @override
  String get otpVerificationFailed => 'OTP सत्यापन अयशस्वी.';

  @override
  String get otpFailedResend => 'कोड पुन्हा पाठवता आला नाही.';

  @override
  String get otpCodeResent => 'कोड पुन्हा पाठवला.';

  @override
  String get otpSafetyFirst => 'सुरक्षा प्रथम';

  @override
  String get otpSafetyNote =>
      'MediMitra च्या एन्क्रिप्शनसह तुमच्या आरोग्य नोंदींशी सुरक्षितपणे कनेक्ट व्हा.';

  @override
  String get communityOutbreakAlerts => 'समुदाय प्रादुर्भाव अलर्ट';

  @override
  String get outbreakPrivacyNote =>
      'गोपनीयता-प्रथम: फक्त PIN3 आणि दिवसानुसार एकत्रित लक्षण मोजणी. नावे, चॅट मजकूर, GPS किंवा अचूक टाइमस्टॅम्प नाहीत.';

  @override
  String get regionNotSet => 'प्रदेश: सेट नाही';

  @override
  String regionPin3Line(Object region) {
    return 'प्रदेश: $region (PIN3)';
  }

  @override
  String get set => 'सेट करा';

  @override
  String get setAreaPin3Title => 'तुमचा परिसर सेट करा (PIN3)';

  @override
  String get setAreaPin3Body =>
      'तुमचा PIN कोड टाका. आम्ही फक्त पहिले 3 अंक (मोठा प्रदेश) साठवतो.';

  @override
  String get pinExampleHint => 'उदा. 411001';

  @override
  String get enterFirst3DigitsPin => 'तुमच्या PIN चे किमान पहिले 3 अंक टाका.';

  @override
  String get unableToSaveRegion => 'प्रदेश जतन करता आला नाही.';

  @override
  String get setPin3ToSeeAlerts =>
      'तुमच्या परिसरासाठी प्रादुर्भाव अलर्ट पाहण्यासाठी PIN3 सेट करा.';

  @override
  String get noAlertsToday => 'आज तुमच्या परिसरासाठी कोणतेही अलर्ट नाहीत.';

  @override
  String get prevention => 'प्रतिबंध';

  @override
  String get outbreakLevelHighRisk => 'उच्च धोका';

  @override
  String get outbreakLevelWarning => 'इशारा';

  @override
  String get outbreakLevelWatch => 'निरीक्षण';

  @override
  String get outbreakLevelNone => 'काही नाही';

  @override
  String get back => 'मागे';

  @override
  String get next => 'पुढे';

  @override
  String get couldNotSaveConsent =>
      'तुमची संमती जतन करता आली नाही. कृपया पुन्हा प्रयत्न करा.';

  @override
  String get termsSigningTitle => 'सेवेच्या अटी';

  @override
  String get termsSigningIntro =>
      'लक्षण मूल्यांकन वापरण्यापूर्वी, कृपया सेवेच्या अटी आणि गोपनीयता धोरण स्वीकारा. कृपया लक्षात घ्या:';

  @override
  String get termsBulletNotDiagnosisTitle => 'हा निकाल निदान नाही.';

  @override
  String get termsBulletNotDiagnosisBody =>
      ' हे फक्त माहितीसाठी आहे आणि पात्र वैद्यकीय मत नाही.';

  @override
  String get termsBulletNoEmergencyTitle =>
      'आपत्कालीन परिस्थितीत याचा वापर करू नका.';

  @override
  String get termsBulletNoEmergencyBody =>
      ' आरोग्य आपत्कालीन परिस्थितीत त्वरित स्थानिक आपत्कालीन क्रमांकावर कॉल करा.';

  @override
  String get termsBulletDataSafeTitle => 'तुमचा डेटा सुरक्षित आहे.';

  @override
  String get termsBulletDataSafeBody =>
      ' तुम्ही दिलेली माहिती शेअर केली जाणार नाही किंवा तुम्हाला ओळखण्यासाठी वापरली जाणार नाही.';

  @override
  String get termsConsentTermsPrefix => 'मी ';

  @override
  String get termsConsentTermsLink => 'सेवेच्या अटी';

  @override
  String get termsConsentTermsSuffix =>
      ' वाचल्या आहेत आणि स्वीकारतो/स्वीकारते.';

  @override
  String get termsConsentPrivacyPrefix =>
      'माझी आरोग्य माहिती मुलाखतीसाठी वापरण्यास मी सहमत आहे. अधिक माहिती ';

  @override
  String get termsConsentPrivacyLink => 'गोपनीयता धोरण';

  @override
  String get termsConsentPrivacySuffix => ' मध्ये आहे.';

  @override
  String get quickQuestions => 'त्वरित प्रश्न';

  @override
  String get typeAQuestionHint => 'प्रश्न लिहा…';

  @override
  String get talkToMaya => 'मायाशी बोला';

  @override
  String get womensHealthHubTitle => 'महिला आरोग्य हब';

  @override
  String get womensHealthHubWelcome => 'तुमच्या आरोग्य प्रवासात स्वागत आहे';

  @override
  String get womensHealthHubSubtitle =>
      'संसाधने पाहण्यासाठी आणि वैयक्तिक काळजी मिळवण्यासाठी एक श्रेणी निवडा.';

  @override
  String get menstrualHealth => 'मासिक पाळी आरोग्य';

  @override
  String get pregnancyAndMaternal => 'गर्भधारणा आणि मातृत्व';

  @override
  String get breastHealth => 'स्तन आरोग्य';

  @override
  String get comingSoon => 'लवकरच येत आहे';

  @override
  String get womensHealthHubTagline => 'MEDIMITRA WELLNESS';

  @override
  String get womensHealthCategoryMenstrualDescription =>
      'तुमचा मासिक पाळीचा चक्र समजून घ्या,\nस्वच्छतेबद्दल शिका, आणि\nपाळी सहजपणे व्यवस्थापित करा.';

  @override
  String get womensHealthCategoryPregnancyDescription =>
      'आरोग्यदायी गर्भधारणेसाठी तज्ज्ञ मार्गदर्शन,\nपोषण टिप्स, आणि\nसुरक्षित प्रसूतीसाठी मदत.';

  @override
  String get womensHealthCategoryBreastDescription =>
      'स्व-परीक्षणासाठी सोपे मार्गदर्शक\nआणि जागरूकतेच्या टिप्स\nलवकर निदान व काळजीसाठी.';

  @override
  String get recommended => 'शिफारस केलेले';

  @override
  String get explore => 'एक्सप्लोर करा';

  @override
  String get menstrualScreenTitle => 'मासिक पाळीचे आरोग्य';

  @override
  String get menstrualWhatIsMenstruationTitle => 'मासिक पाळी म्हणजे काय?';

  @override
  String get menstrualWhatIsMenstruationBody =>
      'मासिक पाळी ही एक नैसर्गिक, मासिक प्रक्रिया आहे ज्यात शरीर गर्भाशयातील आतील थर बाहेर टाकते. हे निरोगी प्रजनन प्रणालीचे लक्षण आहे आणि मोठे होण्याचा एक सामान्य भाग आहे.';

  @override
  String get menstrualQuote => 'नूतनीकरण आणि जीवनाचे चक्र';

  @override
  String get menstrualWhatIsNormalTitle => 'काय सामान्य आहे?';

  @override
  String get menstrualNormalItem1 => 'चक्र 21 ते 35 दिवसांदरम्यान असते';

  @override
  String get menstrualNormalItem2 => 'रक्तस्राव 3 ते 7 दिवस चालतो';

  @override
  String get menstrualNormalItem3 => 'हलकी ते मध्यम पोटदुखी/अस्वस्थता';

  @override
  String get menstrualWarningSignsTitle => 'इशारे';

  @override
  String get menstrualWarningItem1 =>
      'जड रक्तस्रावामुळे दर 1–2 तासांनी पॅड बदलावा लागणे';

  @override
  String get menstrualWarningItem2 =>
      'दैनंदिन कामे करणे अशक्य होईल इतका तीव्र वेदना';

  @override
  String get menstrualWarningItem3 =>
      'चक्र सतत 21 दिवसांपेक्षा कमी किंवा 38 दिवसांपेक्षा जास्त';

  @override
  String get menstrualHygieneTipsTitle => 'स्वच्छतेच्या टिप्स';

  @override
  String get menstrualTipChangeRegularlyTitle => 'नियमित बदला';

  @override
  String get menstrualTipChangeRegularlySubtitle => 'दर 4–6 तासांनी पॅड बदला';

  @override
  String get menstrualTipCleanHandsTitle => 'हात स्वच्छ';

  @override
  String get menstrualTipCleanHandsSubtitle => 'आधी आणि नंतर हात धुवा';

  @override
  String get menstrualTipStayDryTitle => 'कोरडे ठेवा';

  @override
  String get menstrualTipStayDrySubtitle =>
      'जननेंद्रिय भाग स्वच्छ आणि कोरडा ठेवा';

  @override
  String get menstrualMythsFactsTitle => 'समज आणि तथ्य';

  @override
  String get menstrualMyth1 => 'समज: \"पाळीमध्ये व्यायाम करू नये.\"';

  @override
  String get menstrualFact1 =>
      'तथ्य: हलका व्यायाम पोटदुखी कमी करण्यास आणि मूड सुधारण्यास मदत करू शकतो.';

  @override
  String get menstrualMyth2 => 'समज: \"मासिक पाळीचे रक्त \'घाणेरडे\' असते.\"';

  @override
  String get menstrualFact2 =>
      'तथ्य: ते गर्भाशयाच्या आतील थरातून येणारे सामान्य रक्त आणि ऊतक असते.';

  @override
  String get chatHeaderTitle => 'आरोग्य सहाय्यक';

  @override
  String get chatHeaderStatusOnline => 'ऑनलाइन';

  @override
  String get chatToday => 'आज';

  @override
  String get chatQuickChipCheckFever => '🌡️ ताप तपासा';

  @override
  String get chatQuickPromptCheckFever => 'मला ताप तपासायचा आहे.';

  @override
  String get chatQuickChipWomensHealth => '🤰 महिलांचे आरोग्य';

  @override
  String get chatQuickPromptWomensHealth =>
      'मला महिलांच्या आरोग्याबद्दल प्रश्न आहे.';

  @override
  String get chatQuickChipFirstAid => '🩹 प्राथमिक उपचार';

  @override
  String get chatQuickPromptFirstAid => 'मला प्राथमिक उपचाराचा सल्ला हवा आहे.';

  @override
  String get chatQuickChipChildCare => '👶 बाल देखभाल';

  @override
  String get chatQuickPromptChildCare => 'मला बाल देखभाल मार्गदर्शन हवे आहे.';

  @override
  String get chatInputHintAskMeAnything => 'काहीही विचारा...';

  @override
  String get profileSaved => 'प्रोफाइल जतन झाले';

  @override
  String get saving => 'जतन करत आहे...';

  @override
  String get saveChanges => 'बदल जतन करा';

  @override
  String get profileTopBarTitle => 'Profile Settings';

  @override
  String get profileHeaderSubtitle => 'User Profile';

  @override
  String get profileSectionFullName => 'FULL NAME';

  @override
  String get profileHintFullName => 'e.g. Rahul Sharma';

  @override
  String get profileSectionAge => 'AGE';

  @override
  String get profileHintAge => 'Enter your age';

  @override
  String get profileSectionGender => 'GENDER';

  @override
  String get profileGenderMale => 'Male';

  @override
  String get profileGenderFemale => 'Female';

  @override
  String get profileGenderOther => 'Other';

  @override
  String get profileChronicConditions => 'CHRONIC CONDITIONS';

  @override
  String get profileConditionsBadge => 'BILINGUAL';

  @override
  String get conditionDiabetesTitle => 'Diabetes';

  @override
  String get conditionDiabetesSubtitle => 'Diabetes (Sugar)';

  @override
  String get conditionBpHeartTitle => 'BP & Heart';

  @override
  String get conditionBpHeartSubtitle => 'Blood pressure / Heart';

  @override
  String get conditionAsthmaTitle => 'Asthma';

  @override
  String get conditionAsthmaSubtitle => 'Breathing';

  @override
  String get conditionThyroidTitle => 'Thyroid';

  @override
  String get conditionThyroidSubtitle => 'Thyroid';

  @override
  String get conditionTbTitle => 'TB';

  @override
  String get conditionTbSubtitle => 'Tuberculosis';

  @override
  String get conditionNoneTitle => 'None';

  @override
  String get conditionNoneSubtitle => 'No conditions';

  @override
  String get helpFaqBotGreeting =>
      'Hi! I\'m MediMitra Help. Ask me anything about symptom checking, voice input, outbreak alerts, clinics, login, or privacy.\n\nNote: This is not medical advice. If you have a medical emergency, contact local emergency services.';

  @override
  String get helpFaqSuggestionCheckSymptoms => 'How do I check symptoms?';

  @override
  String get helpFaqSuggestionVoiceSymptoms => 'How do voice symptoms work?';

  @override
  String get helpFaqSuggestionOutbreakAlert => 'What is outbreak alert?';

  @override
  String get helpFaqSuggestionNearbyClinics => 'How to find nearby clinics?';

  @override
  String get helpFaqSuggestionOtpLogin => 'How does OTP login work?';

  @override
  String get helpFaqSuggestionDataSafe => 'Is my data safe?';

  @override
  String get helpFaqSuggestionGuestMode => 'Can I use the app without login?';

  @override
  String get helpFaqSuggestionChangeLanguage => 'How to change language?';

  @override
  String get helpFaqSuggestionDarkMode => 'How to enable dark mode?';

  @override
  String get helpFaqReplySymptomChecking =>
      'To check symptoms:\n1) Open Chat / Symptom Checker\n2) Type your symptoms (or use voice)\n3) Answer follow-up questions\n\nMediMitra will show likely causes and next steps. For severe symptoms (chest pain, trouble breathing, fainting), seek urgent care.';

  @override
  String get helpFaqReplyVoiceSymptoms =>
      'Voice symptoms: tap the microphone, speak your symptoms clearly, and the app converts it to text for analysis.\n\nTips: speak one symptom at a time, use simple words (\"fever\", \"cough\"), and allow microphone permission when asked.';

  @override
  String get helpFaqReplyOutbreakAlert =>
      'Outbreak alert helps you see if certain symptoms are trending in your area. It\'s based on anonymized, aggregated symptom patterns and is meant for awareness (not diagnosis).\n\nYou can view outbreak insights from the Outbreak section.';

  @override
  String get helpFaqReplyNearbyClinics =>
      'Nearby clinics: open the Clinic Locator to see clinics around you.\n\nMake sure Location permission is enabled. If you prefer, you can also search by area/city (if available on your build).';

  @override
  String get helpFaqReplyOtpLogin =>
      'OTP login: enter your 10-digit mobile number and we send a verification OTP. Enter the 6-digit OTP to proceed.\n\nIf you don\'t receive it, wait for the resend timer and try again. Also confirm network/SMS permissions.';

  @override
  String get helpFaqReplyGuestMode =>
      'Guest mode lets you explore the app without signing in. Some features that save to your profile (like personalized settings) may be limited until you log in.';

  @override
  String get helpFaqReplyPrivacy =>
      'Your profile data (like name/age/gender/conditions) is stored securely for your account to personalize your experience. We do not want you to share sensitive info in chat.\n\nFor exact details, check Privacy Policy (in the app).';

  @override
  String get helpFaqReplyChangeLanguage =>
      'You can change language from Profile → Language.';

  @override
  String get helpFaqReplyDarkMode =>
      'Dark mode: go to Profile → Dark Mode and toggle it on/off. Your choice is saved and works across the whole app.';

  @override
  String get helpFaqReplyContactSupport =>
      'Contact support: open Contact Us and send your message. Include screenshots and steps if possible.';

  @override
  String get helpFaqReplyFallback =>
      'I can help with: symptom checking, voice input, outbreak alerts, clinic locator, OTP login, privacy, language, and dark mode.\n\nTry one of these: \"How do I check symptoms?\", \"How to find nearby clinics?\", \"Is my data safe?\"';
}
