// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for Gujarati (`gu`).
class AppLocalizationsGu extends AppLocalizations {
  AppLocalizationsGu([String locale = 'gu']) : super(locale);

  @override
  String get appTitle => 'મેડીમિત્રા';

  @override
  String get close => 'બંધ કરો';

  @override
  String get loginTagline => 'તમારા અને તમારા પરિવાર માટે સરળ હેલ્થકેર';

  @override
  String get smsLogin => 'એસએમએસ લૉગિન';

  @override
  String get emailLogin => 'ઇમેઇલ લૉગિન';

  @override
  String get homeHello => 'નમસ્તે,';

  @override
  String get homeThere => 'મિત્ર';

  @override
  String get homeChatCta => 'અમારા AI હેલ્થકેર ચેટ સહાયકને શોધો';

  @override
  String get homeOurFeatures => 'અમારી સુવિધાઓ';

  @override
  String get homeHighlights => 'મુખ્ય મુદ્દાઓ';

  @override
  String get homeDisclaimerTitle => 'અસ્વીકરણ';

  @override
  String get homeDisclaimerBody =>
      'MediMitra માત્ર માહિતી માટે છે અને તબીબી સલાહ નથી. તે ડૉક્ટરની જગ્યાએ નથી.\nકોઈપણ ગંભીર લક્ષણો અથવા તબીબી ઇમરજન્સીમાં, કૃપા કરીને નજીકના હોસ્પિટલમાં જાઓ અથવા તરત જ ઇમરજન્સી સેવાઓનો સંપર્ક કરો.';

  @override
  String get featureSymptomChecker => 'લક્ષણ ચેકર';

  @override
  String get featureWomensHealth => 'મહિલા આરોગ્ય જાગૃતિ';

  @override
  String get featureInsurance => 'વીમા';

  @override
  String get featureAiHealthSummary => 'AI આરોગ્ય સારાંશ';

  @override
  String get featureReminders => 'રીમાઇન્ડર્સ';

  @override
  String get featureLocateClinics => 'તમારી પાસેના ક્લિનિક શોધો';

  @override
  String get promoAiSymptomCheckTitle => 'AI લક્ષણ તપાસ';

  @override
  String get promoAiSymptomCheckSubtitle =>
      'લક્ષણો જણાવો, સેકન્ડોમાં માર્ગદર્શન મેળવો.';

  @override
  String get promoVoiceWaveformTitle => 'વોઇસ + વેવફોર્મ';

  @override
  String get promoVoiceWaveformSubtitle => 'વોઇસ ઇનપુટ સાથે હેન્ડ્સ-ફ્રી ચેટ.';

  @override
  String get promoProfilePersonalizationTitle => 'પ્રોફાઇલ વ્યક્તિગતકરણ';

  @override
  String get promoProfilePersonalizationSubtitle =>
      'વધુ સારી મદદ માટે ઉંમર, લિંગ અને સ્થિતિ સેવ કરો.';

  @override
  String get promoNearbyClinicsTitle => 'નજીકના ક્લિનિક';

  @override
  String get promoNearbyClinicsSubtitle =>
      'તમારા સ્થાન નજીકની આરોગ્ય સેવાઓ શોધો.';

  @override
  String get settings => 'સેટિંગ્સ';

  @override
  String get supportAndInformation => 'સહાય અને માહિતી';

  @override
  String get notifications => 'સૂચનાઓ';

  @override
  String get manageYourNotifications => 'તમારી સૂચનાઓ મેનેજ કરો';

  @override
  String get notificationsEnabled => 'સૂચનાઓ ચાલુ છે';

  @override
  String get notificationsDisabled => 'સૂચનાઓ બંધ છે';

  @override
  String get couldNotUpdateNotifications => 'સૂચનાઓ અપડેટ થઈ શકી નથી';

  @override
  String get darkMode => 'ડાર્ક મોડ';

  @override
  String get toggleDarkTheme => 'ડાર્ક થીમ બદલો';

  @override
  String get helpAndFaq => 'મદદ અને FAQ';

  @override
  String get getHelpAndAnswers => 'મદદ અને જવાબ મેળવો';

  @override
  String get getInTouchWithSupport => 'સપોર્ટ સાથે સંપર્ક કરો';

  @override
  String get aboutMediMitra => 'MediMitra વિશે';

  @override
  String versionLine(Object version) {
    return 'આવૃત્તિ $version';
  }

  @override
  String get privacyPolicy => 'ગોપનીયતા નીતિ';

  @override
  String get howWeProtectYourData =>
      'અમે તમારો ડેટા કેવી રીતે સુરક્ષિત રાખીએ છીએ';

  @override
  String get termsAndConditions => 'નિયમો અને શરતો';

  @override
  String get termsConditionsBody =>
      'Terms & Conditions\n\nBy downloading and using this application, you agree to comply with and be bound by these Terms and Conditions. If you do not agree with any part of these terms, you should discontinue using the app.\n\nThis application is designed to provide health-related information and decision-support guidance only. It is not a medical diagnostic tool and does not replace consultation with a qualified doctor or healthcare professional. All information provided by the app is for educational and support purposes, and users must always seek professional medical advice for diagnosis, treatment, or emergencies.\n\nUsers are responsible for providing accurate and honest information while using the app. The guidance generated by the system depends on the inputs provided by the user, and incorrect or incomplete information may lead to inaccurate results. The app should not be used as the sole basis for making medical decisions.\n\nThis application is not intended for emergency situations. In case of severe symptoms such as chest pain, difficulty breathing, loss of consciousness, or heavy bleeding, users must immediately contact local emergency services or visit the nearest hospital.\n\nTo the maximum extent permitted by law, the developers shall not be held liable for any direct or indirect damages arising from the use of this application. Use of the app is entirely at the user’s own risk, and no guarantee is made regarding the accuracy, completeness, or reliability of the information provided.\n\nUse of this application is also governed by our Privacy Policy. By continuing to use the app, you confirm that you have read, understood, and agreed to both the Privacy Policy and these Terms and Conditions.\n\nWe reserve the right to modify or update these Terms and Conditions at any time. Any changes will be displayed within the app, and continued use of the app after such changes indicates acceptance of the updated terms.';

  @override
  String get legalAgreement => 'કાનૂની કરાર';

  @override
  String get deleteData => 'ડેટા ડિલીટ કરો';

  @override
  String get deleteChatsAndSavedSettings =>
      'ચેટ અને સેઇવ કરેલી સેટિંગ્સ કાઢી નાખો';

  @override
  String get logOut => 'લોગ આઉટ';

  @override
  String get logoutQuestion => 'લોગ આઉટ કરવું છે?';

  @override
  String get logoutReturnToLogin =>
      'તમે લોગ આઉટ થઈ જશો અને લોગિન સ્ક્રીન પર પરત ફરશો.';

  @override
  String get chooseAnAction => 'એક વિકલ્પ પસંદ કરો';

  @override
  String get deleteAccount => 'ખાતું ડિલીટ કરો';

  @override
  String get permanentlyDeleteAccount => 'તમારું ખાતું કાયમી રીતે ડિલીટ કરો';

  @override
  String get deleteLocalData => 'સ્થાનિક ડેટા ડિલીટ કરો';

  @override
  String get deleteLocalDataOnDevice =>
      'આ ઉપકરણ પર ચેટ અને સેઇવ કરેલી સેટિંગ્સ કાઢી નાખો';

  @override
  String get clearLocalDataQuestion => 'સ્થાનિક ડેટા સાફ કરવો છે?';

  @override
  String get clearLocalDataBody =>
      'આ ઉપકરણ પર સ્થાનિક રીતે સંગ્રહિત એપ ડેટા (સેઇવ કરેલી સેટિંગ્સ, કેશ્ડ પ્રોફાઇલ માહિતી અને મેમરીમાં ચેટ ઇતિહાસ) ડિલીટ કરશે.\n\nબધા ફેરફારો લાગુ જોવા માટે તમને એપ રીસ્ટાર્ટ કરવાની જરૂર પડી શકે છે.';

  @override
  String get clear => 'સાફ કરો';

  @override
  String get localDataCleared => 'સ્થાનિક ડેટા સાફ થઈ ગયો';

  @override
  String get couldNotClearLocalData => 'સ્થાનિક ડેટા સાફ થઈ શક્યો નથી';

  @override
  String get accountDeletionNotAvailable =>
      'આ પ્લેટફોર્મ પર ખાતું ડિલીટ કરવું ઉપલબ્ધ નથી';

  @override
  String get noSignedInAccountFound => 'કોઈ સાઇન-ઇન ખાતું મળ્યું નથી';

  @override
  String get deleteAccountQuestion => 'ખાતું ડિલીટ કરવું છે?';

  @override
  String get deleteAccountBody =>
      'આ તમારું ખાતું કાયમી રીતે ડિલીટ કરશે. તમે આ ઉપકરણમાંથી લોગ આઉટ થઈ જશો.';

  @override
  String get deletingAccount => 'ખાતું ડિલીટ થઈ રહ્યું છે...';

  @override
  String get pleaseLoginAgainThenDelete =>
      'કૃપા કરીને ફરીથી લોગિન કરો, પછી ખાતું ડિલીટ કરો';

  @override
  String get couldNotDeleteAccount => 'ખાતું ડિલીટ થઈ શક્યું નથી';

  @override
  String get networkSlowTryAgain =>
      'નેટવર્ક ધીમું છે. કૃપા કરીને ફરી પ્રયાસ કરો.';

  @override
  String get defaultUser => 'વપરાશકર્તા';

  @override
  String userIdLine(Object id) {
    return 'યૂઝર આઈડી: $id';
  }

  @override
  String get clinicsNearYou => 'તમારી પાસેના ક્લિનિક';

  @override
  String get refresh => 'રીફ્રેશ';

  @override
  String get recenter => 'ફરી કેન્દ્રિત કરો';

  @override
  String resultsCount(Object count) {
    return 'પરિણામો ($count)';
  }

  @override
  String get nearbyClinics => 'નજીકના ક્લિનિક';

  @override
  String get call => 'કોલ';

  @override
  String get navigate => 'નેવિગેટ';

  @override
  String get unableToOpenDialer => 'ડાયલર ખૂલ્યો નથી';

  @override
  String get unableToOpenMaps => 'મેપ્સ ખૂલ્યા નથી';

  @override
  String get radius => 'પરિઘ';

  @override
  String get tryAgain => 'ફરી પ્રયાસ કરો';

  @override
  String get openLocationSettings => 'સ્થાન સેટિંગ્સ ખોલો';

  @override
  String get locationServicesDisabled =>
      'સ્થાન સેવાઓ બંધ છે. કૃપા કરીને GPS ચાલુ કરો.';

  @override
  String get locationPermissionDenied => 'સ્થાન પરવાનગી નકારવામાં આવી.';

  @override
  String get locationPermissionDeniedForever =>
      'સ્થાન પરવાનગી કાયમી રીતે નકારવામાં આવી છે. સેટિંગ્સમાંથી એને સક્રિય કરો.';

  @override
  String get chooseLanguage => 'ભાષા પસંદ કરો';

  @override
  String get cancel => 'રદ કરો';

  @override
  String get save => 'સેવ કરો';

  @override
  String get contactUs => 'સંપર્ક કરો';

  @override
  String get needHelp => 'મદદ જોઈએ?';

  @override
  String get contactSubtitle => 'અમને સંદેશ મોકલો અને અમારી ટીમ જવાબ આપશે.';

  @override
  String supportEmailLine(Object email) {
    return 'સપોર્ટ ઇમેઇલ: $email';
  }

  @override
  String get typicalResponseLine => 'સામાન્ય પ્રતિભાવ: 24 કલાકમાં';

  @override
  String get language => 'ભાષા';

  @override
  String languageSetTo(Object language) {
    return 'ભાષા સેટ થઈ: $language';
  }

  @override
  String get fullName => 'પૂર્ણ નામ';

  @override
  String get yourName => 'તમારું નામ';

  @override
  String get email => 'ઇમેઇલ';

  @override
  String get emailHint => 'name@example.com';

  @override
  String get phoneOptional => 'ફોન (વૈકલ્પિક)';

  @override
  String get yourMobileNumber => 'તમારો મોબાઇલ નંબર';

  @override
  String get subject => 'વિષય';

  @override
  String get subjectHint => 'આ શે વિશે છે?';

  @override
  String get message => 'સંદેશ';

  @override
  String get messageHint => 'તમારો પ્રશ્ન અથવા સમસ્યા લખો';

  @override
  String get send => 'મોકલો';

  @override
  String get sentSuccess => 'મોકલ્યું! અમે ટૂંક સમયમાં જવાબ આપશું.';

  @override
  String get required => 'આવશ્યક';

  @override
  String get enterValidEmail => 'માન્ય ઇમેઇલ દાખલ કરો';

  @override
  String get writeMoreDetail => 'કૃપા કરીને થોડું વધુ વિગત લખો';

  @override
  String get couldNotOpenEmailApp => 'ઇમેઇલ એપ ખોલી શકાઈ નથી.';

  @override
  String get couldNotSendTryLater =>
      'મોકલી શક્યા નથી. કૃપા કરીને પછી ફરી પ્રયાસ કરો.';

  @override
  String get tipNoShareOtp => 'ટિપ: અહીં પાસવર્ડ અથવા OTP શેર ન કરો.';

  @override
  String get loginLanguageLabel => 'English / ગુજરાતી';

  @override
  String get loginHeroSubtitle => 'તમારો આરોગ્ય સાથી';

  @override
  String get loginMobileNumberLabel => 'મોબાઇલ નંબર';

  @override
  String get loginMobileHint => '00000 00000';

  @override
  String get loginEmailLabel => 'ઇમેઇલ સરનામું';

  @override
  String get loginPasswordLabel => 'પાસવર્ડ';

  @override
  String get loginPasswordHint => 'પાસવર્ડ દાખલ કરો';

  @override
  String get loginPleaseWait => 'કૃપા કરીને રાહ જુઓ...';

  @override
  String get loginSendOtp => 'OTP મોકલો';

  @override
  String get loginContinue => 'ચાલુ રાખો';

  @override
  String get loginSendingOtp => 'OTP મોકલી રહ્યા છીએ...';

  @override
  String get loginOr => 'અથવા';

  @override
  String get loginContinueAsGuest => 'ગેસ્ટ તરીકે ચાલુ રાખો';

  @override
  String get loginAgreementText =>
      'લોગિન કરીને, તમે MediMitraની\nસેવા શરતો અને ગોપનીયતા નીતિ સાથે સહમત છો.';

  @override
  String get loginUnableContinueGuest => 'ગેસ્ટ તરીકે ચાલુ રાખી શક્યા નથી.';

  @override
  String get loginEnterMobileNumber => 'મોબાઇલ નંબર દાખલ કરો.';

  @override
  String get loginEnterValidMobileNumber =>
      'માન્ય 10 અંકનો મોબાઇલ નંબર દાખલ કરો.';

  @override
  String get loginOtpSent => 'OTP મોકલ્યું.';

  @override
  String get loginFailedSendOtp => 'OTP મોકલવામાં નિષ્ફળ.';

  @override
  String get loginEnterValidEmail => 'માન્ય ઇમેઇલ દાખલ કરો.';

  @override
  String get loginPasswordMinChars => 'પાસવર્ડ ઓછામાં ઓછા 6 અક્ષરનો હોવો જોઈએ.';

  @override
  String get loginEmailPasswordDisabled =>
      'Firebase Console માં Email/Password સાઇન-ઇન બંધ છે.';

  @override
  String get loginAccountExistsTryLogin =>
      'ખાતું પહેલેથી હાજર છે. લોગિન કરીને જુઓ.';

  @override
  String get loginWeakPassword => 'પાસવર્ડ નબળો છે (ઓછામાં ઓછા 6 અક્ષર).';

  @override
  String get loginIncorrectPassword => 'ખોટો પાસવર્ડ.';

  @override
  String get loginInvalidEmail => 'અમાન્ય ઇમેઇલ.';

  @override
  String get loginLoginFailed => 'લોગિન નિષ્ફળ.';

  @override
  String get otpVerifyNumber => 'નંબર ચકાસો';

  @override
  String get otpSentTo => 'અમે 6 અંકનો કોડ મોકલ્યો છે';

  @override
  String get otpHaventReceived => 'કોડ મળ્યો નથી?';

  @override
  String get otpResendCode => 'કોડ ફરી મોકલો';

  @override
  String get otpVerifyProceed => 'ચકાસો અને આગળ વધો';

  @override
  String get otpVerifying => 'ચકાસી રહ્યા છીએ...';

  @override
  String get otpEnter6Digit => '6 અંકનો OTP દાખલ કરો.';

  @override
  String get otpInvalid => 'અમાન્ય OTP.';

  @override
  String get otpVerificationFailed => 'OTP ચકાસણી નિષ્ફળ.';

  @override
  String get otpFailedResend => 'કોડ ફરી મોકલવામાં નિષ્ફળ.';

  @override
  String get otpCodeResent => 'કોડ ફરી મોકલ્યો.';

  @override
  String get otpSafetyFirst => 'સુરક્ષા પ્રથમ';

  @override
  String get otpSafetyNote =>
      'MediMitraના એન્ક્રિપ્શન સાથે તમારા આરોગ્ય રેકોર્ડ્સ સાથે સુરક્ષિત રીતે જોડાઓ.';

  @override
  String get communityOutbreakAlerts => 'સમુદાય પ્રકોપ એલર્ટ';

  @override
  String get outbreakPrivacyNote =>
      'ગોપનીયતા-પ્રથમ: માત્ર PIN3 અને દિવસ પ્રમાણે એકત્રિત લક્ષણ ગણતરી. કોઈ નામ, ચેટ ટેક્સ્ટ, GPS અથવા ચોક્કસ સમયમુદ્રા નથી.';

  @override
  String get regionNotSet => 'વિસ્તાર: સેટ નથી';

  @override
  String regionPin3Line(Object region) {
    return 'વિસ્તાર: $region (PIN3)';
  }

  @override
  String get set => 'સેટ કરો';

  @override
  String get setAreaPin3Title => 'તમારો વિસ્તાર સેટ કરો (PIN3)';

  @override
  String get setAreaPin3Body =>
      'તમારો PIN કોડ દાખલ કરો. અમે ફક્ત પ્રથમ 3 અંક (મોટો વિસ્તાર) જ સંગ્રહીએ છીએ.';

  @override
  String get pinExampleHint => 'જેમ કે 411001';

  @override
  String get enterFirst3DigitsPin =>
      'તમારા PINના ઓછામાં ઓછા પ્રથમ 3 અંક દાખલ કરો.';

  @override
  String get unableToSaveRegion => 'વિસ્તાર સેવ થઈ શક્યો નથી.';

  @override
  String get setPin3ToSeeAlerts =>
      'તમારા વિસ્તારમાં પ્રકોપ એલર્ટ જોવા માટે PIN3 સેટ કરો.';

  @override
  String get noAlertsToday => 'આજે તમારા વિસ્તારમાં કોઈ એલર્ટ નથી.';

  @override
  String get prevention => 'રોકથામ';

  @override
  String get outbreakLevelHighRisk => 'ઉચ્ચ જોખમ';

  @override
  String get outbreakLevelWarning => 'ચેતવણી';

  @override
  String get outbreakLevelWatch => 'નિરીક્ષણ';

  @override
  String get outbreakLevelNone => 'કોઈ નથી';

  @override
  String get back => 'પાછા';

  @override
  String get next => 'આગળ';

  @override
  String get couldNotSaveConsent =>
      'તમારી સંમતિ સેવ કરી શકાઈ નથી. કૃપા કરીને ફરી પ્રયાસ કરો.';

  @override
  String get termsSigningTitle => 'સેવાની શરતો';

  @override
  String get termsSigningIntro =>
      'લક્ષણ મૂલ્યાંકન વાપરતાં પહેલાં, કૃપા કરીને સેવાની શરતો અને ગોપનીયતા નીતિ સ્વીકારો. કૃપા કરીને નોંધ કરો:';

  @override
  String get termsBulletNotDiagnosisTitle => 'આ પરિણામ નિદાન નથી.';

  @override
  String get termsBulletNotDiagnosisBody =>
      ' આ માત્ર માહિતી માટે છે અને લાયક તબીબી અભિપ્રાય નથી.';

  @override
  String get termsBulletNoEmergencyTitle => 'ઇમરજન્સીમાં તેનો ઉપયોગ ન કરો.';

  @override
  String get termsBulletNoEmergencyBody =>
      ' આરોગ્ય ઇમરજન્સીમાં તરત જ તમારા સ્થાનિક ઇમરજન્સી નંબર પર કૉલ કરો.';

  @override
  String get termsBulletDataSafeTitle => 'તમારો ડેટા સુરક્ષિત છે.';

  @override
  String get termsBulletDataSafeBody =>
      ' તમે આપેલી માહિતી શેર નહીં થાય અથવા તમારી ઓળખ માટે ઉપયોગ નહીં થાય.';

  @override
  String get termsConsentTermsPrefix => 'મેં ';

  @override
  String get termsConsentTermsLink => 'સેવાની શરતો';

  @override
  String get termsConsentTermsSuffix => ' વાંચી છે અને સ્વીકારું છું.';

  @override
  String get termsConsentPrivacyPrefix =>
      'મારી આરોગ્ય માહિતી ઇન્ટરવ્યુ માટે ઉપયોગમાં લેવા માટે હું સંમત છું. વધુ માહિતી ';

  @override
  String get termsConsentPrivacyLink => 'ગોપનીયતા નીતિ';

  @override
  String get termsConsentPrivacySuffix => ' માં છે.';

  @override
  String get quickQuestions => 'ઝડપી પ્રશ્નો';

  @override
  String get typeAQuestionHint => 'પ્રશ્ન લખો…';

  @override
  String get talkToMaya => 'માયા સાથે વાત કરો';

  @override
  String get womensHealthHubTitle => 'મહિલા આરોગ્ય હબ';

  @override
  String get womensHealthHubWelcome => 'તમારી આરોગ્ય મુસાફરીમાં સ્વાગત છે';

  @override
  String get womensHealthHubSubtitle =>
      'સ્રોતો જોવા અને વ્યક્તિગત કાળજી મેળવવા માટે કેટેગરી પસંદ કરો.';

  @override
  String get menstrualHealth => 'માસિક ધર્મ આરોગ્ય';

  @override
  String get pregnancyAndMaternal => 'ગર્ભાવસ્થા અને માતૃત્વ';

  @override
  String get breastHealth => 'સ્તન આરોગ્ય';

  @override
  String get comingSoon => 'ટૂંક સમયમાં આવશે';

  @override
  String get womensHealthHubTagline => 'MEDIMITRA WELLNESS';

  @override
  String get womensHealthCategoryMenstrualDescription =>
      'તમારો માસિક ચક્ર સમજો,\nસ્વચ્છતા વિશે જાણો, અને\nપીરિયડ્સ સરળતાથી મેનેજ કરો.';

  @override
  String get womensHealthCategoryPregnancyDescription =>
      'સ્વસ્થ ગર્ભાવસ્થાના માટે નિષ્ણાત માર્ગદર્શન,\nપોષણ સૂચનો, અને\nસુરક્ષિત ડિલિવરી સહાય.';

  @override
  String get womensHealthCategoryBreastDescription =>
      'સ્વ-પરીક્ષણ માટે સરળ માર્ગદર્શન\nઅને જાગૃતિ ટીપ્સ\nવહેલી ઓળખ અને કાળજી માટે.';

  @override
  String get recommended => 'ભલામણ કરેલ';

  @override
  String get explore => 'એક્સપ્લોર કરો';

  @override
  String get menstrualScreenTitle => 'માસિક સ્વાસ્થ્ય';

  @override
  String get menstrualWhatIsMenstruationTitle => 'માસિક ધર્મ શું છે?';

  @override
  String get menstrualWhatIsMenstruationBody =>
      'માસિક ધર્મ એ એક કુદરતી, માસિક પ્રક્રિયા છે જેમાં શરીર ગર્ભાશયની અંદરની પરત છોડે છે. તે સ્વસ્થ પ્રજનન પ્રણાલીની નિશાની છે અને વધતા જવાની સામાન્ય પ્રક્રિયા છે.';

  @override
  String get menstrualQuote => 'નવચેતના અને જીવનનો ચક્ર';

  @override
  String get menstrualWhatIsNormalTitle => 'શું સામાન્ય છે?';

  @override
  String get menstrualNormalItem1 => 'ચક્ર 21 થી 35 દિવસ વચ્ચે રહે છે';

  @override
  String get menstrualNormalItem2 => 'રક્તસ્રાવ 3 થી 7 દિવસ સુધી રહે છે';

  @override
  String get menstrualNormalItem3 => 'હળવો થી મધ્યમ દુખાવો અથવા અસ્વસ્થતા';

  @override
  String get menstrualWarningSignsTitle => 'ચેતવણીના સંકેતો';

  @override
  String get menstrualWarningItem1 =>
      'ભારે પ્રવાહને કારણે દરેક 1–2 કલાકે પેડ બદલવો';

  @override
  String get menstrualWarningItem2 => 'દૈનિક કામ અટકી જાય એટલો ભારે દુખાવો';

  @override
  String get menstrualWarningItem3 =>
      'ચક્ર સતત 21 દિવસથી ઓછું અથવા 38 દિવસથી વધુ';

  @override
  String get menstrualHygieneTipsTitle => 'સ્વચ્છતા ટીપ્સ';

  @override
  String get menstrualTipChangeRegularlyTitle => 'નિયમિત બદલો';

  @override
  String get menstrualTipChangeRegularlySubtitle => 'દર 4–6 કલાકે પેડ બદલો';

  @override
  String get menstrualTipCleanHandsTitle => 'હાથ સાફ રાખો';

  @override
  String get menstrualTipCleanHandsSubtitle => 'પહેલાં અને પછી હાથ ધોવો';

  @override
  String get menstrualTipStayDryTitle => 'સૂકો રાખો';

  @override
  String get menstrualTipStayDrySubtitle =>
      'જનન અંગ વિસ્તાર સ્વચ્છ અને સૂકો રાખો';

  @override
  String get menstrualMythsFactsTitle => 'ભ્રમ અને તથ્યો';

  @override
  String get menstrualMyth1 =>
      'ભ્રમ: \"પીરિયડ્સ દરમિયાન વ્યાયામ ન કરવો જોઈએ.\"';

  @override
  String get menstrualFact1 =>
      'તથ્ય: હળવો વ્યાયામ દુખાવો ઘટાડવામાં અને મનોબળ વધારવામાં મદદ કરી શકે છે.';

  @override
  String get menstrualMyth2 => 'ભ્રમ: \"માસિક ધર્મનું લોહી \'ગંદું\' હોય છે.\"';

  @override
  String get menstrualFact2 =>
      'તથ્ય: તે ગર્ભાશયની અંદરની પરતમાંથી સામાન્ય લોહી અને ટિશ્યૂ છે.';

  @override
  String get chatHeaderTitle => 'આરોગ્ય સહાયક';

  @override
  String get chatHeaderStatusOnline => 'ઓનલાઇન';

  @override
  String get chatToday => 'આજે';

  @override
  String get chatQuickChipCheckFever => '🌡️ તાવ ચકાસો';

  @override
  String get chatQuickPromptCheckFever => 'મને તાવ ચકાસવો છે.';

  @override
  String get chatQuickChipWomensHealth => '🤰 મહિલા સ્વાસ્થ્ય';

  @override
  String get chatQuickPromptWomensHealth =>
      'મને મહિલા સ્વાસ્થ્ય વિશે પ્રશ્ન છે.';

  @override
  String get chatQuickChipFirstAid => '🩹 પ્રાથમિક સારવાર';

  @override
  String get chatQuickPromptFirstAid => 'મને પ્રાથમિક સારવારની સલાહ જોઈએ.';

  @override
  String get chatQuickChipChildCare => '👶 બાળક સંભાળ';

  @override
  String get chatQuickPromptChildCare => 'મને બાળક સંભાળ માર્ગદર્શન જોઈએ.';

  @override
  String get chatInputHintAskMeAnything => 'કંઈપણ પૂછો...';

  @override
  String get profileSaved => 'પ્રોફાઇલ સાચવાઈ';

  @override
  String get saving => 'સાચવી રહ્યા છીએ...';

  @override
  String get saveChanges => 'ફેરફારો સાચવો';

  @override
  String get profileTopBarTitle => 'Profile Settings';

  @override
  String get profileHeaderSubtitle => 'User Profile';

  @override
  String get profileSectionFullName => 'FULL NAME';

  @override
  String get profileHintFullName => 'e.g. Rahul Sharma';

  @override
  String get profileSectionAge => 'AGE';

  @override
  String get profileHintAge => 'Enter your age';

  @override
  String get profileSectionGender => 'GENDER';

  @override
  String get profileGenderMale => 'Male';

  @override
  String get profileGenderFemale => 'Female';

  @override
  String get profileGenderOther => 'Other';

  @override
  String get profileChronicConditions => 'CHRONIC CONDITIONS';

  @override
  String get profileConditionsBadge => 'BILINGUAL';

  @override
  String get conditionDiabetesTitle => 'Diabetes';

  @override
  String get conditionDiabetesSubtitle => 'Diabetes (Sugar)';

  @override
  String get conditionBpHeartTitle => 'BP & Heart';

  @override
  String get conditionBpHeartSubtitle => 'Blood pressure / Heart';

  @override
  String get conditionAsthmaTitle => 'Asthma';

  @override
  String get conditionAsthmaSubtitle => 'Breathing';

  @override
  String get conditionThyroidTitle => 'Thyroid';

  @override
  String get conditionThyroidSubtitle => 'Thyroid';

  @override
  String get conditionTbTitle => 'TB';

  @override
  String get conditionTbSubtitle => 'Tuberculosis';

  @override
  String get conditionNoneTitle => 'None';

  @override
  String get conditionNoneSubtitle => 'No conditions';

  @override
  String get helpFaqBotGreeting =>
      'Hi! I\'m MediMitra Help. Ask me anything about symptom checking, voice input, outbreak alerts, clinics, login, or privacy.\n\nNote: This is not medical advice. If you have a medical emergency, contact local emergency services.';

  @override
  String get helpFaqSuggestionCheckSymptoms => 'How do I check symptoms?';

  @override
  String get helpFaqSuggestionVoiceSymptoms => 'How do voice symptoms work?';

  @override
  String get helpFaqSuggestionOutbreakAlert => 'What is outbreak alert?';

  @override
  String get helpFaqSuggestionNearbyClinics => 'How to find nearby clinics?';

  @override
  String get helpFaqSuggestionOtpLogin => 'How does OTP login work?';

  @override
  String get helpFaqSuggestionDataSafe => 'Is my data safe?';

  @override
  String get helpFaqSuggestionGuestMode => 'Can I use the app without login?';

  @override
  String get helpFaqSuggestionChangeLanguage => 'How to change language?';

  @override
  String get helpFaqSuggestionDarkMode => 'How to enable dark mode?';

  @override
  String get helpFaqReplySymptomChecking =>
      'To check symptoms:\n1) Open Chat / Symptom Checker\n2) Type your symptoms (or use voice)\n3) Answer follow-up questions\n\nMediMitra will show likely causes and next steps. For severe symptoms (chest pain, trouble breathing, fainting), seek urgent care.';

  @override
  String get helpFaqReplyVoiceSymptoms =>
      'Voice symptoms: tap the microphone, speak your symptoms clearly, and the app converts it to text for analysis.\n\nTips: speak one symptom at a time, use simple words (\"fever\", \"cough\"), and allow microphone permission when asked.';

  @override
  String get helpFaqReplyOutbreakAlert =>
      'Outbreak alert helps you see if certain symptoms are trending in your area. It\'s based on anonymized, aggregated symptom patterns and is meant for awareness (not diagnosis).\n\nYou can view outbreak insights from the Outbreak section.';

  @override
  String get helpFaqReplyNearbyClinics =>
      'Nearby clinics: open the Clinic Locator to see clinics around you.\n\nMake sure Location permission is enabled. If you prefer, you can also search by area/city (if available on your build).';

  @override
  String get helpFaqReplyOtpLogin =>
      'OTP login: enter your 10-digit mobile number and we send a verification OTP. Enter the 6-digit OTP to proceed.\n\nIf you don\'t receive it, wait for the resend timer and try again. Also confirm network/SMS permissions.';

  @override
  String get helpFaqReplyGuestMode =>
      'Guest mode lets you explore the app without signing in. Some features that save to your profile (like personalized settings) may be limited until you log in.';

  @override
  String get helpFaqReplyPrivacy =>
      'Your profile data (like name/age/gender/conditions) is stored securely for your account to personalize your experience. We do not want you to share sensitive info in chat.\n\nFor exact details, check Privacy Policy (in the app).';

  @override
  String get helpFaqReplyChangeLanguage =>
      'You can change language from Profile → Language.';

  @override
  String get helpFaqReplyDarkMode =>
      'Dark mode: go to Profile → Dark Mode and toggle it on/off. Your choice is saved and works across the whole app.';

  @override
  String get helpFaqReplyContactSupport =>
      'Contact support: open Contact Us and send your message. Include screenshots and steps if possible.';

  @override
  String get helpFaqReplyFallback =>
      'I can help with: symptom checking, voice input, outbreak alerts, clinic locator, OTP login, privacy, language, and dark mode.\n\nTry one of these: \"How do I check symptoms?\", \"How to find nearby clinics?\", \"Is my data safe?\"';
}
